### ISSUE TITLE
Client Allocation Request for: Seamount Technologies

### ISSUE THREAD

**Issue by mxz9102** [filecoin-project/filecoin-plus-client-onboarding#100]
---

# Client Allocation Questions 

## Core Information
- Name: Seamount Technologies
- Website / Social Media: http://sea-mounts.com/
- Region: North America
- DataCap Requested: 2TiB
- Addresses to be Notarized: f1iibmtpvf7jcn7d6jk6s7s2xszf2xebecvy7lzdi
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @mxz9102 - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- your relationship with the data, especially with regard to copyright
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by mxz9102** [comment]
Hi, Philipp:

Thanks for getting back to me. I'll collect the information and send it back to you .

Michael Zhang

________________________________

**Comment by philippbanhardt** [comment]
Hey @mxz9102, do you have an update you can provide?

**Comment by mxz9102** [comment]
Hi, Philipp:

I found out that the project that I am interested in has been included in the Slingshot. I'll continue on my search. If anything comes up, I'll send you an update.

Michael Zhang

________________________________

**Comment by philippbanhardt** [comment]
Got it, thanks
