### ISSUE TITLE
Client Allocation Request for: Yehyun

### ISSUE THREAD

**Issue by yehyunlabel** [filecoin-project/filecoin-plus-client-onboarding#1002]
---

# Client Allocation Questions 

## Core Information
- Name: Yehyun
- Website / Social Media: http://www.goodlabel.co.kr
- Region: Asia excl. Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3ri7eoqdpai2eor65k3nbzbalseph2sq3ytl4awtocwib5twl2qdqapssehkmpqli2hib5hzkjqktmg5hmd3a
- Notary Requested: IPFSUnion

@yehyunlabel Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by IPFSUnion** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacece5yfahku2pwe6mqmqd4ep3ti7hejx64y6a2liawroyotje56vbo 
#### Address 
> f3ri7eoqdpai2eor65k3nbzbalseph2sq3ytl4awtocwib5twl2qdqapssehkmpqli2hib5hzkjqktmg5hmd3a
#### Datacap Allocated
> NaNB
#### Signer Address
> f1enfilmuyphmnqexjt33zfbk56c25mo2lplgbpxa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacece5yfahku2pwe6mqmqd4ep3ti7hejx64y6a2liawroyotje56vbo
