### ISSUE TITLE
Client Allocation Request for: Zhongchuang Power

### ISSUE THREAD

**Issue by 1ane-1** [filecoin-project/filecoin-plus-client-onboarding#1009]
---

# Client Allocation Questions 

## Core Information
- Name: Zhongchuang Power
- Website / Social Media: https://twitter.com/IPFSZC
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3sy7fibgforclhzxb4n25j4xmp5lpgoumjdaaqijnjoytyyl72xhcsoiz26mcroobqd3jygmsisdi7v2hcnlq
- Notary Requested: IPFSUnion

@1ane-1 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by IPFSUnion** [comment]
After comprehensive consideration, 5T datacap is allocated to you. The related message is here.
https://filscout.com/en/message/bafy2bzaceaahhk3iibm47mahatmqqv633dvei5d5krvkfxdv5dqnwtfy2p2is

**Comment by 1ane-1** [comment]
> After comprehensive consideration, 5T datacap is allocated to you. The related message is here. https://filscout.com/en/message/bafy2bzaceaahhk3iibm47mahatmqqv633dvei5d5krvkfxdv5dqnwtfy2p2is
Our datacap is runn out，next i should provide the deal list for you here, right?

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
