### ISSUE TITLE
Client Allocation Request for: Smashacakebrisbane

### ISSUE THREAD

**Issue by dalicejor** [filecoin-project/filecoin-plus-client-onboarding#1012]
---

# Client Allocation Questions 

## Core Information
- Name: Smashacakebrisbane
- Website / Social Media: www.smashacakebrisbane.com.au
- Region: Oceania
- DataCap Requested: 5TiB
- Addresses to be Notarized: f17puvt5i5vtxmryxw4yqthnv45wn6vrtsgkqdutq
- Notary Requested: MegTei

@dalicejor Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedgzhfrwuxh5ocbp2bwrowyhc66wksszor5snqqhmkve2r7n4aluc 
#### Address 
> f17puvt5i5vtxmryxw4yqthnv45wn6vrtsgkqdutq
#### Datacap Allocated
> NaNB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedgzhfrwuxh5ocbp2bwrowyhc66wksszor5snqqhmkve2r7n4aluc

**Comment by MegTei** [comment]
@dalicejor 5TiB has been granted as requested, let me know if you need anything further
