### ISSUE TITLE
Client Allocation Request for: DukeSoft (Rob on Slack :) )

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/filecoin-plus-client-onboarding#1014]
---

# Client Allocation Questions 

## Core Information
- Name: DukeSoft (Rob on Slack :) )
- Website / Social Media: dukesoft.nl
- Region: Europe
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3soaazrjuc4os4mtov5miqkqtozzeemvhugamp3och7yuhk6jjndibfdmudtwblsxzjh4cgua4g3aoatqiuxa
- Notary Requested: s0nik42

@RobQuistNL Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by s0nik42** [comment]
Thanks for your request. Can you kindly add more information / context here on:

The region you are based and the one you physically operate
Yourself , e.g. include links to social media / news mentions etc
Your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
Type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
Your relationship with the data, especially with regard to copyright
How you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
Have you already ask datacap to another notary that have been accepted or rejected.
Thanks

Julien

**Comment by RobQuistNL** [comment]
Hi Julien,

> The region you are based and the one you physically operate
The Netherlands

> Yourself , e.g. include links to social media / news mentions etc
Theres a lot to find on dukesoft.nl :)

> Your history working on IPFS / Filecoin
Been here since the Spacerace.. Check the Slack, its filled with conversations and me helping out, and otherwise you can also see my issues / PR's in Lotus related repositories;
https://github.com/filecoin-project/devgrants/pull/172
https://github.com/filecoin-project/lotus/issues?q=author%3Arobquistnl
https://github.com/filecoin-project/bellperson/issues?q=author%3Arobquistnl
https://github.com/filecoin-project/rust-fil-proofs/issues?q=author%3Arobquistnl
https://github.com/libp2p/go-libp2p-pubsub/issues?q=author%3Arobquistnl

> Type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
Its the Free Music Archive. This is my slingshot project: https://slingshot.filecoin.io/project/616ea5b96e52aa6e9a816e42

> Your relationship with the data, especially with regard to copyright
Its a validated / curated public dataset used for Slingshot

> How you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
I try to geographically spread as much as possible. I have about 100 unique CID's - I'm selecting from a list of 300 gathered miners (through the lotus commands) at random. Literally; `SELECT * FROM miners WHERE disabled != 1 ORDER BY RAND()`

> Have you already ask datacap to another notary that have been accepted or rejected
Nope, first time :)

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedlnrmht6utln3st3k2acipokv5r2tre47whf7qazmgkvnfvwbg26 
#### Address 
> f3soaazrjuc4os4mtov5miqkqtozzeemvhugamp3och7yuhk6jjndibfdmudtwblsxzjh4cgua4g3aoatqiuxa
#### Datacap Allocated
> NaNB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedlnrmht6utln3st3k2acipokv5r2tre47whf7qazmgkvnfvwbg26
