### ISSUE TITLE
Client Allocation Request for: 星际量子（重庆）科技有限公司

### ISSUE THREAD

**Issue by wendaijie** [filecoin-project/filecoin-plus-client-onboarding#1015]
---

# Client Allocation Questions 

## Core Information
- Name: 星际量子（重庆）科技有限公司
- Website / Social Media: http://ipfs.lcunyun.com/
- Region: Greater China
- DataCap Requested: 100GiB
- Addresses to be Notarized: f1vaxz47wmq5ne6ph7rc4yi66lmrlhxeijebogvuy
- Notary Requested: swatchliu

@wendaijie Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.)
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?

Would you like to submit more company information on www.bytebase.cn?

Would you like to accept our face-to-face visit?

**Comment by wendaijie** [comment]
1、Is your company located in Greater China？
yes

2、Duration of establishment
2020-05-08

3、Number of employees
30

4、Business scope and products or services
Cloud Disk and Cloud Storage
We are committed to creating a rich data storage application ecology for human beings, building a common data storage platform, overcoming the obstacles between different data storage platforms, allowing data to flow and to be used freely and at low cost among various storage platforms, and realizing the real permanence of human data.

5、Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.)
WeChat：977740454

6、Data size to be stored,
10TiB

7、Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?
Did not apply for DataCap with another notary

8、Would you like to submit more company information on www.bytebase.cn?
yes

9、Would you like to accept our face-to-face visit?
accept

**Comment by swatchliu** [comment]
Thank you for your reply. We didn't find your registration record on www.bytebase.cn. Please confirm whether the corresponding materials have been submitted according to the requirements.

**Comment by swatchliu** [comment]
@wendaijie  Please provide the relevant materials if more quota is required. Thanks you!

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceauz2wcfv7cjg6lrldslki4we4sglhlyfv5yoi5uq23iuygln323a 
#### Address 
> f1vaxz47wmq5ne6ph7rc4yi66lmrlhxeijebogvuy
#### Datacap Allocated
> NaNB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceauz2wcfv7cjg6lrldslki4we4sglhlyfv5yoi5uq23iuygln323a
