### ISSUE TITLE
Client Allocation Request for: chaoscube

### ISSUE THREAD

**Issue by seunghyonpark** [filecoin-project/filecoin-plus-client-onboarding#1019]
---

# Client Allocation Questions 

## Core Information
- Name: chaoscube
- Website / Social Media: https://www.chaoscube.co.kr/
- Region: Asia excl. Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f1cc32ipyqunh53ycjhi7bp65zz4qjeo6z27uzkly
- Notary Requested: rayshitou

@seunghyonpark Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by seunghyonpark** [comment]
No answer for too long.
Please reply quickly.

**Comment by rayshitou** [comment]
@seunghyonpark Thanks for your application. Please answer the following questions to let me know you and your company.
1.What's your name and your position in your company?What's your company's business?
2.Could you show me your company's business license? And please show me your company searching consequence in the local business license searching website.
3.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency? Could you please show me your cloud usage evidence?

**Comment by creathpark** [comment]
> @seunghyonpark Thanks for your application. Please answer the following questions to let me know you and your company. 1.What's your name and your position in your company?What's your company's business? 2.Could you show me your company's business license? And please show me your company searching consequence in the local business license searching website. 3.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency? Could you please show me your cloud usage evidence?

1.What's your name and your position in your company?What's your company's business?

My name is Wayne Park. I am business developer in my company. And My company is game community operator.

2.Could you show me your company's business license? And please show me your company searching consequence in the local business license searching website.

korea business license
https://cdn.discordapp.com/attachments/896645847494828064/907553161592598578/20211109_175203.jp

korea business license searching website:
https://teht.hometax.go.kr/websquare/websquare.html?w2xPath=/ui/ab/a/a/UTEABAAA13.xml

3.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency? Could you please show me your cloud usage evidence?

We didn't use cloud. But We plan to use AWS cloud.

**Comment by rayshitou** [comment]
Nice! Please let me know:
1.What kind of data do you want to store and how much?
2.Could you please send me some demos of your data?
3.Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner's terms of service?

**Comment by waynepark77** [comment]
> Nice! Please let me know:
1.What kind of data do you want to store and how much?

We are servicing community service for diablo game users and want to save the image contents of diablo game asset in IPFS. An we are planning video service for diablo game users guide.

2.Could you please send me some demos of your data?

1) image contents of diablo game asset
https://board.chaoscube.co.kr/itemR/u.asp
2) users guild
https://www.youtube.com/watch?v=quAQuF1DLj4


3.Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner's terms of service?

Yes, We agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner's terms of service.

**Comment by seunghyonpark** [comment]
1.What kind of data do you want to store and how much?

We are servicing community service for diablo game users and want to save the image contents of diablo game asset in IPFS. An we are planning video service for diablo game users guide.

2.Could you please send me some demos of your data?

1) image contents of diablo game asset
https://board.chaoscube.co.kr/itemR/u.asp
2) users guide
https://www.youtube.com/watch?v=quAQuF1DLj4

3.Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner's terms of service?

Yes, We agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner's terms of service.

**Comment by rayshitou** [comment]
Okey. About the allocation of DataCap:
1.How many miners do you want to store your data to? How much data for each miner?
2.What method/tool will you use to insperct miners? Which aspect of miners will you inspect?
3.Will you record your allocation decision in public? Which platform will you use?
4.Have you ever allocated before? If yes, how did you do when you were questioned? Any links?
