### ISSUE TITLE
Client Allocation Request for: Shenzhen Xiaoyu Blockchain Technology Co., Ltd

### ISSUE THREAD

**Issue by meng1219** [filecoin-project/filecoin-plus-client-onboarding#102]
---

# Client Allocation Questions 

## Core Information
- Name: Shenzhen Xiaoyu Blockchain Technology Co., Ltd
- Website / Social Media: http://www.xyqkl.cn
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1ry5tgrth2qt4r5zu4e6ssfkf4qrce7hcdp22kbi
- Notary Requested: philippbanhardt

**Comment by meng1219** [comment]
Hey. @philippbanhardt 
I am from Shenzhen Xiaoyu Blockchain Technology Co., Ltd.

Shenzhen Xiaoyu Blockchain Technology Co., Ltd., founded in 2016, focuses on the research and development and application of blockchain technology.It used to serve as the technology center of the sandbox committee of the blockchain supervision of the former China Electronic Commerce Association, and now it is the standing director unit of the Global Blockchain Cooperation Alliance, undertaking national blockchain research and development and application projects. The company owns the underlying technology of blockchain with independent property rights, and has obtained a number of national patents and software copyrights.Base on this, we can trace the source of agricultural products, artworks, cosmetics, commodities and so on to realize the application development of blockchain in supply chain management and supply chain finance.

Here is our social meida: 
http://www.xyqkl.cn
https://baijiahao.baidu.com/s?id=1650805171872828817&wfr=spider&for=pc
https://www.sohu.com/a/226599095_466704
https://www.sohu.com/a/307442761_439726

So we'd like to store blockchain data, web 3.0 data such as Commodity information, Logistics information, which is used for our coutribution of web 3.0 and blockchain. So for the copyright, it's totally our data.

I learned about Filecoin and IPFS because of the 2017 ICO. And we bought some FIL after mainnet launched. And We've also stored data.

We would like to store data with the miners recommended by the official or who attended Slingshot.

**Comment by philippbanhardt** [comment]
Hey @meng1219, thanks for the additional information. Can you kindly elaborate more on the type of data you will be storing. Perhaps would also be helpful if you can share info on the source / origin. Thanks!

**Comment by meng1219** [comment]
Hey. @philippbanhardt
We have developed a blockchain project for anti-counterfeiting and traceability of artworks. The data types stored are blockchain data and Web3.

**Comment by philippbanhardt** [comment]
Thanks @meng1219. Final question: are you OK posting here links to the transactions spending awarded datacap?

**Comment by meng1219** [comment]
Of course, it is okay.

**Comment by meng1219** [comment]
@philippbanhardt Thanks.

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfzli4ab7regehjwjagavhyzq2z3ogh4hz7nj3ws4kxqiolpmwf2 
#### Address 
> f1ry5tgrth2qt4r5zu4e6ssfkf4qrce7hcdp22kbi
#### Datacap Allocated
> 5 TiB
