### ISSUE TITLE
Client Allocation Request for: Amgkorea

### ISSUE THREAD

**Issue by Amgkorea** [filecoin-project/filecoin-plus-client-onboarding#1036]
---

# Client Allocation Questions 

## Core Information
- Name: Amgkorea
- Website / Social Media: http://amg-korea.com/
- Region: Asia excl. Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3vzar7dhytpgencnuzsqiql6xsvidkctxqg52xcq4gpo4uiqta7z7vb56u2mb6ej2xa4svgkdvnop7xbdjnaa
- Notary Requested: IPFSUnion

@Amgkorea Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Amgkorea** [comment]
1. Hi. I'm a member of the sales support team. Our company is AMG KOREA CO., LTD. There is only a Korean homepage, so I ask for your understanding. 
http://amg-korea.com/

2. Our company is located in Korea and operates a medical device wholesale business established in 1999. Our company has 40 employees.

1. Filecoin were found out through companies that interact with us. I understand that the company's vast amounts of data are stored relatively safely, resulting in profits.

2. The right to sell and advertise medical devices belongs to our company and is used according to the preliminary deliberation regulations.

3. No. This is the first time.

1. We import products from a medical device company called Kaneka in Japan and sell them as R&D places for medical foundations or hospitals in Korea. It is also developing new products in the healthcare sector and all of these data will be stored in storage. 
We will produce and store advertisements that meet the preliminary deliberation regulations of medical devices, and include technologies through exchanges with foreign companies. And we will designate and manage three competent miners.

**Comment by IPFSUnion** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebpig6j7bek6rb6icsfbb5qgyd4nit73bw2hwl65q4f6xb3ix36cu 
#### Address 
> f3vzar7dhytpgencnuzsqiql6xsvidkctxqg52xcq4gpo4uiqta7z7vb56u2mb6ej2xa4svgkdvnop7xbdjnaa
#### Datacap Allocated
> NaNB
#### Signer Address
> f1enfilmuyphmnqexjt33zfbk56c25mo2lplgbpxa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebpig6j7bek6rb6icsfbb5qgyd4nit73bw2hwl65q4f6xb3ix36cu
