### ISSUE TITLE
Client Allocation Request for: Dustin greuel

### ISSUE THREAD

**Issue by dgreuel2002** [filecoin-project/filecoin-plus-client-onboarding#104]
---

# Client Allocation Questions 

## Core Information
- Name: Dustin greuel
- Website / Social Media: 
- Region: North America
- DataCap Requested: 5TiB
- Addresses to be Notarized: F047419
- Notary Requested: ann-shin

**Comment by ann-shin** [comment]
Hey @dgreuel2002  - thanks for your request. Can you kindly add more information / context here on:

yourself , e.g. include links to social media / news mentions etc
your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
your relationship with the data, especially with regard to copyright
how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
Thanks

**Comment by dgreuel2002** [comment]
https://www.linkedin.com/in/dustingreuel/
https://www.facebook.com/public/Dustin-Greuel
I am new to the crypto scene but carry 9 certifications from networking to VMWARE.
I joined Filecoin during mainet launch and went in with two other people. I have the physically hardware at my house and am hosting it  over a 1 Gbps connection. The other two are financially invested as I do all the server maint. hardware wise and software wise. I have been very active on slack these last 5 months and have spent 100's of hours educating myself on the process. I am still proving all the original data from launch and will continue to grow. I recently just upgraded to separate the miner/daemon from the seal machine so now I can seal 1 TB a day. I am looking to store public data on filecoin from https://github.com/filecoin-project/slingshot/blob/master/datasets.md 

I will store data in redundancy at least on two different miners in geographical locations in the USA

**Comment by ann-shin** [comment]
hi @dgreuel2002，pls, re-applied it in [https://plus.fil.org/]( https://plus.fil.org/) . I am so sorry,  my account was unavailable before.

For the first time, I suggest you apply for 1T, because we want to know how do you use the datacap. If you need more datacap, you can submit the next application later.
