### ISSUE TITLE
Client Allocation Request for: gnomAD

### ISSUE THREAD

**Issue by nmohammedcourtoiso** [filecoin-project/filecoin-plus-client-onboarding#1054]
---

# Client Allocation Questions 

## Core Information
- Name: gnomAD
- Website / Social Media: https://gnomad.broadinstitute.org/
- Region: North America
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1a7jgstwsyp4iiwrz5bde7gzksrnqhq6czlg72ky
- Notary Requested: swatchliu

@nmohammedcourtoiso Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.)
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?

Would you like to submit more company information on www.bytebase.cn?

Would you like to accept our face-to-face visit?

**Comment by nmohammedcourtoiso** [comment]
No. We are mainly in North America.
a. Our program was founded in June 1, 2016.
b. Our program has more than 120 researchers now.
c. The Genome Aggregation Database (gnomAD), is a coalition of investigators seeking to aggregate and harmonize exome and genome sequencing data from a variety of large-scale sequencing projects, and to make summary data available for the wider scientific community. The project is overseen by co-directors Heidi Rehm and Mark Daly, and steering committee members Daniel MacArthur, Benjamin Neale, Michael Talkowski, Anne O'Donnell-Luria, Konrad Karczewski, Grace Tiao, Matthew Solomonson, and Samantha Baxter. In its first release, which contained exclusively exome data, it was known as the Exome Aggregation Consortium (ExAC).
The v3.1 short variant data set provided on this website spans 76,156 genomes from unrelated individuals sequenced as part of various disease-specific and population genetic studies, and is aligned against the GRCh38 reference. The v2 short variant data set provided on this website spans 125,748 exomes and 15,708 genomes from unrelated individuals sequenced as part of various disease-specific and population genetic studies, totalling 141,456 individuals, and is aligned against the GRCh37 reference. We have removed individuals known to be affected by severe pediatric disease, as well as their first-degree relatives, so these data sets should serve as useful reference sets of allele frequencies for severe pediatric disease studies - however, note that some individuals with severe disease may still be included in the data sets, albeit likely at a frequency equivalent to or lower than that seen in the general population. The data released by gnomAD are available free of restrictions under the Creative Commons Zero Public Domain Dedication. This means that you can use it for any purpose without legally having to give attribution. 
d. You can check out more details by our twitter: @gnomad_project  https://twitter.com/gnomad_project
e. Now we need 5 TiB to storage the aggregation and release of summary data.
f. No
g. If you need more information about our program, we will do our best to meet your needs.
h. We'd be glad to have a meeting if we have an opportunity to visit China.

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaosbhqvl3qf7uolupzx5u4kkbmaz2kilpekz6mzfgzl5wwg6ngxg 
#### Address 
> f1a7jgstwsyp4iiwrz5bde7gzksrnqhq6czlg72ky
#### Datacap Allocated
> NaNB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaosbhqvl3qf7uolupzx5u4kkbmaz2kilpekz6mzfgzl5wwg6ngxg
