### ISSUE TITLE
Client Allocation Request for: 四川星河飞天科技有限公司

### ISSUE THREAD

**Issue by changlizhi** [filecoin-project/filecoin-plus-client-onboarding#1056]
---

# Client Allocation Questions 

## Core Information
- Name: 四川星河飞天科技有限公司
- Website / Social Media: https://stariverpool.io
- Region: Asia excl. Greater China
- DataCap Requested: 50TiB
- Addresses to be Notarized: f1fd7pgiygdwnsvxqj7n3f4ixuioq5btgok25mgzi
- Notary Requested: IPFSUnion

@changlizhi Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by IPFSUnion** [comment]
```
Hi, Stariver. I'd like to know more about your business. Can you kindly answer my following questions?
* individual and organization  
    1.	Please introduce yourself and your team briefly, and show me some your social accounts such as email address, WeChat official account and other evidence proving that you have the right to apply on behalf of the company.
    2.	For your organization, Please describe its time since inception, registration country，scale, named officers, project, industry reputation etc.
* track record
    1. How did you know about Filecoin? Please describe your understanding of Filecoin storage.
    2. Regarding your data you intend to store, What’s the original source of those data, and do you have any proof of ownership or authorization?
    3. Has your organization obtained DataCap before? 
* use plan
    1.	Please describe your plan to use DataCap briefly? (such as use case, miner etc.)
```

**Comment by changlizhi** [comment]
Dear notary, 
I will answer your questions on behalf of the Stariver

 individual or organization

1. 
* I am a developer of Stariver Company.
* My email is changlizhi@aliyun.com，my WeChat account is "changlizhime"
* WeChat Official Account of the company is "Stariverpool-IPfs"
* The corporate email is market@stariverpool.io.

2. You can check the official Accounts ownership to confirm Stariver ,then you can leave a message to verify whether I am a real employee and have the right to apply. (For example,  you can leave a message: "Do you authorize changlizhi@aliyun.com to apply for Filecoin datacap?" and leave your contact information, our colleagues will reply you by phone or email  ), Or any other method of validation that you think is better.

3. Stariver Technology Co., Ltd. is based in Chengdu, Sichuan Province, China, and has 40 employees.Our business is based on IPFS technology to provide users with cloud disk, P2P communication, short video browsing and associated social services. We are also involved in the filecoin ecosystem construction, node number is F01128320.


Track record

1. We've been actively involved in distributed storage projects, especially IPFS and Filecoin, since the first phase of the Space Race when we learned that they were coming online。
2. The name of our software is "Loongbox", which can be downloaded and installed in all major application stores and our official website. The APP uses IPFS technology as the underlying support, and users have been informed to authorize us to use their uploaded data before using the app.
3. This is our first application for datacap.

Use plan
1. We plan to use IPFS technology in "Loongbox"  and all files in it can be viewed cid and accessed in IPFS network. (For example, external gateway: ipfs.io/ipfs/bafkreif5ismnzx4iqbx2ygbf5vp5gv6nriouv5ulvum2d5deurpozq75qy .
Or our own gateway : 
https://ipfsgw.stariverpan.com/ipfs/bafkreif5ismnzx4iqbx2ygbf5vp5gv6nriouv5ulvum2d5deurpozq75qy.)  And we will continue to be used in the future.
