### ISSUE TITLE
Client Allocation Request for: Samil

### ISSUE THREAD

**Issue by Samilco31** [filecoin-project/filecoin-plus-client-onboarding#1057]
---

# Client Allocation Questions 

## Core Information
- Name: Samil
- Website / Social Media: https://www.samilenter.com/
- Region: Asia excl. Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3qtqwsgitaaiz6j5hoga2jx7wxwuob6lx4maxmlofllvrpswyvayhfmuyudsuc3ytl6bg7s6p4777acspdwiq
- Notary Requested: IPFSUnion

@Samilco31 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by IPFSUnion** [comment]
```
Hi, Samil. I'd like to know more about your business. Can you kindly answer my following questions?
* individual and organization  
    1.	Please introduce yourself and your team briefly, and show me some your social accounts such as email address, WeChat official account and other evidence proving that you have the right to apply on behalf of the company.
    2.	For your organization, Please describe its time since inception, registration country，scale, named officers, project, industry reputation etc.
* track record
    1. How did you know about Filecoin? Please describe your understanding of Filecoin storage.
    2. Regarding your data you intend to store, What’s the original source of those data, and do you have any proof of ownership or authorization?
    3. Has your organization obtained DataCap before? 
* use plan
    1.	Please describe your plan to use DataCap briefly? (such as use case, miner etc.)
```

**Comment by Samilco31** [comment]
Thanks for your replying.

* individual and organization  
    1. We are SAMIL ENTERPRISE CO., LTD. I'm an employee of the financial management team. We don't have a social account in our company, so please refer to the web page.
(https://www.samilenter.com/)
    2. We are a comprehensive construction company with a 60-year tradition established in 1958. It is located in Seoul, South Korea, and has abundant experience by participating in numerous facility construction.

* track record
    1. Filecoin received information from IT-related partners. I know that storage management is stable and cost-effective.
    2. We store all the data records we have constructed so far, so we have authority over them, and we can also show certificates.
    3. No.

* use plan
    1. As I said above, we have participated in numerous national infrastructure projects over the past 60 years and have vast amounts of data on them. It also has a large amount of performance in high-rise buildings, complex business facilities, GMP facilities, hospitals and research institutes, and will organize all data created in the process and store it in Datacap. I'll think more about minor. It plans to store 3~4 miners.

Thank you.
