### ISSUE TITLE
Client Allocation Request for: Samjung

### ISSUE THREAD

**Issue by Samjungee** [filecoin-project/filecoin-plus-client-onboarding#1059]
---

# Client Allocation Questions 

## Core Information
- Name: Samjung
- Website / Social Media: http://e-samjung.co.kr/gnuboard4/
- Region: Asia excl. Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3vnnnt6zokj2bfplbzrqiwukdi6y7xprt36vdrnljw752hturceqql5z4grkdwhqws4zxrly5ymyjptdv5oma
- Notary Requested: IPFSUnion

@Samjungee Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by IPFSUnion** [comment]
```
Hi, Samjung. I'd like to know more about your business. Can you kindly answer my following questions?
* individual and organization  
    1.	Please introduce yourself and your team briefly, and show me some your social accounts such as email address, WeChat official account and other evidence proving that you have the right to apply on behalf of the company.
    2.	For your organization, Please describe its time since inception, registration country，scale, named officers, project, industry reputation etc.
* track record
    1. How did you know about Filecoin? Please describe your understanding of Filecoin storage.
    2. Regarding your data you intend to store, What’s the original source of those data, and do you have any proof of ownership or authorization?
    3. Has your organization obtained DataCap before? 
* use plan
    1.	Please describe your plan to use DataCap briefly? (such as use case, miner etc.)
```

**Comment by Samjungee** [comment]
Hi, IPFS Union.

I'm Sooyoung Choi, a member of the technology management team. Please refer to our company's website. (http://e-samjung.co.kr/gnuboard4/)

We're Samjung Trading Co., Ltd., and we're a cosmetics raw material company. We are located in Gyeonggi-do, South Korea, and was established in 2009, and was converted into a corporation in 2011 and has been growing steadily so far.

We heard Filecoin from within our company. We only know information that it is easy to manage and store data.

Ownership of the product belongs to us because we store data about our product in storage.

We have never requested an assignment before.

We research and develop cosmetics raw materials and receive supplies from our partners and trade with manufacturers such as LG Household & Health Care. We will store all the data generated in this process in the Datacap. There are more than a thousand products that our company has researched and manufactured, and more products will continue to come out in the future. Inform our company and data (efficacy or research data) for each product will be publicly stored in the Datacap. We are planning on 5 miners. There is no specific minor yet.


Thank you.
