### ISSUE TITLE
Client Allocation Request for: [other PoW blockchains?]

### ISSUE THREAD

**Issue by miyazono** [filecoin-project/filecoin-plus-client-onboarding#106]
# Client Allocation Questions 

## Core Information
This is a weird one, but bear with me:

We know the root hash of, for example, the bitcoin blockchain.  Could we allocate datacap to a smart contract that would notarize other blockchains, for incentivized storage on Filecoin.  

I'm not sure if it'd even make sense if we could, more than a novelty factor, but I figured I'd at least drop the idea somewhere it might get noticed by someone who could evaluate it more rigorously.

-----------------------------

**Comment by jnthnvctr** [comment]
Interesting! This might be better to land in the https://github.com/filecoin-project/notary-governance repo! This is a bit more operational!
