### ISSUE TITLE
Client Allocation Request for: Video Games Live

### ISSUE THREAD

**Issue by jacintohessell** [filecoin-project/filecoin-plus-client-onboarding#1060]
---

# Client Allocation Questions 

## Core Information
- Name: Video Games Live
- Website / Social Media: https://videogameslive.com/
- Region: North America
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1dyxsubkh32i3wprhfivqmfme6opveloqbaqtwzq
- Notary Requested: TimWilliams00

@jacintohessell Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by TimWilliams00** [comment]
Hi，thanks for application! I would like to know your information.

Could you please introduce you and your company?
What kind of data do you want to store?
How many miners do you want to store? For how many regions?
What questions would you ask the miners?
What do you do to prevent overallocation?

**Comment by jacintohessell** [comment]
Sam Brown. I'm managing a team in the company.
Video Games Live™ is an award winning immersive concert event featuring music from the most popular video games of all time. Created, produced and hosted by world renowned game industry veteran and superstar Tommy Tallarico, top orchestras and choirs around the world perform along with exclusive synchronized video footage and music arrangements, synchronized lighting, well known internet solo performers, electronic percussion, live action and unique interactive segments to create an explosive one-of-a-kind entertainment experience.
video footage and audio files.
3-4miners are ok. 
We focus on time, price.
I think we will check datacap frequently.

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfrmx5tdv5w6m7i26ecokg4jgr4oh5flifsc4yywvekgnps75gek 
#### Address 
> f1dyxsubkh32i3wprhfivqmfme6opveloqbaqtwzq
#### Datacap Allocated
> NaNB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfrmx5tdv5w6m7i26ecokg4jgr4oh5flifsc4yywvekgnps75gek
