### ISSUE TITLE
Client Allocation Request for: 临海雨兰数据信息有限公司

### ISSUE THREAD

**Issue by taohua0528** [filecoin-project/filecoin-plus-client-onboarding#1066]
---

# Client Allocation Questions 

## Core Information
- Name: 临海雨兰数据信息有限公司
- Website / Social Media: N/A
- Region: Greater China
- DataCap Requested: 20TiB
- Addresses to be Notarized: f1lkzv4bfi5t7pb2aj2m7vmh3wdnhmhf53bqfxs7a
- Notary Requested: steven004

@taohua0528 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by steven004** [comment]
Hey @taohua0528  , thanks for your request. Can you kindly add more information / context here on:

1. yourself/ your organization (with links to official website/social media/news mentions etc)
2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners), if you are working with a service provider to store your data to Filecoin network, please name the provider.
5. How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
6. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
7. Would you be OK in posting deal transactions here?

Thanks

**Comment by taohua0528** [comment]
1.Linhai Yulan data information Co., Ltd. is a company on data storage. It cooperates with many media and industrial companies on data storage, participates in some distributed storage preaching activities, and provides computer room, network and hardware in business. Enterprise customers introduce advanced distributed storage technology and related ecological products to help customers quickly realize the change of software definition infrastructure.
2.Participate in some technical discussion activities online and offline and communicate with Chinese communities. We are very optimistic about the filecoin project, but we hope to store our business data on filecoin as an effective way to store data.
3.Music, video, documents, messages, etc. can disclose data without copyright disputes.
4.More than 4 miners currently intend to store data in Asia.
We are willing to store data on the filecoin network.
5.We hope that our applications and services can be supported by filecoin, and all participants can build an ecological chain of mutual profitability and sustainable development.
6.Our next plan is to store files and databases in the filecoin network for no profit.
7.Yes, you can trade.

**Comment by steven004** [comment]
Hey @taohua0528 , Two more questions:

1. The data you are willing to save into Filecoin is publicly available, or you will store private data?
2. Would you please share your website?

You can also share with me your business certificate, so that I could grant you more datacap, or I will grant you small amount for your test first, and later on you can have more once data verified.

**Comment by steven004** [comment]
@taohua0528 2TiB for you to start. 
Please post deals in this thread after you have done with the datacap, so that we could move one to assign you more.

**Comment by steven004** [comment]
Hey @taohua0528  , Your Datacap Allocation Request has been approved

**Message sent to Filecoin Network**
> [bafy2bzacedp2lqezauhq4y64c2hjq7sf3rorg2bznpsnmkhbmivbhroamztvq](https://filscan.io/tipset/message-detail?cid=bafy2bzacedp2lqezauhq4y64c2hjq7sf3rorg2bznpsnmkhbmivbhroamztvq)

**Address**
> [f1lkzv4bfi5t7pb2aj2m7vmh3wdnhmhf53bqfxs7a](https://filscan.io/address/general?address=f1lkzv4bfi5t7pb2aj2m7vmh3wdnhmhf53bqfxs7a)

**Datacap Allocated**
> 2.0TiB
