### ISSUE TITLE
Client Allocation Request for: Public Gold Marketing Sdn. Bhd

### ISSUE THREAD

**Issue by catalinaortga** [filecoin-project/filecoin-plus-client-onboarding#1070]
---

# Client Allocation Questions 

## Core Information
- Name: Public Gold Marketing Sdn. Bhd
- Website / Social Media: https://pgmall.my/
- Region: North America
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1ilszauz6cxgmio3l2mbqlespg47ccsgbjrnwgni
- Notary Requested: TimWilliams00

@catalinaortga Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by TimWilliams00** [comment]
Hi，thanks for application! I would like to know your information.

Could you please introduce you and your company?
What kind of data do you want to store?
How many miners do you want to store? For how many regions?
What questions would you ask the miners?
What do you do to prevent overallocation?

**Comment by catalinaortga** [comment]
This is Bob. He is responsible for technology.
PG Mall is an online shopping platform, operated by PG Mall Sdn. Bhd. and backed by Public Gold Marketing Sdn. Bhd. PG Mall is aimed to present a reliable business platform for the merchants to diversify their business portfolios from a global perspective. PG Mall shoppers have a wide range of product selection ranging from Electronics, Fashion , Books, Home & Living , Food & Beverages , Sports & Leisure , Kids & Baby , Health & Beauty , Automotive to E-Vouchers. The beauty behind this is PG Mall’s product count are increasing on a daily basis as we expand our family of sellers to sell online on this open marketplace.
Pictures related to the products.
2-3miners. We will divide data equally.
We will care about time and scale and we prefer large-scale miners.
Check it several times every 5 days.

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacectb2azlo3fn677w6j4yggek3zewyikdj5tb63spfeb7avxw4jlku 
#### Address 
> f1ilszauz6cxgmio3l2mbqlespg47ccsgbjrnwgni
#### Datacap Allocated
> NaNB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacectb2azlo3fn677w6j4yggek3zewyikdj5tb63spfeb7avxw4jlku
