### ISSUE TITLE
Client Allocation Request for: Premier Enterprise Media Services

### ISSUE THREAD

**Issue by catalinaortga** [filecoin-project/filecoin-plus-client-onboarding#1071]
---

# Client Allocation Questions 

## Core Information
- Name: Premier Enterprise Media Services
- Website / Social Media: https://www.pemsllc.com/
- Region: North America
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1qtrltekjn5ayrqy7uk35jawlqgryeouimlef7dy
- Notary Requested: TimWilliams00

@catalinaortga Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by TimWilliams00** [comment]
Hi，thanks for application! I would like to know your information.

Could you please introduce you and your company?
What kind of data do you want to store?
How many miners do you want to store? For how many regions?
What questions would you ask the miners?
What do you do to prevent overallocation?

**Comment by catalinaortga** [comment]
John. A manager.
As a technology consulting company, at Premier Enterprise Media Services we offer an extensive platform of computer integration services. We assemble cross-disciplined teams to implement a bridge across software, hardware, networking, communications, and storage systems to provide a solution that aligns with business processes, operational requirements, and overall IT strategies.With a focus on supporting infrastructure, operations, and business strategies, we can implement systems that blend technologies for managing data, content, media, and other digital assets. We also have direct experience delivering large IT projects involving integration of networks, data collection and information management services, data protection services, and cloud computing systems. 
Pictures and documents. About our clients.
3miners. North America.
About location of miners.
We will try to ensure allocate equally.
