### ISSUE TITLE
Client Allocation Request for: Opengate

### ISSUE THREAD

**Issue by jksfhajhflalf** [filecoin-project/filecoin-plus-client-onboarding#1073]
---

# Client Allocation Questions 

## Core Information
- Name: Opengate
- Website / Social Media: https://opengate.vip/
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3u7sj4ffs45u2syntwqydlp23hlx2kdbuclvml3p4nx2cwjpuepc2nbifeuntuv2etqb2yjcmrlnnnytepybq
- Notary Requested: MRJAVAZHAO

@jksfhajhflalf Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MRJAVAZHAO** [comment]
@jksfhajhflalf Please provide the following materials.

Organization name and business license (could be sent by email, 1625821971@qq.com); if you are an individual, please provide name, date of birth, working company and scale, employment certificate, social media accounts&follwers, and ID card (can be sent by email, 1625821971@qq.com);

When did you start learning about Filecoin? Please give a description about the projects you have participated in ? What do you want to get from Filecoin? Any suggestions or expectations for the Filecoin Network?

Is there any law risk? What percentage of questions are yours?

Please describe your organization, such as established time, , business scale, social media accounts&follwers, the number of employees, users volumn.

How about your data volume, source and later planning? Please describe the type, format, source, storage capacity, publicity (and if data could be public, how can others retrieve it?) of the data to be stored in Filecoin.

In which area do you plan to store you data? How many miners do you want to find ? Please list the miner ID. How about the proportion of the storage for each miner? What are the requirements about miners? At last, please state your redundancy plan.

Do you agree to disclose transaction information? If you get DataCap, please make the transaction information public on the Issue in time.

**Comment by jksfhajhflalf** [comment]
@MRJAVAZHAO Thanks.

Guangdong Bridgewater Digital Technology Co., LTD

We learned about Filecoin this year through a WEB3 project. We want to be able to store it in Filecoin to make NFT better stored on the chain.

There is no legal risk.

Introduction: OpenGate founded on December 31, 2020-20, OpenGate is an internationally renowned cryptographic digital art development agency. OpenGate is committed to "opening the door of the crypto art world and leading the Renaissance in the digital era", and is committed to promoting the development of the global crypto digital art market. The team is distributed in the United States, Canada, Australia, The United Kingdom, Beijing, Hong Kong, Guangzhou, Shenzhen and other countries and regions.
Wechat official account: Bridge water companion; Number of followers: 1000+
Number of employees: About 30.
Number of users: More than 500 individuals.

Amount of data: about 10T
Data sources: videos created by the company and data stored by customers
Planning: The plan is to store all subsequent NFT works on the Filecoin network.
Data format: video, picture
All data is publicly available.

We have no restrictions on storage areas and I hope to find more than three miners. The proportion of deposits per miner is probably no more than 50%.
We will cancel cooperation with miners who cannot provide permanent storage service in a timely manner.

I agree.

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary

#### Message sent to Filecoin Network
>bafy2bzacedsnlifz4jnruvwqlm3mx774cyawlrroilbph6yrdk4ecswnmzqna

#### Address
>f3u7sj4ffs45u2syntwqydlp23hlx2kdbuclvml3p4nx2cwjpuepc2nbifeuntuv2etqb2yjcmrlnnnytepybq

#### Datacap Allocated
>2 TiB

You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedsnlifz4jnruvwqlm3mx774cyawlrroilbph6yrdk4ecswnmzqna
