### ISSUE TITLE
Client Allocation Request for: Jinhua Zhiyang Information Technology Co., LTD

### ISSUE THREAD

**Issue by LANCY1998** [filecoin-project/filecoin-plus-client-onboarding#1076]
---

# Client Allocation Questions 

## Core Information
- Name: Jinhua Zhiyang Information Technology Co., LTD
- Website / Social Media: http://www.3303033.com/
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3tfhu2vmd5nywh3nnv5vvudn4bisvquyr5jemtfpd4qu3cil4ydjcrjpx3k77q4xms5dcladuagzk7q5lcf6q
- Notary Requested: MRJAVAZHAO

@LANCY1998 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MRJAVAZHAO** [comment]
@LANCY1998 Please provide the following materials.

Organization name and business license (could be sent by email, 1625821971@qq.com); if you are an individual, please provide name, date of birth, working company and scale, employment certificate, social media accounts&follwers, and ID card (can be sent by email, 1625821971@qq.com);

When did you start learning about Filecoin? Please give a description about the projects you have participated in ? What do you want to get from Filecoin? Any suggestions or expectations for the Filecoin Network?

Is there any law risk? What percentage of questions are yours?

Please describe your organization, such as established time, , business scale, social media accounts&follwers, the number of employees, users volumn.

How about your data volume, source and later planning? Please describe the type, format, source, storage capacity, publicity (and if data could be public, how can others retrieve it?) of the data to be stored in Filecoin.

In which area do you plan to store you data? How many miners do you want to find ? Please list the miner ID. How about the proportion of the storage for each miner? What are the requirements about miners? At last, please state your redundancy plan.

Do you agree to disclose transaction information? If you get DataCap, please make the transaction information public on the Issue in time.

**Comment by LANCY1998** [comment]
@MRJAVAZHAO Thanks for your reply. The following is our related information, please check it.

Jinhua Zhiyang Information Technology Co., LTD 
Business license has been sent to your mail.

This year; This is the first Filecoin project we have participated in; Hope to learn more about the blockchain, metasurverse project through Filecoin storage. 
 
There is no legal risk.
 
Our organization was established in 2014. At present, our business mainly faces the domestic market. Currently, we have no social media account and more than 50 employees.  The number of individual users is over 5000.
 
Currently, we hope to store about 10 TB. The data source is the enterprise's own monitoring data. We hope to have a deeper understanding of Filecoin through this storage.  The format are MP4 or MOV, and the data is not public. 
 
Plan to store in China, hope to cooperate with more than 3 miners, no fixed proportion of storage.  Miners need to ensure data integrity and support viewing over time. 
 
I agree to the disclosure.

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary

#### Message sent to Filecoin Network
>bafy2bzacedysgepwkgeftbwefd5rnlowbndh36swqn24rmpmxwarwsuroyni6

#### Address
>f3tfhu2vmd5nywh3nnv5vvudn4bisvquyr5jemtfpd4qu3cil4ydjcrjpx3k77q4xms5dcladuagzk7q5lcf6q

#### Datacap Allocated
>2 TiB

You can check the status of the message here: https://www.atpool.com/zh/chain/msg/bafy2bzacedysgepwkgeftbwefd5rnlowbndh36swqn24rmpmxwarwsuroyni6-1307951
