### ISSUE TITLE
Client Allocation Request for: LiangDao

### ISSUE THREAD

**Issue by hyunsoo12** [filecoin-project/filecoin-plus-client-onboarding#1081]
---

# Client Allocation Questions 

## Core Information
- Name: LiangDao
- Website / Social Media: https://liangdao.ai/
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1lusc7rktephp6o4w5mpvvz43mmv62ubmcy3niri
- Notary Requested: MasaakiNawatani

@hyunsoo12 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MasaakiNawatani** [comment]
Hi @hyunsoo12, I see that you are operating within the Greater China region. Please resubmit your DataCap Request and choose a Notary in the same region as your operations. I will close this request now. Thanks!
