### ISSUE TITLE
Client Allocation Request for: Net Activity Inc.

### ISSUE THREAD

**Issue by wcoreneburnn2** [filecoin-project/filecoin-plus-client-onboarding#1082]
---

# Client Allocation Questions 

## Core Information
- Name: Net Activity Inc.
- Website / Social Media: https://www.netactivity.us/
- Region: North America
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1xnfcild4h2ux2ympnbjop4kqjsxaz2ruskqdeta
- Notary Requested: TimWilliams00

@wcoreneburnn2 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by TimWilliams00** [comment]
Hi，thanks for application! I would like to know your information.

Could you please introduce you and your company?
What kind of data do you want to store?
How many miners do you want to store? For how many regions?
What questions would you ask the miners?
What do you do to prevent overallocation?

**Comment by wcoreneburnn2** [comment]
Hi. I'm Harry. Our company  is to help businesses become more competitive in their industry by utilizing Information Technology.OUR BUSINESS IS A SERVICE TO OUR CLIENTS.WE PROVIDE SERVICES AS FOLLOWS: CLOUD COMPUTING SERVICES---Net Activity’s enterprise cloud services are adaptable, scalable, reliable and affordable; VOIP BUSINESS PHONE SERVICES---Net Activity, Inc. installs and configures on premise based phone systems and IP based solutions; IT MANAGED SERVICES---Our monthly Server and Desktop monitoring solutions at a fixed price that takes the worry and anxiety out of knowing that your systems are up and running; SOFTWARE DEVELOPMENT SERVICES---Our software development services aim at developing solutions in alignment with the clients’ needs and invest in innovation to deliver client satisfaction.
Some data about clients' information and pictures.
2-3miners. We want to store in america. Because it can be convenient.
How long will you spend? Which regions will you do it?
Increase the frequency of inspections.
