### ISSUE TITLE
Client Allocation Request for: JKC Global

### ISSUE THREAD

**Issue by JKCGlobal** [filecoin-project/filecoin-plus-client-onboarding#1083]
---

# Client Allocation Questions 

## Core Information
- Name: JKC Global
- Website / Social Media: https://smartstore.naver.com/jkcglobal
- Region: Asia excl. Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3s27xfwb6pdne5qgfkdbf7ekuvpnfeo3iq2kuu6a2nixxxitsnlkmotrxtj2jtegewx6kvugo2lj4dy3pesrq
- Notary Requested: TimWilliams00

@JKCGlobal Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by JKCGlobal** [comment]
Hi. Williams. Thanks for your replying.

I'm Park, team leader of the management support team. Our company is JKC Global and sells fashion clothing, cosmetics, household goods distribution, and manufacturing wholesale and retail. We will store data and promotional videos for all the products we have in our Datacap. Datacap is needed because there is a vast amount of data on products that will be released later as well as the current products.

For us, 3-4 miners are enough.

I'll ask how much time they can spend on our storage.

We will check the Datacap often.

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5ebtzvwvmkcgasbn7iadbhpeynq5x445cjgfwlrga6jbk35psbe 
#### Address 
> f3s27xfwb6pdne5qgfkdbf7ekuvpnfeo3iq2kuu6a2nixxxitsnlkmotrxtj2jtegewx6kvugo2lj4dy3pesrq
#### Datacap Allocated
> NaNB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5ebtzvwvmkcgasbn7iadbhpeynq5x445cjgfwlrga6jbk35psbe
