### ISSUE TITLE
Client Allocation Request for: CM3

### ISSUE THREAD

**Issue by tskalskitim** [filecoin-project/filecoin-plus-client-onboarding#1086]
---

# Client Allocation Questions 

## Core Information
- Name: CM3
- Website / Social Media: https://cm3inc.com/
- Region: North America
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1rfoz2ygapvtx7qgkykqqexfdlbmc4plywoomh3q
- Notary Requested: TimWilliams00

@tskalskitim Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by TimWilliams00** [comment]
Hi，thanks for application! I would like to know your information.

Could you please introduce you and your company?
What kind of data do you want to store?
How many miners do you want to store? For how many regions?
What questions would you ask the miners?
What do you do to prevent overallocation?

**Comment by tskalskitim** [comment]
Yes, I can. My name is JOE MAJOR. I am the service operations manager. CM3 Building Solutions, Inc. is a privately-held corporation serving Pennsylvania, New Jersey, and Delaware. Our Solutions encompass Air, Energy, Security, Communications, and Maintenance Services. We identify, install, integrate, and service building solutions that inspire well-being.
We have a large amount of draft pictures of architectural design proposal for our clients.
We need 4 miners for mainly north america.
Questions about time、cost. These two are the most important.
We will calculate the amount we prepare to allocate.
