### ISSUE TITLE
Client Allocation Request for: Guangzhou Shanghong

### ISSUE THREAD

**Issue by uuoopee** [filecoin-project/filecoin-plus-client-onboarding#1089]
---

# Client Allocation Questions 

## Core Information
- Name: Guangzhou Shanghong
- Website / Social Media: gz-shanghong.com
- Region: Greater China
- DataCap Requested: 20TiB
- Addresses to be Notarized: f3vp2f66fv2rux5ax6h4o2we4z7kbx5eoro5ymbqxbdrxbodk3ecsnkgh6k5zl37xnzpbbj66wrbnc3zoo3g3a
- Notary Requested: MRJAVAZHAO

@uuoopee Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MRJAVAZHAO** [comment]
@uuoopee  Please provide the following materials.

 if you are an organization, Please describe your organization, such as established time, business scale, social media accounts&follwers, the number of employees, users volumn and business license (could be sent by email, 1625821971@qq.com); if you are an individual, please provide name, date of birth, working company and scale, employment certificate, social media accounts&follwers, and ID card (can be sent by email, 1625821971@qq.com);

When did you start learning about Filecoin? Please give a description about the projects you have participated in ? What do you want to get from Filecoin? Any suggestions or expectations for the Filecoin Network?

Is there any law risk? What percentage of questions are yours?

How about your data volume, source and later planning? Please describe the type, format, source, storage capacity, publicity (and if data could be public, how can others retrieve it?) of the data to be stored in Filecoin.

In which area do you plan to store you data? How many miners do you want to find ? Please list the miner ID. How about the proportion of the storage for each miner? What are the requirements about miners? At last, please state your redundancy plan.

Do you agree to disclose transaction information? If you get DataCap, please make the transaction information public on the Issue in time.

**Comment by uuoopee** [comment]
We are Guangzhou Shanghong Trading Co., LTD., founded in 2014. Our main business is import and export hardware products, electronic products wholesale, commodity trade wholesale, wine retail, and shipping processing of import and export documents. No social media account. The number of employees is about 20, and the number of users has reached more than 2000. The organization's business license has been sent to you.

We want to try distributed storage.

There is no legal risk.

We plan to store about 10 TB data, which are videos and pictures of company. These data could be public.

The plan is to store the data in China, about three miners, each with a storage ratio of less than 50%.

Willing to disclosure.

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary

#### Message sent to Filecoin Network
>bafy2bzacedfasoh3v6wqh4igvgtixttmhtqbdbsufkqxl367r2fro4sxg4wri

#### Address
>f3vp2f66fv2rux5ax6h4o2we4z7kbx5eoro5ymbqxbdrxbodk3ecsnkgh6k5zl37xnzpbbj66wrbnc3zoo3g3a

#### Datacap Allocated
>2 TiB

You can check the status of the message here: https://www.atpool.com/zh/chain/msg/bafy2bzacedfasoh3v6wqh4igvgtixttmhtqbdbsufkqxl367r2fro4sxg4wri-1307954
