### ISSUE TITLE
Client Allocation Request for: tianluo

### ISSUE THREAD

**Issue by mykylaturiya17** [filecoin-project/filecoin-plus-client-onboarding#1091]
---

# Client Allocation Questions 

## Core Information
- Name: tianluo
- Website / Social Media: http://www.kitchenidea.com.cn/#/CloudKit
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1frrnjahwxvc4z2et6trbmvofccz5sfmokakceri
- Notary Requested: ozhtdong

@mykylaturiya17 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I have some questions about you and your company:
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by mykylaturiya17** [comment]
1. My name is Xu Xia. I'm the Supervisor
2. Kitchenidea, formerly known as Hangzhou Chuyi Technology, was established in 2011. As a service provider specializing in intelligent high-end kitchen appliances, Tianluo Cloud Kitchen integrates product research and development, sales, manufacturing, logistics, one-stop procurement, and service to provide global customers with intelligent AI cooking robots.
    We have wechat official account: tianluoyunchu
3. Yes. I will email you.
4. 2miners.  We will divide to each miner equally.
5. Yes, we will. We want to use github.
6. We will use filfox to inspect miners. We will inspect creditable miners.

**Comment by mykylaturiya17** [comment]
Here it is.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceak4lh6jojepfxp2mukqbks35hmgjxfesynmm6rkhpwpvhao3c74m 
#### Address 
> f1frrnjahwxvc4z2et6trbmvofccz5sfmokakceri
#### Datacap Allocated
> NaNB
#### Signer Address
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceak4lh6jojepfxp2mukqbks35hmgjxfesynmm6rkhpwpvhao3c74m
