### ISSUE TITLE
Client Allocation Request for: DukeSoft (Free Music Archive)

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/filecoin-plus-client-onboarding#1096]
---

# Client Allocation Questions 

## Core Information
- Name: DukeSoft (Free Music Archive)
- Website / Social Media: https://ffma.dukesoft.nl
- Region: Europe
- DataCap Requested: 20TiB
- Addresses to be Notarized: f3soaazrjuc4os4mtov5miqkqtozzeemvhugamp3och7yuhk6jjndibfdmudtwblsxzjh4cgua4g3aoatqiuxa
- Notary Requested: s0nik42

@RobQuistNL Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by RobQuistNL** [comment]
Same data / address / project as this one: https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1014

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebi3p5aq3r7hyjd7jzelv26qsplnzmka3pnowbetcvop3x7c26zoi 
#### Address 
> f3soaazrjuc4os4mtov5miqkqtozzeemvhugamp3och7yuhk6jjndibfdmudtwblsxzjh4cgua4g3aoatqiuxa
#### Datacap Allocated
> NaNB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebi3p5aq3r7hyjd7jzelv26qsplnzmka3pnowbetcvop3x7c26zoi

**Comment by mr-spaghetti-code** [comment]
Hi,

It looks like you received 26TiBs of DataCap to date but have spent less than 20% of it so far.

We would love to understand if there's anything holding you back. We are working hard to make the data onboarding process easier for clients like you and your feedback is very valuable. If you have a moment, please fill in this survey: https://forms.gle/s6AuTXZPZSMokscLA

If you have any feedback or would like to consult with an expert, please let me know. 

Thanks,

João Fiadeiro
Product Manager, Large Data Client Onboarding
Protocol Labs

**Comment by RobQuistNL** [comment]
The issue here is that I tried to make deals on the regular lotus network using the provided tools (using lotus to find miners and make deals).

I've tried making over 150.000 deals, from which 15.000 came through, from which about only 300 really ended up sealed on chain.

Next time I'm using offline deals with manually selected miners, as I've been doing for the slingshot restore (over 2 PiB in deals)
