### ISSUE TITLE
Client Allocation Request for: 四川星河飞天科技有限公司

### ISSUE THREAD

**Issue by changlizhi** [filecoin-project/filecoin-plus-client-onboarding#1097]
---

# Client Allocation Questions 

## Core Information
- Name: 四川星河飞天科技有限公司
- Website / Social Media: www.stariverpool.io
- Region: Greater China
- DataCap Requested: 20TiB
- Addresses to be Notarized: f1fd7pgiygdwnsvxqj7n3f4ixuioq5btgok25mgzi
- Notary Requested: neogeweb3

@changlizhi Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by changlizhi** [comment]
dear @neogeweb3 ,
sorry to apply again,because I realized that the miner address like `f2ihq67iqx2cj7fzi6h4co5d7qyxmgj3ad3ytkeua` or shorter address `f01128320` cant be used in deals.
these are my trying:
![image](https://user-images.githubusercontent.com/4144452/141393639-24459b55-b4b7-4bca-bf34-bc04a963682f.png)
![image](https://user-images.githubusercontent.com/4144452/141393656-0ca018c0-9250-4231-8d66-567a4403bb86.png)
so I want to apply another datacap,and please take back the datacap witch is allocated to `f2ihq67iqx2cj7fzi6h4co5d7qyxmgj3ad3ytkeua` if it can be take back

this is my info below witch is replied in issue #1077 

```

1. My email is changlizhi@aliyun.com,my wechat is changlizhime,my github account is changlizhi
2. I'm a developer of Stariver Technology Co., Ltd. witch is based in Chengdu, Sichuan Province, China, and has 40 employees, officers of our organization is "胡杨",time since inception is 09/2020.you can find these informations in our official website https://www.stariverpool.io/contact.html
3. We apply datacap for our app "小龙云盘" ,witch can be used in all regions of global.
4. The app named “小龙云盘” is the product of the datacap will be used,you can install it from appstore(android in vivo store)or you can find it in our clouddisk websit https://www.stariverpan.com/ for pc client(mobile client too),this app is based on ipfs network,all of the datas on the app is uploaded to ipfs,you can verify any right cid by using our own gateway https://ipfsgw.stariverpan.com/ipfs/cid... (if you dont have any cid ,the app will give you one if you upload an asset,you can alse seach it on external ipfs gateway if you get one),and there is almost 2Tb data in it(we just put this app online for about 1 month)
5. I think that Allocating the assets of the app to filecoin is the advanced feature,so we are applying the datacap
6. 6-12 miners.but there are no specially designated miners now,we will find the miners on https://plus.fil.org/miners first
7. I agree. I will check it carefully
```

and abort the 5 option about advanced feature `5.Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.`,we dont make a decision up to now,cause the path of useing filecion-plus is not done.

**Comment by neogeweb3** [comment]
I would reopen this issue if #1077 problem persists.

**Comment by neogeweb3** [comment]
manually post tx: https://filfox.info/en/message/bafy2bzacedweq35xhlffuz4mrodadlakxklajb4g4kna6nat26f2u7ha2xj7q

100GiB of DataCap was successfully allocated to f1fd7pgiygdwnsvxqj7n3f4ixuioq5btgok25mgzi

**Comment by changlizhi** [comment]
@neogeweb3 ,ok thank you ,I will leave that DataCap in address f01128320
