### ISSUE TITLE
Client Allocation Request for: LAC

### ISSUE THREAD

**Issue by shaneythreadkell** [filecoin-project/filecoin-plus-client-onboarding#1101]
---

# Client Allocation Questions 

## Core Information
- Name: LAC
- Website / Social Media: https://lac-group.com/
- Region: North America
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1kr2toqkm7cblvabe7klx4ekkkpr5kgzdn426nzq
- Notary Requested: TimWilliams00

@shaneythreadkell Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by TimWilliams00** [comment]
Hi，thanks for application! I would like to know your information.

Could you please introduce you and your company?
What kind of data do you want to store?
How many miners do you want to store? For how many regions?
What questions would you ask the miners?
What do you do to prevent overallocation?

**Comment by shaneythreadkell** [comment]
YES.  Jason.The story of LAC Group began in 1986 when Deborah Schwarz left her library director position at a major law firm in Los Angeles and founded Libraries, Inc. When asked by a client if she would be willing to manage the firm’s library, she recognized an opportunity to expand her business through managed services.
LAC Group has grown, both through opportunities and strategic acquisitions, to add greater value to our clients by offering more comprehensive services for managing and leveraging information. Today we are a diversified, business-to-business information services provider. Our clients include Fortune 500 corporations, major law firms, federal government agencies, media and entertainment companies and leading universities throughout the United States and Canada.
We will storage data of libraries.
2 miners are enough. For North America.
How much will it spend totally?
We'll check it multiple times.
