### ISSUE TITLE
Client Allocation Request for: Hunter Jozwiak

### ISSUE THREAD

**Issue by hjozwiak** [filecoin-project/filecoin-plus-client-onboarding#1105]
---

# Client Allocation Questions 

## Core Information
- Name: Hunter Jozwiak
- Website / Social Media: https://itmslaves.com/users/sektor
- Region: North America
- DataCap Requested: 1TiB
- Addresses to be Notarized: f14tmi3ac25yu77wa5x2tqywnfdfcptfgzczr3jba
- Notary Requested: MegTei

@hjozwiak Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by hjozwiak** [comment]
Sorry for the duplicates; I lost track of what was on my clipboard the first two times.

**Comment by MegTei** [comment]
HI @hjozwiak I'll run through some application triage questions with you, can you answer as best as possible, ping me if anything is unclear

DATACAP REQUEST

1. In which region(s) do you intend to use the DataCap?
2. How did you hear about the FIL+ program? Do you have a good understanding of the network and/or are involved in the web3.0 community?
3. What is your registered business name & address?
4. Provide a description of your business, the industry you work in and what you do.
5. What type/ category of data is being stored? (E.g Public data - back-up files, private encrypted files etc)
6. How much data will you onboard each week?
7. For how long do you intend to store your data with Filecoin?
8. Have you previously received DataCap? If so, please link to any previous requests/ github issues.
9. Are you aware of and do you intend to use any advanced features (e.g. Fast Retrieval) with your storage deals? If so, please specify the feature.
10. How frequently do you intend to retrieve data stored on Filecoin e.g. monthly, a couple times a year, infrequently.
MINER DETAILS
11. How many miners do you plan on using to distribute the data, providing their ID's?
12. Are any of those miners controlled by yourself / your organization and if so, what is the percentage?
13. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?
