### ISSUE TITLE
Client Allocation Request for: Blucon

### ISSUE THREAD

**Issue by Blucon** [filecoin-project/filecoin-plus-client-onboarding#1109]
---

# Client Allocation Questions 

## Core Information
- Name: Blucon
- Website / Social Media: http://blucon.io/
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3wxegeffsajm7qgmv7rqda373kbzuhkiwhmihk7s3bmzc4f7mh76zsswls7nydtcs4slmurcy6w2chxtcwiva
- Notary Requested: ozhtdong

@Blucon Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Blucon** [comment]
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1069

**Comment by Blucon** [comment]
![KakaoTalk_20211103_104619966](https://user-images.githubusercontent.com/93633951/141879020-e253756d-1f90-42bf-bb64-96e2e61a5710.jpg)

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea74r37isf5fitnkgtopzucuejiyeivsriuptw5td3k5bvq3icnai 
#### Address 
> f3wxegeffsajm7qgmv7rqda373kbzuhkiwhmihk7s3bmzc4f7mh76zsswls7nydtcs4slmurcy6w2chxtcwiva
#### Datacap Allocated
> NaNB
#### Signer Address
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea74r37isf5fitnkgtopzucuejiyeivsriuptw5td3k5bvq3icnai
