### ISSUE TITLE
Client Allocation Request for: CoinHub Korea

### ISSUE THREAD

**Issue by CoinhubKorea** [filecoin-project/filecoin-plus-client-onboarding#1110]
---

# Client Allocation Questions 

## Core Information
- Name: CoinHub Korea
- Website / Social Media: https://coinhubkorea.com/
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3thgy2b3m25t34eltpfeuayayqb2ca43ls37pk4z7rjc3pl2w2owgjjxn26w6n27eronrrdjauifhmq4wr73q
- Notary Requested: ozhtdong

@CoinhubKorea Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by CoinhubKorea** [comment]
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1068

**Comment by CoinhubKorea** [comment]
[주식회사 코인허브코리아 사업자등록증(최신).pdf](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/7542632/default.pdf)

**Comment by CoinhubKorea** [comment]
Please check this

**Comment by ozhtdong** [comment]
Please change to other notary in your region.

**Comment by CoinhubKorea** [comment]
I can't accept your opinion.

Didn't you accept requests from other regions?
