### ISSUE TITLE
Client Allocation Request for: pchome

### ISSUE THREAD

**Issue by jaylinneingree** [filecoin-project/filecoin-plus-client-onboarding#1118]
---

# Client Allocation Questions 

## Core Information
- Name: pchome
- Website / Social Media: https://www.pchome.com.tw
- Region: Asia excl. Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1vmxm2biqcs4scqfibjdf4yrr5lumwmm3fp6wjfq
- Notary Requested: ozhtdong

@jaylinneingree Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I have some questions about you and your company:
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by jaylinneingree** [comment]
Lily Huang. I'm a manager.
jwebsite was founded in 1996 and is one of Taiwan’s portals. In July 1998,  PChome Online Inc. was formally established. In January 2005, it was listed on the OTC under the "PChome" code 8044. Became the first Internet service company listed on the Taiwan Stock Exchange. After more than ten years of hard work, PChome is now the leading integrated Internet service provider group in Taiwan, providing e-commerce and online financial services. Services such as portals and portals provide users with the most local and high-quality Internet services.
Sure, I can email you.
4miners I think. We will allocate a share of no more than 30% to each miner.
Github is the best choice. We will use filfox to inspect miners. We want creditable miners.

**Comment by jaylinneingree** [comment]
please check it， thank you

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7cy5qd7ek6xn63ekkzuxc36k7mfpkdj5pqkn2vlntjlnomnbudu 
#### Address 
> f1vmxm2biqcs4scqfibjdf4yrr5lumwmm3fp6wjfq
#### Datacap Allocated
> NaNB
#### Signer Address
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7cy5qd7ek6xn63ekkzuxc36k7mfpkdj5pqkn2vlntjlnomnbudu

**Comment by mr-spaghetti-code** [comment]
Hi,

It looks like you received 15TiBs of DataCap to date but have spent less than 20% of it so far.

We would love to understand if there's anything holding you back. We are working hard to make the data onboarding process easier for clients like you and your feedback is very valuable. If you have a moment, please fill in this survey: https://forms.gle/s6AuTXZPZSMokscLA

If you have any feedback or would like to consult with an expert, please let me know. 

Thanks,

João Fiadeiro
Product Manager, Large Data Client Onboarding
Protocol Labs
