### ISSUE TITLE
Client Allocation Request for: [UJOONET]

### ISSUE THREAD

**Issue by ozzi0221** [filecoin-project/filecoin-plus-client-onboarding#1120]
# Client Allocation Questions 

## Core Information
- Name: [UJOONET]
- Website / Social Media: [ujoonet.com, mylinkplus.io]
- Region: Asia excl. Greater China
- DataCap Requested: [3TiB]
- Addresses to be Notarized: f3rpablljxoko6djyzbkmtqukfa6dnrzjuzflokeuou4x42nyrfa64e5f4isjm4yfv4mb5v6jtfqgx7hchkh4a
-Notary Requested: XnMatrixSV
-----------------------------

**Comment by ozzi0221** [comment]
Please refer to the previous request which is "Client Allocation Request for: UJOONET #553".

**Comment by XnMatrixSV** [comment]
@ozzi0221 Please attach transaction records to the previous application (https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/868) as the application record.

**Comment by ozzi0221** [comment]
[ujoonet transaction record (#868).xlsx](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/7568303/ujoonet.transaction.record.868.xlsx)
rd.868.xlsx)

**Comment by ozzi0221** [comment]
Do you need another records? If so, could you advice me any sample?

> XnMatrixSV

**Comment by ozzi0221** [comment]
We reduced "Datacap requested" to 3 TiB.

**Comment by ozzi0221** [comment]
We will open webhard for enterprize market and live streamimg platform soon, next month. Do we have to move to large dataset request?
