### ISSUE TITLE
Client Allocation Request for: GMWBR INC

### ISSUE THREAD

**Issue by Vincentof** [filecoin-project/filecoin-plus-client-onboarding#1122]
---

# Client Allocation Questions 

## Core Information
- Name: GMWBR INC
- Website / Social Media: www.gmwbr.org
- Region: North America
- DataCap Requested: 20TiB
- Addresses to be Notarized: f3w4wlayytfmsay6gu5phhij5r4yyx7t4xxrlosgotlmqg5eih3co5atsra4h2pe4qd2d6c76bvhj6nwim7lgq
- Notary Requested: XnMatrixSV

@Vincentof Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by XnMatrixSV** [comment]
@Vincentof Please attach transaction records to the previous application (#868) as the application record.
