### ISSUE TITLE
Client Allocation Request for: 北京东星源科技发展有限公司

### ISSUE THREAD

**Issue by totoactor** [filecoin-project/filecoin-plus-client-onboarding#1123]
---

# Client Allocation Questions 

## Core Information
- Name: 北京东星源科技发展有限公司
- Website / Social Media: http://www.hbzjtp.org/
- Region: Greater China
- DataCap Requested: 50TiB
- Addresses to be Notarized: f3sp77fqqmknt6ectd5vf7h4ofqfwkkdeyb6jzy6swyxdqavn6c67zp34rfsbktxnwptnozhqlcmtzf4wdssva
- Notary Requested: MRJAVAZHAO

@totoactor Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MRJAVAZHAO** [comment]
@totoactor  Please provide the following materials.

if you are an organization, Please describe your organization, such as established time, business scale, social media accounts&follwers, the number of employees, users volumn and business license (could be sent by email, 1625821971@qq.com); if you are an individual, please provide name, date of birth, working company and scale, employment certificate, social media accounts&follwers, and ID card (can be sent by email, 1625821971@qq.com);

When did you start learning about Filecoin? Please give a description about the projects you have participated in ? What do you want to get from Filecoin? Any suggestions or expectations for the Filecoin Network?

Is there any law risk? What percentage of questions are yours?

How about your data volume, source and later planning? Please describe the type, format, source, storage capacity, publicity (and if data could be public, how can others retrieve it?) of the data to be stored in Filecoin.

In which area do you plan to store you data? How many miners do you want to find ? Please list the miner ID. How about the proportion of the storage for each miner? What are the requirements about miners? At last, please state your redundancy plan.

Do you agree to disclose transaction information? If you get DataCap, please make the transaction information public on the Issue in time.

**Comment by totoactor** [comment]
@MRJAVAZHAO I‘m sorry for late reply.
Beijing Dongxingyuan Science and Technology Development Co., Ltd. is a high-tech enterprise dedicated to creating smart archives and electronic archives application based on mixed reality technology. Digital archives management solutions. Through virtual reality technology and digital twin technology for the current archives digital transformation and construction.

Incorporation duration: 9 years
Team Member: ＜80
Business Scope: world
Number of Users: more than 100 business VIP members
Official website: http://www.hbzjtp.org
Project:  Smart archives and Electronic archives application based on mixed reality technology		

No previous exposure to IPFS/Filecoin.		
	
There is no legal risk.		
	
The data we'll store in Filecoin includes Electronic files, pictures, documents, journals and etc. 
Data Volume is more than 1000TIB

Digital archives management solutions. Through virtual reality technology and digital twin technology for the current archives digital transformation and construction. The cataloging output and input management of all archival files, and finally through the integration of the characteristics and advantages of optical, magnetic and electric mixed storage media for hierarchical storage and unified management of data. Provides intelligent optical storage services for backup, archiving, and disaster recovery data, ensuring secure, long-term, and low-cost storage of important data. Its products and technical services are widely used in archives, public security law, educational research institutes, oil exploration, finance, media assets, social networking sites and other fields.		
		
China.We'd like to cooperate with five.		
	
No

**Comment by MRJAVAZHAO** [comment]
Your Datacap Allocation Request has been approved by the Notary

Message sent to Filecoin Network
bafy2bzaceddjht4zlmwmopzwzxvtdenxaubcb6szjt7dlmcmy2leanaffj4i2

Address
f3sp77fqqmknt6ectd5vf7h4ofqfwkkdeyb6jzy6swyxdqavn6c67zp34rfsbktxnwptnozhqlcmtzf4wdssva

Datacap Allocated
2 TiB

You can check the status of the message here: https://www.atpool.com/zh/chain/msg/bafy2bzaceddjht4zlmwmopzwzxvtdenxaubcb6szjt7dlmcmy2leanaffj4i2-1320279
