### ISSUE TITLE
Client Allocation Request for: Human EV

### ISSUE THREAD

**Issue by Humax-EV** [filecoin-project/filecoin-plus-client-onboarding#1126]
---

# Client Allocation Questions 

## Core Information
- Name: Human EV
- Website / Social Media: https://www.humaxev.com/
- Region: Asia excl. Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3rlg63jbpkauu4e5pawou5rl2t7zkmidditj6fos7anpmiav4bblqd6u47qwvi4qtbzqw7ytyr3y23gogbw6q
- Notary Requested: ozhtdong

@Humax-EV Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I have some questions about you and your company:
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?
