### ISSUE TITLE
Client Allocation Request for: jkopay

### ISSUE THREAD

**Issue by fletcher331** [filecoin-project/filecoin-plus-client-onboarding#1128]
---

# Client Allocation Questions 

## Core Information
- Name: jkopay
- Website / Social Media: https://www.jkos.com/
- Region: Asia excl. Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1vxl5xdawg7kwcuvtawracbzfwmiy3mpfbh3abgq
- Notary Requested: ozhtdong

@fletcher331 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I have some questions about you and your company:
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by ozhtdong** [comment]
Thanks for your application. I have some questions about you and your company:
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by fletcher331** [comment]
1. My name is Daoze Chen, a manager of the company.
2. Our company is called Jkopay, by linking your bank accounts you will get 2% more rebate on payments and no fees on transfers. We are the leading company in payment solutions in Taiwan, transfers can be made anywhere, anytime by simply scanning the QR codes.
3. An email will be sent to you shortly.
4. I plan to have 2 miners and distribute the workloads evenly.
5. Github will be the primary platform and yes i intend to make my decisions public.
6. Filfox will be used for supervision, stability and reliability are the qualities we value the most.

**Comment by fletcher331** [comment]
hi:

See attachment for our company's license.

Best,

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebzxbanh3oalwmkyjohxoz5frudqwabbwr7m77332v3ijn2rnzexw 
#### Address 
> f1vxl5xdawg7kwcuvtawracbzfwmiy3mpfbh3abgq
#### Datacap Allocated
> NaNB
#### Signer Address
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebzxbanh3oalwmkyjohxoz5frudqwabbwr7m77332v3ijn2rnzexw
