### ISSUE TITLE
Client Allocation Request for: 飞图影像

### ISSUE THREAD

**Issue by llb890427** [filecoin-project/filecoin-plus-client-onboarding#1129]
# Client Allocation Questions 

## Core Information
- Name: 飞图影像
- Website / Social Media: http://www.ftimage.cn/
- DataCap Requested: 100T
- Addresses to be Notarized:f12y74czbkrjizcwwudvrsfdbmgpxarfrpfovpjwq
- Notary Requested: ozhtdong

-----------------------------

**Comment by ozhtdong** [comment]
Thanks for your application. I have some questions about you and your company:
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by llb890427** [comment]
1、你好，我是Bob。我们希望在分布式存储上以更加安全、更低成本下长期存储我们的医疗数据，这些数据本是根据政策需要保持长久的存储生命周期。并且数据量庞大，目前我们的数据有超过3PB。
 2、一家专注于提供医疗影像大数据管理应用服务的高新技术企业。基于大数据、云计算、人工智能、移动互联网技术、医学影像科学的融合创新，自主研发“专业影像云+人工智能应用平台”，以医学影像云服务为核心，提供“软件+硬件+服务”的完整解决方案。使各级医疗机构实现信息化建设和“互联网+”应用，促进健康中国建设。
3、可以提供邮件地址吗？单独发给你。
4、大概使用2、3个。相对平均的分配。
5.你会公开记录你的分配决定吗？您将使用哪个平台？
医疗数据本是病人隐私数据，难以公开。但是希望能找到一个可以验证的方法，或者是其他协议。Github是个不错的平台。
6.您将使用什么方法/工具来检查矿工？你会考察矿工的哪些方面？
使用FilFox浏览器。安全稳定。

**Comment by llb890427** [comment]
1. Hello, I'm Bob. We want to store our medical data on distributed storage for the long term at a more secure and lower cost, which is required by policy to maintain a long storage life cycle. And the amount of data is huge. At present, we have more than 3PB of data.
2. A high-tech enterprise focusing on providing medical image big data management application services. Based on the fusion innovation of big data, cloud computing, artificial intelligence, mobile Internet technology and medical imaging science, the company independently develops "Professional imaging cloud + ARTIFICIAL intelligence application platform", with medical imaging cloud service as the core, providing a complete solution of "software + hardware + services". Medical institutions at all levels will realize it application and "Internet Plus" application to promote the building of a healthy China.
3. Can you provide your email address? Send it to you separately.
4. Use about 2 or 3. A relatively even distribution.
5. Do you publicly record your allocation decisions? Which platform will you use?
Medical data is patient private data and difficult to disclose. But hopefully we can find a way to verify that, or some other protocol. Github is a great platform.
6. What methods/tools will you use to check miners? What would you look at in a miner?
Use the FilFox browser. Security and stability.

**Comment by llb890427** [comment]
1. Hello, I'm Bob. We want to store our medical data on distributed storage for the long term at a more secure and lower cost, which is required by policy to maintain a long storage life cycle. And the amount of data is huge. At present, we have more than 3PB of data.
2. A high-tech enterprise focusing on providing medical image big data management application services. Based on the fusion innovation of big data, cloud computing, artificial intelligence, mobile Internet technology and medical imaging science, the company independently develops "Professional imaging cloud + ARTIFICIAL intelligence application platform", with medical imaging cloud service as the core, providing a complete solution of "software + hardware + services". Medical institutions at all levels will realize it application and "Internet Plus" application to promote the building of a healthy China.
3. Can you provide your email address? Send it to you separately.
4. Use about 2 or 3. A relatively even distribution.
5. Do you publicly record your allocation decisions? Which platform will you use?
Medical data is patient private data and difficult to disclose. But hopefully we can find a way to verify that, or some other protocol. Github is a great platform.
6. Use FilFox. Security and stability.

**Comment by llb890427** [comment]
@ozhtdong Please check our reply. If you have any questions, we can supplement it as soon as possible

**Comment by ozhtdong** [comment]
Is your dataset public or not? Where could we download them?
