### ISSUE TITLE
Client Allocation Request for: Dong Fong Technologies Vietnam Company Limited

### ISSUE THREAD

**Issue by viet9991** [filecoin-project/filecoin-plus-client-onboarding#1136]
---

# Client Allocation Questions 

## Core Information
- Name: Dong Fong Technologies Vietnam Company Limited
- Website / Social Media: http://vn.dongfong.com.tw/contact-page.html
- Region: Asia excl. Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1qhxirxuq3l6ctigantm7csbh5wyy54eq4dzaz5y
- Notary Requested: ozhtdong

@viet9991 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I have some questions about you and your company:
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by viet9991** [comment]
1. My name is Pham, I'm the CFO
2. We have established for 13 years, from the beginning of selling equipment until to reach into internet service, Dong Fong Technology (DFT) always tries hard to provide customers "one- stop" service. After the completion of the IDC in Nei Hua, Taiwan, Dong Fong's business lines have been expanding and growing rapidly. The turnover of the two recent years has doubled. Internet
We provide server room planning and construction, low voltage intelligentize planning and construction, software development.
3.![Dongfong](https://user-images.githubusercontent.com/94895599/143005114-a250da6d-e5e5-4973-9258-054f2f3343af.png)
4. 2 miners and the data will be assigned equally
5. Yes the whole process will be public
6. Filfox would be an ideal approach. Stable ones are prefered

**Comment by viet9991** [comment]
check the attachment

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceawixeqiwyj3g3xilwvcsn2we6clrrr2sg6m225sj2he7rn7syevw 
#### Address 
> f1qhxirxuq3l6ctigantm7csbh5wyy54eq4dzaz5y
#### Datacap Allocated
> NaNB
#### Signer Address
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceawixeqiwyj3g3xilwvcsn2we6clrrr2sg6m225sj2he7rn7syevw
