### ISSUE TITLE
Client Allocation Request for: theseaer

### ISSUE THREAD

**Issue by runtuer** [filecoin-project/filecoin-plus-client-onboarding#1137]
---

# Client Allocation Questions 

## Core Information
- Name: theseaer
- Website / Social Media: www.runtuer.com
- Region: Greater China
- DataCap Requested: 100TiB
- Addresses to be Notarized: f3u3unadf654vezf62cd4jo6r7h6qpkx26g5amcdc3oe6rmpmk2nfosfd2kjkdhj4ndvr626gsm7fhpmt7gg2q
- Notary Requested: MRJAVAZHAO

@runtuer Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MRJAVAZHAO** [comment]
Please provide the following materials.

if you are an organization, Please describe your organization, such as established time, business scale, social media accounts&follwers, the number of employees, users volumn and business license (could be sent by email, 1625821971@qq.com); if you are an individual, please provide name, date of birth, working company and scale, employment certificate, social media accounts&follwers, and ID card (can be sent by email, 1625821971@qq.com);

When did you start learning about Filecoin? Please give a description about the projects you have participated in ? What do you want to get from Filecoin? Any suggestions or expectations for the Filecoin Network?

Is there any law risk? What percentage of questions are yours?

How about your data volume, source and later planning? Please describe the type, format, source, storage capacity, publicity (and if data could be public, how can others retrieve it?) of the data to be stored in Filecoin.

In which area do you plan to store you data? How many miners do you want to find ? Please list the miner ID. How about the proportion of the storage for each miner? What are the requirements about miners? At last, please state your redundancy plan.

Do you agree to disclose transaction information? If you get DataCap, please make the transaction information public on the Issue in time.

**Comment by MRJAVAZHAO** [comment]
You can open this issue when you want to apply again.
