### ISSUE TITLE
Client Allocation Request for: Ruten

### ISSUE THREAD

**Issue by hipeterkk** [filecoin-project/filecoin-plus-client-onboarding#1138]
---

# Client Allocation Questions 

## Core Information
- Name: Ruten
- Website / Social Media: https://www.ruten.com.tw/
- Region: Asia excl. Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1ueitq6m743a23bxjnfsjp73a253yabho2sxhjgi
- Notary Requested: ozhtdong

@hipeterkk Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I have some questions about you and your company:
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by hipeterkk** [comment]
1. My name is Tung Chee-hwa, I work in marketing department.
2. Ruten is a PChome & eBay JV Company and the biggest marketplace in Taiwan, stands not only the Taiwan No.1 C2C marketplace, but also the first e-commerce platform with more than 100 billions GMV. 
3. Check email
4. Even distribution for 2 miners
5. Allocation process will be transparent and public for sure.
6. Filfox is the way to go, minors with stable nodes.

**Comment by hipeterkk** [comment]
check it out

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacechrzptbboadfr7nzp5hhfouqk23jt3lx6e6h64gkjxbo2ytclru4 
#### Address 
> f1ueitq6m743a23bxjnfsjp73a253yabho2sxhjgi
#### Datacap Allocated
> NaNB
#### Signer Address
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechrzptbboadfr7nzp5hhfouqk23jt3lx6e6h64gkjxbo2ytclru4
