### ISSUE TITLE
Client Allocation Request for: Beijing Blue Qiyuan Technology Ltd. 

### ISSUE THREAD

**Issue by uupptoday** [filecoin-project/filecoin-plus-client-onboarding#1139]
---

# Client Allocation Questions 

## Core Information
- Name: Beijing Blue Qiyuan Technology Ltd. 
- Website / Social Media: http://www.tpjx.org/
- Region: Greater China
- DataCap Requested: 50TiB
- Addresses to be Notarized: f3qoc4rldxutogaa72hbnml3rqh6xlbyy4m562l5jwumyyfdqqupen446gh5gwkra5xbcjitgrrruemrsxr4za
- Notary Requested: MRJAVAZHAO

@uupptoday Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MRJAVAZHAO** [comment]
Please provide the following materials.

if you are an organization, Please describe your organization, such as established time, business scale, social media accounts&follwers, the number of employees, users volumn and business license (could be sent by email, 1625821971@qq.com); if you are an individual, please provide name, date of birth, working company and scale, employment certificate, social media accounts&follwers, and ID card (can be sent by email, 1625821971@qq.com);

When did you start learning about Filecoin? Please give a description about the projects you have participated in ? What do you want to get from Filecoin? Any suggestions or expectations for the Filecoin Network?

Is there any law risk? What percentage of questions are yours?

How about your data volume, source and later planning? Please describe the type, format, source, storage capacity, publicity (and if data could be public, how can others retrieve it?) of the data to be stored in Filecoin.

In which area do you plan to store you data? How many miners do you want to find ? Please list the miner ID. How about the proportion of the storage for each miner? What are the requirements about miners? At last, please state your redundancy plan.

Do you agree to disclose transaction information? If you get DataCap, please make the transaction information public on the Issue in time.

**Comment by uupptoday** [comment]
Hi,@MRJAVAZHAO
Our company assists enterprises to find suitable candidates for selection and research through comprehensive analysis of talents from multiple perspectives, such as specialty, profession, life circle and integrity. 
Currently, the company is involved in registering and parsing information about the identity, likes, and duration of a person or organization on the Internet through distributed digital identities (diDs) through decentralized, verifiable digital identifiers. 
 
Incorporation Date: (1year) 
Team Member: ＜50 
Business Scope: world 
Number of Users: more than 100 business users 
Official website: http://www.tpjx.org 
Project: Talent information big data project and Traceability of industrial chain information. 
 
No previous exposure to IPFS/Filecoin. 
 
There is no legal risk. 
 
The data we'll store in Filecoin includes Pictures, videos, documents, logs, etc. 
Our data volume is more than 1000TB, mainly from Internet public data, enterprise docking data and independent analysis data, etc. 
Along with the development of metasverse, we will also track the virtual world talent information, creative contents copyright, virtual transactions and other metasverse models. 
Data is public. 
 
We prefer to store our data in China, but haven't decide who is the best miner for us. 
We plan to store 3-5 backups, miners are expected to have worked for Filecoin in a long time . 
 
Yes.

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary

#### Message sent to Filecoin Network
>bafy2bzacedt5qlde5b3weftgpiz4qxkgz36sy7ij54eoecwslxd55emvkbnvm

#### Address
>f3qoc4rldxutogaa72hbnml3rqh6xlbyy4m562l5jwumyyfdqqupen446gh5gwkra5xbcjitgrrruemrsxr4za

#### Datacap Allocated
>2 TiB

You can check the status of the message here: https://www.atpool.com/zh/chain/msg/bafy2bzacedt5qlde5b3weftgpiz4qxkgz36sy7ij54eoecwslxd55emvkbnvm-1320279
