### ISSUE TITLE
Client Allocation Request for: Himelight

### ISSUE THREAD

**Issue by carol890** [filecoin-project/filecoin-plus-client-onboarding#1151]
---

# Client Allocation Questions 

## Core Information
- Name: Himelight
- Website / Social Media: https://www.himelight.com/org/59a7d564c809aa474f41089c
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f12ku7fqbp2k6njm3j5wqry24yig3ptah4nr33xpa
- Notary Requested: rayshitou

@carol890 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by rayshitou** [comment]
Thanks for your application. Please answer the following questions to let me know you and your company.
1.What's your name and your position in your company?What's your company's business?
2.Could you show me your company's business license? And please show me your company searching consequence in the local business license searching website.
3.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency? Could you please show me your cloud usage evidence?

**Comment by carol890** [comment]
1. My name is Jhan jhuang-syong, you can call me john, I'm the marketing manager of the company. Our company's business is to digitalize traditional marketing tools such as point coupons, to achieve customer management and big data analysis, and record customer spending profiles through point collection to achieve better marketing benefits.
2. see here for licence
![himelight](https://user-images.githubusercontent.com/95023030/144366505-26d1ad0b-5fd6-40a1-b3af-5688a2ecff16.png)

3. We have been using azure and about 300GB growth rate per month. And apologies due to company's regulations I cannot provide you the evidence.
