### ISSUE TITLE
Client Allocation Request for: Yahoo Taiwan holdings limited.

### ISSUE THREAD

**Issue by nickyh123** [filecoin-project/filecoin-plus-client-onboarding#1152]
---

# Client Allocation Questions 

## Core Information
- Name: Yahoo Taiwan holdings limited.
- Website / Social Media: https://tw.buy.yahoo.com/
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1poxtmorxzj6kchi2twz42phmvvuszexaoegjwia
- Notary Requested: rayshitou

@nickyh123 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by rayshitou** [comment]
Hi @nickyh123, thanks for your application. Please answer the following questions to let me know you and your company.
1.What's your name and your position in your company?What's your company's business?
2.Could you show me your company's business license? And please show me your company searching consequence in the local business license searching website.
3.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency? Could you please show me your cloud usage evidence?

**Comment by nickyh123** [comment]
1. Name's John, I work in the administration management department. We are a branch company in Taiwan belongs to Yahoo, our business mode resembles other famous e-commerce companies like Amazon or Taobao.com. We provide convenient online shopping experience and offers commodities in many categories.
2. Will send you an email.
3. Yes we use google and have a growing usage volume of 400GB a month. Sorry can't provide any evidence because of company's guides.
