### ISSUE TITLE
Client Allocation Request for: AppleMango

### ISSUE THREAD

**Issue by AppleMangoo** [filecoin-project/filecoin-plus-client-onboarding#1154]
---

# Client Allocation Questions 

## Core Information
- Name: AppleMango
- Website / Social Media: http://www.applemango.co.kr/
- Region: Asia excl. Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f3wrdtgn75il5r6rnjeqcotwn7cum2t3jxuwy5u7n7wcstg3gr72apdtlyr4mbnjzi7vjschutd7hcv4qinjia
- Notary Requested: ozhtdong

@AppleMangoo Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by AppleMangoo** [comment]
1. Hi. I'm Kelly, and the sales support team.
2. Our company is developing electric vehicle charger manufacturing and power control systems. It will expand its power charging infrastructure business through the Datacap. There is no social media link, but please look at the website.
3. Yes.
4. It will store 3 minor players. They will receive 5TiB of data.
5. Yes
6. We will check them once a week. We believe they will do well.

**Comment by AppleMangoo** [comment]
[Business License.pdf](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/7606082/Business.License.pdf)

**Comment by AppleMangoo** [comment]
Any problem with our information?

**Comment by ozhtdong** [comment]
Please choose your local notary.
