### ISSUE TITLE
Client Allocation Request for: Trueelite

### ISSUE THREAD

**Issue by marverickkk** [filecoin-project/filecoin-plus-client-onboarding#1155]
---

# Client Allocation Questions 

## Core Information
- Name: Trueelite
- Website / Social Media: trueelite-global.com
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1ikwpo5erenhppgirvpall3nkk43jjiwctbksr2i
- Notary Requested: ozhtdong

@marverickkk Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I have some questions about you and your company:
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by marverickkk** [comment]
1. Name's Tian, I work in the technical department.
2. We provide cloud managed services with the best cloud architecture that suits customer's needs.
3.  Will send an email.
4.  We plan to have 4 miners and divide the workload evenly.
5. All decisions will be made public, we'll use github.
6. Filfox will be used to inspect miners, we focus on miners with stable nodes.

**Comment by marverickkk** [comment]
See attachment

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecnsctnvbsm5lukslwcg6y6jdakf4wkog5elgwgrohgruvzvrei64 
#### Address 
> f1ikwpo5erenhppgirvpall3nkk43jjiwctbksr2i
#### Datacap Allocated
> NaNB
#### Signer Address
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecnsctnvbsm5lukslwcg6y6jdakf4wkog5elgwgrohgruvzvrei64
