### ISSUE TITLE
Client Allocation Request for: 甘肃铂族网络科技有限公司

### ISSUE THREAD

**Issue by sunnyliner** [filecoin-project/filecoin-plus-client-onboarding#1158]
---

# Client Allocation Questions 

## Core Information
- Name: 甘肃铂族网络科技有限公司
- Website / Social Media: http://bozuyunsuan.com
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1vsaankm5nbbdd4ow6ezniu7sx5kn46ynylhtvvq
- Notary Requested: steven004

@sunnyliner Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by steven004** [comment]
Hey @sunnyliner , thanks for your request. Can you kindly add more information / context here on:

1. yourself/ your organization (with links to official website/social media/news mentions etc)
2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners), if you are working with a service provider to store your data to Filecoin network, please name the provider.
5. How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
6. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
7. Would you be OK in posting deal transactions here?

Thanks

**Comment by sunnyliner** [comment]
1. The name of our organization is Gansu Bozu Network Technology Co., LTD., and the official website is http://bozuyunsuan.com. At present, the policy control is relatively strict, and there are no social media accounts and news reports.
2. Our company is a distributed storage servicer in the Web3.0 era and provide  artificial intelligence based on decentralization in the Web3.0. We are committed to solving the privacy and security of data and reducing the cost of data storage. At the same time, it also provides enterprises with artificial intelligence public service platform technology consulting services, information technology consulting services, data processing services, etc. To help enterprises long-term developing in the digital economy.
3. We will store system data on Filecoin, mainly including ldf and mdf files. And the total amount of this application is about 20TB.
4. We plan to contact about 5 storage providers in China to provide services for this storage.
5. The data we intend to store are private, so we don't support public retrieval.
6. We want to build Filecoin distributed storage for our users. For-profit.
7. We are willing to do that.

**Comment by steven004** [comment]
> The data we intend to store are private, so we don't support public retrieval.

Could you suggest how to verify the data you will store into Filecoin? This is important since we really need to know they are valuable and real data. Thanks.

**Comment by sunnyliner** [comment]
Can I give you some data samples?  
Didn't think of a proper way to verify.

**Comment by steven004** [comment]
Hey @sunnyliner , 

Since you are applying 10TiB datacap, not that much, and also not a small amount, I am considering issue you 1TiB to start, and I would like to randomly pick a few deals to check the data. If you can promise providing us the data of that deal we randomly pick in the verification process, I will move on to issue you the grants. 

And,  you can apply more when the first datacap is used up. Does it sound OK to you?

**Comment by sunnyliner** [comment]
I think it is a good idea.
We can try.

**Comment by sunnyliner** [comment]
It would be better to start with more datacap.

**Comment by steven004** [comment]
Hey @sunnyliner , Your Datacap Allocation Request has been approved

**Message sent to Filecoin Network**
> [bafy2bzacedxeiidkdn2hgamzwq4zujuz7fwunxhg3pod7t232wadxny3jbsgc](https://filscan.io/tipset/message-detail?cid=bafy2bzacedxeiidkdn2hgamzwq4zujuz7fwunxhg3pod7t232wadxny3jbsgc)

**Address**
> [f1vsaankm5nbbdd4ow6ezniu7sx5kn46ynylhtvvq](https://filscan.io/address/general?address=f1vsaankm5nbbdd4ow6ezniu7sx5kn46ynylhtvvq)

**Datacap Allocated**
> 1.0TiB

**Comment by steven004** [comment]
1TiB granted. 
Please upload your deal list when you completed the uploading, so that I can move on for verification, and then you can apply more if it goes well. 
To apply more, you need pass the verification, and it would be better if you can share me your business certificate via email too.
