### ISSUE TITLE
Client Allocation Request for: Eliovp

### ISSUE THREAD

**Issue by Eliovp** [filecoin-project/filecoin-plus-client-onboarding#116]
---

# Client Allocation Questions 

## Core Information
- Name: Eliovp BVBA
- Website / Social Media: https://eliovp.com
- Region: Europe
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3rnzgvmh6itjywfy3n6e23s3impootcafbook4x3et5qqmxrces6hd5oypufdwkwi6eobnhfqny3oohr2s5ea
- Notary Requested: s0nik42

**Comment by s0nik42** [comment]
Hi @Eliovp ,

Thanks for your request. Can you kindly add more information / context here on:

- Yourself , e.g. include links to social media / news mentions etc
- Your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- Type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- Your relationship with the data, especially with regard to copyright
- How you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
- Have you already ask datacap to another notary that have been accepted or rejected. 

Thanks

Julien

**Comment by Eliovp** [comment]
@s0nik42 , 

As this is public and the info is in many ways private, I will answer as much as possible.
You can contact me privately for more info.

-  Europe
-  eliovp.com -> amd.com/blockchain
- Active participant in the SpaceRace looking to build a specific automated process on top of FileCoin
- Private Data for Private clients, mostly metrics and automated builds.
- Self-built, completely owned by the company
- Redundancy based on own clients location
- No

Greetings

**Comment by s0nik42** [comment]
@Eliovp, as of today notaries only accept public request. All the information requested will have to be shared here.
The only thing that we could treat privately is an audit of the data you are uploading. I imagine the data are going to be encrypted, I may ask you to provide the content of a specific deal.  

- Could you provide a link to one or two social media of yourself as an individual ?
- Please describe more the data you are going to store (type, expected volume per client, how your client are going to access these data, are you going to have one encryption key per client).  
- Could you describe more, the intended data location(How many copies of the data are you going to store, to how many miner per client, miners already identified if any, any useful information) ?

 Regards,

Julien

**Comment by Eliovp** [comment]
@s0nik42 , I gave you an answer to all the questions.

And yes, the only thing which is private are the clients and their data.

- sure :[linkedin ](https://www.linkedin.com/in/eliovp/)
- .img files and sql data, approximately 64GiB per client, I have around 400
Clients will be able to access this data as soon as it becomes available through my automated build system.
- Minimum 3 copies per client (in his own region).
So 3 miners per region per client. 

Cheers

**Comment by s0nik42** [comment]
Thank you for this additional information, could you please confirm :
- you will upload here the relevant CIDs ?
- if data will be encrypted ? 
-  your address for the datacap allocation : f3rnzgvmh6itjywfy3n6e23s3impootcafbook4x3et5qqmxrces6hd5oypufdwkwi6eobnhfqny3oohr2s5ea

Thank you,

Julien

**Comment by Eliovp** [comment]
Hey Julien,

- If that is necessary, then yes.
- Yes, data will be encrypted.
- Correct

I do not need the data cap immediately as we're going through a testing phase here that isn't going as planned, so no need to rush :)

Cheers

**Comment by s0nik42** [comment]
Thank you, yes it's necessary.

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedokjmttu5sihmdcjeamp2c5xkqyw7eckshpm4tc5n6hchwcrsass 
#### Address 
> f3rnzgvmh6itjywfy3n6e23s3impootcafbook4x3et5qqmxrces6hd5oypufdwkwi6eobnhfqny3oohr2s5ea
#### Datacap Allocated
> 1 TiB
