### ISSUE TITLE
Client Allocation Request for: 北京鼎创合源科技有限公司

### ISSUE THREAD

**Issue by czhtestdfgdfg** [filecoin-project/filecoin-plus-client-onboarding#1161]
---

# Client Allocation Questions 

## Core Information
- Name: 北京鼎创合源科技有限公司
- Website / Social Media:  http://www.dchy1688.com/
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3vpiaxhk273vrcffpcj2s7alie75naf6uykeqdec7bhe23tehxxkoktkfoh5elvb6biws4xbby7ooqrr4kxua
- Notary Requested: steven004

@czhtestdfgdfg Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by steven004** [comment]
Hey @czhtestdfgdfg , thanks for your request. Can you kindly add more information / context here on:

1. yourself/ your organization (with links to official website/social media/news mentions etc)
2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners), if you are working with a service provider to store your data to Filecoin network, please name the provider.
5. How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
6. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
7. Would you be OK in posting deal transactions here?

Thanks

**Comment by czhtestdfgdfg** [comment]
My name is ZongLiang, you can contact me via email, 1274540533@qq.com.Beijing Dingchuang Heyuan Technology Co., Ltd. was founded in 2008, registered in China's Silicon Valley - Zhongguancun Science park. Relying on the resource advantages of the science and technology park and the technical advantages of the company, it has professional experience and solutions in government office network automation, real-time remote security monitoring, office equipment product optimization configuration, etc. It is a double high new enterprise, senior service provider of office automation and information software and hardware products.At present, the company has 6 r&d personnel, 7 technical engineers, 12 customer service personnel, 21 sales and development department, the company's own consumable brand 2, and in jingdong, Tmall, opened stores for promotion.Technical support: The department will combine customer needs, the company also launched innovative personalized door-to-door customized services, providing timing equipment and timing engineer services, on-site demonstration services, engineering construction and office equipment rental services.
I learned about Filecoin in the first half of this year and haven't worked on any other projects yet. Hopefully Filecoin will reduce storage costs and improves storage security.
The amount of data is greater than 1000 TB, which contains internet open data, enterprise docking data and independent analysis data.
We've cooperated with f01308916/f01308862/f01308857/f01169692/f01308863, each miners will be allocated less than 50%.
No tool.
Just for data storage.
We are willing to be transparent about datacap allocations.

**Comment by steven004** [comment]
Hey @czhtestdfgdfg , thanks, just wrote you a mail for the following questions: 

1) would you please suggest how to verify your data while you said there is no tool available?
2) would you please share me your business certificate?

**Comment by czhtestdfgdfg** [comment]
The last mail(1274540533@qq.com) is no longer in use. I will change the mail address to contact you.  I'll send you the business license via this email address(3505978125@qq.com).

**Comment by czhtestdfgdfg** [comment]
Your e-mail address is steven004@gmail.com, right?

**Comment by steven004** [comment]
Hey @czhtestdfgdfg , 
I will grant you 2TiB for you start, and when you are using the datacap up, please submit deals, and we can go through verification process, then you can apply more if it goes well.

**Comment by steven004** [comment]
Hey @czhtestdfgdfg , Your Datacap Allocation Request has been approved

**Message sent to Filecoin Network**
> [bafy2bzacebqvrc2psv46p4mggxdyiveipmedvp3s63pirtluuk6k6gd5pof66](https://filscan.io/tipset/message-detail?cid=bafy2bzacebqvrc2psv46p4mggxdyiveipmedvp3s63pirtluuk6k6gd5pof66)

**Address**
> [f3vpiaxhk273vrcffpcj2s7alie75naf6uykeqdec7bhe23tehxxkoktkfoh5elvb6biws4xbby7ooqrr4kxua](https://filscan.io/address/general?address=f3vpiaxhk273vrcffpcj2s7alie75naf6uykeqdec7bhe23tehxxkoktkfoh5elvb6biws4xbby7ooqrr4kxua)

**Datacap Allocated**
> 2.0TiB
