### ISSUE TITLE
Client Allocation Request for: Asia-360

### ISSUE THREAD

**Issue by Keith1231** [filecoin-project/filecoin-plus-client-onboarding#1162]
---

# Client Allocation Questions 

## Core Information
- Name: Asia-360
- Website / Social Media: https://www.asia-360.net/
- Region: Asia excl. Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1cxff2c26tbuawi2gnyruwi2d6wj66lmbkqzt4ga
- Notary Requested: ozhtdong

@Keith1231 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I have some questions about you and your company:
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by Keith1231** [comment]
1. Name's Keith, I'm a manager of the company.
2. We provide community marketing to increase our customerss mechandise exposure, and its popularity and publicity.
3. I will send you an email
4. We plan to have 4 miners, the larger bandwidth the miner has , more data he shall receive.
5. Yes the decisions will be made public, we will use Github.
6. We will use Filfox to inspect miners and we favor miners with larger bandwidth and stable nodes.

**Comment by Keith1231** [comment]
business licence

**Comment by ozhtdong** [comment]
It has already finished just now. You can check it.
