### ISSUE TITLE
Client Allocation Request for: 威洁施

### ISSUE THREAD

**Issue by Cookieed** [filecoin-project/filecoin-plus-client-onboarding#1163]
---

# Client Allocation Questions 

## Core Information
- Name: 威洁施
- Website / Social Media: http://walgis.net
- Region: Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1oiaqg4ujsc534p7ts7x6nlcbe5fh2pyt4b3inpa
- Notary Requested: steven004

@Cookieed Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by steven004** [comment]
Hey @Cookieed, thanks for your request. Can you kindly add more information / context here on:

1. yourself/ your organization (with links to official website/social media/news mentions etc)
2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners), if you are working with a service provider to store your data to Filecoin network, please name the provider.
5. How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
6. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
7. Would you be OK in posting deal transactions here?

Thanks

**Comment by Cookieed** [comment]
@steven004 Thanks for your reply.
Guangdong Weijiishi Technology Co., LTD
Website:http://walgis.net
Founded in 2014, the company is a technology company, which is the joint operation unit of Shenzhen Chinese TV Big Data Center. With the concept of "Creativity leads, integration leads to innovation, one-stop media service platform". The company provides professional media services from planning to execution. The scope of business covers conference services, radio and television program production, sports and sports events, executive parallel service concept. With high quality and efficient services, leading the media events industry.
No history working on IPFS/Filecoin.
The data we intend to store are mainly he film and television video generated by the company's operation, environmental monitoring data, family and corporate office monitoring data, etc.
The data to be stored is 15TB.
We plan to allocate DataCap to more than 3 miners; The proportion is not definite; About 3 copies will be stored; The storage location is in China.
No tool.
To store more cold data on the Filecoin network.
Yes.​

**Comment by steven004** [comment]
Hey @Cookieed, there are two more requests before the grants:

1) would you please suggest how to verify your data while you said there is no tool available?
2) would you please share me your business certificate? you could share me via e-mail. 

Thanks.

**Comment by Cookieed** [comment]
I don't have a better idea about verification. You can follow your rule.
This is our business certificate. You can download it. I will delete it after receiving your answer. 
![1](https://user-images.githubusercontent.com/93968346/144529745-c8e4a0e2-eff3-42fd-a99a-226feacd73da.jpg)

**Comment by steven004** [comment]
Hey @Cookieed , thanks for the business license sharing, I already download it. 

Since you are storing private data, I would like to issue you a small amount for you to start, like 1TiB. And you can apply more after verification, which will be done by randomly select a few deals to check the data volubility.

**Comment by steven004** [comment]
Hey @Cookieed  , Your Datacap Allocation Request has been approved

**Message sent to Filecoin Network**
> [bafy2bzaceavx5md42fwobopgkhsvhoth4fgkkzk5tjlphvpkqhc5a3o5qtcc4](https://filscan.io/tipset/message-detail?cid=bafy2bzaceavx5md42fwobopgkhsvhoth4fgkkzk5tjlphvpkqhc5a3o5qtcc4)

**Address**
> [f1oiaqg4ujsc534p7ts7x6nlcbe5fh2pyt4b3inpa](https://filscan.io/address/general?address=f1oiaqg4ujsc534p7ts7x6nlcbe5fh2pyt4b3inpa)

**Datacap Allocated**
> 1.0TiB
