### ISSUE TITLE
Client Allocation Request for: Taiwan Envionmental Information Center

### ISSUE THREAD

**Issue by harrissss3** [filecoin-project/filecoin-plus-client-onboarding#1168]
---

# Client Allocation Questions 

## Core Information
- Name: Taiwan Envionmental Information Center
- Website / Social Media: https://e-info.org.tw/about
- Region: Asia excl. Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1zlmlnspyivvevewh7hqfx4g7y3yc4z44unfcwei
- Notary Requested: ozhtdong

@harrissss3 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I have some questions about you and your company:
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by harrissss3** [comment]
1. My name is Anna, I am the community editor of my company
2. Environmental Information Center is a non-profit online media. Since 2000, we have been providing comprehensive environmental coverage domesticly and abroad. We hope to make voice for the mountains, seas and lands that have no votes.
3. Will send an email
4. We want to have 5 miners, and provide the miners more data who have faster network
5. Yes decisions will be public on github.
6. Filfox, miners with fast internet

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecajf3m246byhiy4txkydrejvjc7akm2mk6wmuk7wr7zj5p6wwbcu 
#### Address 
> f1zlmlnspyivvevewh7hqfx4g7y3yc4z44unfcwei
#### Datacap Allocated
> NaNB
#### Signer Address
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecajf3m246byhiy4txkydrejvjc7akm2mk6wmuk7wr7zj5p6wwbcu
