### ISSUE TITLE
Client Allocation Request for: Public Gold Marketing Sdn. Bhd

### ISSUE THREAD

**Issue by lee3391** [filecoin-project/filecoin-plus-client-onboarding#1169]
---

# Client Allocation Questions 

## Core Information
- Name: Public Gold Marketing Sdn. Bhd
- Website / Social Media: https://pgmall.my/
- Region: Asia excl. Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1w2i6kvzpjbxex37g7nzx4fi3gij3aiggwp6hvsy
- Notary Requested: ozhtdong

@lee3391 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I have some questions about you and your company:
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by lee3391** [comment]
1. Jack, I'm the manager
2. PG Mall is a Malaysia online shopping platform, operated by PG Mall Sdn. Bhd.(836625-K) and backed by Public Gold Marketing Sdn. Bhd. PG Mall is aimed to present a reliable business platform for the merchants to diversify their business portfolios from a global perspective. https://twitter.com/PG_Mall
3. Yes will do
4. We will have 2 miners and distribute the data half and half
5. Decisions will be made public on github
6. We will use filfox to check miners, and put an emphasis on their network speed.

**Comment by lee3391** [comment]
licence

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgooibcbpykcj55ovdvd7ezivz52nwve356sixovapnkjto7tm7g 
#### Address 
> f1w2i6kvzpjbxex37g7nzx4fi3gij3aiggwp6hvsy
#### Datacap Allocated
> NaNB
#### Signer Address
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgooibcbpykcj55ovdvd7ezivz52nwve356sixovapnkjto7tm7g
