### ISSUE TITLE
Client Allocation Request for: Hxmps.com

### ISSUE THREAD

**Issue by JJsuperm** [filecoin-project/filecoin-plus-client-onboarding#1183]
---

# Client Allocation Questions 

## Core Information
- Name: Hxmps.com
- Website / Social Media: https://www.hxmps.com.tw/about-us
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1mguxgsx72xrpki3s2ynwygdy57tzzdxxinkjmdq
- Notary Requested: ozhtdong

@JJsuperm Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I have some questions about you and your company:
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by JJsuperm** [comment]
1. call me Steve, I work in the administration department.
2. we are a professional apartment management and security company and have accumulated considerable experience in the management and security business because we know how to protect the privacy of our residents and understand their needs.  
3. i will send you an email
4. we plan on having 2 miners, and distribute the data roughly equal to them
5. allocation plans will be made public on github
6. we will use filfox for inspection, we favor miners with fast internet

**Comment by JJsuperm** [comment]
see pic

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedayorhi7vzeuycz44bpcv6ncce6jbi7uz5nxlcng5z6yayiwavny 
#### Address 
> f1mguxgsx72xrpki3s2ynwygdy57tzzdxxinkjmdq
#### Datacap Allocated
> NaNB
#### Signer Address
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedayorhi7vzeuycz44bpcv6ncce6jbi7uz5nxlcng5z6yayiwavny
