### ISSUE TITLE
Client Allocation Request for: Himelight

### ISSUE THREAD

**Issue by carol890** [filecoin-project/filecoin-plus-client-onboarding#1185]
---

# Client Allocation Questions 

## Core Information
- Name: Himelight
- Website / Social Media: https://www.himelight.com/org/59a7d564c809aa474f41089c
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f12ku7fqbp2k6njm3j5wqry24yig3ptah4nr33xpa
- Notary Requested: ozhtdong

@carol890 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I have some questions about you and your company:
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by carol890** [comment]
see attachment

**Comment by carol890** [comment]
1. You can call me Joe, I am the manager of the marketing department
2. Himelight is a group of people who want to use the technology to benefit themselves and others, add fun and change the habit pattern. We are committed to developing the most interesting  customer management platform, digitizing traditional marketing tools such as point collection, coupons, and birthday coupons to achieve customer management and big data analysis, recording customer consumption profiles through point collection, achieving better marketing benefits for stores, and smarter retail.
3. Check inbox
4. We will choose 3 miners possibly and divide the data for miners in a principle "faster transmission, larger portion".
5. Yes all decisions will be in public. We will make decisions on github.
6. Filfox is a great tool, and we put an emphasis on miner's transfering speed

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecrayz5jfk4yzctza2ezeytmwu2nylapyoj5qczbascfhrqim6cfs 
#### Address 
> f12ku7fqbp2k6njm3j5wqry24yig3ptah4nr33xpa
#### Datacap Allocated
> NaNB
#### Signer Address
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecrayz5jfk4yzctza2ezeytmwu2nylapyoj5qczbascfhrqim6cfs
