### ISSUE TITLE
Client Allocation Request for: Yahoo Taiwan holdings limited.

### ISSUE THREAD

**Issue by nickyh123** [filecoin-project/filecoin-plus-client-onboarding#1189]
---

# Client Allocation Questions 

## Core Information
- Name: Yahoo Taiwan holdings limited.
- Website / Social Media: https://tw.buy.yahoo.com/
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1poxtmorxzj6kchi2twz42phmvvuszexaoegjwia
- Notary Requested: swatchliu

@nickyh123 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.)
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?

Would you like to submit more company information on www.bytebase.cn?

Would you like to accept our face-to-face visit?

**Comment by nickyh123** [comment]
Hi, our company is located in Taiwan.

Our social media link: https://www.facebook.com/Ybestbuy
We established the enterprise since 2004,  lasted about 17 years and have over 2000 employees in our branch.
We provide convenience for our customers in online shopping, millions of products in every category ready to be delivered to your doorstep fast and reliable within few clicks, easy and efficient.
We intend to store about 10TiB of data, we currently don't possess any DataCap.

We would like to submit more info on your web, and to answer your last question, I think it's better to simply meet online via video conferencing if needed due to the pandemic.

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebs7wr4bpeu2zzurskl5h3wvebjlfktocepkcbf2ycoojlg6qbh4y 
#### Address 
> f1poxtmorxzj6kchi2twz42phmvvuszexaoegjwia
#### Datacap Allocated
> NaNB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebs7wr4bpeu2zzurskl5h3wvebjlfktocepkcbf2ycoojlg6qbh4y
