### ISSUE TITLE
Client Allocation Request for: xycloud-f

### ISSUE THREAD

**Issue by xycloud-f** [filecoin-project/filecoin-plus-client-onboarding#119]
---

# Client Allocation Questions 

## Core Information
- Name: xycloud-f
- Website / Social Media: www.xycloud.com
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: 
- Notary Requested: steven004

**Comment by steven004** [comment]
Hey @xycloud-f , thanks for your request. Can you kindly add more information / context here on:

1. yourself/ your organization (with links to official website/social media/news mentions etc)
2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners)
5. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
6. Would you be OK in posting deal transactions here?

Thanks

**Comment by xycloud-f** [comment]
@steven004 Hi, Steven, our answers are as follows:
1、 yourself/ your organization (with links to official website/social media/news mentions etc) 
      official website：www.xycloud.com 
      news mentions：https://www.sohu.com/a/275303997_100161167 
               ：https://tech.qq.com/a/20180516/030158.htm 
                ：https://tech.qq.com/a/20150724/055940.htm 
2、 Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc) 
      We've been adhering to the progress of filecoin. The main network of filecoin published in October 2020, we envisaged its tremendous potential in landing the formal business scenario. Thus in near future, we would discuss the possibility of follow-up cooperation and development with the protocol laboratory. 

3、 Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin 
       Use case: Audio and video files, documents, messages and etc. The customers we serve can be seen on our official website.

4、Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners) 
     Our customers spread all over the international stage, who are mainly concentrated in China, Southeast Asia, the United States and other places. For miners, we put requirements including region, network operator, device performance and uplink bandwidth. Our early testing and application will be held as scheduled in China 

5、 What's your next plan for the data you plan to store in Filecoin Network? For-profit or not? 
       We hope that our applications and services can receive good support from the filecoin network, in which all participants can build a mutual-beneficial, sustainable-developmental and ecological chain shoulder to shoulder. We are optimistic about the future profit expectation and think that it's up to the market to decide everything.
6、 Would you be OK in posting deal transactions here? 
      We would post the deal ID after sending it to the miners.
Thanks。

**Comment by steven004** [comment]
Hey @xycloud-f , thanks for your clarification, and welcome to the Filecoin world. IPFS/Filecoin network is distributed and decentralized. It supports CDN naturally. Some more questions: 
1) Did you have applications, or ever did experiments to store data on IPFS or Filecoin network? 
2) Are the data you plan to store in Filecoin publicly available, or not? 
3) Is there an application available already to download or view your data to store in Filecoin network? 

Thanks.

**Comment by xycloud-f** [comment]
@steven004 Hi, Steven, our new answers are as follows:
1、Did you have applications, or ever did experiments to store data on IPFS or Filecoin network?
At present, we have not stored data and tested it in filecoin network. Because we are also a blockchain company（ blockchain.xunlei.com ）, very familiar with the application of blockchain technology and file storage technology. Some time ago, we also had a technical exchange with the miners recommended by the protocol laboratory, and judged that the fast retrieval storage service of filecoin network is basically in line with the business we plan to test. We believe that with the assistance of the agreement laboratory and the miners, we will soon be able to run through the business。
2、Are the data you plan to store in Filecoin publicly available, or not?
We understand that according to the communication with the protocol laboratory, our data can be disclosed.
3、Is there an application available already to download or view your data to store in Filecoin network?
Our program can be used after slightly adjusting to the filecoin network features. We have strong technical ability. We are a technology driven company.
thanks.

**Comment by steven004** [comment]
Thanks again @xycloud-f for your further explanation. It's good. 
Since you are not storing the curated data, I have another question requiring your confirmation. You have the obligation to make sure  that all the data you use the granted datacap to store in Filecoin comply China's related laws and regulations, where you are located, and comply the laws and regulations of the storage providers' countries or areas if the miners storing the data are not located in China. So, you are responsible to screen the data and guarantee no piece of data breaking the laws/regulations to be stored using the datacap. 

Could you please confirm?

**Comment by xycloud-f** [comment]
@steven004 Hi, Steven, Whether in China or in the rest of the world, we confirm the legitimacy of our data storage.

**Comment by steven004** [comment]
Great! Please let me know your addresses to be Notarized for next step.

**Comment by xycloud-f** [comment]
China's Spring Festival is coming. We suggest that we start the follow-up work after the festival. I wish you all a good holiday。thanks .

**Comment by xycloud-f** [comment]
@steven004 Hi, Steven，It's a good year to start,Our address：f1rr7d5cgkd772fan5gi2s3izuftnkmxer64bvtsi。

**Comment by steven004** [comment]
Your Datacap Allocation Request has been approved

**Message sent to Filecoin Network**
> [bafy2bzacectqoarxriol5w2gyajruzbljiwgjgsgzeact5s2w3czs6qkiwye2](https://filscan.io/#/tipset/message-detail?cid=bafy2bzacectqoarxriol5w2gyajruzbljiwgjgsgzeact5s2w3czs6qkiwye2)

**Address**
> [f1rr7d5cgkd772fan5gi2s3izuftnkmxer64bvtsi](https://filscan.io/#/address/detail?address=f1rr7d5cgkd772fan5gi2s3izuftnkmxer64bvtsi)

**Datacap Allocated**
> 2 TiB

**Comment by dkkapur** [comment]
Update: message ID for this one is actually bafy2bzaceb4dvtvpllubs3ftlmeynbcbmzb3oui2qy7jehki7ztqajvs7xo7o.
See https://filfox.info/en/message/bafy2bzaceb4dvtvpllubs3ftlmeynbcbmzb3oui2qy7jehki7ztqajvs7xo7o
