### ISSUE TITLE
Client Allocation Request for: AppleMango

### ISSUE THREAD

**Issue by AppleMangoo** [filecoin-project/filecoin-plus-client-onboarding#1197]
---

# Client Allocation Questions 

## Core Information
- Name: AppleMango
- Website / Social Media: http://www.applemango.co.kr/
- Region: Asia excl. Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f3wrdtgn75il5r6rnjeqcotwn7cum2t3jxuwy5u7n7wcstg3gr72apdtlyr4mbnjzi7vjschutd7hcv4qinjia
- Notary Requested: rayshitou

@AppleMangoo Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by AppleMangoo** [comment]
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1154

**Comment by rayshitou** [comment]
Thanks for your application. Please answer the following questions to let me know you and your company.
1.What's your name and your position in your company?What's your company's business?
2.Could you show me your company's business license? And please show me your company searching consequence in the local business license searching website.
3.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency? Could you please show me your cloud usage evidence?

**Comment by AppleMangoo** [comment]
1. Hi. I'm Kelly Kim, and the sales support team. Our company is developing electric vehicle charger manufacturing and power control systems. We respond to the direction of eco-friendly energy-oriented industries and contribute to industrial development with differentiated products and services. Our products include DC fast chargers, AC slow chargers, AC/DC power modules, and wattage testing devices, and will produce more products. We will store data on all of these products in  Datacap and actively utilize them. It will expand its power charging infrastructure business through the Datacap. 

2. Yes

3. No. However, we have used large amounts of hard disks.

**Comment by AppleMangoo** [comment]
[Business License.pdf](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/7702341/Business.License.pdf)

**Comment by rayshitou** [comment]
@AppleMangoo Please show me your company searching consequence in the local business license searching website. And could you share what's your usage volume of hard disks?

**Comment by LSCcoltd** [comment]
![image](https://user-images.githubusercontent.com/93900968/146169843-6e68d15e-fc8c-4b40-af10-df25c02148cf.png)

**Comment by AppleMangoo** [comment]
This is the result of our company's search. We are using a hard disk of about 40TB.

**Comment by AppleMangoo** [comment]
![image](https://user-images.githubusercontent.com/95061825/146170151-d2544a35-4fc9-46f7-a2e3-7945465616f5.png)

**Comment by AppleMangoo** [comment]
https://bizno.net/article/6628801182

**Comment by rayshitou** [comment]
Nice!
1.What kind of data do you want to store and how much?
2.Could you please send me some demos of your data?
3.Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner's terms of service?

**Comment by AppleMangoo** [comment]
1. As mentioned above, we are producing electric vehicle charger products. It will store data on product design, products currently being developed, and media representing products. All stored data are public. Can I be allocated more because the current data is more than 20TB?


2. I will post an introduction to the data.


3. Yes, I agree. Thanks.

**Comment by AppleMangoo** [comment]
Oh, I send you email

**Comment by AppleMangoo** [comment]
[기업소개자료_애플망고1.pptx](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/7724783/_.1.pptx)

**Comment by rayshitou** [comment]
About the allocation of Datacap:
1.How many miners do you want to store your data to? How much data for each miner?
2.What method/tool will you use to insperct miners? Which aspect of miners will you inspect?
3.Will you record your allocation decision in public? Which platform will you use?
4.Have you ever allocated before? If yes, how did you do when you were questioned? Any links?

**Comment by AppleMangoo** [comment]
1. It will be stored in 3 miners.Each miner will receive 5Tib.

2. We want a minor with fast internet speed and stable. And I will check it once a week.

3. Yes. 

4. That's our first time.

**Comment by rayshitou** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceafyk5bnotcsrt3d3npehy6biv7annfklivvbt4ut6ta5aa5odozs 
#### Address 
> f3wrdtgn75il5r6rnjeqcotwn7cum2t3jxuwy5u7n7wcstg3gr72apdtlyr4mbnjzi7vjschutd7hcv4qinjia
#### Datacap Allocated
> NaNB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceafyk5bnotcsrt3d3npehy6biv7annfklivvbt4ut6ta5aa5odozs
