### ISSUE TITLE
Client Allocation Request for: Guangdong Radio and Television Modern Education channel

### ISSUE THREAD

**Issue by GDRTModernEducationChannel** [filecoin-project/filecoin-plus-client-onboarding#1212]
---

# Client Allocation Questions 

## Core Information
- Name: Guangdong Radio and Television Modern Education channel
- Website / Social Media: http://www.gdetv.net/
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3wwfhucp4y5qgdqq3g6lya6gonqh4qtpt7iorrth2sguyhrn7rbdakgjr2nmpdcpaspkhxtifgkytdquix2ga
- Notary Requested: steven004

@GDRTModernEducationChannel Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by steven004** [comment]
Hey @GDRTModernEducationChannel , thanks for your request. Can you kindly add more information / context here on:

1. yourself/ your organization (with links to official website/social media/news mentions etc)
2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners), if you are working with a service provider to store your data to Filecoin network, please name the provider.
5. How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
6. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
7. Would you be OK in posting deal transactions here?

Thanks

**Comment by GDRTModernEducationChannel** [comment]
We have got 512GiB datacap from you before, https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/920

You can check our deal transactions from the following link:
https://pluskit.io/user?id=f3wwfhucp4y5qgdqq3g6lya6gonqh4qtpt7iorrth2sguyhrn7rbdakgjr2nmpdcpaspkhxtifgkytdquix2ga

Thanks

**Comment by steven004** [comment]
Great!
Would you please share me your wechat id? either in this thread or in Email, both OK. 
We will go through the verification process, I'll approve this one once the verification is done and goes well. Thanks.

**Comment by GDRTModernEducationChannel** [comment]
Wechat id: xz223i. You can do the verification.

**Comment by steven004** [comment]
> Wechat id: xz223i. You can do the verification.

Tried adding you twice, but never get response.

**Comment by steven004** [comment]
Close the issue due to no response. 
Please reopen it if you still need to datacap.
