### ISSUE TITLE
Client Allocation Request for: 深圳市伍链云存储科技有限公司

### ISSUE THREAD

**Issue by kyokaki** [filecoin-project/filecoin-plus-client-onboarding#1216]
---

# Client Allocation Questions 

## Core Information
- Name: 深圳市伍链云存储科技有限公司
- Website / Social Media: https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzkxNTI1MDc3Nw==&scene=124#wechat_redirect
- Region: Greater China
- DataCap Requested: 100TiB
- Addresses to be Notarized: f3wtdob5ymm5qy3t6w2ggk3bb4niq25e3zaolvzhrkzc2fkphrrvrsqau74qvhwncghqoutg6lztjqyrsnlysa
- Notary Requested: steven004

@kyokaki Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by steven004** [comment]
Hey @kyokaki , one of your application is still under evaluation.

**Comment by kyokaki** [comment]
Can I just cancel that one? Cause the file address was got wrong.

Steven Li ***@***.***>于2021年12月10日 周五13:28写道：
