### ISSUE TITLE
Client Allocation Request for: IPFS FORCE

### ISSUE THREAD

**Issue by taoshengshi** [filecoin-project/filecoin-plus-client-onboarding#122]
# Client Allocation Questions 

## Core Information
- Name: IPFS FORCE
- Website / Social Media: https://ipfser.org/
- Region: Greater China
- DataCap Requested: 5 TiB
- Addresses to be Notarized: f3rtqrpxadmhkfgy3cmtib4q6pwiqxpn6fxxq7kvopwqtwghwhwhyy7lm4euqvkg5h26ll3fpc54zsv7jtwdna

[Client Allocation Request for IPFS FORCE.docx](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/5909557/Client.Allocation.Request.for.IPFS.FORCE.docx)

-----------------------------

**Comment by philippbanhardt** [comment]
Hey @taoshengshi - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size, source and your relationship with the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data, who owns the data / license, etc
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by taoshengshi** [comment]
Could you please refer the attached file :` Client Allocation Request for IPFS FORCE.docx` ?

**Comment by philippbanhardt** [comment]
Hey @taoshengshi unfortunately for security reasons I can not open files posted here. Can you kindly share your answers in the comment section here? Thank you

**Comment by taoshengshi** [comment]
okay! ;) 

Client Allocation Request for: IPFS FORCE


1. yourself , e.g. include links to social media / news mentions etc

IPFS Force started in May 2017 is a non-profit decentralization storage and web3 community, based in Shanghai, China. IPFS Force community is sponsered by Shanghai Kunyao Network S&T Co., Ltd. since Kunyao was set up in July 2018 as a company. IPFS Force regularly conduct meetups and events, and support the industry to develop application, Filecoin mining, and provide services. Currently, IPFS Force has near 100 core members, and hundreds of thousands of participants of hosted events via on-site or on-line events.

About IPFS Force:
Website: ipfser.org
Twitter: https://twitter.com/force_ipfs
Weibo: IPFS原力区
WeChat Oifficial Account: IPFS原力区


2. your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc

IPFS-Force community: 
- Established and lead IPFS/Filecoin activities in China: Force Open Day(#153 on Dec. 22nd 2020), Protocol School Shanghai & Chengdu, EOS & IPFS HackFS
- Published IPFS/Filecoin related reports and articles: whitepaper translation, 1-79 Filecoin Weekly Report, 1-118 IPFS Weekly Report, IPFS/Filecoin Ecological Report, SpaceRace Report, Filecoin Mining Guidelines (1-3 series), 100 Questions about IPFS/Filecoin and other reports and articles wrote by IPFS-Force researchers and analyzers

Contributions to Filecoin protocol and code development via issues/PRs commitments
- Some of the issues submitted related to security: 
	https://github.com/filecoin-project/specs/issues/559
	https://github.com/filecoin-project/venus/issues/3308 
	https://github.com/filecoin-project/venus/issues/3349
	https://github.com/filecoin-project/venus/issues/3523
- There are some discussion in slack private channel or via email too, e.g. 
	Non-deterministic signature of round winner calculation
	Owner change proposal from security prospective
	Deterministic winner of big miners, to drive the winning algorithm change
- Participated in Filecoin Devgrants Program
	https://github.com/filecoin-project/devgrants/pull/70
	https://github.com/filecoin-project/devgrants/pull/73
	https://github.com/filecoin-project/devgrants/pull/171

Participating to DevNet/ TestNet/ HackFS/ SR1/ SR2/ Slingshot 1(as reviewer)/Filecoin Community activities as one of top testers and miners

Stewardship of Filecoin Implementation: Venus(go-fliecoin)

Developed the Filecoin explore: Filscan(https://filscan.io/#/home)

Participated in recently Filecoin Community activities
- Storage Market Summit, Dec. 11st 2020
- Filecoin Open Day, Oct. 26th 2020
- Filecoin Core Devs Biweekly #5
- How We Won Space Race, Oct. 21th 2020
- Filecoin Protocol Implementation: What's next?, Oct. 21th 2020
- Filecoin Chain Explorers, Oct. 21th 2020
- Space Race Miner Show & Tell, Spe. 4th 2020


3. type and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc

IPFS Force will mainly store real and public data to the Filecoin Network, such as public data from curated dataset list of Slingshot.
https://proofs.filecoin.io/
https://ghtorrent.org/
https://registry.opendata.aws/landsat-8/#usageexamples
https://storage.googleapis.com/openimages/web/index.html
https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge
https://www.kaggle.com/paultimothymooney/chest-xray-pneumonia
Besides, we will also consider to store public data related to IPFS/Filecoin created by IPFS Force community.


4. how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

IPFS Force will choose at least 3 miners to store real data with 3-5 copies. Both small and big miners in Asia will be considered, and the deal duration will be one year or longer. 
Besides, we will not allocate any DataCap to our own nodes.
IPFS Force Miner ID: f02438, f02425, f02731, f020604, f02726, f03266, f03287, f02610, f02721


5. Would you be OK in posting deal transactions here?

Of course, we’d like to post deal transaction in public.

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecs7kcrt5ly6fuevfdeht6fg57ruvqbxgqhpyrewf4c7gtwrn2nf6 
#### Address 
> f3rtqrpxadmhkfgy3cmtib4q6pwiqxpn6fxxq7kvopwqtwghwhwhyy7lm4euqvkg5h26ll3fpc54zsv7jtwdna
#### Datacap Allocated
> 5 TiB
