### ISSUE TITLE
Client Allocation Request for: Samil Enterprise CO., LTD

### ISSUE THREAD

**Issue by Samilco31** [filecoin-project/filecoin-plus-client-onboarding#1236]
---

# Client Allocation Questions 

## Core Information
- Name: Samil Enterprise CO., LTD
- Website / Social Media: https://www.samilenter.com/
- Region: Asia excl. Greater China
- DataCap Requested: 1 TiB
- Addresses to be Notarized: f3qtqwsgitaaiz6j5hoga2jx7wxwuob6lx4maxmlofllvrpswyvayhfmuyudsuc3ytl6bg7s6p4777acspdwiq
- Notary Requested: MasaakiNawatani

@Samilco31 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Samilco31** [comment]
Hi. Glad to meet you.

Please describe the nature of your organization, project, or use case. For organizations, please include your relationship with the organization the size of the organization, and time since inception. For projects and other use cases, please link to relevant web pages or Github. Please include as much relevant detail to provide contextual information (with external links). If you have any presentation document about your business, please provide it to me.

- We are Samil Enterprise CO., LTD, Established in 1958, a comprehensive construction company with a 60-year. We have participated in numerous national infrastructure projects over the past 60 years and have vast amounts of data on them. It also has a large amount of performance in high-rise buildings, complex business facilities, GMP facilities, hospitals and research institutes, and will organize all data created in the process and store it in Datacap. There are numerous achievements and media on our website. If necessary, I will send you a sample.

Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision (who approved your DataCap, what your plan was for spending it, how you executed on that plan)?

- I have made an allocation request, but I have not received any response. I'll leave the link. (https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1057)

**Allocation Strategy
Do you intend to store your data in a single geography or many?

- For now, I will only save our data in single area. However, if the business expands, other regions will be stored.

Are you aware of and do you intend to use the features you may specify (e.g. Fast Retrieval) with your storage deals?

- No

How do you plan on securing the DataCap to ensure your organization (and its delegated members) are the ones allocating the DataCap?

- We will manage the Datacap from 1~2 time  a week. And data will also be strictly managed with partners.

Do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners?

- We will spread it across 3~4miners

For application developers, will you be acting as the client on behalf of your users or you applying as a Notary on behalf of your users? If so, how much DataCap per user are you seeking to have approved?

- We are applying as the client

Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner’s terms of service?

- Yes, I agree

**Track Record
Have you previously received DataCap to allocate before? If so, please link to any previous decisions that have been made.

- None

Are there any disputes open against you from your previous DataCap allocations?

- None

**Comment by MasaakiNawatani** [comment]
Hi @Samilco31 

Thank you for the information. We will go ahead and review this.

**Comment by MasaakiNawatani** [comment]
Hi @Samilco31 

After reviewing the information, since this is your first datacap allocation request, I will give you 1 TB. You can ask for more once you are able to consume the allocation given.

**Comment by MasaakiNawatani** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced5iwxdsszjk5jzmszsglepemg6dfuok3iyakiwzmeqdwp7gijxh2 
#### Address 
> f3qtqwsgitaaiz6j5hoga2jx7wxwuob6lx4maxmlofllvrpswyvayhfmuyudsuc3ytl6bg7s6p4777acspdwiq
#### Datacap Allocated
> NaNB
#### Signer Address
> f1fh53sdaie3yi25qxwcqxpt5h4naex5ibdaffibi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced5iwxdsszjk5jzmszsglepemg6dfuok3iyakiwzmeqdwp7gijxh2

**Comment by Samilco31** [comment]
Unfortunately, your approval results are regrettable, but thanks for your decision.
I will make additional requests later.
