### ISSUE TITLE
Client Allocation Request for: ATB(About The Block)

### ISSUE THREAD

**Issue by nnrecive** [filecoin-project/filecoin-plus-client-onboarding#1238]
---

# Client Allocation Questions 

## Core Information
- Name: ATB(About The Block)
- Website / Social Media: https://www.youtube.com/c/ATB%EC%96%B4%EB%B0%94%EC%9B%83%EB%8D%94%EB%B8%94%EB %A1%9D%EB%8F%88%EB%B2%8C%EA%B1%B8%EB%8F%88%EB%B2%84%EB%82%A8
- Region: Asia excl. Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3uunvj53p2u47exsoeg2ygoios7kn5avkf5mwbogfvirgvrdfcti6hns4iz4rjwwjhbdeycr2evfuobtwxisq
- Notary Requested: MasaakiNawatani

@nnrecive Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by nnrecive** [comment]
This is what I requested before.
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1075
I'm applying again after changing the address.

**Comment by MasaakiNawatani** [comment]
Hi @nnrecive 

Can you provide a reference to deals you made using the datacap I allocated you? Thank you.

**Comment by nnrecive** [comment]
> 
I can't provide data because I applied for an address that doesn't operate the Lotus Node.
If I want to change the address, is there any other procedure or cancellation?

**Comment by MasaakiNawatani** [comment]
Hi @nnrecive we currently do not have a method to retrieve the datacap I already allocated on your address.

**Comment by nnrecive** [comment]
> 

다른지갑주소로 데이터캡 재신청으로 가능한가요..?

**Comment by MasaakiNawatani** [comment]
@nnrecive sorry for the delayed response. Yes you can, but you need to open a new request. Also, please choose a different Notary as I have no more datacap left to allocate until the next round of Notary elections. Thank you.
