### ISSUE TITLE
Client Allocation Request for: HoireTechnology Co., Ltd

### ISSUE THREAD

**Issue by Edward1996625** [filecoin-project/filecoin-plus-client-onboarding#131]
---

# Client Allocation Questions 

## Core Information
- Name: HoireTechnology Co., Ltd
- Website / Social Media: http://www.hoire.cn/
- Region: Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f1ry5tgrth2qt4r5zu4e6ssfkf4qrce7hcdp22kbi
- Notary Requested: ericfish

**Comment by rayshitou** [comment]
Sorry, @Edward1996625 
Our region to allocate Datacap is [Asia-GCN](https://github.com/filecoin-project/notary-governance/issues/26#issuecomment-747910061).
