### ISSUE TITLE
Client Allocation Request for: Jungbonet INC.

### ISSUE THREAD

**Issue by bluequintain** [filecoin-project/filecoin-plus-client-onboarding#1317]
---

# Client Allocation Questions 

## Core Information
- Name: Jungbonet INC.
- Website / Social Media: jungbo.net
- Region: Asia excl. Greater China
- DataCap Requested: 100TiB
- Addresses to be Notarized: f14yjeyzlh27kwb6rwjgel3ge4vo4hmi57tt2t5sq
- Notary Requested: MasaakiNawatani

@bluequintain Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MasaakiNawatani** [comment]
Hi @bluequintain 

Thank you for your request. Unfortunately, the datacap you need is larger than my allocation. Please resubmit your request as a large dataset allocation request. I will now close this issue.

**Comment by bluequintain** [comment]
thank you @MasaakiNawatani 
ok i will resubmit
