### ISSUE TITLE
Client Allocation Request for: Jkopay

### ISSUE THREAD

**Issue by Rsandraonancy** [filecoin-project/filecoin-plus-client-onboarding#1322]
---

# Client Allocation Questions 

## Core Information
- Name: Jkopay
- Website / Social Media: https://www.jkos.com/
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1lz2p3veoepwwgn5fq4jna2rdkr3sc262okxdmxa
- Notary Requested: ozhtdong

@Rsandraonancy Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I have some questions about you and your company:
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by Rsandraonancy** [comment]
1.Yijia Hu.I am the founder of the company.
2.The company's main project is to support mobile payment functions. It creates a personal store message wall by setting up a dynamic wall to keep abreast of the latest news of favorite stores. And we support delivery services and various payment services in life. And it helps ensure information security and safe payment.
3.Ok. It can be provided as an email. Later I will send you.
4.3 miners. We will allocate a share of no more than 30% to each miner.
5.Github is the first choice.
6.I don't know which tools we can use. We need creditable miners.

**Comment by Rsandraonancy** [comment]
Here it is.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebfzvvysly2exnejcqnwndtyirb74g7bciljock6csnrbsocc4rng 
#### Address 
> f1lz2p3veoepwwgn5fq4jna2rdkr3sc262okxdmxa
#### Datacap Allocated
> NaNB
#### Signer Address
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebfzvvysly2exnejcqnwndtyirb74g7bciljock6csnrbsocc4rng
