### ISSUE TITLE
Client Allocation Request for: 四川星河飞天科技

### ISSUE THREAD

**Issue by changlizhi** [filecoin-project/filecoin-plus-client-onboarding#1325]
---

# Client Allocation Questions 

## Core Information
- Name: 四川星河飞天科技
- Website / Social Media: www.stariverpool.io
- Region: Greater China
- DataCap Requested: 16TiB
- Addresses to be Notarized: f1fd7pgiygdwnsvxqj7n3f4ixuioq5btgok25mgzi
- Notary Requested: steven004

@changlizhi Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by steven004** [comment]
@changlizhi ,  this is a new round of datacap application you submitted. The previous one can be find from #1111 .   The restored data had been verified as real data. 

I am granting you 16TiB this time. Please be aware of the verification process is only to verify your data are real. You need to be responsible for copyright of the data, and be sure there is no any legal issues.

**Comment by steven004** [comment]
Hey @changlizhi  , Your Datacap Allocation Request has been approved

**Message sent to Filecoin Network**
> [bafy2bzaced76hwzzd25bewe6fe7yckkad63umd5ekysbu5ozyke7nebmeancs](https://filscan.io/tipset/message-detail?cid=bafy2bzaced76hwzzd25bewe6fe7yckkad63umd5ekysbu5ozyke7nebmeancs)

**Address**
> [f1fd7pgiygdwnsvxqj7n3f4ixuioq5btgok25mgzi](https://filscan.io/address/general?address=f1fd7pgiygdwnsvxqj7n3f4ixuioq5btgok25mgzi)

**Datacap Allocated**
> 16.0TiB
