### ISSUE TITLE
Client Allocation Request for: Titansoft

### ISSUE THREAD

**Issue by quinn463** [filecoin-project/filecoin-plus-client-onboarding#1339]
---

# Client Allocation Questions 

## Core Information
- Name: Singapore Titansoft
- Website / Social Media: https://titansoft.com/
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1pmzqfwengdwvbw54n45emtizxqgqekpmrgtaygi
- Notary Requested: rayshitou

@quinn463 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by rayshitou** [comment]
@quinn463 Thanks for your application. 
Please answer the following questions to let me know you and your company.
1.What's your name and your position in your company?What's your company's business?
2.Could you show me your company's business license? And please show me your company searching consequence in the local business license searching website.
3.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency? Could you please show me your cloud usage evidence?

**Comment by quinn463** [comment]
1. I'm Nicola. A system integration engineer.
Titansoft is a software development company dedicated to the development and maintenance of online software platforms through Agile Software Development. With extensive experience in software engineering, we offer a wide range of consulting services, including market research, server and network development and management, network infrastructure, and cloud deployment. Our product lines are diversified, best known for: Project Management Systems, System Performance Monitoring Centers, Subscriber Accounting Systems, and Business Intelligence Management Systems.
2. OK, I can.
![image](https://user-images.githubusercontent.com/79658535/147820020-cb608fb2-3287-4898-
![image1](https://user-images.githubusercontent.com/79658535/147820027-f570d99b-556e-48b8-9417-203f555c82c8.png)
8f77-38c359772967.png)
 3.No, we haven't.

**Comment by quinn463** [comment]
1. I'm Quinn. A system integration engineer.
Titansoft is a software development company dedicated to the development and maintenance of online software platforms through Agile Software Development. With extensive experience in software engineering, we offer a wide range of consulting services, including market research, server and network development and management, network infrastructure, and cloud deployment. Our product lines are diversified, best known for: Project Management Systems, System Performance Monitoring Centers, Subscriber Accounting Systems, and Business Intelligence Management Systems.
2.OK, I can.
![mail](https://user-images.githubusercontent.com/79658535/147820103-49587e5e-91bd-4ac2-9
![image1](https://user-images.githubusercontent.com/79658535/147820109-cff724c8-766b-4203-847d-830205f01dbc.png)
68f-920a902de7bd.jpg)
3.No, we haven't.

**Comment by rayshitou** [comment]
Sorry, could you show me your company's business license? 
And, please let me know:
1.What kind of data do you want to store and how much?
2.Could you please send me some demos of your data?
3.Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner's terms of service?

**Comment by quinn463** [comment]
1. We would store the data about log from our system performance monitoring centers
2.OK. Here it is.
[access.log.11.gz](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/7844950/access.log.11.gz)
3.Yes! We will obey the rules.

**Comment by rayshitou** [comment]
Sorry, do you have business license?

**Comment by quinn463** [comment]
----- 原始邮件 -----
发件人：ST ***@***.***>
收件人：filecoin-project/filecoin-plus-client-onboarding ***@***.***>
抄送人：quinn463 ***@***.***>,  Mention ***@***.***>
主题：Re: [filecoin-project/filecoin-plus-client-onboarding] Client Allocation Request for: Titansoft (Issue #1339)
日期：2022年01月12日 11点03分


Sorry, do you have business license?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you were mentioned.

Yes, I have emailed you.Message ID: ***@***.***>

**Comment by quinn463** [comment]
> Sorry, do you have business license?

Yes, I have emailed you.

**Comment by rayshitou** [comment]
@quinn463 
1.How many miners do you want to store your data to? How much data for each miner?
2.What method/tool will you use to insperct miners? Which aspect of miners will you inspect?
3.Will you record your allocation decision in public? Which platform will you use?
4.Have you ever allocated before? If yes, how did you do when you were questioned? Any links?

**Comment by quinn463** [comment]
1. 4-5 miners. We try to allocate a share of no more than 30% to each miner.
2.github; Providers who have strong sealing capability will be chosen.
3.Yes. Filfox.
4.This is the first time for Titansoft to apply for datacap.

**Comment by rayshitou** [comment]
@quinn463 The DataCap has been granted, But grant information not shown here for some reason. You could check the transaction bellow for details. I will close this issue and please reopen it if you have any question about this application.
https://filscan.io/tipset/message-detail?cid=bafy2bzacec3cddpw3pnb53pfdppdvd5oiewiockn6fktsuuntbflq5m475mrw
