### ISSUE TITLE
Client Allocation Request for: hxmps

### ISSUE THREAD

**Issue by seboynestamica** [filecoin-project/filecoin-plus-client-onboarding#1341]
---

# Client Allocation Questions 

## Core Information
- Name: hxmps
- Website / Social Media: https://www.hxmps.com.tw/
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1x5hm6tts3byx4bipvufds33o34wyv6gqackrieq
- Notary Requested: ozhtdong

@seboynestamica Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by seboynestamica** [comment]
@ozhtdong [https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1005](url)

**Comment by seboynestamica** [comment]
Our capacity has used up. Can you allocate us new one? Thanks a lot!

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedknhpza7kbbxc5ocrstquh566pcaphfa4abtdqz3ks5if3io3vbg 
#### Address 
> f1x5hm6tts3byx4bipvufds33o34wyv6gqackrieq
#### Datacap Allocated
> NaNB
#### Signer Address
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedknhpza7kbbxc5ocrstquh566pcaphfa4abtdqz3ks5if3io3vbg
