### ISSUE TITLE
Client Allocation Request for: journeysendmarketing

### ISSUE THREAD

**Issue by AnitaBowen** [filecoin-project/filecoin-plus-client-onboarding#1357]
---

# Client Allocation Questions 

## Core Information
- Name: journeysendmarketing
- Website / Social Media: https://www.journeysendmarketing.com/
- Region: Oceania
- DataCap Requested: 10TiB
- Addresses to be Notarized: f146n6um6vijphged2c5pznottysaorzshufl2fea
- Notary Requested: MegTei

@AnitaBowen Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MegTei** [comment]
HI @AnitaBowen I'll run through some application triage questions with you, can you answer as best as possible, ping me if anything is unclear

DATACAP REQUEST

1. In which region(s) do you intend to use the DataCap?
2. How did you hear about the FIL+ program? Do you have a good understanding of the network and/or are involved in the web3.0 community?
3. What is your registered ASIC business name & address?
4. Provide a description of your business, the industry you work in and what you do.
5. What type/ category of data is being stored? (E.g Public data - back-up files, private encrypted files etc)
6. How much data will you onboard each week?
7. For how long do you intend to store your data with Filecoin?
8. Have you previously received DataCap? If so, please link to any previous requests/ github issues.
9. Are you aware of and do you intend to use any advanced features (e.g. Fast Retrieval) with your storage deals? If so, please specify the feature.
10. How frequently do you intend to retrieve data stored on Filecoin e.g. monthly, a couple times a year, infrequently.
MINER DETAILS
11. How many miners do you plan on using to distribute the data, providing their ID's?
12. Are any of those miners controlled by yourself / your organization and if so, what is the percentage?
13. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?

**Comment by AnitaBowen** [comment]
1. In which region(s) do you intend to use the DataCap?
We intend to use it in several regions, including Australia and Hong Kong.
2. How did you hear about the FIL+ program? Do you have a good understanding of the network and/or are involved in the web3.0 community?
We learned about it through YouTube.
3. What is your registered ASIC business name & address?
Journeys End Marketing    903/50 Clarence St, Sydney NSW 2000
4. Provide a description of your business, the industry you work in and what you do.
Australia’s top lead generation business. We are generating thousands and thousands of high quality leads each week for our customers.(Solar Power Leads\Debt Solution Leads\Real Estate Leads\Insurance Leads)
5. What type/ category of data is being stored? (E.g Public data - back-up files, private encrypted files etc)
We will store some publicly available data, mainly including some publicly available business statistics.
6. How much data will you onboard each week?
About 200G per week
7. For how long do you intend to store your data with Filecoin?
This is determined by the duration of the storage provider's service.
8. Have you previously received DataCap? If so, please link to any previous requests/ github issues.
None.
9. Are you aware of and do you intend to use any advanced features (e.g. Fast Retrieval) with your storage deals? If so, please specify the feature.
We will be looking for storage providers that offer Fast Retrieval.
10. How frequently do you intend to retrieve data stored on Filecoin e.g. monthly, a couple times a year, infrequently.
Maybe a few times a year
    MINER DETAILS
11. How many miners do you plan on using to distribute the data, providing their ID's?
We will look for more than 3 different storage providers to store the data.
12. Are any of those miners controlled by yourself / your organization and if so, what is the percentage?
None.
13. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?
Yes I agree.

**Comment by MegTei** [comment]
HI @AnitaBowen Apologies for extended delay in responding, Ive been down with COVID.
Can you provide your ABN and year the business was registered?

**Comment by kylyhorton** [comment]
Hi,MegTei    ABN 36 056 849 426    Registered from 01 Jul 2000

**Comment by AnitaBowen** [comment]
Hi,MegTei ABN 36 056 849 426 Registered from 01 Jul 2000

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaaiujdyqas4pprhikyeoxrbejoos5ra4eoffd2pbewfueczfcyxi 
#### Address 
> f146n6um6vijphged2c5pznottysaorzshufl2fea
#### Datacap Allocated
> NaNB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaaiujdyqas4pprhikyeoxrbejoos5ra4eoffd2pbewfueczfcyxi

**Comment by MegTei** [comment]
HI @AnitaBowen this has been approved, dont hesitate to reach out if you need any support.
