### ISSUE TITLE
Client Allocation Request for: YangsKitchen

### ISSUE THREAD

**Issue by yangsk5** [filecoin-project/filecoin-plus-client-onboarding#1373]
# Client Allocation Questions 

## Core Information
- Name: YangsKitchen
- Region: Asia excl. Greater China
- Website / Social Media: https://yangskitchen.modoo.at/
- DataCap Requested: 50TiB
- Addresses to be Notarized: f3u47afciyqsp3dib6cif2ozn5iyftcpk2hwx2mineakwdw6cddykuwdehahqwwbhs2o6f43ptcygetbydoxxq

-----------------------------

**Comment by galen-mcandrew** [comment]
Looks like you submitted this directly in GitHub by opening a new issue, which means it was not assigned to a notary. 

Can you resubmit your request using our form and selecting a notary?

https://plus.fil.org/verifiers
