### ISSUE TITLE
Client Allocation Request for: SD Cloud

### ISSUE THREAD

**Issue by 1ane-1** [filecoin-project/filecoin-plus-client-onboarding#1374]
---

# Client Allocation Questions 

## Core Information
- Name: SD Cloud
- Website / Social Media: https://www.sdcloud.top/
- Region: Greater China
- DataCap Requested: 2TiB
- Addresses to be Notarized: f3rk3f2lcts5vi6solqy7sibtazfj7ngpriztuwseol36uu4dwv6wdkc7zesvlli54becpxw4ukrffdrto3m3q
- Notary Requested: swatchliu

@1ane-1 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.)
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?

Would you like to submit more company information on www.bytebase.cn?

Would you like to accept our face-to-face visit?

**Comment by 1ane-1** [comment]
Of course
We are in Greater China, here is the website:https : //www.sdcloud.top/
Our company started in 2021 with 80 staffs. Our aim is to become the world's leading distributed storage technology service provider, committed to providing efficient, strong privacy, low-cost storage solutions for the digital economy era.
The link about us:https://twitter.com/IPFSZC    Weibo:https://weibo.com/u/7583724940
The data size maybe large to several TIBs. I didn't applied for Datacap to another notary.
Yes, we would like to check it and have a face-to-face visit ~

**Comment by swatchliu** [comment]
The  project of FIL+ is for the client who have public datasets to store ,not for the storage provider of filecoin. Looks like you are SP of filecoin according to the information you provided. If you want to have a try of receiving verified deals , I can allocate 2T datacap to you. By the way, totally we have only 4 TiB datacap left.

**Comment by 1ane-1** [comment]
i am glad to hear from you. 2T is ok for us. Thanks a lot.

**Comment by swatchliu** [comment]
ok

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebznraqtd6x6mgrtxmegifcb73mfolyyk5patt74vmbj7c3wertag 
#### Address 
> f3rk3f2lcts5vi6solqy7sibtazfj7ngpriztuwseol36uu4dwv6wdkc7zesvlli54becpxw4ukrffdrto3m3q
#### Datacap Allocated
> NaNB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebznraqtd6x6mgrtxmegifcb73mfolyyk5patt74vmbj7c3wertag

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
