### ISSUE TITLE
Client Allocation Request for: [cocopictures]

### ISSUE THREAD

**Issue by cocopic01** [filecoin-project/filecoin-plus-client-onboarding#1375]
# Client Allocation Questions 

## Core Information
- Name: [cocopictures]
- Website / Social Media: [https://cocopictures.modoo.at]
- Region: [Asia excl. Greater China]
- DataCap Requested: [50TiB]
- Addresses to be Notarized: [f3w6yowcqppelxgtzqvkggm7dxdeijao4i55lyefs5r6lro4orllt3c66amp77zcxbtpsvyajuzilfucu3voha]
- 
-----------------------------

**Comment by galen-mcandrew** [comment]
Looks like you submitted this directly in GitHub by opening a new issue, which means it was not assigned to a notary. 

Can you resubmit your request using our form and selecting a notary?

https://plus.fil.org/verifiers
