### ISSUE TITLE
Client Allocation Request for: YMH 

### ISSUE THREAD

**Issue by ymh220111** [filecoin-project/filecoin-plus-client-onboarding#1376]
# Client Allocation Questions 

## Core Information
- Name: YMH TV
- Website / Social Media: https://www.youtube.com/channel/UCK_RHaKSenHMocMtVMlOdRQ
- DataCap Requested: 50TiB
- Region: [Asia excl. Greater China]
- Addresses to be Notarized: f3vu3xgmns4s2dnzelnbqmh2q2ntoaumd7a254j2ghkirsn44nt7nbyp3mnlthztkt24tpne6l6n3x6746wipa
- Notary Requested: dannyob

-----------------------------

**Comment by dannyob** [comment]
Hi @ymh220111 -- could you apply to one of the notaries working in the Greater China area, where they will be able to confirm your allocation. We concentrate on Europe at FF currently.
