### ISSUE TITLE
Client Allocation Request for: TravelingD

### ISSUE THREAD

**Issue by TravelingD** [filecoin-project/filecoin-plus-client-onboarding#1380]
# Client Allocation Questions 

## Core Information
- Name: TravelingD
- Region: Asia excl. Greater China
- Website / Social Media: https://travelingmagazine.modoo.at/
- DataCap Requested: 50TiB
- Addresses to be Notarized: f3srucqpizvluijphh4ul6dxbeacbl7cnpjwa7fgnwmldawe6t4ar4kz7cjtxzgrxj5veiov54i53h6qrs46va
- Notary Requested: dannyob

-----------------------------

**Comment by dannyob** [comment]
Hi, could you [re-apply here](http://plus.fil.org/verifiers), but choose a notary in your region? Thank you.
