### ISSUE TITLE
Client Allocation Request for: AION EDU

### ISSUE THREAD

**Issue by HillYoo1** [filecoin-project/filecoin-plus-client-onboarding#1382]
# Client Allocation Questions 

## Core Information
- Name: AION EDU
- Website / Social Media: https://aionedu.com/
- DataCap Requested: [50TiB]
- Region: [Asia excl. Greater China]
- Addresses to be Notarized: f3rldygpqo5nasck7ov54z6me3zgjkjoujx3cbogq7zuprpaisuyfuemcqibekmdd7y3stdnjs7b6f3jurj5aa
- Notary Requested: dannyob

-----------------------------

**Comment by dannyob** [comment]
Hi @HillYoo1  -- could you apply to one of the notaries working in the Asia (excl. Greater China) area, where they will be able to confirm your allocation. We concentrate on Europe at FF currently.
