### ISSUE TITLE
Client Allocation Request for: ML Studio

### ISSUE THREAD

**Issue by boa0226** [filecoin-project/filecoin-plus-client-onboarding#1383]
# Client Allocation Questions 

## Core Information
- Name: ML Studio
- Website / Social Media: https://www.mooonlightstudio.com/
- DataCap Requested: [10 TiB]
- Region: Asia excl. Greater China
- Addresses to be Notarized: f3vvrdzb7fb35ln5tqcoaupfurtbb3l3gpbypld33yawidrwazpsgjeszj7sajwfev7m3i7zlsaj7267y4ikgq
- Notary Requested: rayshitou

-----------------------------

**Comment by rayshitou** [comment]
@boa0226 Thanks for your application. Please answer the following questions to let me know you and your company.
1.What's your name and your position in your company?What's your company's business?
2.Could you show me your company's business license? And please show me your company searching consequence in the local business license searching website.
3.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency? Could you please show me your cloud usage evidence?

**Comment by boa0226** [comment]
@rayshitou Hi, My name is Boa Ko, general manager of company. 

This is my Business License.
![License](https://user-images.githubusercontent.com/97571852/149080398-67368014-a7de-4b3e-8b54-ce087f10554a.jpg)
![License2](https://user-images.githubusercontent.com/97571852/149084812-2924a695-b3de-43db-b12a-91692caa6b17.jpg)

We've been storing and managing our data on our own NAS servers so far. However, some time ago, the data was lost due to an unexpected accident, and there was a lot of damage. So I'm hoping to use IPFS storage for secure data backup.

Thank you.

**Comment by rayshitou** [comment]
@boa0226 thanks for your answer.
1.What kind of data do you want to store and how much?
2.Could you please send me some demos of your data?
3.Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner's terms of service?

**Comment by jpo92po** [comment]
@rayshitou Hi! I'll try to answer your questions

1. We are a company that specializes in producing and servicing video and photo materials. So, we want to store video data such as video data and photos in Filecoin storage.
2. 
2. We have uploaded our video sample file.

https://user-images.githubusercontent.com/28918021/150479365-a3c31444-85d2-498d-8699-6e31289bf832.mp4

3. Yes, I agree

**Comment by boa0226** [comment]
@rayshitou 
1. Our Data is Video Things, about Fashion Model.
2.

https://user-images.githubusercontent.com/97571852/150713977-146fbe95-fc27-4592-817e-5de15c6ec993.mp4

3. Yes, I agree
