### ISSUE TITLE
Client Allocation Request for: allyn

### ISSUE THREAD

**Issue by ly82505129** [filecoin-project/filecoin-plus-client-onboarding#1389]
---

# Client Allocation Questions 

## Core Information
- Name: allyn
- Website / Social Media: https://filecoinproject.slack.com/team/U02L05CV9SM
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1niularcneibvkss6o7yjvc2jxt46pytiw7443wi
- Notary Requested: steven004

@ly82505129 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by steven004** [comment]
Hey @ly82505129 , thanks for your request. Can you kindly add more information / context here on:

1. yourself/ your organization (with links to official website/social media/news mentions etc)
2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners), if you are working with a service provider to store your data to Filecoin network, please name the provider.
5. How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
6. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
7. Would you be OK in posting deal transactions here?

Thanks

**Comment by ly82505129** [comment]
Dear natory @steven004 ,thx for verifying, these are my info below：
1、Our organzition ：福州易区块科技有限公司，my company does not currently have a website，myself slack link [](https://filecoinproject.slack.com/team/U02L05CV9SM)，my company will empower the filecoin ecosystem and provide ecological applications in the future
2、Actively participate in the venus community incubation project, active in various user communities, including “Filecoin技术交流-7群”“FilSwan开发者群”；
3、The first phase mainly includes video and document resources stored by myself, PM（product manager） industry cases；
4、I decide to allocate datacap to f01509930 miners or i will find more miners on https://plus.fil.org/miners；
5、There is no retrieval tool yet, but I will make it public，will be after Chinese New Year；
6、There are no profitable plans, the focus is on reducing the cost of storing data；
7、ok

**Comment by steven004** [comment]
Hey @ly82505129 , 

Are you applying the datacap for yourself or on behalf of the company? If you are applying for your company, I need to validate your business certification before moving further. 
I will issue you 2TiB as a start, you could apply again when it is done. Of course, we will go through a verification process before the next datacap is issued. Thanks. 

In addition, one service provider is not enough to save in Filecoin network for real useful data. Please try to find at least 3 service 
providers even it is for test.

**Comment by ly82505129** [comment]
@steven004 
This time I applied for the datacap for myself, but in the near future, I will apply for certification through the enterprise as a unit, because our project is in progress, including the production of the website and the development of the project.

I will find more providers in （https://filplus.d.interplanetary.one/ 、https://filrep.io/）.

**Comment by steven004** [comment]
Hey @ly82505129 , Your Datacap Allocation Request has been approved

**Message sent to Filecoin Network**
> [bafy2bzaceabhqm5zjc2fthfjq6tj4xarozwptpwhjikpa4lpxpyh3ge2h56cy](https://filscan.io/tipset/message-detail?cid=bafy2bzaceabhqm5zjc2fthfjq6tj4xarozwptpwhjikpa4lpxpyh3ge2h56cy)

**Address**
> [f1niularcneibvkss6o7yjvc2jxt46pytiw7443wi](https://filscan.io/address/general?address=f1niularcneibvkss6o7yjvc2jxt46pytiw7443wi)

**Datacap Allocated**
> 2.0TiB
