### ISSUE TITLE
Client Allocation Request for: Costel

### ISSUE THREAD

**Issue by Costelcoltd** [filecoin-project/filecoin-plus-client-onboarding#1392]
---

# Client Allocation Questions 

## Core Information
- Name: Costel
- Website / Social Media: www.costel.com
- Region: Asia excl. Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f3vpvtzcb6w6uwixeztmscfh2mvvjhrpmohyxazix6tw2sc6t4zufqs4iuhepf2f4uuqreqoxas6enpenxekoa
- Notary Requested: rayshitou

@Costelcoltd Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by rayshitou** [comment]
@Costelcoltd Sorry. We don't have enough DataCap left as you need. I will colse this issue. Welcome back if we have been granted new DataCap.
