### ISSUE TITLE
Client Allocation Request for: Klinelex

### ISSUE THREAD

**Issue by Klinelec** [filecoin-project/filecoin-plus-client-onboarding#1393]
---

# Client Allocation Questions 

## Core Information
- Name: Klinelex
- Website / Social Media: https://kcharger.net/
- Region: Asia excl. Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f3ubwsfcjydejzkuukx6wslfp7x7w6xgz2tdjn3ccvmvzz736onji6uyr32jhhebea4rmfqnb2mnvcwgigmxrq
- Notary Requested: rayshitou

@Klinelec Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by rayshitou** [comment]
@Klinelec Sorry. We don't have enough DataCap left as you need. I will colse this issue. Welcome back if we have been granted new DataCap.
