### ISSUE TITLE
Client Allocation Request for: Unicom

### ISSUE THREAD

**Issue by Sanguni** [filecoin-project/filecoin-plus-client-onboarding#1395]
---

# Client Allocation Questions 

## Core Information
- Name: Unicom
- Website / Social Media: https://iservice.10010.com/
- Region: Greater China
- DataCap Requested: 50TiB
- Addresses to be Notarized: f1kftqp5kdhd4bc3b6vo6o675vkn2elbmkfzsjkli
- Notary Requested: Fenbushi-Filecoin

Please make sure to check out the guidelines and criteria to accept Datacap request for [Fenbushi Capital](https://github.com/filecoin-project/filecoin-plus-client-onboarding/tree/main/Fenbushi%20Capital)

@Sanguni Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Sanguni** [comment]
@Fenbushi-Filecoin Hello, our company had applied for you in the past and we had sent you our information. Now we need more datacap to store. Please admit our application! Thank you!

**Comment by Sanguni** [comment]
@Fenbushi-Filecoin Hello, our company had applied to you in the past and we had sent you our information. Now we need more datacap to store. Please admit our application! Thank you!

**Comment by Sanguni** [comment]
Hello, this is the record of our previous request.
![dd4a7517-ec71-4907-ae8c-147071f25c5d](https://user-images.githubusercontent.com/97662500/149745829-46311aba-ab1c-45a6-993a-33e9ef02ad82.png)
Our previous issue: https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/558
That issue met some errors so that the previous account was suspended.

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebqh3vfjz634hxfh3t7jcsoyvgh6jpc3k2l4pppkjeiiizyicv7fa 
#### Address 
> f1kftqp5kdhd4bc3b6vo6o675vkn2elbmkfzsjkli
#### Datacap Allocated
> NaNB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebqh3vfjz634hxfh3t7jcsoyvgh6jpc3k2l4pppkjeiiizyicv7fa
