### ISSUE TITLE
Client Allocation Request for: Halmebooks

### ISSUE THREAD

**Issue by KhalmeAudio** [filecoin-project/filecoin-plus-client-onboarding#1400]
# Client Allocation Questions 

## Core Information
- Name: HalmeBooks
- Region: Asia excl. Greater China
- Website / Social Media: https://halmebooks.modoo.at/
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3s4wotkxd2piay4tlrt2c7j2ktosepmceb5ptwghk2x7jxohqnc5eahfylwrxwreafx22hglb7rycp3plemza
- Notary Requested: steven004

-----------------------------

**Comment by steven004** [comment]
Hey @KhalmeAudio , thanks for your request. Can you kindly add more information / context here on:

1. yourself/ your organization (with links to official website/social media/news mentions etc)
2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners), if you are working with a service provider to store your data to Filecoin network, please name the provider.
5. How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
6. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
7. Would you be OK in posting deal transactions here?

Thanks

**Comment by KhalmeAudio** [comment]
Hello @steven004 , thank you for your interest. I'll do my best to answer, so you can ask me again if you have any questions.

1.   We just have our website, https://halmebooks.modoo.at/  and recently we also manage youtube account, https://www.youtube.com/channel/UCiZSHsC4xx5Kawe0x8D7Sgg. We only have these.
2.   We don’t have any history on IPFS/Filecoin yet. But we already knew the value of FileCoin and were investing, so we applied because we think that it would be a good opportunity to us.
3.   Our data is many videos, grandmothers in hanbok tell old stories to children. We made the video in the kindergarten, and now we are sharing it with youtube for many kids in our country. And we have a lot of old stories for them.
4.   When we receive Datacap, we will divide it into five. I haven't decided on a specific minor yet. It will be selected based on reputation and distance of my place among Filecoin storage providers in Korea. The close distance would be an important factor because we might deliver our data offline.
5.   Unfortunately, we do not have any tools or apps. We will find a way if it is essential for getting the Datacap.
6.   We will use IPFS for storage to backup our data. We are a non-profit organization. We are planning to produce a video of an English version for children around the world, so we need a lot of data storage space.
7.   Yes it would be ok.

**Comment by steven004** [comment]
Hey @KhalmeAudio , It is great that you are interested by IPFS/Filecoin storage for your data. I would like to support you on this. The data you mentioned - the stories told by grandmothers are definitely very valuable. I will grant you 2TiB datacap for you to start to try and do some test, and I will issue you more once it is used up. Please let me know if you need any other support. 

One more question, do you know how much data you will save in Filecoin? if it is huge, e.g. more than 500TiB, you could apply large dataset cap instead.

**Comment by steven004** [comment]
Hey @KhalmeAudio , Your Datacap Allocation Request has been approved

**Message sent to Filecoin Network**
> [bafy2bzacecz5d3crxzmk4jk5vbad5s2cab2yliseq3ges5npqssnfyjehifg2](https://filscan.io/tipset/message-detail?cid=bafy2bzacecz5d3crxzmk4jk5vbad5s2cab2yliseq3ges5npqssnfyjehifg2)

**Address**
> [f3s4wotkxd2piay4tlrt2c7j2ktosepmceb5ptwghk2x7jxohqnc5eahfylwrxwreafx22hglb7rycp3plemza](https://filscan.io/address/general?address=f3s4wotkxd2piay4tlrt2c7j2ktosepmceb5ptwghk2x7jxohqnc5eahfylwrxwreafx22hglb7rycp3plemza)

**Datacap Allocated**
> 2.0TiB

**Comment by KhalmeAudio** [comment]
Thanks @steven004
I am really thanks for taking a good look at our data! I'll post the deal transaction here after spending the 2TB you gave me as I told you before.

We don't have more than 500TiB of data yet, so we plan to apply for General Verification next time. I'll request the datacap to you again.
