### ISSUE TITLE
Client Allocation Request for: EDGE22

### ISSUE THREAD

**Issue by edge22E** [filecoin-project/filecoin-plus-client-onboarding#1401]
# Client Allocation Questions 

## Core Information
- Name: EDGE22
- Region: Asia excl. Greater China
- Website / Social Media: https://edge22.co.kr/
- DataCap Requested: 50TiB
- Addresses to be Notarized: f3qjrgxzbr7uhsduaz2kpvivv43kvlfopvuqutabzb7cvhmrpjhv4pomvepktsru7xqi6xv376ebaxoysvclxq
- Notary Requested: steven004

-----------------------------

**Comment by steven004** [comment]
Hey @edge22E , thanks for your request. Can you kindly add more information / context here on:

1. yourself/ your organization (with links to official website/social media/news mentions etc)
2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners), if you are working with a service provider to store your data to Filecoin network, please name the provider.
5. How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
6. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
7. Would you be OK in posting deal transactions here?

Thanks

**Comment by edge22E** [comment]
@steven004  hello, this is the answer to your question.

1.   We have the website and Instagram and Youtube channel
- https://edge22.co.kr/
- https://www.youtube.com/channel/UCLEEsVloLKJMMQyFgc5M9rw
- https://www.instagram.com/edge22_official/
2.   We have no experience working on IPFS/Filecoin. But we think that this would be a good chance of starting working on IPFS/Filecoin.
3.   My company, Edge22’s data is many videos. We made commercial films, music videos, short dramas, web dramas, documentaries for our clients. We help our clients promote their products or the message they want to deliver.
4.   8~10 Miners,
Location : Located in Seoul, or Korea. (for offline deal.)
Specific requirement of storage miners : pretty new miner within 1month. (worrying about old miner would have hardware problem before contract duration over)
Recently I heard of Meta C&C and Maxpia for this. But didn't made contract with them specifically.
5.   Maybe miner company will help us retrieve the data.
6.   Our next plan is to make a metaverse Cinema. It would be found for profit, but for now we just want to store our video clips for future plan. 
7.   Yes! 

Thanks for your interest and I hope you give us a good opportunity.

**Comment by steven004** [comment]
Hey @edge22E , very glad you are interested in Filecoin network. 
I will grant you 2TiB for you first as a start point. You can use this to do some test and figure out how to work with Miners and Filecoin network. You can apply a new one anytime if you it is needed. 

Before the new data cap assigning, we need go through the verification process, which need to randomly check the data you uploaded into Filecoin network. And, I need to know more about your company. 

I hope there will be notaries from Korea next so that you could apply datacap from local notaries in the future.

**Comment by steven004** [comment]
Hey @edge22E , Your Datacap Allocation Request has been approved

**Message sent to Filecoin Network**
> [bafy2bzacecpb6z4egsg2yxzc333aghkm5lqnrjondis27edpinywfulibaxag](https://filscan.io/tipset/message-detail?cid=bafy2bzacecpb6z4egsg2yxzc333aghkm5lqnrjondis27edpinywfulibaxag)

**Address**
> [f3qjrgxzbr7uhsduaz2kpvivv43kvlfopvuqutabzb7cvhmrpjhv4pomvepktsru7xqi6xv376ebaxoysvclxq](https://filscan.io/address/general?address=f3qjrgxzbr7uhsduaz2kpvivv43kvlfopvuqutabzb7cvhmrpjhv4pomvepktsru7xqi6xv376ebaxoysvclxq)

**Datacap Allocated**
> 2.0TiB

**Comment by edge22E** [comment]
@steven004 I'm really thank you for your approval. 

We will request the new data cap after we use the Datacap you approve us with our data. If you want to know about our company, ask me more please.

I hope the next time there are notaries from Korea too.
