### ISSUE TITLE
Client Allocation Request for: ITBANK

### ISSUE THREAD

**Issue by ITbank** [filecoin-project/filecoin-plus-client-onboarding#1404]
# Client Allocation Questions 

## Core Information
- Name: ITBANK
- Region: Asia excl. Greater China
- Website / Social Media: http://www.goitbank.net/
- DataCap Requested: 30TiB
- Addresses to be Notarized: f3vghjxni5j2gtepqij4roishkzerbgzdjnacb4q5au5a4hogktpkwyvsnwpzgrdphm7miodffh26k7evs4goq
- Notary Requested: dannyob

-----------------------------

**Comment by dannyob** [comment]
Hi @ITbank  -- could you apply to one of the notaries working in the Asia region, where they will be able to confirm your allocation. We concentrate on Europe at FF currently.
