### ISSUE TITLE
Client Allocation Request for: Toastmasters

### ISSUE THREAD

**Issue by Jacintos** [filecoin-project/filecoin-plus-client-onboarding#1406]
---

# Client Allocation Questions 

## Core Information
- Name: Toastmasters
- Website / Social Media: https://www.toastmasters.org/
- Region: North America
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1hzdld5oikfi4p2h2qmnmqwjtl2znj2qfycxnuuq
- Notary Requested: MegTei

@Jacintos Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MegTei** [comment]
HI @Jacintos I'll run through some application triage questions with you, can you answer as best as possible, ping me if anything is unclear

1. In which region(s) do you intend to use the DataCap?
2. How did you hear about the FIL+ program? Do you have a good understanding of the network and/or are involved in the web3.0 community?
3. What is your registered business name & address?
4. Provide a description of your business, the industry you work in and what you do.
5. What type/ category of data is being stored? (E.g Public data - back-up files, private encrypted files etc)
6. How much data will you onboard each week?
7. For how long do you intend to store your data with Filecoin?
8. Have you previously received DataCap? If so, please link to any previous requests/ github issues.
9. Are you aware of and do you intend to use any advanced features (e.g. Fast Retrieval) with your storage deals? If so, please specify the feature.
10. How frequently do you intend to retrieve data stored on Filecoin e.g. monthly, a couple times a year, infrequently.
MINER DETAILS
11. How many miners do you plan on using to distribute the data, providing their ID's?
12. Are any of those miners controlled by yourself / your organization and if so, what is the percentage?
13. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?

**Comment by Jacintos** [comment]
1.We choose China, Korea or other countries.
2.We hear FIL+ from our partner. Yes, we do know about the Filecoin network and the Web3.0.
3.Toastmasters International; 9127 S. Jamaica Street, Suite 400 Englewood, CO 80112
You can refer to more details via https://www.toastmasters.org/
4.Toastmasters International is a nonprofit educational organization that teaches public speaking and leadership skills through a worldwide network of clubs. Headquartered in Englewood, Colo., the organization's membership exceeds 300,000 in more than 15,800 clubs in 149 countries. Since 1924, Toastmasters International has helped people from diverse backgrounds become more confident speakers, communicators, and leaders.
5.Video for our online and offline meeting. https://www.youtube.com/c/toastmasters
6.It may be 35TiB/week
7.2 more years
8.No, it’s my first time to make this application.
9.No, just backup file no retrieval request.
10.Infrequently.
11.2-3 storage providers will be cooperated with us.
12.No, we don’t have any controlled storage provider.
13.Yes, I agree.

**Comment by Jacintos** [comment]
Hi @MegTei 
1.We choose China, Korea or other countries.
2.We hear FIL+ from our partner. Yes, we do know about the Filecoin network and the Web3.0.
3.Toastmasters International; 9127 S. Jamaica Street, Suite 400 Englewood, CO 80112
You can refer to more details via https://www.toastmasters.org/
4.Toastmasters International is a nonprofit educational organization that teaches public speaking and leadership skills through a worldwide network of clubs. Headquartered in Englewood, Colo., the organization's membership exceeds 300,000 in more than 15,800 clubs in 149 countries. Since 1924, Toastmasters International has helped people from diverse backgrounds become more confident speakers, communicators, and leaders.
5.Video for our online and offline meeting. https://www.youtube.com/c/toastmasters
6.It may be 35TiB/week
7.2 more years
8.No, it’s my first time to make this application.
9.No, just backup file no retrieval request.
10.Infrequently.
11.2-3 storage providers will be cooperated with us.
12.No, we don’t have any controlled storage provider.
13.Yes, I agree.

**Comment by MegTei** [comment]
Thanks @Jacintos, working through a tech issue, will get this resolved asap and deliver your allocation.
@galen-mcandrew seeing this issue in attempting to allocate 
<img width="455" alt="image" src="https://user-images.githubusercontent.com/80305349/153089579-96a117a5-0266-407d-b70c-9784385a839b.png">

**Comment by galen-mcandrew** [comment]
Sounds like this same issue: https://github.com/keyko-io/filecoin-verifier-frontend/issues/377
@fabriziogianni7

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaapoqdx5r5kycagsxpzspebfxppl62547fomde2yv5qtm7cofdvi 
#### Address 
> f1hzdld5oikfi4p2h2qmnmqwjtl2znj2qfycxnuuq
#### Datacap Allocated
> 5.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaapoqdx5r5kycagsxpzspebfxppl62547fomde2yv5qtm7cofdvi

**Comment by MegTei** [comment]
HI @Jacintos your DataCap has been approved, dont hesitate to shout if you need any support.

**Comment by Jacintos** [comment]
Thanks a lot!! You have been a big help!

**Comment by Jacintos** [comment]
@MegTei Thanks a lot!! You have been a big help!
