### ISSUE TITLE
Client Allocation Request for: 上海小工蚁电子商务股份有限公司

### ISSUE THREAD

**Issue by sunhehe1314** [filecoin-project/filecoin-plus-client-onboarding#141]
---

# Client Allocation Questions 

## Core Information
- Name: 上海小工蚁电子商务股份有限公司
- Website / Social Media: https://baijiahao.baidu.com/s?id=1670705287832346196&wfr=spider&for=pc
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1xl5b4vmjnikoku4j6brt33yoyqqepmqt7aowzny
- Notary Requested: ozhtdong

**Comment by ozhtdong** [comment]
Hi. @sunhehe1314 Thanks for your application. I want to know more basic information of you and your company. Please answer following question:

What's your name? What's your position?
What's your company's business?
Cloud you show me your company's business license?
