### ISSUE TITLE
Client Allocation Request for: Edenvalley Resort

### ISSUE THREAD

**Issue by frametable** [filecoin-project/filecoin-plus-client-onboarding#1424]
---

# Client Allocation Questions 

## Core Information
- Name: Edenvalley Resort
- Website / Social Media: http://edenvalley.co.kr/
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3wkli64jh2oqnt47xni75hic2mbsodamwcrave5xqzf44jn3q3mk3pncylwzmgwxmsa3c5md23fw3o72wfysa
- Notary Requested: MasaakiNawatani

@frametable Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MasaakiNawatani** [comment]
Hi @frametable 

I currently have no available datacap to allocate for your organization. For now, please find a different Notary preferably from the same region as your operations. I will close this ticket now. Thanks.
