### ISSUE TITLE
Client Allocation Request for: 成都星际探索网络

### ISSUE THREAD

**Issue by xingjitansuo** [filecoin-project/filecoin-plus-client-onboarding#143]
---

# Client Allocation Questions 

## Core Information
- Name: 成都星际探索网络
- Website / Social Media: http://api.sr2.glm2m.com/index.php?r=smartcity-dataset/index
- Region: Asia excl. Greater China
- DataCap Requested: 100TiB
- Addresses to be Notarized: f1xlpzyo3lsejyafjhv6jc76r3jpfsampttbm4y4a
- Notary Requested: ozhtdong

**Comment by ozhtdong** [comment]
@xingjitansuo Thanks for your application. I want to know more basic information of you and your company. Please answer following question:

1. What's your name? What's your position?
2. What's your company's business? 
3. Cloud you show me your company's business license?
