### ISSUE TITLE
Client Allocation Request for: Julien NOEL

### ISSUE THREAD

**Issue by s0nik42** [filecoin-project/filecoin-plus-client-onboarding#145]
---

# Client Allocation Questions 

## Core Information
- Name: Julien NOEL
- Website / Social Media: https://www.linkedin.com/in/julien42/
- Region: Europe
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3vlzrzb6wjzlogdkhd5bsu2dzq6hrqryciu7bysmb7glimexcqfxzxrcfnygrco7j3zcw4346vb6oeue4uvhq
- Notary Requested: philippbanhardt

**Comment by s0nik42** [comment]
Hi @philippbanhardt ,

I'm following my previous datacap allocation (https://github.com/keyko-io/filecoin-clients-onboarding/issues/32) to store the freerainbowtables dataset to filecoin. 

I updated the previous allocation issue with the CIDs. The files have been store to 5 miners own by 5 different entities.

Thank you,

Julien

**Comment by philippbanhardt** [comment]
Fantastic, thanks @s0nik42

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceck4capojay6k32b6ezrk3rwf73y5zhhryugpzsdfnqnyqdycuhs2 
#### Address 
> f3vlzrzb6wjzlogdkhd5bsu2dzq6hrqryciu7bysmb7glimexcqfxzxrcfnygrco7j3zcw4346vb6oeue4uvhq
#### Datacap Allocated
> 5 TiB

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
