### ISSUE TITLE
Client Allocation Request for: Novi-Dao

### ISSUE THREAD

**Issue by novidao** [filecoin-project/filecoin-plus-client-onboarding#1455]
---

# Client Allocation Questions 

## Core Information
- Name: Novi-Dao
- Website / Social Media: https://novidao.io/
- Region: Europe
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1epuhw7ypm3lddyurirpekwsbbzgq5xltr2izisy
- Notary Requested: dannyob

@novidao Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
Hey @novidao, sorry for the delay. 

Here's your datacap. Please remember that this datacap should be used for material that is unencrypted and licensed to be distributed to the public. Please use your datacap to make deals with more than one miner. And please don't use a miner you have a pre-existing relationship with. Use your datacap for the public good! Any questions, mail me at danny@fil.org or @dannyob on the [Filecoin Project slack](https://filecoinproject.slack.com/)

这是您的数据上限。 请记住，此数据上限应用于未加密并许可向公众分发的材料。 请使用您的数据上限与多个矿工进行交易。 并且请不要使用与您有预先存在关系的矿工。 将您的数据上限用于公共利益！ 有任何问题，请在 [Filecoin Project slack](https://filecoinproject.slack.com/) 上给我发邮件至 danny@fil.org 或 @dannyob

**Comment by dannyob** [comment]
Okay, we hit a small bug with this datacap grant. Looking into it! Thank you again for your patience!

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaql2jkkiisy33qma5byqbbh4ri5jvbpjahxvttilom5ycddgzaba 
#### Address 
> f1epuhw7ypm3lddyurirpekwsbbzgq5xltr2izisy
#### Datacap Allocated
> 10.00TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaql2jkkiisy33qma5byqbbh4ri5jvbpjahxvttilom5ycddgzaba

**Comment by mr-spaghetti-code** [comment]
Hi,

It looks like you received 100TiBs of DataCap to date but have spent less than 20% of it so far.

We would love to understand if there's anything holding you back. We are working hard to make the data onboarding process easier for clients like you and your feedback is very valuable. If you have a moment, please fill in this survey: https://forms.gle/s6AuTXZPZSMokscLA

If you have any feedback or would like to consult with an expert, please let me know. 

Thanks,

João Fiadeiro
Product Manager, Large Data Client Onboarding
Protocol Labs
