### ISSUE TITLE
Client Allocation Request for: Dustin Greuel

### ISSUE THREAD

**Issue by dgreuel2002** [filecoin-project/filecoin-plus-client-onboarding#146]
---

# Client Allocation Questions 

## Core Information
- Name: Dustin Greuel
- Website / Social Media: https://www.linkedin.com/in/dustingreuel/
- Region: North America
- DataCap Requested: 5TiB
- Addresses to be Notarized: f047419
- Notary Requested: ann-shin

**Comment by ann-shin** [comment]
Hey @dgreuel2002 ,  thanks for your request. Can you kindly add more information / context here on:

1.Are you representing an individual or a company？
2.If you are representing a company, Please answer the following questions: What are the establishment time, number of employees, business scope, number of registered users, number of social media followers, and storage usage of your company? e.g. include links to social media/news mentions etc.
If you are an individual, Please introduce yourself,e.g. include links to social media/news mentions, etc.
3.Your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time, etc.
4.Type, size, and source of the data you will be store on Filecoin,e.g. public data or private data, etc. Is there any sensitive content or illegal content?
5.How you intend to store the data on Filecoin, e.g. redundancy, location/miner preferences, etc
6.Have you already apply for DataCap to another notary, and has it been accepted or rejected.
7.Would you be OK in posting deal transactions on Github?

**Comment by dgreuel2002** [comment]
https://www.linkedin.com/in/dustingreuel/
https://www.facebook.com/public/Dustin-Greuel
I am new to the crypto scene but carry 9 certifications from networking to VMWARE.
I joined Filecoin during mainet launch and went in with two other people. I have the physically hardware at my house and am hosting it over a 1 Gbps connection. The other two are financially invested as I do all the server maint. hardware wise and software wise. I have been very active on slack these last 5 months and have spent 100's of hours educating myself on the process. I am still proving all the original data from launch and will continue to grow. I recently just upgraded to separate the miner/daemon from the seal machine so now I can seal 1 TB a day. I am looking to store public data on filecoin from https://github.com/filecoin-project/slingshot/blob/master/datasets.md

I will store data in redundancy at least on two different miners in geographical locations in the USA

**Comment by ann-shin** [comment]
Hi, @dgreuel2002  , thank you for your application, unfortunately, we cannot grant you DataCap at this moment, due to your account activated time < 6 months, I will recommend you to apply again after 6 months of your account activated.

Thank you for your understanding.
