### ISSUE TITLE
Client Allocation Request for: KDEE ASSOCIATION

### ISSUE THREAD

**Issue by kdeekdee** [filecoin-project/filecoin-plus-client-onboarding#1463]
---

# Client Allocation Questions 

## Core Information
- Name: KDEE ASSOCIATION
- Website / Social Media: http://kdee.co.kr
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1miibe34hryhaefok2cfquqpmzr755wkd3plui3a
- Notary Requested: MasaakiNawatani

@kdeekdee Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MasaakiNawatani** [comment]
Hi @kdeekdee 

I currently have no more datacap to allocate. I am still awaiting the next round of distribution by March. Please feel free to check with other Notaries preferably from the same region where your business operates. Thanks.
