### ISSUE TITLE
Client Allocation Request for: Cyberpop Labs Ltd. Games, Inc.

### ISSUE THREAD

**Issue by cyberpopcyberpop** [filecoin-project/filecoin-plus-client-onboarding#1491]
---

# Client Allocation Questions 

## Core Information
- Name: Cyberpop Labs Ltd. Games, Inc.
- Website / Social Media: https://cyberpop.online/
- Region: Asia excl. Greater China
- DataCap Requested: 50TiB
- Addresses to be Notarized: f1we7ggmtqxl3nihei42vfhfafjjkqummxopaqvha
- Notary Requested: ozhtdong

@cyberpopcyberpop Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Please apply to your local notary.
