### ISSUE TITLE
Client Allocation Request for: Lcunyun

### ISSUE THREAD

**Issue by xjlz2022** [filecoin-project/filecoin-plus-client-onboarding#1494]
---

# Client Allocation Questions 

## Core Information
- Name: Lcunyun
- Website / Social Media: http://ipfs.lcunyun.com/
- Region: Greater China
- DataCap Requested: 1.5TiB
- Addresses to be Notarized: f3upvqixcfedlpvbinrtssgsr2adc6ek2vc2jbj3bwu4do2vwzj45m2wysabdww6uitx5luj73cwmhbbgusqoq
- Notary Requested: swatchliu

@xjlz2022 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.)
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?

Would you like to submit more company information on [www.bytebase.cn](http://www.bytebase.cn/)?

Would you like to accept our face-to-face visit?

**Comment by xjlz2022** [comment]
Yes. We are located at Chongqing.
Our company was established in 2020.
We have 120 employees.
We provide mainly conducts business in the field of blockchain distributed storage. Our goal is to construct an interoperable, safe and fast distributed storage node, and to provide trusted, controllable and scalable storage nodes and data storage scheme for enterprises, units and government agencies with storage needs. 
Wechat: 星际量子数字永生
Now we need 1.5TiB to store our data.
No, this is the first time we apply for datacap.
Sure, if you want more information about our company, we'll provide it by email.
With pleasure! We are located at Chongqing and welcome you!
