### ISSUE TITLE
Client Allocation Request for: zhang anne

### ISSUE THREAD

**Issue by 1ane-1** [filecoin-project/filecoin-plus-client-onboarding#1496]
---

# Client Allocation Questions 

## Core Information
- Name: zhang anne
- Website / Social Media: zhongchuangIPFS 
- Region: Greater China
- DataCap Requested: 20TiB
- Addresses to be Notarized: f3wwiudiv2vjdswtc4aab5o3qs6ygeujrrixyv6a2z4o6aoma34rjayapsmwvqxxgn7aavmzomfquzwd2dn3fa
- Notary Requested: steven004

@1ane-1 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by steven004** [comment]
@1ane-1 , I think you had perviously applied datacap, please provide the links of your previous applications, and then we will go through a verification process to grant you more. thanks.

**Comment by 1ane-1** [comment]
https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/720
here it is.

**Comment by 1ane-1** [comment]
> @1ane-1 , I think you had perviously applied datacap, please provide the links of your previous applications, and then we will go through a verification process to grant you more. thanks.

https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/720

**Comment by steven004** [comment]
@1ane-1 Your deals are verified. I am granting you the new one. Thanks for landing more data into Filecoin network.

**Comment by steven004** [comment]
Hey @1ane-1 , Your Datacap Allocation Request has been approved

**Message sent to Filecoin Network**
> [bafy2bzacecc37n7xkxphswx24ecu4563d7canpjezcrm6bjgixvh5upygc2gm](https://filscan.io/tipset/message-detail?cid=bafy2bzacecc37n7xkxphswx24ecu4563d7canpjezcrm6bjgixvh5upygc2gm)

**Address**
> [f3wwiudiv2vjdswtc4aab5o3qs6ygeujrrixyv6a2z4o6aoma34rjayapsmwvqxxgn7aavmzomfquzwd2dn3fa](https://filscan.io/address/general?address=f3wwiudiv2vjdswtc4aab5o3qs6ygeujrrixyv6a2z4o6aoma34rjayapsmwvqxxgn7aavmzomfquzwd2dn3fa)

**Datacap Allocated**
> 20.0TiB)

**Comment by 1ane-1** [comment]
[real data.txt](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/8503872/real.data.txt)

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
