### ISSUE TITLE
Client Allocation Request for: KDEE ASSOCIATION

### ISSUE THREAD

**Issue by kdeekdee** [filecoin-project/filecoin-plus-client-onboarding#1497]
---

# Client Allocation Questions 

## Core Information
- Name: KDEE ASSOCIATION
- Website / Social Media: http://kdee.co.kr
- Region: North America
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1miibe34hryhaefok2cfquqpmzr755wkd3plui3a
- Notary Requested: steven004

@kdeekdee Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by steven004** [comment]
Hey @kdeekdee , you set the region North America, which is not covered by me. I am basically focusing on Great China. 
I am closing this one, please submit a new one to another notary. thanks.
