### ISSUE TITLE
Client Allocation Request for: Crypto Times

### ISSUE THREAD

**Issue by cryptotimes-japan** [filecoin-project/filecoin-plus-client-onboarding#1501]
---

# Client Allocation Questions 

## Core Information
- Name: Crypto Times
- Website / Social Media: https://crypto-times.jp/
- Region: Asia excl. Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1kuludsgydjiy52f5pdemoajdrhqs4pztwbkq7wi
- Notary Requested: ozhtdong

@cryptotimes-japan Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Please apply to your local notary. Thanks.
