### ISSUE TITLE
Client Allocation Request for: Blockinpress

### ISSUE THREAD

**Issue by Blockinpress** [filecoin-project/filecoin-plus-client-onboarding#1505]
---

# Client Allocation Questions 

## Core Information
- Name: Blockinpress
- Website / Social Media: https://blockinpress.com/
- Region: Asia excl. Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1egqrp5gjqsivj6j3o6gj7gskdi2qh6uladnxlta
- Notary Requested: steven004

@Blockinpress Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by steven004** [comment]
Hey @Blockinpress , the region you set is Asia excl. Greater China, which is not covered by me.
You could either send this to one who is focusing on the region you defined, or you submit a new one to region Greater China.
