### ISSUE TITLE
Client Allocation Request for: Blockchainhub

### ISSUE THREAD

**Issue by blockchainhubkr** [filecoin-project/filecoin-plus-client-onboarding#1509]
---

# Client Allocation Questions 

## Core Information
- Name: Blockchainhub
- Website / Social Media: https://blockchainhub.kr/
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1muddct2iaaacpckx7u7us6ozg4graf2i3ua6v5q
- Notary Requested: ozhtdong

@blockchainhubkr Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Please apply to your local notary.
