### ISSUE TITLE
Client Allocation Request for: GStarLive

### ISSUE THREAD

**Issue by GStarLivekor** [filecoin-project/filecoin-plus-client-onboarding#1514]
---

# Client Allocation Questions 

## Core Information
- Name: GStarLive
- Website / Social Media: https://gstarlive.com/
- Region: Asia excl. Greater China
- DataCap Requested: 20TiB
- Addresses to be Notarized: f1ngy3m3fri2k7bnavh7l7qdj4jvkocrcf2h6c6ti
- Notary Requested: steven004

@GStarLivekor Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by steven004** [comment]
Hey @GStarLivekor , Thanks for your interest in loading data into Filecoin network. And sorry that you need to change the notary since your region is Asia excl. Greater China, which I am not in. Thanks.
