### ISSUE TITLE
Client Allocation Request for: Kodebox

### ISSUE THREAD

**Issue by Kodeboxkr** [filecoin-project/filecoin-plus-client-onboarding#1516]
---

# Client Allocation Questions 

## Core Information
- Name: Kodebox
- Website / Social Media: https://kodebox.io/
- Region: Asia excl. Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f16pippzh5h2sgg54npcpjgu6pialdlo2idpkwl7a
- Notary Requested: dannyob

@Kodeboxkr Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
Hi @Kodeboxkr ! Could you put this request to one of the notaries serving Asia? We concentrate at Filecoin Foundation on public data repositories and European requests. Thanks!
