### ISSUE TITLE
Client Allocation Request for: yahoo

### ISSUE THREAD

**Issue by bmollicafrederic** [filecoin-project/filecoin-plus-client-onboarding#1526]
---

# Client Allocation Questions 

## Core Information
- Name: yahoo
- Website / Social Media: https://tw.buy.yahoo.com/
- Region: Asia excl. Greater China
- DataCap Requested: 20TiB
- Addresses to be Notarized: f1gexwvdbyupazqecz5mqox7ckp3pxdatm25m4bvy
- Notary Requested: ozhtdong

@bmollicafrederic Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by bmollicafrederic** [comment]
@ozhtdong Hello, thanks for your approval last time, and we have used all of datacap. Now we want to apply for next round. Can you give us new datacap? Waiting for you!

**Comment by ozhtdong** [comment]
OK. Please be sure that your allocation will under the committee's rule.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacechvlwkgisweh6ioubt5fyct576w6x5n6carnfcw2noumx2tndtxe 
#### Address 
> f1gexwvdbyupazqecz5mqox7ckp3pxdatm25m4bvy
#### Datacap Allocated
> 20.00TiB
#### Signer Address
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacechvlwkgisweh6ioubt5fyct576w6x5n6carnfcw2noumx2tndtxe
