### ISSUE TITLE
Client Allocation Request for: Himelight

### ISSUE THREAD

**Issue by whitneywulkan** [filecoin-project/filecoin-plus-client-onboarding#1549]
---

# Client Allocation Questions 

## Core Information
- Name: Himelight
- Website / Social Media: https://www.himelight.com/
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1gecmx43as4xvhysmwr7pysjit4b3gpdks2h7j5q
- Notary Requested: ozhtdong

@whitneywulkan Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by whitneywulkan** [comment]
@ozhtdong https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1010 This is the previous issue. We need your approval again!

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb2ktzhu54snxfolt6llvs6v7p5xkbyfloqmqavv7kkl7tdh3g74g 
#### Address 
> f1gecmx43as4xvhysmwr7pysjit4b3gpdks2h7j5q
#### Datacap Allocated
> 20.00TiB
#### Signer Address
> f1lwpw2bcv66pla3lpkcuzquw37pbx7ur4m6zvq2a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb2ktzhu54snxfolt6llvs6v7p5xkbyfloqmqavv7kkl7tdh3g74g
