### ISSUE TITLE
Client Allocation Request for: kako

### ISSUE THREAD

**Issue by 2lifetop** [filecoin-project/filecoin-plus-client-onboarding#1583]
---

# Client Allocation Questions 

## Core Information
- Name: kako
- Website / Social Media: hostloc.com
- Region: Europe
- DataCap Requested: 20TiB
- Addresses to be Notarized: f1pyzn4a2mwkxpk7kdqr235dpeyoaqwhl4m7d6ltq
- Notary Requested: dannyob

@2lifetop Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
Hi @2lifetop -- could you apply to a notary serving your region (Asia minus GCR)?

Thanks!
