### ISSUE TITLE
Client Allocation Request for: miPool

### ISSUE THREAD

**Issue by filmipool** [filecoin-project/filecoin-plus-client-onboarding#16]
---

# Client Allocation Questions 

## Core Information
- Name: miPool
- Website / Social Media: https://mipool.one
- DataCap Requested: 120TiB
- Addresses to be Notarized: f086151
- Notary Requested: Rin-huang

**Comment by filmipool** [comment]
Anyone tell me how to go through next ?

**Comment by 1am5UP3RasM4R10** [comment]
> Anyone tell me how to go through next ?

Can you provide me the email of the person in charge of your company's Filecoin + project?

**Comment by filmipool** [comment]
Yes, pls contact this email: purson.chen@gmail.com
