### ISSUE TITLE
Client Allocation Request for: 四川星际荣威科技有限公司

### ISSUE THREAD

**Issue by yhcaozyyz** [filecoin-project/filecoin-plus-client-onboarding#1605]
---

# Client Allocation Questions 

## Core Information
- Name: 四川星际荣威科技有限公司
- Website / Social Media: 无
- Region: Greater China
- DataCap Requested: 1PiB
- Addresses to be Notarized: f3vhw33iashdhdkjxlwmjit5fey7xp74dibowyyl4haojlyqx5h4kv2r3pbedpieyspcmkql7nocyjhtnu7lia
- Notary Requested: steven004

@yhcaozyyz Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by steven004** [comment]
Hey @yhcaozyyz , thanks for your interest in loading data into Filecoin network. The information you provided is helpful. And if you could provide more information to the following questions, that would be wonderful. 
1. yourself/ your organization (with links to official website/social media/news mentions etc)
2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners), if you are working with a service provider to store your data to Filecoin network, please name the provider.
5. How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
6. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
7. Would you be OK in posting deal transactions here?

Thanks

**Comment by yhcaozyyz** [comment]
1：四川性急荣威科技有限公司
2：矿商




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Steven ***@***.***&gt;; 
发送时间: 2022年3月18日(星期五) 上午9:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [filecoin-project/filecoin-plus-client-onboarding] Client Allocation Request for: 四川星际荣威科技有限公司 (Issue #1605)





 
Hey @yhcaozyyz , thanks for your interest in loading data into Filecoin network. The information you provided is helpful. And if you could provide more information to the following questions, that would be wonderful.
  
yourself/ your organization (with links to official website/social media/news mentions etc)
 
Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
 
Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
 
Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners), if you are working with a service provider to store your data to Filecoin network, please name the provider.
 
How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
 
What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
 
Would you be OK in posting deal transactions here?
  
Thanks
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yhcaozyyz** [comment]
yourself/ your organization (with links to official website/social media/news mentions etc)四川星际荣威科技有限公司，https://baike.baidu.com/item/%E5%9B%9B%E5%B7%9D%E6%98%9F%E9%99%85%E8%8D%A3%E5%A8%81%E7%A7%91%E6%8A%80%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/50148481?fr=aladdin

Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)参加过太空竞赛，目前是一家纯粹的存储提供商

Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin&nbsp; &nbsp; &nbsp;计划存储的数据为某大型企业的企业数据，数据量约为1PB

Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners), if you are working with a service provider to store your data to Filecoin network, please name the provider.需要1PB的空间，预计放在我们自己的集群里，指定至f0463383

How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?&nbsp; 有工具，支持检索

What's your next plan for the data you plan to store in Filecoin Network? For-profit or not? 继续为企业及政府存储真实数据，盈利

Would you be OK in posting deal transactions here? 可以在这里发布







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "秋燚"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月18日(星期五) 上午9:44
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [filecoin-project/filecoin-plus-client-onboarding] Client Allocation Request for: 四川星际荣威科技有限公司 (Issue #1605)



 1：四川性急荣威科技有限公司
2：矿商




------------------ 原始邮件 ------------------
发件人: "Steven ***@***.***&gt;; 
发送时间: 2022年3月18日(星期五) 上午9:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [filecoin-project/filecoin-plus-client-onboarding] Client Allocation Request for: 四川星际荣威科技有限公司 (Issue #1605)





 
Hey @yhcaozyyz , thanks for your interest in loading data into Filecoin network. The information you provided is helpful. And if you could provide more information to the following questions, that would be wonderful.
  
yourself/ your organization (with links to official website/social media/news mentions etc)
 
Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
 
Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
 
Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners), if you are working with a service provider to store your data to Filecoin network, please name the provider.
 
How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
 
What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
 
Would you be OK in posting deal transactions here?
  
Thanks
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
