### ISSUE TITLE
Client Allocation Request for: Fleek

### ISSUE THREAD

**Issue by jsonsivar** [filecoin-project/filecoin-plus-client-onboarding#161]
---

# Client Allocation Questions 

## Core Information
- Name: Fleek
- Website / Social Media: fleek.co
- Region: North America
- DataCap Requested: 3TiB
- Addresses to be Notarized: f1u77wemzteznm5zar3dyyi4ybithzoite7f4sqky
- Notary Requested: s0nik42

**Comment by s0nik42** [comment]
Thanks for your request. Can you kindly add more information / context here on:

Exposure : 
- Yourself , e.g. include links to social media / news mentions etc

Ecosystem : 
-  Your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc 

Data : 
- Type, size and source of the data you are looking to store on Filecoin, e.g. public data vs private data etc 
- Your relationship with the data, especially with regard to copyright 
- If the data is encrypted, are you authorized  in case of an Audit to provide me or another notary the key to decrypt a deal of our choice ?

Storage : 
- How you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc 
- Could you confirm if the data will be encrypted or not ?
- How much data are you considering storing to your own miner ?
- Please describe the nature of the relationship you have with the miners you are going to store data to. Especially if you have  any interests ?

- Have you already ask Datacap to another notary that have been accepted or rejected. 
- Finally, will you agree to share here all the CIDs related to the datacap ? 

Thanks

**Comment by jsonsivar** [comment]
> Exposure :
>
> Yourself , e.g. include links to social media / news mentions etc

<a href="https://fleek.co">Fleek.co</a>, <a href="https://space.storage">space.storage</a>, <a href="https://twitter.com/fleekhq">twitter.com/fleekhq</a>, <a href="https://twitter.com/spacestorage">twitter.com/spacestorage</a>

>Ecosystem :
>
>     Your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc 

* Running IPFS site hosting since start of 2020 (fleek.co)
* Developed Space storage app based on IPFS
* Close collaboration with Protocol labs team (support, product discussions, roadmapping)
* Participated in Filecoin verification process brainstorming

>Data :
>
>    Type, size and source of the data you are looking to store on Filecoin, e.g. public data vs private data etc 
    Your relationship with the data, especially with regard to copyright 
    If the data is encrypted, are you authorized in case of an Audit to provide me or another notary the key to decrypt a deal of our choice ?

In general, we store files for our users across Fleek and Space.  We aggregate them together so that we can bundle more economic batch sizes and in the future, we want to have user-specific bundles so that they can set their own policies and own the deals. We are storing different types of data so will break it down as per those types:
* Sites data: this data is public since it is meant for public static site hosting so it is not encrypted and therefore the Filecoin deal content will be visible by yourself
* Storage data: this data is also public since it is meant for public assets so it is not encrypted and therefore the Filecoin deal content will be visible by yourself
* Space data: since Space is a privacy focused app, users own these files and we do not have access to their file decryption keys. In this case we would have encrypted files in the bundle and would not be able to decrypt them ourselves. However in the case of an incident, the available option would be to contact our user and request a copy of the file. Perhaps a future improvement could be to store some hash of the original file in our metadata so that if we do require to follow up with the user and get a specific file for incidents, we can confirm it was the original file by generating the hash and comparing to the users metadata

> Storage :

>    How you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc 

We are currently storing the archives with Piknik miner.  They have been super helpful in getting us setup and are great to work with. They are located in US west which was ideal for us given our infrastructure is also mostly there. 

>     Could you confirm if the data will be encrypted or not ?

Please see the "data" section above for more details. But essentially since we are batching together files from different products, some of the files in a given deal will be encrypted, while other files may not.

>     How much data are you considering storing to your own miner ?

Currently we generate about 3GB of data per day and we have set the sector size to be 16GB with the miner.  Once this verification process goes through, we may be able to bring the sector size down if Piknik is okay with it. But this size also works for us.

>    Please describe the nature of the relationship you have with the miners you are going to store data to. Especially if you have any interests ?

We don't have any financial interests with the miner (Piknik). We met them through Julien and have built a relationship with them around the mining setup.  They are our exclusive miners currently.  

>     Have you already ask Datacap to another notary that have been accepted or rejected. 

No

>    Finally, will you agree to share here all the CIDs related to the datacap ? 

Agreed

**Comment by s0nik42** [comment]
@jsonsivar thank you for you answers, datacap has to be consume in the spirit of the filecoin network, which means your data should have multiple copy accross the network. Could you confirm you are planning to store short term multiple copies to multiple miners ?

Thank you,

Julien

**Comment by jsonsivar** [comment]
Thanks @s0nik42 .  I can confirm that we will store short term copies with multiple miners :+1:

**Comment by s0nik42** [comment]
Thank you, you will receive 3TiB, could you confirm that your adress will be : f1u77wemzteznm5zar3dyyi4ybithzoite7f4sqky

**Comment by jsonsivar** [comment]
Confirming that is the address :+1:
