### ISSUE TITLE
Client Allocation Request for: Plant Research South China Base of China Agricultural University

### ISSUE THREAD

**Issue by vetetable360** [filecoin-project/filecoin-plus-client-onboarding#1642]
---

# Client Allocation Questions 

## Core Information
- Name: Plant Research South China Base of China Agricultural University
- Website / Social Media: http://vetetable.com/
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy
- Notary Requested: dannyob

@vetetable360 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
Hi! Could you request this through a notary in your region? A list is available here: https://plus.fil.org/verifiers
