### ISSUE TITLE
Client Allocation Request for: K+ IPFS (주)

### ISSUE THREAD

**Issue by junwooamin** [filecoin-project/filecoin-plus-client-onboarding#1668]
---

# Client Allocation Questions 

## Core Information
- Name: K+ IPFS (주)
- Website / Social Media: ipfs-k.com
- Region: North America
- DataCap Requested: 2TiB
- Addresses to be Notarized: f3qei5u6w2r56kjnt3d4a7ypva6yiddytx5szasijnani64vz65yedzztcf72ei2jik3pfa4dpeh7gisvnxzeq
- Notary Requested: MasaakiNawatani

@junwooamin Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by bellanandakim** [comment]
We have registered Datacap before.
 Please refer to the previous request which is  <Client Allocation Request for: K+IPFS #1092>
