### ISSUE TITLE
Client Allocation Request for: Plant Elements

### ISSUE THREAD

**Issue by niutonghz** [filecoin-project/filecoin-plus-client-onboarding#1669]
---

# Client Allocation Questions 

## Core Information
- Name: Plant Elements
- Website / Social Media: http://vetetable.com
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy
- Notary Requested: dannyob

@niutonghz Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
Hi! Could you submit this to a notary in your region? You can find them here: https://plus.fil.org/verifiers
