### ISSUE TITLE
Client Allocation Request for: Plant Elements

### ISSUE THREAD

**Issue by vetetable360** [filecoin-project/filecoin-plus-client-onboarding#1675]
---

# Client Allocation Questions 

## Core Information
- Name: Plant Elements
- Website / Social Media: http://vetetable.com
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy
- Notary Requested: MRJAVAZHAO

@vetetable360 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MRJAVAZHAO** [comment]
Hi,@[vetetable360](https://github.com/vetetable360)
There is no DataCap for approval at present, please apply to other notaries.
