### ISSUE TITLE
Client Allocation Request for: 海员实验室

### ISSUE THREAD

**Issue by farmingDCH** [filecoin-project/filecoin-plus-client-onboarding#1677]
---

# Client Allocation Questions 

## Core Information
- Name: 海员实验室
- Website / Social Media: wu
- Region: Greater China
- DataCap Requested: 5GiB
- Addresses to be Notarized: f1bsfkx3qs6s5e4ldld5mkpsq4smfp7s4na3sec2a
- Notary Requested: MRJAVAZHAO

@farmingDCH Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MRJAVAZHAO** [comment]
Hi,@[farmingDCH](https://github.com/farmingDCH)
There is no DataCap for approval at present, please apply to other notaries.
