### ISSUE TITLE
Client Allocation Request for: Plant Elements

### ISSUE THREAD

**Issue by vetetable360** [filecoin-project/filecoin-plus-client-onboarding#1684]
---

# Client Allocation Questions 

## Core Information
- Name: Plant Elements
- Website / Social Media: http://vetetable.com
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy
- Notary Requested: steven004

@vetetable360 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by steven004** [comment]
Hey @vetetable360 , thanks for your request. You have submitted a bunch of duplicated applications. I closed all others except of this one. To better understand your request, can you kindly add more information / context here on:

1. yourself/ your organization (with links to official website/social media/news mentions etc)
2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners), if you are working with a service provider to store your data to Filecoin network, please name the provider.
5. How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
6. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
7. Would you be OK in posting deal transactions here?

Thanks

**Comment by vetetable360** [comment]
Hello @steven004, thanks for the prompt reply. I've posted the answers to the questions below:

**1. Yourself/ your organization (with links to official website/social media/news mentions etc)**
Vetetable.com, also known as Plant Elements, was founded in 2019. It was initiated by 5 professors and 12 scholars from Agricultural University, and a plant science website jointly built by several plant enthusiasts from all over the country. Preserve originals and copies of botanical photographs, negatives, slides, digital image source files, and other botanical-related images. Nearly 10,000 original pictures of plants, pictures of wild plants such as ferns, and 100,000 digital photos have been collected, which have produced a significant effect of building a library in scientific research, popular science education, book publishing, and economic and social services. The website aims to promote plant science, popularize plant knowledge, and let more people understand the habits and characteristics of different plants, so as to achieve peaceful coexistence between humans and nature, and make the earth full of green and oxygen.

**2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)**
Not yet, we want to store our data on a safe and reliable filecoin, and we will do our best to recommend filecoin to our partners.

**3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin**
We plan to store publicly available large datasets and make it available for anyone.

**4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners), if you are working with a service provider to store your data to Filecoin network, please name the provider.**
We plan to allocate the data to around 4-5 different SPs based on our own evaluation of their reputation, with each miner storing between 15-20% of the data.

**5. How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?**
We currently do not have an application for retrieval. We plan to leverage on the open dataset to experiment building data retrieval apps and other possible applications to build on the workflow.

**6. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?**
We plan to let the public use these dataset if they require, providing a decentralised option for these publicly available datasets. This will be non-profit.

**7. Would you be OK in posting deal transactions here?**
Yes

Thank you!

**Comment by steven004** [comment]
Hey @vetetable360 , very interesting project. I'd love to support it, especially you are saving public data which is good for the planet. 

I'm grant you 5TiB datacap, you could apply more before it is used up. More datacap can be granted once your data with this datacap is verified. Thanks again for your interest in Filecoin.

**Comment by steven004** [comment]
Hey @vetetable360 , Your Datacap Allocation Request has been approved

**Message sent to Filecoin Network**
> [bafy2bzacedk65rtxfjgg5ijyur7osttzfogyph5xqy6gskektijkt7a4uhrqo](https://filscan.io/tipset/message-detail?cid=bafy2bzacedk65rtxfjgg5ijyur7osttzfogyph5xqy6gskektijkt7a4uhrqo)

**Address**
> [f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy](https://filscan.io/address/general?address=f15d5pxriekd6rcxx2t5xlebbubc5qlqtcuyewxfy)

**Datacap Allocated**
> 5.0TiB
