### ISSUE TITLE
Client Allocation Request for: charternorth

### ISSUE THREAD

**Issue by vivicajon** [filecoin-project/filecoin-plus-client-onboarding#1699]
---

# Client Allocation Questions 

## Core Information
- Name: charternorth
- Website / Social Media: https://www.charternorth.com.au/
- Region: Oceania
- DataCap Requested: 10TiB
- Addresses to be Notarized: f17nj6x2rt7yuk4wyw33gc2jxjjxqibvpve22inna
- Notary Requested: MegTei

@vivicajon Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MegTei** [comment]
HI @vivicajon I'll run through some application triage questions with you, can you answer as best as possible, ping me if anything is unclear

DATACAP REQUEST

1. In which region(s) do you intend to use the DataCap?
2. How did you hear about the FIL+ program? Do you have a good understanding of the network and/or are involved in the web3.0 community?
3. What is your registered business name & address?
4. Provide a description of your business, the industry you work in and what you do.
5. What type/ category of data is being stored? (E.g Public data - back-up files, private encrypted files etc)
6. For how long do you intend to store your data with Filecoin?
7. Have you previously received DataCap? If so, please link to any previous requests/ github issues.
8. How frequently do you intend to retrieve data stored on Filecoin e.g. monthly, a couple times a year, infrequently.
MINER DETAILS
9. How many miners do you plan on using to distribute the data, providing their ID's?
10. Are any of those miners controlled by yourself / your organization and if so, what is the percentage?
11. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?

**Comment by vivicajon** [comment]
Hi，MegTei

1.We expect to use it in Hong Kong and Australia.
2.We were introduced to Filecoin by a friend.
3.Charternorth  NT 0820
4.Charter North 4WD Safaris is the result of a rising interest in genuine small group tours as a great alternative to larger coach style products.
5.Primarily public video.
6.I tend to prefer permanent.
7.No.
8.Maybe 2-3 times a year.
9.We expect to pick 3 miners.
10.They are not under my control.
11.Yes, I agree.

**Comment by MegTei** [comment]
Hi @vivicajon having some technical issues approving this, bear with me.
Hi @galen-mcandrew can you see this approval showing up?

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb2cd654ogtjsfvtcz2w5rwhuivo64axz5o237p2jcik7ndvgarbk 
#### Address 
> f17nj6x2rt7yuk4wyw33gc2jxjjxqibvpve22inna
#### Datacap Allocated
> 10.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb2cd654ogtjsfvtcz2w5rwhuivo64axz5o237p2jcik7ndvgarbk

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4gejuf2o3wk6nsrusgejlgvro63upar5j2fzr3mntmq4ing22vo 
#### Address 
> f17nj6x2rt7yuk4wyw33gc2jxjjxqibvpve22inna
#### Datacap Allocated
> 10.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4gejuf2o3wk6nsrusgejlgvro63upar5j2fzr3mntmq4ing22vo

**Comment by MegTei** [comment]
HI @vivicajon apologies for the delay, you now have datacap to use, do you need any assistance locating Storage Providers?
