### ISSUE TITLE
Client Allocation Request for: TEST TEST TEST - ONBOARDING EXAMPLE

### ISSUE THREAD

**Issue by Kevin-FF-USA** [filecoin-project/filecoin-plus-client-onboarding#1711]
---

# Client Allocation Questions 

## Core Information
- Name: TEST TEST TEST - ONBOARDING EXAMPLE
- Website / Social Media: Filecoinfoundation.org
- Region: North America
- DataCap Requested: 1TiB
- Addresses to be Notarized: 1234
- Notary Requested: dannyob

@Kevin-FF-USA Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Kevin-FF-USA** [comment]
Opened as an example for Notary onboarding. Closing. No action needed.

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
