### ISSUE TITLE
Client Allocation Request for: Kite Magic

### ISSUE THREAD

**Issue by yudcgu** [filecoin-project/filecoin-plus-client-onboarding#1719]
---

# Client Allocation Questions 

## Core Information
- Name: Kite Magic
- Website / Social Media: https://kitesite.com.au/index.html
- Region: Oceania
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1sr7skr2qwsfatufxqduu4jz33mwg7qygthsmuta
- Notary Requested: MegTei

@yudcgu Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MegTei** [comment]
HI @yudcgu I'll run through some application triage questions with you, can you answer as best as possible, ping me if anything is unclear

DATACAP REQUEST

1. In which region(s) do you intend to use the DataCap?
2. How did you hear about the FIL+ program? Do you have a good understanding of the network and/or are involved in the web3.0 community?
3. What is your registered business name & address?
4. Provide a description of your business, the industry you work in and what you do.
5. What type/ category of data is being stored? (E.g Public data - back-up files, private encrypted files etc)
6. How much data will you onboard each week?
7. For how long do you intend to store your data with Filecoin?
8. Have you previously received DataCap? If so, please link to any previous requests/ github issues.
9. How frequently do you intend to retrieve data stored on Filecoin e.g. monthly, a couple times a year, infrequently.
MINER DETAILS
10. How many miners do you plan on using to distribute the data, providing their ID's?
11. Are any of those miners controlled by yourself / your organization and if so, what is the percentage?
12. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?

**Comment by yudcgu** [comment]
@MegTei Thank you for your questions!
1.Australia
2.My friends have told me about this.
3.Kite Magic
1/99 Malabar Road, Coogee
NSW, Australia, 2034
4.Our business aims to provide good quality resources and the largest range of kite making components in Australia plus STEM kits. Our greatest love is offering the knowledge about how to create fun and interesting STEM projects. These include kites, solar kits and solar cars plus soon to be added other new interesting ideas we are working on.
5.Videos
6. 2TiB/a week
7.Permanent
8.No. It's the first time.
9. 3-4 times/per year
10.About 3 miners
11.No one
12.Yes, I do.

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaecdm6gbhj6sl6fwwqqc3xa3ttvja6ouwstm55udtcyfmpiaftme 
#### Address 
> f1sr7skr2qwsfatufxqduu4jz33mwg7qygthsmuta
#### Datacap Allocated
> 10.00TiB
#### Signer Address
> f1ystxl2ootvpirpa7ebgwl7vlhwkbx2r4zjxwe5i
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaecdm6gbhj6sl6fwwqqc3xa3ttvja6ouwstm55udtcyfmpiaftme

**Comment by MegTei** [comment]
Thanks @yudcgu for your responses, you now have datacap, let us know if you need any further support
