### ISSUE TITLE
Client Allocation Request for: One Chao

### ISSUE THREAD

**Issue by wjrayf** [filecoin-project/filecoin-plus-client-onboarding#1766]
---

# Client Allocation Questions 

## Core Information
- Name: One Chao
- Website / Social Media: http://www.1-zhao.com/
- Region: Greater China
- DataCap Requested: 50TiB
- Addresses to be Notarized: f1euzpiitzkcsauqgprpnskagob3erf4v5j64eggy
- Notary Requested: Fenbushi-Filecoin

Please make sure to check out the guidelines and criteria to accept Datacap request for [Fenbushi Capital](https://github.com/filecoin-project/filecoin-plus-client-onboarding/tree/main/Fenbushi%20Capital)

@wjrayf Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Fenbushi-Filecoin** [comment]
We have received the materials via email. The materials have proved that the applicant is qualified to receive the datacap.

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceag2j4sokb2uujemzdv2tvebfgyk3s3o6linerkhmcnowyijojjow 
#### Address 
> f1euzpiitzkcsauqgprpnskagob3erf4v5j64eggy
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceag2j4sokb2uujemzdv2tvebfgyk3s3o6linerkhmcnowyijojjow
