### ISSUE TITLE
Client Allocation Request for: Good Chef Bad Chef

### ISSUE THREAD

**Issue by GCBC01** [filecoin-project/filecoin-plus-client-onboarding#1799]
---

# Client Allocation Questions 

## Core Information
- Name: Good Chef Bad Chef
- Website / Social Media: https://www.goodchefbadchef.com.au/
- Region: Oceania
- DataCap Requested: 20TiB
- Addresses to be Notarized: f1ldzhbaoh2rmfw66rnbou4z53jphwapwhg73j5gq
- Notary Requested: MegTei

@xctmph Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MegTei** [comment]
HI @GCBC01 I'll run through some application triage questions with you, can you answer as best as possible, ping me if anything is unclear

DATACAP REQUEST

1. In which region(s) do you intend to use the DataCap?
2. How did you hear about the FIL+ program? Do you have a good understanding of the network and/or are involved in the web3.0 community?
3. What is your registered business name & address?
4. Provide a description of your business, the industry you work in and what you do.
5. What type/ category of data is being stored? (E.g Public data - back-up files, private encrypted files etc)
6. How much data will you onboard each week?
7. For how long do you intend to store your data with Filecoin?
8. Have you previously received DataCap? If so, please link to any previous requests/ github issues.
9. How frequently do you intend to retrieve data stored on Filecoin e.g. monthly, a couple times a year, infrequently.
MINER DETAILS
10. How many miners do you plan on using to distribute the data, providing their ID's?
11. Are any of those miners controlled by yourself / your organization and if so, what is the percentage?
12. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?

**Comment by GCBC01** [comment]
@MegTei 
Australia.

My partner told me and recommend me to FIL+ program.

We are a TV show on channel10 in Australia. Good Chef Bad Chef.

We want more people can join chef Adrian Richardson and Dr Preeya Alexander as they cook up a storm-sometimes healthy, sometimes comforting, always delicious. Whether it's nutrition or decadence you're after, there's something for everyone on Good Chef Bad Chef!

Video records and images.

4TIB.

We intend to keep data storage 2 years.

Not yet.

Monthly.

We plan to distribute to 4 miners.

No, we'll contact someone.

Yes, I do.

**Comment by MegTei** [comment]
Thanks @GCBC01 for your answers, yes Im a foodie, I know your show!
Im having some issues with my wallet allocating datacap, standby, the tech team are looking into it
