### ISSUE TITLE
Client Allocation Request for: miPool

### ISSUE THREAD

**Issue by filmipool** [filecoin-project/filecoin-plus-client-onboarding#18]
---

# Client Allocation Questions 

## Core Information
- Name: miPool
- Website / Social Media: https://mipool.one
- DataCap Requested: 120TiB
- Addresses to be Notarized: f0119336
- Notary Requested: jsonsivar

**Comment by dkkapur** [comment]
Closing this application out since @jsonsivar / Fleek are stepping back from Notary responsibilities for the time being.
