### ISSUE TITLE
Client Allocation Request for: Cakes in a Jar

### ISSUE THREAD

**Issue by CakesinaJar** [filecoin-project/filecoin-plus-client-onboarding#1800]
---

# Client Allocation Questions 

## Core Information
- Name: Cakes in a Jar
- Website / Social Media: https://www.cakesinajar.online/
- Region: Oceania
- DataCap Requested: 20TiB
- Addresses to be Notarized: f1mqj7a32xlxvjpjarkvzszgokzk4uadoglr72sja
- Notary Requested: MegTei

@cyrkvx Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MegTei** [comment]
Hi @CakesinaJar I'll run through some application triage questions with you, can you answer as best as possible, ping me if anything is unclear

DATACAP REQUEST

1. In which region(s) do you intend to use the DataCap?
2. How did you hear about the FIL+ program? Do you have a good understanding of the network and/or are involved in the web3.0 community?
3. What is your registered business name & address?
4. Provide a description of your business, the industry you work in and what you do.
5. What type/ category of data is being stored? (E.g Public data - back-up files, private encrypted files etc)
6. How much data will you onboard each week?
7. For how long do you intend to store your data with Filecoin?
8. Have you previously received DataCap? If so, please link to any previous requests/ github issues.
9. How frequently do you intend to retrieve data stored on Filecoin e.g. monthly, a couple times a year, infrequently.
MINER DETAILS
10. How many miners do you plan on using to distribute the data, providing their ID's?
11. Are any of those miners controlled by yourself / your organization and if so, what is the percentage?
12. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?

**Comment by CakesinaJar** [comment]
> Hi @CakesinaJar I'll run through some application triage questions with you, can you answer as best as possible, ping me if anything is unclear
> 
> DATACAP REQUEST
> 
> 1. In which region(s) do you intend to use the DataCap?
Austrilia or some countries where I can find miners.
> 2. How did you hear about the FIL+ program? Do you have a good understanding of the network and/or are involved in the web3.0 community?
When my friend introduced FIL+ program to me, I was interested in it. I'd love to take part in the program.
> 3. What is your registered business name & address?
Cakes in a Jar
43 Maxworthy Street Australia，Kambah，ACT 2906
> 4. Provide a description of your business, the industry you work in and what you do.
Cakes in a Jar creates gorgeous little treats. Imagine cake layered with chocolate, caramel, buttercream and other goodies - and then imagine it in the perfect single size ready to take with you anywhere! And we can cater for birthdays, christenings and wedding bonbonnieries.
> 5. What type/ category of data is being stored? (E.g Public data - back-up files, private encrypted files etc)
Pictures and videos of products and menus.
> 6. How much data will you onboard each week?
3TiB.
> 7. For how long do you intend to store your data with Filecoin?
I intend to store data for 10 years.
> 8. Have you previously received DataCap? If so, please link to any previous requests/ github issues.
No.
> 9. How frequently do you intend to retrieve data stored on Filecoin e.g. monthly, a couple times a year, infrequently.
Once half a year.
>    MINER DETAILS
> 10. How many miners do you plan on using to distribute the data, providing their ID's?
5 miners or more.
> 11. Are any of those miners controlled by yourself / your organization and if so, what is the percentage?
No.
> 12. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?
Yes.

**Comment by MegTei** [comment]
HI @CakesinaJar your request is approved, let me know if you need any support sourcing Storage Providers
