### ISSUE TITLE
Client Allocation Request for: Samdata Trade

### ISSUE THREAD

**Issue by Samdatatrade1** [filecoin-project/filecoin-plus-client-onboarding#1807]
---

# Client Allocation Questions 

## Core Information
- Name: Samdata Trade
- Website / Social Media: www.samdata.trade
- Region: Asia excl. Greater China
- DataCap Requested:8TiB
- Addresses to be Notarized: f1scsmm3mzvdty3noh7gvizzwxc7hnv67zddjf3yq
- Notary Requested: rayshitou

@Samdatatrade1 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by rayshitou** [comment]
@Samdatatrade1 Thanks for your application! We do not have enough DataCap as you needed. If you don't mind, please answer the following questions to let me know you and your company.
1.What's your name and your position in your company?What's your company's business?
2.Could you show me your company's business license? And please show me your company searching consequence in the local business license searching website.
3.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency? Could you please show me your cloud usage evidence?

**Comment by rayshitou** [comment]
Please send your license to this [address](dlleig@gmail.com). Thanks!
And:
1.What kind of data do you want to store and how much?
2.Could you please send me some demos of your data?
3.Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner's terms of service?

**Comment by Samdatatrade1** [comment]
1.Data stored on Filecoin is mainly from Quotation data, such as market reference data, options data, index data, fund data, futures data, bond data.
Now we need at least 20 TiB as the first step.
2.
[AMPUSDT_daily.csv](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/8869795/AMPUSDT_daily.csv)
3.Yes, I do.

**Comment by Samdatatrade1** [comment]
> @rayshitou
> 
> 1. I'm Dennis.
>    Matrix mainly takes quantitative investment transaction  as the core , and has the quantitative investment management system with asset portfolio management and other functions, creating a set of full-stack quantitative trading solutions for professional quantitative institutions and quants.
> 
> ![5](https://user-images.githubusercontent.com/105560098/172357297-9fdb6d09-ebe4-454d-b255-5c163ea44cb6.png) Company's license will be emailed you. 3. In the past, we don't use any cloud before.

Business license was sent to you.

**Comment by rayshitou** [comment]
Thanks! 
And:
1.How many miners do you want to store your data to? How much data for each miner?
2.What method/tool will you use to insperct miners? Which aspect of miners will you inspect?
3.Will you record your allocation decision in public? Which platform will you use?
4.Have you ever allocated before? If yes, how did you do when you were questioned? Any links?

**Comment by Samdatatrade1** [comment]
1. 3-4 miners. No more than 30% data to each miners.
2. Github is the proper tool. I'll choose miners with good reputation.
3. Yes. Github will be used for recording.
4. No.

**Comment by rayshitou** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtf572vn67uayhnseoyt63fbdvtf36diw4phx26zk4jrsikx42fe 
#### Address 
> f1scsmm3mzvdty3noh7gvizzwxc7hnv67zddjf3yq
#### Datacap Allocated
> 8.00TiB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtf572vn67uayhnseoyt63fbdvtf36diw4phx26zk4jrsikx42fe
