### ISSUE TITLE
Client Allocation Request for: Unicom-for new round application

### ISSUE THREAD

**Issue by kallu12** [filecoin-project/filecoin-plus-client-onboarding#1808]
---

# Client Allocation Questions 

## Core Information
- Name: Unicom-for new round application
- Website / Social Media: https://iservice.10010.com/
- Region: Greater China
- DataCap Requested: 50TiB
- Addresses to be Notarized: f1kvffnugu5j2fjjuispqr2y7bzmmtrvj6hk32xoq
- Notary Requested: Fenbushi-Filecoin

Please make sure to check out the guidelines and criteria to accept Datacap request for [Fenbushi Capital](https://github.com/filecoin-project/filecoin-plus-client-onboarding/tree/main/Fenbushi%20Capital)

@kallu12 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by kallu12** [comment]
@Fenbushi-Filecoin Hello notary, here is the link of last application. https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1395
This is the allocation of datacap. https://filplus.d.interplanetary.one/clients?filter=f1kftqp5kdhd4bc3b6vo6o675vkn2elbmkfzsjkli
![image](https://user-images.githubusercontent.com/105602345/171079430-e393996d-ed49-475b-b8c0-727f89615b70.png)
![image](https://user-images.githubusercontent.com/105602345/171079481-ab0bc5b0-6f00-403a-9ab1-9499419f706d.png)

Hope you can give us a new round datacap for storage. Thanks again!

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedcvqymv5nbwlt5d2i7gijlo7pmaxhdpib7la23ossh7qeikveop4 
#### Address 
> f1kvffnugu5j2fjjuispqr2y7bzmmtrvj6hk32xoq
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yqydpmqb5en262jpottko2kd65msajax7fi4rmq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedcvqymv5nbwlt5d2i7gijlo7pmaxhdpib7la23ossh7qeikveop4
