### ISSUE TITLE
Client Allocation Request for: Phoenix

### ISSUE THREAD

**Issue by lucas556** [filecoin-project/filecoin-plus-client-onboarding#183]
# Client Allocation Questions

**Comment by ozhtdong** [comment]
Hi. @lucas556 Thanks for your application!

Your data demo is very attractive and useful.
But I still want to learn about your company name and company official website.

**Comment by lucas556** [comment]
@ozhtdong  thank you for your reply. We are an EOS ADD node from the EOS community(website: www.eosadd.com ). 

We have been working hard to build distributed storage based on blockchain.

When filecoin was released, we found that filecoin is very suitable for the storage of blockchain data that add has been working hard to promote.

In the future, we will continue to import customer (corporate and personal) data storage into filecoin.

我们一直努力建设基于区块链的分布式存储.

当filecoin发布,我们发现filecoin很适合add一直以来努力推动的基于区块链数据的存储.

未来,我们会把客户(企业和个人)数据存储持续导入filecoin.

**Comment by Addtoken-ops** [comment]
> @ozhtdong thank you for your reply. We are an EOS ADD node from the EOS community(website: [www.eosadd.com](http://www.eosadd.com) ).
> 
> We have been working hard to build distributed storage based on blockchain.
> 
> When filecoin was released, we found that filecoin is very suitable for the storage of blockchain data that add has been working hard to promote.
> 
> In the future, we will continue to import customer (corporate and personal) data storage into filecoin.
> 
> 我们一直努力建设基于区块链的分布式存储.
> 
> 当filecoin发布,我们发现filecoin很适合add一直以来努力推动的基于区块链数据的存储.
> 
> 未来,我们会把客户(企业和个人)数据存储持续导入filecoin.

From the ADD official, our philosophy has always been to build distributed storage based on blockchain.

**Comment by lucas556** [comment]
@ozhtdong can you approve me?

**Comment by ozhtdong** [comment]
Hi. @lucas556 Sorry for the late reply.
So from my understanding, you are an individual, the community  member of EOS. Is that right? I am quite interested in your project and also hope EOS can cooperate with Filecoin.

**Comment by lucas556** [comment]
@ozhtdong Yes, I am a member of the eos community.I am also the technical leader of the EOS ADD project.The eos community also very much hopes to cooperate with filecoin.

**Comment by lucas556** [comment]
> @ozhtdong Yes, I am a member of the eos community.I am also the technical leader of the EOS ADD project.The eos community also very much hopes to cooperate with filecoin.

我是来自EOS社区的一员,同时也是EOS ADD的技术负责人,我相信,EOS社区非常希望能和filecoin项目以及IPFS进行合作.

**Comment by ozhtdong** [comment]
Hi. 
I also want to know more about your allocation strategy.
1.How many miners do you want to store your data to? How much data for each miner? 
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to insperct miners? Which aspect of miners will you inspect? 
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by Addtoken-ops** [comment]
@ozhtdong ,thank you for your reply.
> 1.How many miners do you want to store your data to? How much data for each miner? 

For each file, I will select 2-3 miners from eligible miners for data storage.Each miner has the same amount of data.
每一份文件,我会选择2-3个矿工进行冗余存储.每个矿工的数据量相同.

> 2. Will you record your allocation decision in public? Which platform will you use?

The distribution record (CID; document size/name; miner, etc.) is disclosed here: https://github.com/lucas556/Filecoin_Datacap and here.
分配记录会在这里和https://github.com/lucas556/Filecoin_Datacap页面公开.

> 3. What method/tool will you use to insperct miners? Which aspect of miners will you inspect?
I will choose based on region; reputation and stored power.And it requires that miners can use offline storage.
我会根据地区;声誉和存储量选择合适的矿工.并且矿工可以使用离线存储.

> 4. Have you ever allocated before? If yes, how did you do when you were questioned? 
Because data sorting is very complicated, we have not done any distribution yet.
因为数据整理非常复杂,我们还没有进行过分配.

**Comment by lucas556** [comment]
@ozhtdong ,thank you for your reply.
> 1.How many miners do you want to store your data to? How much data for each miner? 

For each file, I will select 2-3 miners from eligible miners for data storage.Each miner has the same amount of data.
每一份文件,我会选择2-3个矿工进行冗余存储.每个矿工的数据量相同.

> 2. Will you record your allocation decision in public? Which platform will you use?

The distribution record (CID; document size/name; miner, etc.) is disclosed here: https://github.com/lucas556/Filecoin_Datacap and here.
分配记录会在这里和https://github.com/lucas556/Filecoin_Datacap页面公开.

> 3. What method/tool will you use to insperct miners? Which aspect of miners will you inspect?

I will choose based on region; reputation and stored power.And it requires that miners can use offline storage.
我会根据地区;声誉和存储量选择合适的矿工.并且矿工可以使用离线存储.

> 4. Have you ever allocated before? If yes, how did you do when you were questioned? 

Because data sorting is very complicated, we have not done any distribution yet.
因为数据整理非常复杂,我们还没有进行过分配.

**Comment by ozhtdong** [comment]
Thanks for your detailed answer! 

I would like to know have you ever used cloud? Which platform do you use? What's your usage volume and frequency? 

I also want to get some evidence about your usage volume and your relationship with EOS.

**Comment by lucas556** [comment]
@ozhtdong We use Tencent Cloud; Alibaba Cloud and Amazon S3 storage; because the network fee is too high, our total storage limit is below 100Tib, and the data that exceeds 100Tib can only be deleted.
We believe that IPFS and Filecoin can reduce our costs and are more conducive to the storage and development of our data.
我们使用腾讯云;阿里云和亚马逊S3存储;因为网络费用太高,我们的限制存储总量在100Tib以下,超过的100Tib的数据只有删除.
我们相信在IPFS和Filecoin上可以降低我们的成本,更加有利于我们数据的存储和发展.

Regarding the usage of filecoin, our current data volume is based on 100 Tib, and is continuing to develop, according to past experience; maintaining a monthly growth of 8 Tib-10 Tib.
对于filecoin的使用量,我们目前的数据量在100Tib的基础,并且在持续发展,按照以往的经验;每月保持在8Tib-10Tib的增长.
Because books cannot be stored for a long time, we need to organize each book into electronic data, and continue to store it.
因为书籍不能长期保存,我们需要对每份书籍进行整理形成电子数据,并持续保存下去.

Regarding EOS, I cannot represent anyone. Our team participates in the launch of the mainnet and the construction of some communities; our node EOS ADD is the first token issued by the EOS mainnet.
关于EOS，我并不能代表任何人，我们团队参与主网启动和部分社区的建设;我们的节点EOS ADD是EOS主网第一个发行的Token.

**Comment by ozhtdong** [comment]
Could you please show me some social media link of you?

**Comment by lucas556** [comment]
My Social Media:
```
wechat:18515015560
slack:lucas556
github:https://github.com/lucas556
```

**Comment by lucas556** [comment]
hello,@ozhtdong,Is there any way to deal with it quickly?

**Comment by ozhtdong** [comment]
Hi. We are under discussion whether we approve individual's request since we don't have something like business license.

**Comment by lucas556** [comment]
> Hi. We are under discussion whether we approve individual's request since we don't have something like business license.

@ozhtdong We have a business license, Misunderstood

**Comment by lucas556** [comment]
Here is our business license, I will delete it after you check it。

![image](https://user-images.githubusercontent.com/34140831/110898118-9a4c5380-8339-11eb-823d-e5ea528bac0f.jpeg)

**Comment by lucas556** [comment]
@ozhtdong  Local business license search results
[https://github.com/lucas556/lotus_auto_sh/blob/master/1615697146078.jpg?raw=true](url)

**Comment by lucas556** [comment]
@ozhtdong Can i do it now?
