### ISSUE TITLE
Client Allocation Request for: Xinshu

### ISSUE THREAD

**Issue by Xinshu01** [filecoin-project/filecoin-plus-client-onboarding#1853]
---

# Client Allocation Questions 

## Core Information
- Name: Xinshu
- Website / Social Media: http://iaphoto.cn/
- Region: Greater China
- DataCap Requested: 20TiB
- Addresses to be Notarized: f1iar2mv5zz5il5tqlizxvbodwla2xpdvxb5ozlmi
- Notary Requested: swatchliu

@Bonnie556 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.)
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?

Would you like to submit more company information on [www.bytebase.cn](http://www.bytebase.cn/)?

Would you like to accept our face-to-face visit?

**Comment by Xinshu01** [comment]
@swatchliu 
Yes.

50+ employees.

Shanghai Xinshu Information Technology Co., Ltd. was founded in March 2018. The company is committed to becoming a leading provider of image management solutions for the mobile Internet. The company's mission is to promote people to develop the habit of video recording and pick up the passing years. The brand of Shishi Photo Album is named after it. In May 2019, the company launched the Shishi Photo Album mobile app, officially entering the Internet industry. Shanghai Xinshu will promote Shishi photo albums into the daily life of every ordinary person, and let beautiful images record everyone's life.

Wechat:拾时相册

We need 20TiB for storage.

Yes, we used to apply for datacap in the past and I got more than 50TiB. Now we've used up all datacap we got.

Yes, I can provide all information you need.

Sure, I'd like to have a visit with you. Welcome to our company in Shanghai or we can choose some places for meeting.

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecsqbm3udzy3a6pfoq7hl42z2jkgqxbmapwnlrdg5ukbpysh77y7i 
#### Address 
> f1iar2mv5zz5il5tqlizxvbodwla2xpdvxb5ozlmi
#### Datacap Allocated
> 20.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecsqbm3udzy3a6pfoq7hl42z2jkgqxbmapwnlrdg5ukbpysh77y7i
