### ISSUE TITLE
Client Allocation Request for: DeWei Art

### ISSUE THREAD

**Issue by Danny103** [filecoin-project/filecoin-plus-client-onboarding#1888]
---

# Client Allocation Questions 

## Core Information
- Name: 德谓文化 DeWei Art
- Website / Social Media: http://deweiart.com
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f165cfyx6bwlkfzcius4qmvfecq3rfoj4sao7zgai
- Notary Requested: swatchliu

@Danny103 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.)
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?

Would you like to submit more company information on [www.bytebase.cn](http://www.bytebase.cn/)?

Would you like to accept our face-to-face visit?

**Comment by Danny103** [comment]
Thank you for you questions.
DeWei Art was founded in 2019 and located in Shanghai, China. We have over 40 employees, focusing in providing a platform for artists to have creative works. Over 60 artists are cooperating with us, creating masterpieces like traditional Chinese painting, modern arts and NFT. I'm glad to share our WeChat Official account, "德谓文化" with you.
We estimate there is 2.4TB of data to backup, and one copy will make our data safer. So 4.8TB in total.
We haven't reach any other notary yet and no reliable DataCap left.
Sure we'd like to share more information with and looking forward to meeting face to face.

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqoaq57iwft5zvn7hpf4wf5avbbrba3ssnxnk2sm3juaej4wmilq 
#### Address 
> f165cfyx6bwlkfzcius4qmvfecq3rfoj4sao7zgai
#### Datacap Allocated
> 5.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqoaq57iwft5zvn7hpf4wf5avbbrba3ssnxnk2sm3juaej4wmilq
