### ISSUE TITLE
Client Allocation Request for: ratohe

### ISSUE THREAD

**Issue by ratohe** [filecoin-project/filecoin-plus-client-onboarding#1889]
---

# Client Allocation Questions 

## Core Information
- Name: ratohe
- Website / Social Media: 
- Region: Europe
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3stzriiqe6hxoig363uhi6jf77o2a4s4lodpf6oguxvt52jzpu6dcmsun6n4ithh2r7mml6vou2haaig6sipa
- Notary Requested: cryptowhizzard

@ratohe Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by cryptowhizzard** [comment]
Hi!

I could not sign this one ( It did not pop up on the dashboard ). I therefore did a assignment for 10 TB with a private request that went through.

@galen-mcandrew @dkkapur
