### ISSUE TITLE
Client Allocation Request for: 上海跃伽信息科技有限公司

### ISSUE THREAD

**Issue by cloudzzz3** [filecoin-project/filecoin-plus-client-onboarding#189]
---

# Client Allocation Questions 

## Core Information
- Name: 上海跃伽信息科技有限公司
- Website / Social Media: http://www.hopsum.com/
- Region: Greater China
- DataCap Requested: 2TiB
- Addresses to be Notarized: f15jlo5iesrvhcvm2jphl3uygsgji6gxcnnfpaqiq
- Notary Requested: ozhtdong

**Comment by ozhtdong** [comment]
Hi. @cloudzzz3  Thanks for application!

I want to know more basic information of you and your company. Please answer following question:

What's your name? What's your position?
What's your company's business?
Cloud you show me your company's business license?

**Comment by cloudzzz3** [comment]
Hi,ozhtdong 

1.What's your name? What's your position?
My name is 魏爱敏,My position is technical director.

2.What's your company's business?
Our company is to provide technical services for e-commerce businesses, through the independent research and development of the integrated system to achieve WeChat small program + Baidu small program + Alipay small program + Douyin small program + Toutiao small program +QQ small program +H5+PC+ full-end coverage.

3.Cloud you show me your company's business license?
<img width="343" alt="图片 1" src="https://user-images.githubusercontent.com/79350483/108793283-26cae800-75be-11eb-91e6-84b50dad29e6.png">

**Comment by cloudzzz3** [comment]
1.What's your name? What's your position?
My name is 魏爱敏,My position is technical director.

2.What's your company's business?
Our company is to provide technical services for e-commerce businesses, through the independent research and development of the integrated system to achieve WeChat small program + Baidu small program + Alipay small program + Douyin small program + Toutiao small program +QQ small program +H5+PC+ full-end coverage.

3.Cloud you show me your company's business license?
I will send you the business license through the E-mail.

**Comment by ozhtdong** [comment]
Thanks for your furhter information! @cloudzzz3 

I have further more questions about data and storing.
1.What kind of data do you want to store and how much?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?
3.Could you please send me some demos of your data?
4. Could you please show me your cloud usage evidence?

**Comment by cloudzzz3** [comment]
Hi,ozhtdong

1.What kind of data do you want to store and how much?
E-commerce product information(Video ads, posters, product descriptions),about 5TB.

2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?
Yes,We usually use Ali Cloud,We need to back up these data ,about 5TB, Once a year.

3.Could you please send me some demos of your data?
OK, I will send you  the data via email.

4. Could you please show me your cloud usage evidence?
None

**Comment by ozhtdong** [comment]
Hi. 

I also want to know more about your allocation strategy.

1.How many miners do you want to store your data to? How much data for each miner? 
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to insperct miners? Which aspect of miners will you inspect? 
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by cloudzzz3** [comment]
Hi,ozhtdong

1.How many miners do you want to store your data to? How much data for each miner? 
We want to store our data to 3 miners.  We will not store data on one miner above 70%.

2. Will you record your allocation decision in public? Which platform will you use?
Yes. I will record our allocation decision in public, in Github.

3. What method/tool will you use to insperct miners? Which aspect of miners will you inspect? 
 I will find the miners who are active in the community.

4. Have you ever allocated before? If yes, how did you do when you were questioned? 
No.

Thanks.

**Comment by ozhtdong** [comment]
Hi. 
Thanks for your information.
The last step, please show me your company searching consequence in the local business license searching website.

**Comment by storagezx** [comment]
Hi,ozhtdong

Here is the  searching consequence:

http://www.gsxt.gov.cn/%7B7A59AF0112780ED3E14F680230A48C9F318D0F3D57EB7FDD2B4152FC4039E6486FD347E51379FB26EAF924E86A4DCFA5301E8FB14490F2E430A19781558F92C5BFF9BFF9BFE892D4A8FFB9FFB9FFB9C5B9FF85C88ED99F8EC88ED93472803810697083B1250D9ABDAE9C1B611B4D37F476AB67E5597143C4BEF8BEF8BEF8-1614650117004%7D

Thanks.

**Comment by cloudzzz3** [comment]
Hi,ozhtdong

Here is the  searching consequence:

http://www.gsxt.gov.cn/%7B7A59AF0112780ED3E14F680230A48C9F318D0F3D57EB7FDD2B4152FC4039E6486FD347E51379FB26EAF924E86A4DCFA5301E8FB14490F2E430A19781558F92C5BFF9BFF9BFE892D4A8FFB9FFB9FFB9C5B9FF85C88ED99F8EC88ED93472803810697083B1250D9ABDAE9C1B611B4D37F476AB67E5597143C4BEF8BEF8BEF8-1614650117004%7D

Thanks.

**Comment by ozhtdong** [comment]
That's nice.

[1475 allocation table_跃伽.xlsx](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/6065969/1475.allocation.table_.xlsx)

You can see your score here. Since your company just need 5 TiB for one year. I would like to give you 2 TiB first. And you can apply for more once you finish the storage. Please record the deal here after finishing.

**Comment by cloudzzz3** [comment]
Okay! I really appreciate it.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb5j7d5t5pt7wcgexfjcm4o3i2wsmjjmvfi5tleflymfhi2ngzx3s 
#### Address 
> f15jlo5iesrvhcvm2jphl3uygsgji6gxcnnfpaqiq
#### Datacap Allocated
> 2TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb5j7d5t5pt7wcgexfjcm4o3i2wsmjjmvfi5tleflymfhi2ngzx3s
