### ISSUE TITLE
Client Allocation Request for: Wenkeer

### ISSUE THREAD

**Issue by notpj25** [filecoin-project/filecoin-plus-client-onboarding#1891]
---

# Client Allocation Questions 

## Core Information
- Name: Wenkeer
- Website / Social Media: https://www.mart.global/
- Region: Greater China
- DataCap Requested: 20TiB
- Addresses to be Notarized: f13npbrhv4jryhgirvgcx2fvdiyvqvzsryeenfvna
- Notary Requested: swatchliu

@notpj25 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.)
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?

Would you like to submit more company information on [www.bytebase.cn](http://www.bytebase.cn/)?

Would you like to accept our face-to-face visit?

**Comment by notpj25** [comment]
Thanks for your request.
Duration of establishment:
Wenkeer platform was established in Shanghai Free Trade Zone on Apri l8th 2021.

Number of employees:
We build a technical team 7 members.

Business scope and products or services:
Our company's main business is digital trading platform based on blockchain underlying technology+Web3.0 community .It involves art, meta-universe, media, entertainment. Our cooperative clients include: International Youth Art Research Center, Meta-Universe of Solomon Islands, Himalaya Art Museum, etc.

Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.):
You can downloaded Wenkeer app on PC and mobile,
WeChat ID:gh_eed18270a8ea

Data size to be stored:
We have more than 50TiB of storage on our platform which can support the application.

Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?
We haven't contacted any other notary yet, and  no reliable DataCap left.

Would you like to submit more company information on www.bytebase.cn?
I’m very glad to share more information on the web side.

Would you like to accept our face-to-face visit?
I’m looking forward to meeting you.

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedyplukbe4sqejsqr3id7iidofkq7gbcvxa3ypdanr3jtnltv7oa4 
#### Address 
> f13npbrhv4jryhgirvgcx2fvdiyvqvzsryeenfvna
#### Datacap Allocated
> 20.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedyplukbe4sqejsqr3id7iidofkq7gbcvxa3ypdanr3jtnltv7oa4
