### ISSUE TITLE
Client Allocation Request for: My Offer

### ISSUE THREAD

**Issue by Sandy9032** [filecoin-project/filecoin-plus-client-onboarding#1895]
---

# Client Allocation Questions 

## Core Information
- Name: My Offer
- Website / Social Media: www.myoffer.com
- Region: Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f17m55qnozf7vatndflypm3mk5ph3hymbxvyjcomi
- Notary Requested: swatchliu

@Sandy9032 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.)
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?

Would you like to submit more company information on [www.bytebase.cn](http://www.bytebase.cn/)?

Would you like to accept our face-to-face visit?

**Comment by Sandy9032** [comment]
Much appreciated for your quick response. I’m very glad to share more information with you. 
Our company was established in 2011, Shanghai,China. More than 60 employees are working for us. We focus in collecting data with cooperative schools and campus to boost our AI system and provide better service for students to meet their own requirements. 
Currently we don’t have social media accounts other than official website. 
We estimate the total size of our data is 4.7TB, so we’d to have a 5TB available space. It’s our first time to cooperate with Filecoin, so we don’t have any reliable DataCap left and haven’t made any contact with other notary. 
Sure we are very pleased to share more information with Bytebase, and since we locate in Shanghai, it’s convenient for us to have a face to face meeting.

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedptay6i42xwksbmfzcyvx4a6yv5ard3uxoicjkmvlura4u7frnzy 
#### Address 
> f17m55qnozf7vatndflypm3mk5ph3hymbxvyjcomi
#### Datacap Allocated
> 15.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedptay6i42xwksbmfzcyvx4a6yv5ard3uxoicjkmvlura4u7frnzy
