### ISSUE TITLE
Client Allocation Request for: Kims Korea Co., Ltd.

### ISSUE THREAD

**Issue by kimskorea1** [filecoin-project/filecoin-plus-client-onboarding#1896]
---

# Client Allocation Questions 

## Core Information
- Name: Kims Korea Co., Ltd.
- Website / Social Media: https://www.kims-korea.co.kr
- Region: Asia excl. Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1qddkgwnntv2uby6u4hy5keubofu6pnlpix66cgq
- Notary Requested: MasaakiNawatani

@kimskorea1 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MasaakiNawatani** [comment]
Hi @kimskorea1 thank you for reaching out. Unfortunately, as of this time, my team is experiencing issues in our ability to allocate datacap. We are still working with Filecoin Admins to have this issue fixed. Please reopen another request with another Notary for now. Thank you for your cooperation. I will close this ticket now.
