### ISSUE TITLE
Client Allocation Request for: Unicom

### ISSUE THREAD

**Issue by kallu12** [filecoin-project/filecoin-plus-client-onboarding#1898]
---

# Client Allocation Questions 

## Core Information
- Name: Unicom
- Website / Social Media: https://iservice.10010.com/
- Region: Greater China
- DataCap Requested: 50TiB
- Addresses to be Notarized: f1h24uonqrkruvcrgp5bhehenvejn3u5d24stmrsa
- Notary Requested: swatchliu

@kallu12 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.)
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?

Would you like to submit more company information on [www.bytebase.cn](http://www.bytebase.cn/)?

Would you like to accept our face-to-face visit?

**Comment by kallu12** [comment]
@swatchliu 
Yes.

Founded in May 30, 2001.
142 employees.
Douyin: Yibinliantong

Yes. It was accepted and no reliable DataCap left.
Yes. If you need more information, please email me.
Glad to have a visit and welcome to our company!
