### ISSUE TITLE
Client Allocation Request for: imageorbit

### ISSUE THREAD

**Issue by imageorbit** [filecoin-project/filecoin-plus-client-onboarding#19]
---

# Client Allocation Questions 

## Core Information
- Name: imageorbit
- Website / Social Media: https://github.com/imageorbit/
- DataCap Requested: 100TiB
- Addresses to be Notarized: f3q62254o2seww5a2dxliteqiwsl2lmexc6s2sjco42l5tbbci2kfjcs6jrpvmdq6vg4v7sbxn5guwpqnsvawa
- Notary Requested: Rin-huang

**Comment by 1am5UP3RasM4R10** [comment]
> # Client Allocation Questions
> ## Core Information
> * Name: imageorbit
> * Website / Social Media: https://github.com/imageorbit/
> * DataCap Requested: 100TiB
> * Addresses to be Notarized: f3q62254o2seww5a2dxliteqiwsl2lmexc6s2sjco42l5tbbci2kfjcs6jrpvmdq6vg4v7sbxn5guwpqnsvawa
> * Notary Requested: Rin-huang

May I have your email? We will contact you soon.
