### ISSUE TITLE
Client Allocation Request for: Blue Cefa Technology Co., Ltd

### ISSUE THREAD

**Issue by everysummer-code** [filecoin-project/filecoin-plus-client-onboarding#193]
---

# Client Allocation Questions 

## Core Information
- Name: Blue Cefa Technology Co., Ltd
- Website / Social Media: http://www.bluecefa.com/
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f12rbwbf5skcll64tsdh5uyg3w43lc5qqr252msza
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Closing this application per https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1612965452101400
