### ISSUE TITLE
Client Allocation Request for:Shanghai Aihui Health Technology Co., Ltd.

### ISSUE THREAD

**Issue by dalzellng** [filecoin-project/filecoin-plus-client-onboarding#1953]
---

# Client Allocation Questions 

## Core Information
- Name: Shanghai Aihui Health Technology Co., Ltd.
- Website / Social Media: http://www.aihuichina.com/
- Region: Greater China
- DataCap Requested: 100TiB
- Addresses to be Notarized: f1crhsa6czawwislz35lcwt3zke2cr2vy5rmdmt3y
- Notary Requested: XnMatrixSV

@dalzellng Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by XnMatrixSV** [comment]
Hi, @dalzellng 
Thanks for your request. Can you kindly add more information here.
1.Is your company located in North America？
2.Please give the following informations, duration of etablishment, number of employees, business scope, users volume, number of social media followers, data size to be stored, products or projects, and so on. Provide links to social media/news mentions.
3.The history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time, etc.
Type, size, and source of the data you will be store on Filecoin,e.g. public data or private data, etc. Is there any sensitive or illegal content?
4.How do you intend to store the data on Filecoin, e.g. redundancy, location/miner preferences, etc
5.Have you already apply for DataCap to another notary, and whether it is accepted or rejected. Is there any reliable DataCap left?
6.Would you like to post real transactions on Github?

**Comment by dalzellng** [comment]
> Hi, @dalzellng Thanks for your request. Can you kindly add more information here. 1.Is your company located in North America？ 2.Please give the following informations, duration of etablishment, number of employees, business scope, users volume, number of social media followers, data size to be stored, products or projects, and so on. Provide links to social media/news mentions. 3.The history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time, etc. Type, size, and source of the data you will be store on Filecoin,e.g. public data or private data, etc. Is there any sensitive or illegal content? 4.How do you intend to store the data on Filecoin, e.g. redundancy, location/miner preferences, etc 5.Have you already apply for DataCap to another notary, and whether it is accepted or rejected. Is there any reliable DataCap left? 6.Would you like to post real transactions on Github?


Hi, @XnMatrixSV 
Thanks for the feedback. We would love to provide more information.
1. Our company is not located in North America; instead, we are located in China.
2. We are a 6 years old company, started from 2016. We currently have around 220 employees due to the covid in China; we had over 300 people during peak time. We are an IoMT, Internet of Medical Things, based e-health company, and provided IoMT services to 250 hospitals. We planned to store most of our data over 1-year time frame to decentralized storage providers, but not yet decided how much to the Filecoin network. Our first patch would likely be the smart hospital data collected by our 60,000 medical devices inside of general wards of a hospitals. We don't directly interact much with individual customers, other than the wechat account AihuiHealth offers free wifi inside of hospitals to doctors and patients. There are media/news mentions about us from many channels, e.g. 
https://news.newseed.cn/p/1347426
https://e.huawei.com/cn/videolist/networking/f121e706628a4313a06ab3634fb1d704
https://www.sohu.com/a/468587054_133140
3. We don't have much working history on IPFS/Filecoin. Our IoMT data is fairly large, in Petabyte. We don't mind to store either public data or private data with Filecoin, as long as the storage is safe. We don't have any sensitive or illegal contents.
4. We don't have much preferences in locations/miners. Other than the P/L consideration, efficiency, simplicity, effectiveness are the key items we take into consideration.
5. This is the first time we do it; somehow the same request goes to multiple notaries. We probably have clicked the wrong button. Thank you for taking your time feedback our request; none of other notaries replied yet.
6. I can't think of why not. We could post real transactions on Github.

**Comment by XnMatrixSV** [comment]
Hi,@dalzellng sorry for my late answer.
Your organization is not in North America.
According to our allocation strategy(https://github.com/filecoin-project/notary-governance/issues/27), you wait for seven days.
I will do client due diligence for you quickly.

**Comment by XnMatrixSV** [comment]
Hi, @dalzellng 
According to our allocation strategy, we will grant you 3TiB.
Please ensure the following informations.
Scoring Result:
![image](https://user-images.githubusercontent.com/74889675/176812972-e3cdd51c-a09e-41b6-8207-0c57b3f7615e.png)
The Address：f1crhsa6czawwislz35lcwt3zke2cr2vy5rmdmt3y

**Comment by dalzellng** [comment]
> Hi, @dalzellng According to our allocation strategy, we will grant you 3TiB. Please ensure the following informations. Scoring Result: ![image](https://user-images.githubusercontent.com/74889675/176812972-e3cdd51c-a09e-41b6-8207-0c57b3f7615e.png) The Address：f1crhsa6czawwislz35lcwt3zke2cr2vy5rmdmt3y

Very logical scoring mechanism. Thanks! We'll try it out.

**Comment by XnMatrixSV** [comment]
Maybe you should wait for a period, because there are some approval problems should be solved by governance.

**Comment by dalzellng** [comment]
> Maybe you should wait for a period, because there are some approval problems should be solved by governance.

Thanks for the heads up. Let's wait for the governance.

**Comment by XnMatrixSV** [comment]
@dalzellng f1crhsa6czawwislz35lcwt3zke2cr2vy5rmdmt3y has 3.0 TiB of DataCap left.

**Comment by dalzellng** [comment]
> @dalzellng f1crhsa6czawwislz35lcwt3zke2cr2vy5rmdmt3y has 3.0 TiB of DataCap left.

We had the 3.0Tb used up. Sorry about taking quite some time to have it done. Could we have a bit more this time?
