### ISSUE TITLE
Client Allocation Request for: smagdali

### ISSUE THREAD

**Issue by smagdali** [filecoin-project/filecoin-plus-client-onboarding#1964]
---

# Client Allocation Questions 

## Core Information
- Name: smagdali
- Website / Social Media: smagdali
- Region: North America
- DataCap Requested: 1TiB
- Addresses to be Notarized: f1xa3txiberntsszfcdex2ztfibciuakyjlm4pj4y
- Notary Requested: dannyob

@smagdali Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
Lgtm. Please use your datacap responsibly!

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec5vqvpu2o7le2btcinivdkxice26xbcchacimhn6b7agwdfqaqga 
#### Address 
> f1xa3txiberntsszfcdex2ztfibciuakyjlm4pj4y
#### Datacap Allocated
> 1.00TiB
#### Signer Address
> f1k6wwevxvp466ybil7y2scqlhtnrz5atjkkyvm4a
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec5vqvpu2o7le2btcinivdkxice26xbcchacimhn6b7agwdfqaqga
