### ISSUE TITLE
Client Allocation Request for: LCD 4 U / Digital Thinking

### ISSUE THREAD

**Issue by bluenix** [filecoin-project/filecoin-plus-client-onboarding#197]
---

# Client Allocation Questions 

## Core Information
- Name: LCD 4 U / Digital Thinking
- Website / Social Media: www.digitalthinking.nl
- Region: Europe
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1ceg2pfxiud3346ak4efqmopddvmnxslwfm5vaey
- Notary Requested: s0nik42

**Comment by bluenix** [comment]
**Exposure :**
**Yourself , e.g. include links to social media / news mentions etc**
Website: www.digitalthinking.nl
Our business operates regionally in The Netherlands and our clients are B2B and Education.

**Ecosystem :**
 **Your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc** 

We do not have any history on IPFS / Filecoin. We periodically store the data our clients store with us off-premise for disaster recovery purposes.

**Data :**
**Type, size and source of the data you are looking to store on Filecoin, e.g. public data vs private data etc** 

The data we would like to store is private data and will not be publicly available.


**Your relationship with the data, especially with regard to copyright** 

This concerns data that our clients store with us for their daily work. It consists of documents and files they create, exchange etc. for their work or school.
 
**If the data is encrypted, are you authorized in case of an Audit to provide me or another notary the key to decrypt a deal of our choice ?**
We cannot allow access to the data to other parties. It is of the utmost importance that this data remains private. It will therefore be encrypted and only accessible by us and our respective clients.
 
**Storage :**
**How you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc** 
We will need one off-premise location to store our data for disaster recovery purposes. Our regular backups will be stored outside the filecoin network. We will therefore store a copy of the data with one miner we know and trust.
 
**Could you confirm if the data will be encrypted or not ?**
The data will be encrypted
 
**How much data are you considering storing to your own miner ?**
We do not have our own miner, since that would defeat the purpose of storing data for disaster recovery.

**Please describe the nature of the relationship you have with the miners you are going to store data to. Especially if you have any interests ?**
We personally know and trust the miner we will store the data with. The miner told us that if we applied for verified data, the miner will store our data for free. We are given to understand that verified data also acts favourably to the miner currently starting up in the Filecoin network. The other interest we have is that we know for sure we can trust this miner and that our data will be safe.

**Have you already ask Datacap to another notary that have been accepted or rejected.**
No, we have not asked for a Datacap before. Filecoin is new to us and we have been introduced to Filecoin by the miner we will store our data with.

**Finally, will you agree to share here all the CIDs related to the datacap ?**
Yes

**Comment by s0nik42** [comment]
Hi @bluenix, 

Thank you for your detailled message.

Applying to Fil+  implies providing access for audit purpose; we even recommend you to back it in your contract with your customer.  Without this autorization, I won't be able to grant you any Fil+ datacap.    

Regards,

Julien

**Comment by bluenix** [comment]
Hi @s0nik42 ,

Thank you for your reply.

I was under the impression that you are looking to motivate companies to store their data on Filecoin instead of the cloud suppliers. I’m not sure why you would need to access our data? Amazon would never ask for that. It is unreasonable to expect a company to store its data on Filecoin if that means allowing an unknown third party access to that data. How can we ask our customers to agree with giving auditing-permission to a party that is unknown to even us?

We would be happy to draft an official declaration about the type of data we would store, if that would help? Otherwise, can you point me to the official documentation that states the terms for storing data with Filecoin Plus and the assurances / liability in place regarding audit-access?

Hope to hear from you. We love new technology and would be happy to get started on Filecoin!

**Comment by s0nik42** [comment]
Thank you for your message, let me explained. 

Clients can store data to the network encrypted or not. You can consume the filecoin service without providing access to your data by design. 

Fil+ is a program to which Filecoin clients can apply to.  When you apply to Fil+, you get the benefits of having your data more attractive and miner may give you a better price. The counter part of requesting a VERIFIED datacap, is to prove to the filecoin ecosystem, through a notary, the data you store are real and useful data. A filecoin notary will have to verify and confirm to the filecoin ecosystem the data you store is real data. The auditor will be a notary. 

Fil+ is a very young program, criteria and processes may changed. But what I asked you here is what we ask to all fil+ client.  
 
Hope it's answering your questions. 

Julien
