### ISSUE TITLE
Client Allocation Request for: 桂林市忆图云网络科技有限公司

### ISSUE THREAD

**Issue by litai686** [filecoin-project/filecoin-plus-client-onboarding#2009]
---

# Client Allocation Questions 

## Core Information
- Name: 桂林市忆图云网络科技有限公司
- Website / Social Media: https://www.etu1314.com/
- Region: Greater China
- DataCap Requested: 500TiB
- Addresses to be Notarized: f14lwf3q5ihmacnp4bd3ai3upd3kficremy26foxi
- Notary Requested: swatchliu

@litai686 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
In FIL+ channel we can't offer you 500TiB, you can try LDN for your request.
