### ISSUE TITLE
Client Allocation Request for: 成都星硕科技有限公司

### ISSUE THREAD

**Issue by zzxiasz** [filecoin-project/filecoin-plus-client-onboarding#201]
---

# Client Allocation Questions 

## Core Information
- Name: 成都星硕科技有限公司
- Website / Social Media: http://www.xingshuoyun.com/
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1oxsiozcbsjeypzlclhfxt7xgbi637izhqsw75qy
- Notary Requested: ozhtdong

**Comment by ozhtdong** [comment]
Thanks for your application. @zzxiasz I want to know more basic information of you and your company. Please answer following question:
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Cloud you show me your company's business license?

**Comment by zzxiasz** [comment]
Hello,I will handle the application of valid data.I hope our communication goes well.
Please check my answers:
1.I'm Jiang Jiang,you can call me Jiang.I graduated from Chengdu University of Electronic Science and Technology, and now I am the CEO of Chengdu Yingda Technology Co., Ltd.
2.We are an innovative technology company dedicated to the Internet medical imaging field.We independently develop PACS（Picture Archiving and Communication Systems）.This is our official website: _http://www.xingshuoyun.com/_ . Or you can learn more about us here: _https://www.qcc.com/firm/75c7d1059fd9d1e5f42339c4e5bf0e25.html_
3.Our company's business license:
![图片3](https://user-images.githubusercontent.com/79324384/109776482-93d52200-7c3d-11eb-99c6-cb0728379804.png)

**Comment by ozhtdong** [comment]
Thanks for your quick reply and detailed information.
I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?

**Comment by zzxiasz** [comment]
OK,I think I am one step closer to the success of my application,hh.
1.We have 20TB of medical record data and DICOM image data to store.And the amount of data is growing fast.(So I really need these datacap) I think I need to send the demo to you by email because this page cannot be displayed.
2.Yes,our company has used Ali Cloud, Qiniu Cloud, Huawei Cloud and Telecom Cloud.We will invest 500,000 rmb in cloud storage services every year.
Looking forward to your reply again.Is there any other information or data to refer to that can be presented all at once.

**Comment by ozhtdong** [comment]
Hi, I also want to know more about your allocation strategy.

1.How many miners do you want to store your data to? How much data for each miner? 
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect? 
4. Have you ever allocated before? If yes, how did you do when you were questioned? 

Also, please show me your company searching consequence in the local business license searching website.

**Comment by zzxiasz** [comment]
Hi,the attachment is our data demo,please check it.
















At 2021-03-04 13:28:27, "ozhtdong" <notifications@github.com> wrote:

Hi, I also want to know more about your allocation strategy.

1.How many miners do you want to store your data to? How much data for each miner? 
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect? 
4. Have you ever allocated before? If yes, how did you do when you were questioned? 

Also, please show me your company searching consequence in the local business license searching website.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

从网易163邮箱发来的超大附件
data demo.rar (94.67M, 2021年3月19日 13:31 到期)
下载

**Comment by ozhtdong** [comment]
Hi, I also want to know more about your allocation strategy.

1.How many miners do you want to store your data to? How much data for each miner? 
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect? 
4. Have you ever allocated before? If yes, how did you do when you were questioned? 

Also, please show me your company searching consequence in the local business license searching website.

**Comment by zzxiasz** [comment]
Wow,so many questions! I'm sorry it took me some time to prepare the answers.

1.If approved, I will divide the 5TB data capacity equally between two miners.
2.Yes,I will paste a screenshot of the assignment information on the GitHub conversation page.
3.I already know some of the miners.I will make my choice based on the miner's power and the blocks mined.
4.Never.
5.Company searching consequence:

![星硕](https://user-images.githubusercontent.com/79324384/109948190-0c5ae200-7d15-11eb-8ff1-27dd2dd9133f.png)

**Comment by ozhtdong** [comment]
![QQ图片20210305095742](https://user-images.githubusercontent.com/69976222/110056534-f9d6bc00-7d99-11eb-80aa-d9c8d0009b47.png)
Hi, you can find your score here.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedhgulsqcxenlprzcbgd27lfadstxokrm2cnivb3mwkhnadajt7so 
#### Address 
> f1oxsiozcbsjeypzlclhfxt7xgbi637izhqsw75qy
#### Datacap Allocated
> 5TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedhgulsqcxenlprzcbgd27lfadstxokrm2cnivb3mwkhnadajt7so
