### ISSUE TITLE
Client Allocation Request for: Friday Shopping

### ISSUE THREAD

**Issue by Aimee-Friday** [filecoin-project/filecoin-plus-client-onboarding#2019]
---

# Client Allocation Questions 

## Core Information
- Name: Friday Shopping
- Website / Social Media: https://shopping.friday.tw/
- Region: Greater China
- DataCap Requested: 20TiB
- Addresses to be Notarized: f1iach3ih3q5x5k4lxy6wlysmqm65vwegpxwm4oii
- Notary Requested: swatchliu

@Aimee-Friday Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.)
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?

Would you like to submit more company information on [www.bytebase.cn](http://www.bytebase.cn/)?

Would you like to accept our face-to-face visit?

**Comment by Aimee-Friday** [comment]
@swatchliu Hi, welcome to give me some response.

Yes. We are chinese company.

In 2017, it merged with GoHappy Shopping, a subsidiary of Far East E-commerce, to deepen the operation of the friday shopping brand, and integrate the advantages of the group-combined with the largest retail channel under the department store sales line, hoping to create the most complete retail channel system for O2O in Taiwan.

We have 100+ employees now.

Friday shopping starts from "let's shopping for a better life", and together with FarEasTone Telecom Group. We will use considerate and innovative services to make technology simpler, help people live in the present more conveniently and smartly, and become a good partner in people's digital life.

Facebook: https://www.facebook.com/fridayshopping

Now we have 19.57TiB data.

No other application.

Yes, we will. You can emile me or contact me in github.

It's my pleasure!

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaihm4ohhdzzy2z7dkk7ehcarosue5kxphuwibyav2yu4ge7ewbyy 
#### Address 
> f1iach3ih3q5x5k4lxy6wlysmqm65vwegpxwm4oii
#### Datacap Allocated
> 20.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaihm4ohhdzzy2z7dkk7ehcarosue5kxphuwibyav2yu4ge7ewbyy
