### ISSUE TITLE
Client Allocation Request for: United Information Technology Co., Ltd

### ISSUE THREAD

**Issue by uglyboy123** [filecoin-project/filecoin-plus-client-onboarding#202]
---

# Client Allocation Questions 

## Core Information
- Name: United Information Technology Co., Ltd
- Website / Social Media: http://www.uit.com.cn/
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f17chz2xuedput42kfhfs722f7q6lk7ue4ioi2zyi
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Closing this application per https://filecoinproject.slack.com/archives/C01DLAPKDGX/p1612965452101400
