### ISSUE TITLE
Client Allocation Request for: alteo

### ISSUE THREAD

**Issue by domms9911** [filecoin-project/filecoin-plus-client-onboarding#2020]
---

# Client Allocation Questions 

## Core Information
- Name: alteo
- Website / Social Media: 
- Region: Europe
- DataCap Requested: 20TiB
- Addresses to be Notarized: 
- Notary Requested: cryptowhizzard

@domms9911 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by cryptowhizzard** [comment]
Hello @domms9911 

Thank you for joining the Filecoin community. Before i grant you datacap, can you please tell us what it is meant for and how you are going to spend it?
