### ISSUE TITLE
Client Allocation Request for: 上海大智慧财汇数据科技有限公司

### ISSUE THREAD

**Issue by Tina5520** [filecoin-project/filecoin-plus-client-onboarding#203]
---

# Client Allocation Questions 

## Core Information
- Name: 上海大智慧财汇数据科技有限公司
- Website / Social Media: https://www.finchina.com/
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1qaajtfjd6azzoylf6ugrffef5ua7i6bzq4jfh5q
- Notary Requested: ozhtdong

**Comment by Tina5520** [comment]
@ozhtdong Sorry to bother, we are in a hurry since we have so much data to store. Also need to know if IPFS suitable for us.

**Comment by ozhtdong** [comment]
@Tina5520 Thanks for your application! 

Actually, I 've heard about your company.  

I want to know more basic information of you and your company. Please answer following question:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Cloud you show me your company's business license?

**Comment by Tina5520** [comment]
@ozhtdong 
Following is the answer:
**1.What's your name? What's your position?**
My name is Guo Chao, a test controler.

**2.What's your company's business? Do you have any other social media link?**
You can find it in our official website. FC Financial Big Data, FC Financial Database, Tailored Database, Solution.
Wiki in China: https://baike.baidu.com/item/%E4%B8%8A%E6%B5%B7%E5%A4%A7%E6%99%BA%E6%85%A7%E8%B4%A2%E6%B1%87%E6%95%B0%E6%8D%AE%E7%A7%91%E6%8A%80%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/19997253?fr=aladdin

**3.Cloud you show me your company's business license?**
It's quite secret for us. Can I delete it after you see it?

**Comment by Tina5520** [comment]
![eb0c6d61baa58d9237534f0489c92c0](https://user-images.githubusercontent.com/79354344/109140580-b37cce00-7797-11eb-8b73-cdc07424e8d2.jpg)
### Business license

**Comment by ozhtdong** [comment]
@Tina5520 Thanks for your quick reply and detailed information. I saw the business license and downloaded it for archive usage. I help you to delete it.

I have further more questions about data and storing.

1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency? Could you please show me your cloud usage evidence?

**Comment by Tina5520** [comment]
@ozhtdong Can you ask all questions in one time?

**1.What kind of data do you want to store and how much? Could you please send me some demos of your data?**
**What kind** - Market analysis, essential data analysis, news, also analysis tool
**how much** - If you can give me 1 PiB, it would be better.
**demo** - How to send it to you? So many pictures, text and other documentations.

**2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency? Could you please show me your cloud usage evidence?**
**ever used** - Of course.
 **Which platform** - Baidu cloud、 Tencent cloud、 Ali cloud ……
**usage volume and frequency** - For One hundred thousand yuan/ month. 
**usage evidence** - What do you mean by evidence? I think it is nonsense.

**Comment by Tina5520** [comment]
@ozhtdong Please go forward as soon as possible. Thanks.

**Comment by ozhtdong** [comment]
Hi. 

I also want to know more about your allocation strategy.

1.How many miners do you want to store your data to? How much data for each miner? 
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to insperct miners? Which aspect of miners will you inspect? 
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by Tina5520** [comment]
**1.How many miners do you want to store your data to? How much data for each miner?** 
For one miner.

**2. Will you record your allocation decision in public? Which platform will you use?**
Record in https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/203

**3. What method/tool will you use to insperct miners? Which aspect of miners will you inspect?** 
The miner who is 0 Fil for verified data. Just find its reputation.

**4. Have you ever allocated before? If yes, how did you do when you were questioned?** 
No.

**Comment by Tina5520** [comment]
![Uploading 1614580832(1).png…]()

**Comment by ozhtdong** [comment]
![1614582606(1)](https://user-images.githubusercontent.com/69976222/109463579-39528f00-7aa0-11eb-9596-b2f89a398a40.png)
You can find your score here.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceciqezv7ijf24ncawtlv7ulyqeegdssw3xrphmm2nsgxgvauljbl2 
#### Address 
> f1qaajtfjd6azzoylf6ugrffef5ua7i6bzq4jfh5q
#### Datacap Allocated
> 5TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceciqezv7ijf24ncawtlv7ulyqeegdssw3xrphmm2nsgxgvauljbl2
