### ISSUE TITLE
Client Allocation Request for: winland srl

### ISSUE THREAD

**Issue by futurixlab** [filecoin-project/filecoin-plus-client-onboarding#2046]
---

# Client Allocation Questions 

## Core Information
- Name: winland srl
- Website / Social Media: www.winland.it
- Region: Europe
- DataCap Requested: 2TiB
- Addresses to be Notarized: f1tcwgbb6eniizbwvizckiajzsr3xc52p4dupemby
- Notary Requested: s0nik42

@futurixlab Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaw6fq5alcpwxo4gtknwqc7cr4nvgven4fbxkvmo4f6avdjsgjggm 
#### Address 
> f1tcwgbb6eniizbwvizckiajzsr3xc52p4dupemby
#### Datacap Allocated
> 2.00TiB
#### Signer Address
> f1wxhnytjmklj2czezaqcfl7eb4nkgmaxysnegwii
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaw6fq5alcpwxo4gtknwqc7cr4nvgven4fbxkvmo4f6avdjsgjggm
