### ISSUE TITLE
Client Allocation Request for: 爱建信托

### ISSUE THREAD

**Issue by zzshao11** [filecoin-project/filecoin-plus-client-onboarding#205]
---

# Client Allocation Questions 

## Core Information
- Name: 爱建信托
- Website / Social Media: http://www.ajxt.com.cn/ajxt/
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1ru6n2lvnaawezj3qc24v6bfwtvwud2u4grqviby
- Notary Requested: ozhtdong

**Comment by ozhtdong** [comment]
Hi. @zzshao11 Thanks for your application!

I want to know more basic information of you and your company. Please answer following question:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Cloud you show me your company's business license?

**Comment by zzshao11** [comment]
@ozhtdong Sorry for the late reply. I am 张嵩, a technical manager of 爱建. Established in 1986, 爱建信托 is the first private financial institution in China. You can find more detailed information in our Baidu Baike: 
https://baike.baidu.com/item/%E4%B8%8A%E6%B5%B7%E7%88%B1%E5%BB%BA%E4%BF%A1%E6%89%98%E6%8A%95%E8%B5%84%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/10861672?fr=aladdin

Our company's business license:

![微信图片_20210302174625](https://user-images.githubusercontent.com/79312893/109629865-41353080-7b7f-11eb-9702-c8a848e96a82.jpg)

**Comment by ozhtdong** [comment]
Thanks for your detailed information.
I have further more questions about data and storing.

**1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?**

**Comment by KwrayPL** [comment]
Hello!
Sending a friendly ping to this issue since it hasnt had movement and closing out. Should you wish to continue please feel free to reopen.  Thanks and Best!
