### ISSUE TITLE
Client Allocation Request for: 南京物盟信息技术有限公司

### ISSUE THREAD

**Issue by jingyushishi** [filecoin-project/filecoin-plus-client-onboarding#206]
---

# Client Allocation Questions 

## Core Information
- Name: 南京物盟信息技术有限公司
- Website / Social Media: http://www.vomont.com/
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1sszhqbou3pya2xglly6shquajygdm665gqlef4q
- Notary Requested: ozhtdong

**Comment by ozhtdong** [comment]
Hi. @jingyushishi Thanks for your application. I want to know more basic information of you and your company. Please answer following question:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Cloud you show me your company's business license?

**Comment by jingyushishi** [comment]
Good afternoon!
You can call me Shaobo Liang.I currently serve as the legal person of Nanjing Wumeng Information Technology Co., Ltd.  :D
Our company mainly engaged in streaming media, video surveillance, security and multimedia.You can know more information of us in this web address:_http://company.rfidworld.com.cn/Rfidworld_Company_144760.html_
I have put my company's business license here:
![图片2](https://user-images.githubusercontent.com/79633771/109623934-a2a5d100-7b78-11eb-9d03-9ec26ae7eaea.png)

**Comment by ozhtdong** [comment]
Hi.

I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency? Could you please show me your cloud usage evidence?

**Comment by jingyushishi** [comment]
Good evening!
I need to store about 48 TiB of video streaming and picture data.  :D
I am not sure how to send the demo to you.Maybe I can send it to you by email.Please check it later.  :D
I've been using cloud storage for a long time.Our company has been using Ali Cloud to store data.We need to make a storage backup of our data once a week.Currently, about 50 terabytes of data are stored.And I will send the cloud usage evidence and demo to you by email.  :D

**Comment by ozhtdong** [comment]
Good evening. Thanks for your quick reply and detailed information. @jingyushishi :D

I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?

**Comment by jingyushishi** [comment]
Good morning!  :D
1.I will store our data to 3 or 4 miners.I will divide my data equally among the miners.  :D
2.Of course, I will record it on this page.  :D
3.I'll inspect miners based on storage power data and industry reputation.  :D
4.No,I never did that.  :D

**Comment by ozhtdong** [comment]
Hi. 
Thanks for your information.
The last step, please show me your company searching consequence in the local business license searching website. :D

**Comment by jingyushishi** [comment]
OK,I took a screenshot of our company information in a famous Chinese enterprise inquiry website.I hope it will be usefull.

![物盟](https://user-images.githubusercontent.com/79633771/109942376-1974d280-7d0f-11eb-86cb-9eeaf380a19f.png)

**Comment by ozhtdong** [comment]
Your company reputation is good. If needed, you can ask for more DataCap.
![1614909990(1)](https://user-images.githubusercontent.com/69976222/110057119-f7c12d00-7d9a-11eb-8d76-db37c1f6df34.png)

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvdnki7fw2shw4dydt7oyqljrf5kse7cpyz26sl3imjdzhbvfuho 
#### Address 
> f1sszhqbou3pya2xglly6shquajygdm665gqlef4q
#### Datacap Allocated
> 5TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvdnki7fw2shw4dydt7oyqljrf5kse7cpyz26sl3imjdzhbvfuho
