### ISSUE TITLE
Client Allocation Request for: PiKNiK

### ISSUE THREAD

**Issue by jessie8o8** [filecoin-project/filecoin-plus-client-onboarding#2080]
---

# Client Allocation Questions 

## Core Information
- Name: PiKNiK
- Website / Social Media: 
- Region: North America
- DataCap Requested: 1TiB
- Addresses to be Notarized: 1111
- Notary Requested: s0nik42

@jessie8o8 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
