### ISSUE TITLE
Client Allocation Request for: 桂林市忆图云网络科技有限公司

### ISSUE THREAD

**Issue by litai686** [filecoin-project/filecoin-plus-client-onboarding#2081]
---

# Client Allocation Questions 

## Core Information
- Name: 桂林市忆图云网络科技有限公司
- Website / Social Media: https://www.etu1314.com
- Region: Greater China Region
- DataCap Requested: 100TiB
- Addresses to be Notarized: f14lwf3q5ihmacnp4bd3ai3upd3kficremy26foxi
- Notary Requested: 1475Notary

@litai686 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by 1475Notary** [comment]
Hello @litai686, thanks for the request! 
Please answer the following questions giving as much detail as possible.

1. Please introduce yourself and the organization you represent, what is its name, nature, country of incorporation and date of establishment?
2. How many employees does the company currently have?
3. In which region do you plan to use DataCap? 
4. What kind of social media platforms do you have (Github, Twitter, Linkedin handle, Wechat, etc.)? How many followers do you have, please share me the link or screenshot.
5. How did you hear about the FIL+ project? Do you have a good understanding of web 3.0 or have/are you involved in the web 3.0 community? If you do, please give me a brief intoduction and share me your account.
6. What kind of data do you plan to store? Can you share any kind of sample data?
7. Please provide the business license of your company.
8. Are you willing to store data outside of Greater China?

**Comment by litai686** [comment]
1、Please introduce yourself and the organization you represent, what is its name, nature, country of incorporation and date of establishment?
 `I  am the technical director of the company, the company name is 桂林市忆图云网络科技有限公司,  Registered address in China, Established in 2014`

2、How many employees does the company currently have?
`The company currently has 20 employees`

3、In which region do you plan to use DataCap?
`China`

4、What kind of social media platforms do you have (Github, Twitter, Linkedin handle, Wechat, etc.)? How many followers do you have, please share me the link or screenshot.
` This our Wechat applet `
![image](https://user-images.githubusercontent.com/38679986/180770205-183b17d4-57c9-4df2-8bba-56f71a9d21c6.png)

<img width="410" alt="image" src="https://user-images.githubusercontent.com/38679986/180770825-ff835167-b678-48a7-a90e-94a641ad10da.png">

5、How did you hear about the FIL+ project? Do you have a good understanding of web 3.0 or have/are you involved in the web 3.0 community? If you do, please give me a brief introduction and share your account.
`Listen to a friend's introduction `

6、What kind of data do you plan to store? Can you share any kind of sample data?
`We are engaged in scenic spot photography, mainly tourists' photos.`
https://file.huikaoqin.com/searchImg/search?n=L0773-20220420211123-C029-2
https://file.huikaoqin.com/searchImg/search?n=B0887-20220516110822-C2-2
https://file.huikaoqin.com/searchImg/search?n=B0887-20220516111016-C3-1
https://file.huikaoqin.com/searchImg/search?n=B0691-20220619202901-A1-4

7、Please provide the business license of your company.
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/38679986/180771978-50734563-e3c2-4996-a909-07952fd08be4.png">

8、Are you willing to store data outside of Greater China?
`No`

**Comment by litai686** [comment]
@1475Notary  Sorry，I didn't notice the email. The above questions have been answered

**Comment by litai686** [comment]
@1475Notary  Hi，are you there?  When can it be approved？
