### ISSUE TITLE
Client Allocation Request for: qikanlogo.com

### ISSUE THREAD

**Issue by ericripi** [filecoin-project/filecoin-plus-client-onboarding#2100]
---

# Client Allocation Questions 

## Core Information
- Name: qikanlogo.com
- Website / Social Media: http://qikanlogo.com
- Region: Asia (excl. Greater China)
- DataCap Requested: 1TiB
- Addresses to be Notarized: f1ujyknzb77k5jwbmmfsqyjm5y62z6asbhnvpzr7y
- Notary Requested: swatchliu

@ericripi Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thank you for your request. But the categories and the 'Inquiry Trial' button on your website do not seem to be accessible properly.
