### ISSUE TITLE
Client Allocation Request for: DIDIBOYU

### ISSUE THREAD

**Issue by wianeigniengggoe** [filecoin-project/filecoin-plus-client-onboarding#2101]
---

# Client Allocation Questions 

## Core Information
- Name: DIDIBOYU
- Website / Social Media: www.didiboyu.com
- Region: Asia (excl. Greater China)
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1kbd5gfrl7rnnfg7wzylsh2tuwcbtlik3usz244i
- Notary Requested: TimGuo7

@wianeigniengggoe Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by wianeigniengggoe** [comment]
@TimGuo7 Hi would be great if you can take some time to check on this request. Thx!

**Comment by TimGuo7** [comment]
@wianeigniengggoe Thanks for asking, unfortunately I cannot approve any DataCap as my on-chain address pending approval.  Try to find someone who has access to do so, thanks.
