### ISSUE TITLE
Client Allocation Request for: Market NewsDesk

### ISSUE THREAD

**Issue by tokencan1** [filecoin-project/filecoin-plus-client-onboarding#2102]
---

# Client Allocation Questions 

## Core Information
- Name: Market NewsDesk
- Website / Social Media: https://www.marketnewsdesk.com/
- Region: Greater China Region
- DataCap Requested: 10TiB
- Addresses to be Notarized: f14huykewyaqqdw2qkhvpjfwcdr5gxoqjdy2giyxi
- Notary Requested: 1475Notary

@tokencan1 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by tokencan1** [comment]
@1475Notary Hi could you check on my request? Thx!

**Comment by 1475Notary** [comment]
Hello @tokencan1 thanks for the request!
Please answer the following questions giving as much detail as possible.

1. Please introduce yourself and the organization you represent, what is its name, nature, country of incorporation and date of establishment?
2. How many employees does the company currently have?
3. In which region do you plan to use DataCap?
4. What kind of social media platforms do you have (Github, Twitter, Linkedin handle, Wechat, etc.)? How many followers do you have, please share me the link or screenshot.
5. How did you hear about the FIL+ project? Do you have a good understanding of web 3.0 or have/are you involved in the web 3.0 community? If you do, please give me a brief introduction and share your account.
6. What kind of data do you plan to store? Can you share any kind of sample data?
7. Please provide the business license of your company.
8. Are you willing to store data outside of Greater China?

**Comment by tokencan1** [comment]
@1475Notary Hi Thanks for the reply. Please refer to below and let me know if you need more information.

1.Please introduce yourself and the organization you represent, what is its name, nature, country of incorporation and date of establishment?
Charlie Yu. Engineer. Established in March 2010 in Hong Kong, Market Newsdesk is one of the world’s leading providers of investment, advisory and risk management solutions. With a diverse audience and a broad reach, Market Newsdesk publishes on behalf of government, financial agencies, financial and commercial institutions, markets, and other official bodies.

2.How many employees does the company currently have?
51-200 employees.

3.In which region do you plan to use DataCap?
China.

4.What kind of social media platforms do you have (Github, Twitter, Linkedin handle, Wechat, etc.)? How many followers do you have, please share me the link or screenshot.
N/A.

5.How did you hear about the FIL+ project? Do you have a good understanding of web 3.0 or have/are you involved in the web 3.0 community? If you do, please give me a brief introduction and share your account.
With the “decentralized storage” war waging on over the years, Filecoin enables decentralized, trust-minimized, censorship-resistant data storage for long periods. Web 3.0 which ensures data privacy would play an important role as the world digitizes its working.

6.What kind of data do you plan to store? Can you share any kind of sample data?
Mainly pictures and texts of industry news and sharing. Will send sample data by email. 

7.Please provide the business license of your company.
Will be sent to you by email.

8.Are you willing to store data outside of Greater China?
Yes.

**Comment by 1475Notary** [comment]
Hi, please resend the mail to simon686@protonmail.com.
