### ISSUE TITLE
Client Allocation Request for: BLOCK GLOBAL

### ISSUE THREAD

**Issue by liyanhahahah** [filecoin-project/filecoin-plus-client-onboarding#2108]
---

# Client Allocation Questions 

## Core Information
- Name: BLOCK GLOBAL
- Website / Social Media: https://www.blockglobal.pro/
- Region: Greater China Region
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1joqydiliofrcmvktxzump6bnnnjt6ttxo3ovq3i
- Notary Requested: swatchliu

@liyanhahahah Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by liyanhahahah** [comment]
@swatchliu Hi Please let me know if there's anything you need. Many thanks!

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.),
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?
Would you like to submit more company information on www.bytebase.cn?
Would you like to accept our face-to-face visit?

**Comment by liyanhahahah** [comment]
@swatchliu Hi Thanks for the reply. Please refer to below and let me know if you need more information.

1、Is your company located in Greater China？
Yes. 

2、Duration of establishment
Founded in March 2018.

3、Number of employees
51-200.

4、Business scope and products or services
Block Global is committed to building the world's leading blockchain technology media group, including Block Tech in Chinese Mainland, Coinin in Korea, blocktimes in Taiwan, Beecast in Southeast Asia. These're all crypto media companies. Also, Block Global set up a token fund named Block Capital and a blockchain recruitment project named Huopin Online. Global and ecological layout is the key to BlockGlobal. With the mission of "syndicating transnational information, linking global resources, and empowering economic development", Block Global serves entrepreneurs and investors in the global blockchain field, and invests in more than ten blockchain upstream and downstream enterprises, basically achieving the ecological layout of the blockchain industry and the full layout of Asian blockchain media.


5、Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.)
https://www.linkedin.com/company/blockglobal

6、Data size to be stored,
We need 10TiB for storage.

7、Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?
This is our first time working with Filecoin.

8、Would you like to submit more company information on www.bytebase.cn?
Yes. 

9、Would you like to accept our face-to-face visit?
Absolutely.

**Comment by swatchliu** [comment]
@liyanhahahah Thanks for the quick reply. The linkedin link you provided does not work. And I tried to search for your company name directly, but oddly it shows that 'company not found'. Can you provide a screenshot of your company's linkedin?

**Comment by liyanhahahah** [comment]
@swatchliu Sorry our LinkedIn page is in maintenance. This is our Facebook link: https://www.facebook.com/BlockGlobal-775504152848901/

**Comment by liyanhahahah** [comment]
@swatchliu Hi we got any update here?
