### ISSUE TITLE
Client Allocation Request for: Sharif University of Technology

### ISSUE THREAD

**Issue by emf-developer** [filecoin-project/filecoin-plus-client-onboarding#2115]
---

# Client Allocation Questions 

## Core Information
- Name: Sharif University of Technology
- Website / Social Media: https://www.sharif.edu
- Region: Asia (excl. Greater China)
- DataCap Requested: 300TiB
- Addresses to be Notarized: f1lakkooooyscwt5crl3b5nj3szcnh5g2mcz3sxsa
- Notary Requested: IreneYoung

@emf-developer Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by IreneYoung** [comment]
Sorry @emf-developer, I suggest you issue a large Dataset application. You can apply here: https://github.com/filecoin-project/filecoin-plus-large-datasets/issues
