### ISSUE TITLE
Client Allocation Request for: Plate Woman House

### ISSUE THREAD

**Issue by jiangbinyi** [filecoin-project/filecoin-plus-client-onboarding#2121]
---

# Client Allocation Questions 

## Core Information
- Name: Plate Woman House
- Website / Social Media: http://www.pznrfsy.com/
- Region: Greater China Region
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1pvqt754w3r6djygzmx4iqsiksr2p7qrvtpbpn5q
- Notary Requested: swatchliu

@jiangbinyi Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by jiangbinyi** [comment]
@swatchliu Hi could you take some time to check this

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.),
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?
Would you like to submit more company information on www.bytebase.cn?
Would you like to accept our face-to-face visit?

**Comment by jiangbinyi** [comment]
@swatchliu Hi Thanks for the reply. Please refer to below and let me know if you need more information.

1、Is your company located in Greater China？
Yes. 

2、Duration of establishment
Founded in 2003.

3、Number of employees
500-999.

4、Business scope and products or services
Plate Woman House is a comprehensive cultural industry organization featuring Chinese traditional art experience, which has formed a pattern of "five industries and diversified development" with photography and video, cultural communication, product design and research and development, clothing production and related services as the main industries. It deals with digital imaging services, entertainment, film production, program production, employment guidance (education or training consultancy), videotape production, video clips, photography, book publishing.

5、Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.)
Weibo: 盘子女人坊官方
WeChat: 盘子女人坊官方
Douyin: 盘子女人坊旗舰店
Zhihu: 盘子女人坊

6、Data size to be stored,
We need 10TiB for storage.

7、Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?
No, this is our first time.

8、Would you like to submit more company information on www.bytebase.cn?
Sure. 

9、Would you like to accept our face-to-face visit?
Looking forward to it.

**Comment by swatchliu** [comment]
![Image2](https://user-images.githubusercontent.com/46444977/179677360-cf9a5c02-1e79-4918-b6fd-72bddac62a1e.png)
Since 2020, your company has no registered social security employees according to the official website qixin.com. Please reapply with real and corresponding information.
