### ISSUE TITLE
Client Allocation Request for: HIMO

### ISSUE THREAD

**Issue by qiufuyang** [filecoin-project/filecoin-plus-client-onboarding#2123]
---

# Client Allocation Questions 

## Core Information
- Name: HIMO
- Website / Social Media: http://www.haimati.cn/#/
- Region: Greater China Region
- DataCap Requested: 5TiB
- Addresses to be Notarized: f152laimpuls5cxt7qjqn7ses5e5k5bpr4yd5h5oy
- Notary Requested: steven004

@qiufuyang Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by steven004** [comment]
Hey @qiufuyang , you have an interested project. If you could provide more information to the following questions, that would be wonderful. 
1. yourself/ your organization (with links to official website/social media/news mentions etc)
2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners), if you are working with a service provider to store your data to Filecoin network, please name the provider.
5. How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
6. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
7. Would you be OK in posting deal transactions here?

Thanks

**Comment by steven004** [comment]
Hey @qiufuyang , Very glad to see you are interested by IPFS/Filecoin network, I would you suggest you to discuss with some IPFS/Filecoin service provider to save your data into IPFS/Filecoin network, which will make things easier. You can connect to Estuary, Web3.Storage, Filedrive, etc. 

I will grant you 5TiB for you to start. Once you are using up, you could apply more after a validation process, and I'll ask more information while grant more datacap.

**Comment by steven004** [comment]
Hey @qiufuyang , Your Datacap Allocation Request has been approved

**Message sent to Filecoin Network**
> [bafy2bzaced7a5l7vh4kgkzmha3smsbmw25z755clhx5fdhy2zbbse7ajcj3za](https://filscan.io/tipset/message-detail?cid=bafy2bzaced7a5l7vh4kgkzmha3smsbmw25z755clhx5fdhy2zbbse7ajcj3za)

**Address**
> [f152laimpuls5cxt7qjqn7ses5e5k5bpr4yd5h5oy](https://filscan.io/address/general?address=f152laimpuls5cxt7qjqn7ses5e5k5bpr4yd5h5oy)

**Datacap Allocated**
> 5.0TiB

**Comment by qiufuyang** [comment]
@steven004 Hi really appreciate your prompt reply and support! Many thanks!
