### ISSUE TITLE
Client Allocation Request for: NFTBomb

### ISSUE THREAD

**Issue by johnchenyan** [filecoin-project/filecoin-plus-client-onboarding#2140]
---

# Client Allocation Questions 

## Core Information
- Name: NFTBomb
- Website / Social Media: https://nftbomb.org/
- Region: Asia (excl. Greater China)
- DataCap Requested: 50TiB
- Addresses to be Notarized: f1sjd6e63h5vtm47wj5jk5nw46pq62ikkx6f3jofy
- Notary Requested: neogeweb3

@johnchenyan Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by johnchenyan** [comment]
Related to [#1897](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1897)

**Comment by neogeweb3** [comment]
Allocation was successful: https://filfox.info/en/message/bafy2bzaceadiqc2bnnppxmgvc4jkjhquaqsrpyodhth6sxr56vahu3dlvrwue
