### ISSUE TITLE
Client Allocation Request for: SAYTRY

### ISSUE THREAD

**Issue by wangweijfdiansgn** [filecoin-project/filecoin-plus-client-onboarding#2142]
---

# Client Allocation Questions 

## Core Information
- Name: SAYTRY
- Website / Social Media: https://www.sscyxch.com/
- Region: Greater China Region
- DataCap Requested: 10TiB
- Addresses to be Notarized: f14mxmgppjxkn6wfhtxiwkvjhq353jem6brx54ynq
- Notary Requested: swatchliu

@wangweijfdiansgn Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by wangweijfdiansgn** [comment]
@swatchliu Hi can you check this request plz? Thanks

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.),
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?
Would you like to submit more company information on www.bytebase.cn?
Would you like to accept our face-to-face visit?

**Comment by wangweijfdiansgn** [comment]
@swatchliu Hi Thanks for the reply. Please refer to below and let me know if you need more information.

1、Is your company located in Greater China？
Yes. 

2、Duration of establishment
Established on October 13, 2015.

3、Number of employees
Less than 50.

4、Business scope and products or services
SAYTRY is one of the most rebellious creative organizations in China composed of planning, design and interactive marketing elites. SAYTRY provides the industry's top brand marketing planning and promotion services, including: market research, brand planning, marketing planning, product planning/new product launch promotion, graphic design, packaging design, new media promotion, video planning and production, WeChat official account/new media content agency operation/media delivery and other services. SAYTRY consists of veterans from international 4A, local marketing planning flagship, international media, public relations companies, with an average experience of more than 10 years.

5、Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.)
Weibo: 深圳尚上策品牌营销策划机构
WeChat: 深圳尚上策品牌营销

6、Data size to be stored,
We need 10TiB for storage.

7、Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?
No, this is our first time.

8、Would you like to submit more company information on www.bytebase.cn?
Yes. 

9、Would you like to accept our face-to-face visit?
Sure.

**Comment by swatchliu** [comment]
![Image1](https://user-images.githubusercontent.com/46444977/179672906-93fab569-1095-4df9-b793-1d86972f6fb5.png)
@wangweijfdiansgn I found only one company with the same name as the one you provided, but it seems to be no longer registered according to the National Enterprise Credit Information System. Can you confirm that this is your company?

**Comment by wangweijfdiansgn** [comment]
@swatchliu Hi This is not our company. You may want to check relevant infomation at https://m.dingtalk.com/qidian/company-0002E4578Ddc0f

**Comment by swatchliu** [comment]
Hi, we have verified your company on TianYanCha. Please use your corporate email to send the confirmation request to [partner@bytebase.cn](mailto:partner@bytebase.cn) and attach the screenshot here. Ping me once the email is sent.
