### ISSUE TITLE
Client Allocation Request for: Shanghai YueJia

### ISSUE THREAD

**Issue by Emma967** [filecoin-project/filecoin-plus-client-onboarding#2146]
---

# Client Allocation Questions 

## Core Information
- Name: Shanghai YueJia
- Website / Social Media: www.hopsum.com
- Region: Greater China Region
- DataCap Requested: 30TiB
- Addresses to be Notarized: f1kf2yfbxnvrfxonacjen5zkclqbfg74efhqtecta
- Notary Requested: 1475Notary

@Emma-YJ Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by 1475Notary** [comment]
Hello @Emma-YJ, thanks for the request! 
Please answer the following questions giving as much detail as possible.

1. Please introduce yourself and the organization you represent, what is its name, nature, country of incorporation and date of establishment?
2. How many employees does the company currently have?
3. In which region do you plan to use DataCap? 
4. What kind of social media platforms do you have (Github, Twitter, Linkedin handle, Wechat, etc.)? How many followers do you have, please share me the link or screenshot.
5. How did you hear about the FIL+ project? Do you have a good understanding of web 3.0 or have/are you involved in the web 3.0 community? If you do, please give me a brief introduction and share your account.
6. What kind of data do you plan to store? Can you share any kind of sample data?
7. Please provide the business license of your company.
8. Are you willing to store data outside of Greater China?
