### ISSUE TITLE
Client Allocation Request for: NAPAI

### ISSUE THREAD

**Issue by zhuyinjieigoe** [filecoin-project/filecoin-plus-client-onboarding#2149]
---

# Client Allocation Questions 

## Core Information
- Name: NAPAI
- Website / Social Media: https://beijing.napai.cn/
- Region: Greater China Region
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1y7qv5fxkowmyf7wqffrlfnmdvdmzddrct2het3i
- Notary Requested: steven004

@zhuyinjieigoe Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by zhuyinjieigoe** [comment]
@steven004 Hi would be great if you can take some time to check this! Thx

**Comment by steven004** [comment]
Hey @zhuyinjieigoe , you have an interested project. If you could provide more information to the following questions, that would be wonderful.

1. yourself/ your organization (with links to official website/social media/news mentions etc)
2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners), if you are working with a service provider to store your data to Filecoin network, please name the provider.
5. How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
6. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
7. Would you be OK in posting deal transactions here?

Thanks

**Comment by zhuyinjieigoe** [comment]
@steven004 Hi Thanks for the reply. Please refer to below and let me know if you need more information.

1.yourself/ your organization (with links to official website/social media/news mentions etc)
Affiliated with Napai Technology (Beijing) Co. Ltd., NAPAI is a brand that provides cashback on consumer spending on life services. Founded in May 2010, NAPAI specializes in photographic services including wedding photography, artistic photos, children's photography as well as wedding planning, wedding banquets and other wedding services. At present, it serves more than 600 cities, has more than 10,000 partners on the platform, and every year more than 600,000 couples in the country choose NAPAI services. Through strict quality control processes partners need to abide by, NAPAI has tackled the problems facing consumers such as "hidden consumption, mandatory recommendation, and challenges in the protection of rights" that are common in photography and wedding services.
official website: https://beijing.napai.cn/ 

2.Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
It’s our first time working with IPFS/Filecoin, and we would like to play a part in building a better Filecoin community.

3.Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
Publicly available data including photos and videos stored by customers which is about 100 TiB. 

4.Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners), if you are working with a service provider to store your data to Filecoin network, please name the provider.
Redundancy: at least 3 copies.
Location: China.
3 miners who have great reputation and are willing to store real data.

5.How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
We would like to use Filecoin official retrieval. 

6.What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
As a private data storage, we have no intention of making profits for the time being..

7.Would you be OK in posting deal transactions here?
Yes.

**Comment by steven004** [comment]
One more question: you mentioned it is publicly available data, and you also mentioned it's a private data storage. Please clarify it's public data or private data you'll to store in Filecoin. Thanks.

**Comment by steven004** [comment]
Hey @zhuyinjieigoe , Your Datacap Allocation Request has been approved

**Message sent to Filecoin Network**
> [bafy2bzacecrbgpbeq27h7u2g4lvdzt2b4uqys27s7flyeofxtc7dq3ofenygy](https://filscan.io/tipset/message-detail?cid=bafy2bzacecrbgpbeq27h7u2g4lvdzt2b4uqys27s7flyeofxtc7dq3ofenygy)

**Address**
> [f1y7qv5fxkowmyf7wqffrlfnmdvdmzddrct2het3i](https://filscan.io/address/general?address=f1y7qv5fxkowmyf7wqffrlfnmdvdmzddrct2het3i)

**Datacap Allocated**
> 5.0TiB
