### ISSUE TITLE
Client Allocation Request for: Ewesion

### ISSUE THREAD

**Issue by YunisEVS** [filecoin-project/filecoin-plus-client-onboarding#2152]
---

# Client Allocation Questions 

## Core Information
- Name: Ewesion
- Website / Social Media: https://www.pickfoto.com/
- Region: Greater China Region
- DataCap Requested: 100TiB
- Addresses to be Notarized: f1mrivgz3yiqzxc7gcig5xiq3vhqvlqjf2lr6pa3i
- Notary Requested: swatchliu

@YunisEVS Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.),
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?
Would you like to submit more company information on www.bytebase.cn?
Would you like to accept our face-to-face visit?

**Comment by swatchliu** [comment]
@YunisEVS  contacted me saying they want to continue this application. 
Reopening it now and please answer the questions soon.
