### ISSUE TITLE
Client Allocation Request for: [Personal or Organization Name]

### ISSUE THREAD

**Issue by TarGet0ne** [filecoin-project/filecoin-plus-client-onboarding#2166]
# Client Allocation Questions 

## Core Information
- Name: hasheagle
- Website / Social Media: https://www.hasheagle.com/
- Region:  Asia excl. Greater China / Greater China
- DataCap Requested: 50TiB
- Addresses to be Notarized: f1w5cddiuvqei74uetfmcaftailvbzut3d7m6v2nq
- Notary Requested: 1LISA2

-------------------------

**Comment by fabriziogianni7** [comment]
@1LISA2 can you assign yourself to the issue?

**Comment by 1LISA2** [comment]
@TarGet0ne thanks for the request!
Please answer the following questions giving as much detail as possible.

Please introduce yourself and the organization you represent, what is its name, nature, country of incorporation and date of establishment?
How many employees does the company currently have?
In which region do you plan to use DataCap?
What kind of social media platforms do you have (Github, Twitter, Linkedin handle, Wechat, etc.)? How many followers do you have, please share me the link or screenshot.
How did you hear about the FIL+ project? 
What kind of data do you plan to store? Can you share any kind of sample data?
Are you willing to store data outside of Greater China?

**Comment by 1LISA2** [comment]
@fabriziogianni7  sure, Thank you for your reminder

**Comment by 1LISA2** [comment]
@fabriziogianni7 honey，I can‘t  assign myself to the issue, can you help me , I found    https://github.com/filecoin-project/filecoin-plus-client-onboarding/invitations.  not invitation to me.

**Comment by raghavrmadya** [comment]
No response. @TarGet0ne please open a new issue if still interested.
