### ISSUE TITLE
Client Allocation Request for: Tedu Edu

### ISSUE THREAD

**Issue by Vicky1911** [filecoin-project/filecoin-plus-client-onboarding#2167]
---

# Client Allocation Questions 

## Core Information
- Name: Tedu Edu
- Website / Social Media: http://www.tedu.cn/
- Region: Greater China Region
- DataCap Requested: 50TiB
- Addresses to be Notarized: f1dabytgrmuqit3pckmik5snxwktwggrtv5al66ma
- Notary Requested: swatchliu

@Vicky1911 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.
Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.)
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?
Would you like to submit more company information on www.bytebase.cn?
Would you like to accept our face-to-face visit?

**Comment by Vicky1911** [comment]
Hello @swatchliu 
Yes. We have established several campus in many cities of China.

Our company were established in September 2002.
We have 900 employees now.
Tedu has a comprehensive education group covering IT and Internet career empowerment, industry-education integration, school-enterprise cooperation and other fields.
Wechat：达内教育
We have more than 24TiB data and we need 2 copies, total 50TiB.
Yes, we used to send applications and all of them were accepted. No datacap left.
Sure! You can contact me via github.
We have office in Shanghai. Welcome!

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec7ntcehjcqk3odbcrcneowvl7sjxbgrgsf6xxc7gvhjwv3ete6ac 
#### Address 
> f1dabytgrmuqit3pckmik5snxwktwggrtv5al66ma
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec7ntcehjcqk3odbcrcneowvl7sjxbgrgsf6xxc7gvhjwv3ete6ac
