### ISSUE TITLE
Client Allocation Request for: Woropay

### ISSUE THREAD

**Issue by Yeter-woro** [filecoin-project/filecoin-plus-client-onboarding#2168]
---

# Client Allocation Questions 

## Core Information
- Name: Woropay
- Website / Social Media: http://www.woropay.cn/index.html
- Region: Greater China Region
- DataCap Requested: 100TiB
- Addresses to be Notarized: f1kzptz47vgpgg7jbwn2rnqbzwjaa3rtdjtedramy
- Notary Requested: 1475Notary

@Yeter-woro Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by 1475Notary** [comment]
Hello @Yeter-woro, thanks for the request!
Please answer the following questions giving as much detail as possible.
1. Please introduce yourself and the organization you represent, what is its name, nature, country of incorporation and date of establishment?
2. How many employees does the company currently have?
3. In which region do you plan to use DataCap?
4. What kind of social media platforms do you have (Github, Twitter, Linkedin handle, Wechat, etc.)? How many followers do you have, please share me the link or screenshot.
5. How did you hear about the FIL+ project? Do you have a good understanding of web 3.0 or have/are you involved in the web 3.0 community? If you do, please give me a brief introduction and share your account.
6. What kind of data do you plan to store? Can you share any kind of sample data?
7. Please provide the business license of your company.
8. Are you willing to store data outside of Greater China?

**Comment by Yeter-woro** [comment]
1. My english name is yeter and i work in the operation department. Recently my manager asked me to apply Filecoin on behalf of our company. Our company's full name is Shanghai Wangfu (woropay) Technology Group Co. Woropay is a joint brand of Shanghai Worong Internet Technology Co., Ltd, which is a combined smart cash register system jointly produced by Suke IOT (Shanghai) Co. As the first batch of channel merchants authorized by AliPay, Woropay has become one of the few companies in China to cooperate with Alibaba, Tencent, UnionPay, commercial banks, Jingdong and Baidu. Our company was founded in 2019-09-24.  
2. We have around 130 employees. 
3. China.
4. We have Wechat official account: 旺付收银 or you can find us by woropay（weixin ID). Also new mentions for you reference. https://t.cj.sina.com.cn/articles/view/1794681085/6af8a8fd00100jjfk
5.  Since the beginning of the Internet booming era, woropay has been acquiring many famous domestic Internet brands in the fields of e-commerce, social networking, self media, cloud computing, and consumer services, etc. As our business grows and as an Internet-related industry ourselves, we have always had a continuous interest in decentralized storage.
6. Our unified social credit Number91310114MA1GWJ2C0F. Business license contains too many details in it. We would like to send you by email together with data sample. 
7. No. As required by financial and information laws, we can only store data within the country.

Sorry we haven't checked here in a while, could you help us on the application? @1475Notary Thanks!

**Comment by 1475Notary** [comment]
bot error.  Approved by lotus.
