### ISSUE TITLE
Client Allocation Request for: Kitchenidea

### ISSUE THREAD

**Issue by MI1ca** [filecoin-project/filecoin-plus-client-onboarding#2169]
---

# Client Allocation Questions 

## Core Information
- Name: Kitchenidea
- Website / Social Media: http://www.kitchenidea.com.cn/
- Region: Greater China Region
- DataCap Requested: 30TiB
- Addresses to be Notarized: f1rgthnuxaodonu2aug6fwq5mrpbabfodgm4kvhly
- Notary Requested: swatchliu

@MI1ca Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.),
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?
Would you like to submit more company information on www.bytebase.cn?
Would you like to accept our face-to-face visit?

**Comment by MI1ca** [comment]
Hi @swatchliu 
1. Yes, our company is located in Hangzhou, Zhejiang Province.
2. Our company was founded in 2020.
3. Currently we have 72 employees. 
4. As you can see from our company name, it's kitchen + idea. We are a brand with kitchen appliances as the main product, dedicated to the development of AI cooking robot and multifunctional cooking machine. In line with the contemporary trend of artificial intelligence, our brand is very popular among young generation customers and was trending on Chinese social media such as Douyin and RED(小红书). 
Our machines are multi-functional, providing recipes on the touch screen, covering the functions of basic kitchen appliances such as coffee maker, kettle, yogurt maker, juicer and electronic scale and so on. We are proud of our brand for turning beginners into chefs and will continue to develop and improve our existing machines and recipes. 
Here is a link to some of our products: http://www.kitchenidea.com.cn/#/Product?propType=1&type=10
5. Weibo 田螺云厨 with 63k followers 
https://m.weibo.cn/u/5980246058?uid=5980246058&t=0&luicode=10000011&lfid=100103type%3D1%26q%3D%E7%94%B0%E8%9E%BA%E4%BA%91%E5%8E%A8
We have our Wechat Official under the same name as 田螺云厨
6. Currently we need 30TB, but with the expansion of our business, we might gonna apply more in the future.
7. No, this is our first time working with Filecoin.
8. Sure, we would love that.
9. Yes, our company is in Hangzhou and we welcome you to visit us.

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasouhuieznnaodxa7yrnufzfp3z7j7malkt2sqbizy4zkiigsuwo 
#### Address 
> f1rgthnuxaodonu2aug6fwq5mrpbabfodgm4kvhly
#### Datacap Allocated
> 30.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasouhuieznnaodxa7yrnufzfp3z7j7malkt2sqbizy4zkiigsuwo
