### ISSUE TITLE
Client Allocation Request for: 863Soft

### ISSUE THREAD

**Issue by Grace531** [filecoin-project/filecoin-plus-client-onboarding#2170]
---

# Client Allocation Questions 

## Core Information
- Name: 863Soft
- Website / Social Media: https://www.863soft.com/en/
- Region: Greater China Region
- DataCap Requested: 30TiB
- Addresses to be Notarized: f1krlbzha5oio7rri3gcg4g3svq4t63v3zwjceh5y
- Notary Requested: 1475Notary

@Grace531 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.),
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?
Would you like to submit more company information on www.bytebase.cn?
Would you like to accept our face-to-face visit?

**Comment by 1475Notary** [comment]
Hello @Grace531, thanks for the request!
Please answer the following questions giving as much detail as possible.
1. Please introduce yourself and the organization you represent, what is its name, nature, country of incorporation, and date of establishment?
2. How many employees does the company currently have?
3. In which region do you plan to use DataCap?
4. What kind of social media platforms do you have (Github, Twitter, Linkedin handle, Wechat, etc.)? How many followers do you have, please share me the link or screenshot.
5. How did you hear about the FIL+ project? Do you have a good understanding of web 3.0 or have/are you involved in the web 3.0 community? If you do, please give me a brief introduction and share your account.
6. What kind of data do you plan to store? Can you share any kind of sample data?
7. Please provide the business license of your company.
8. Are you willing to store data outside of Greater China?

**Comment by 1475Notary** [comment]
I have received the email from the applicant with the company's business license attached. Reopening this application.

**Comment by Grace531** [comment]
@1475Notary thanks for reopening our application and the answers to your questions are as below.

1. Please introduce yourself and the organization you represent, what is its name, nature, country of incorporation, and date of establishment?
Our company is Henan 863 Software Company and I work in the Big Data Division. Our company is registered in China and was established on November 23, 2017. Our company was formerly the software business headquarters of Henan Province 863 Software Incubator Co., Ltd. which was established in 2001.

2. How many employees does the company currently have?
We currently have approximately 600 full-time employees. Because of the global distribution of our customers, we also have hundreds of professional software engineers located around the world. 
3. In which region do you plan to use DataCap?
Greater China. 
4. What kind of social media platforms do you have (Github, Twitter, Linkedin handle, Wechat, etc.)? How many followers do you have, please share me the link or screenshot.
We specialize in the development of custom applications for companies around the world, such as e-commerce, big data, catering, logistics and other industries. After years of accumulation we have a stable customer base and industry recognition, so we do not run multiple social platforms. Currently we are on linkedin and here's the link for the reference. 
https://www.linkedin.com/company/%E6%B2%B3%E5%8D%97%E5%85%AB%E5%85%AD%E4%B8%89%E8%BD%AF%E4%BB%B6%E8%82%A1%E4%BB%BD%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/?originalSubdomain=cn
5. How did you hear about the FIL+ project? Do you have a good understanding of web 3.0 or have/are you involved in the web 3.0 community? If you do, please give me a brief introduction and share your account.
As an Internet-related company, we have always attached importance to the future development. Following the rapid growth from 2010 to 2020, the period when mobile devices made it possible for people to connect to the Internet anytime and anywhere has been almost completely reached, and the room for development has been significantly limited.
If Web 2.0 is a store that responds to the needs of the user anywhere, anytime, web 3 is a store that connects the user with the store, where human-computer interaction means that the distance between "people" and "technology" is further reduced, and it can even be said that "Technology is becoming an integral part of people. 
We have great expectations for web3, the decentralized mechanism of filecoin, and we have applied accordingly in LDN. We have also responded as per the official suggestion and are still waiting for the process. Here is our account https://github.com/863software. 
6. What kind of data do you plan to store? Can you share any kind of sample data?
@raghavrmadya yes, we do have an LDN open. As you may know it is still in the approval process, we are planning to store a very small portion through the direct allocation as we want to take this opportunity to get familiar with the entire filecoin storage process in advance.
Data sample: https://github.com/filecoin-project/filecoin-plus-large-datasets/files/9054256/863122.zip
7. Please provide the business license of your company.
I have sent it to your email already. 
8. Are you willing to store data outside of Greater China?
Yes.

**Comment by 1475Notary** [comment]
@raghavrmadya  We have done KYC with this client, it's a real active company and  the requirement is also resonable .

@Grace531  We can give you 30T datacap at most because our own quota is also limited, Recommended that you can continue to apply for LDN.

**Comment by 1475Notary** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7y2lp4tmh3u4xnxsr3joa46kkbpnhvkkkgwop5rjqa2jfgrek2q 
#### Address 
> f1krlbzha5oio7rri3gcg4g3svq4t63v3zwjceh5y
#### Datacap Allocated
> 30.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7y2lp4tmh3u4xnxsr3joa46kkbpnhvkkkgwop5rjqa2jfgrek2q
