### ISSUE TITLE
Client Allocation Request for: 信联科技

### ISSUE THREAD

**Issue by tddey01** [filecoin-project/filecoin-plus-client-onboarding#2172]
---

# Client Allocation Questions 

## Core Information
- Name: 信联科技
- Website / Social Media: https://github.com/tddey01
- Region: Greater China Region
- DataCap Requested: 20TiB
- Addresses to be Notarized: f17ko6ejaixp2mf67tj7jexndrkjijd5kqwnphepa
- Notary Requested: swatchliu

@tddey01 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Hi, thanks for your request. But the link you provided to the website is the personal page of github. And what does Kevin Liu represent? An organization or an individual?

**Comment by tddey01** [comment]
sir
im is personal

ByteBase ***@***.***> 于2022年7月18日周一 14:36写道：

**Comment by swatchliu** [comment]
Thanks for the quick reply.
I just noticed that the title has been changed to '信联科技', if you represent an individual, what is your connection to this company? 
Do you have authorization from the company to make the application? 
Please share the information about the company along with it.
