### ISSUE TITLE
Client Allocation Request for: TBZX

### ISSUE THREAD

**Issue by TBZXBJ** [filecoin-project/filecoin-plus-client-onboarding#2174]
---

# Client Allocation Questions 

## Core Information
- Name: TBZX
- Website / Social Media: http://www.2b.cn/
- Region: Greater China Region
- DataCap Requested: 50TiB
- Addresses to be Notarized: f1ij6pmcrinf4tkujao4eqekl75srj7jvvovel3qi
- Notary Requested: swatchliu

@TBZXBJ Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.),
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?
Would you like to submit more company information on [www.bytebase.cn](http://www.bytebase.cn/)?
Would you like to accept our face-to-face visit?

**Comment by TBZXBJ** [comment]
Sorry @swatchliu, we missed the notification. Please check our answers. 

Is your company located in Greater China？
Yes. Our company is located in Beijing.

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Our company was established in 2014.

Number of employees,
Around 20 employess. 

Business scope and products or services,
We are a professional media website for B2B industry in China. We focus on enterprise news reporting and strategic brand communication, serve B2B platforms, e-commerce enterprises and so on. We focus on information, research, communication, consulting, training and branding services. In short, we are a third-party information, research and communication agency.

Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.),
weibo: B2B行业资讯
wechat: 托比网

Data size to be stored,
Around 135T. This is our first application.

Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?
No.

Would you like to submit more company information on [www.bytebase.cn](http://www.bytebase.cn/)?
Yes.

Would you like to accept our face-to-face visit?
Yes.

**Comment by TBZXBJ** [comment]
Could you help us reopen it? Thanks. @swatchliu

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecsmyxtwynjeedcbthdiavog24cxllxrn6c75pxdqxv6jebrxl4am 
#### Address 
> f1ij6pmcrinf4tkujao4eqekl75srj7jvvovel3qi
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecsmyxtwynjeedcbthdiavog24cxllxrn6c75pxdqxv6jebrxl4am
