### ISSUE TITLE
Client Allocation Request for: Momoshop

### ISSUE THREAD

**Issue by Tiffany730** [filecoin-project/filecoin-plus-client-onboarding#2175]
---

# Client Allocation Questions 

## Core Information
- Name: Momoshop
- Website / Social Media: https://www.momoshop.com.tw/
- Region: Greater China Region
- DataCap Requested: 50TiB
- Addresses to be Notarized: f17u6swhlk6mb347i47ces2vl3p3kptfzt6qeuqby
- Notary Requested: 1475Notary

@Tiffany730 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by 1475Notary** [comment]
Hello @Tiffany730, thanks for the request!
Please answer the following questions giving as much detail as possible.

1. Please introduce yourself and the organization you represent, what is its name, nature, country of incorporation, and date of establishment?
2. How many employees does the company currently have?
3. In which region do you plan to use DataCap?
4. What kind of social media platforms do you have (Github, Twitter, Linkedin handle, Wechat, etc.)? How many followers do you have, please share me the link or screenshot.
5. How did you hear about the FIL+ project? Do you have a good understanding of web 3.0 or have/are you involved in the web 3.0 community? If you do, please give me a brief introduction and share your account.
6. What kind of data do you plan to store? Can you share any kind of sample data?
7. Please provide the business license of your company.
8. Are you willing to store data outside of Greater China?

**Comment by Tiffany730** [comment]
Sorry about the late reply. please check below. Thank you @1475Notary 
> 1. Please introduce yourself and the organization you represent, what is its name, nature, country of incorporation, and date of establishment?
I am an employee of the Technical Services Department and represent the company in making this application. Momo shopping is under Fubon Media Technology which is the leading online retailer in Taiwan. Our business includs Motian Mall, TV shopping and catalog shopping. Headquartered in Taiwan, our group is also actively establishing international markets. On the mainland, Fubon Gehua (Beijing) Trade Co., Ltd. was established in May 2011. In March 2014, our company established TVD momo in Thailand as a joint venture.

> 2. How many employees does the company currently have?
Around 2800 in the whole Fubon Group. 

> 3. In which region do you plan to use DataCap?|
Greater China.

> 4. What kind of social media platforms do you have (Github, Twitter, Linkedin handle, Wechat, etc.)? How many followers do you have, please share me the link or screenshot.
Wikipedia - https://zh.wikipedia.org/zh-hant/MOMO%E8%B3%BC%E7%89%A9%E7%B6%B2
Linkedin - https://www.linkedin.com/company/fubon-multimedia-technology-co.-ltd/?originalSubdomain=tw
> 5. How did you hear about the FIL+ project? Do you have a good understanding of web 3.0 or have/are you involved in the web 3.0 community? If you do, please give me a brief introduction and share your account.
From friend in the same field. 

> 6. What kind of data do you plan to store? Can you share any kind of sample data?
Our website related sources. You can check on our site. 

> 7. Please provide the business license of your company.
We will provide it via email. 

> 8. Are you willing to store data outside of Greater China?
Yes.

**Comment by Tiffany730** [comment]
Hello @1475Notary, is there any update? Please contact me if you need any further information. Thank you.

**Comment by 1475Notary** [comment]
have given 50TiB to you manaually. Pls check.
