### ISSUE TITLE
Client Allocation Request for: Plate Woman House

### ISSUE THREAD

**Issue by jiangbinyi** [filecoin-project/filecoin-plus-client-onboarding#2177]
---

# Client Allocation Questions 

## Core Information
- Name: Plate Woman House
- Website / Social Media:  http://www.pznrfsy.com/
- Region: Greater China Region
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1pvqt754w3r6djygzmx4iqsiksr2p7qrvtpbpn5q
- Notary Requested: swatchliu

@jiangbinyi Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by jiangbinyi** [comment]
@swatchliu Hi Please refer to #2121 and check our social security information at https://aiqicha.baidu.com/annualreport?pid=32225933230327&year=2020

**Comment by swatchliu** [comment]
Hi, we have verified your company on TianYanCha. Please use your corporate email to send the confirmation request to [partner@bytebase.cn](mailto:partner@bytebase.cn) and attach the screenshot here. Ping me once the email is sent

**Comment by swatchliu** [comment]
Hi, we have verified your company on TianYanCha. Please use your corporate email to send the confirmation request to [partner@bytebase.cn](mailto:partner@bytebase.cn) and attach the screenshot here. Ping me once the email is sent.
