### ISSUE TITLE
Client Allocation Request for: Ghost Byte | Trevor K Smith

### ISSUE THREAD

**Issue by Trevor-K-Smith** [filecoin-project/filecoin-plus-client-onboarding#2178]
---

# Client Allocation Questions 

## Core Information
- Name: Ghost Byte | Trevor K Smith
- Website / Social Media: https://ghostbyte.io
- Region: North America
- DataCap Requested: 210TiB
- Addresses to be Notarized: f1xk675y7irqo6ym3qfhvkeswsihlrm33walljmii
- Notary Requested: @cryptowhizzard

@Trevor-K-Smith Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Trevor-K-Smith** [comment]
Purpose: Slingshot V3
Dataset: Cancer Cell Line Encyclopedia (CCLE)
Size: 20.7 TiB
Project URL: https://portals.broadinstitute.org/ccle/about

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
