### ISSUE TITLE
Client Allocation Request for: 天宏阳光新能源股份有限公司

### ISSUE THREAD

**Issue by quinn463** [filecoin-project/filecoin-plus-client-onboarding#218]
---

# Client Allocation Questions 

## Core Information
- Name: 天宏阳光新能源股份有限公司
- Website / Social Media: www.hongsolar.com.cn
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1akfbnyuemagwocknlqbx3nbzmrhcfyzx3wtxsci
- Notary Requested: ozhtdong

**Comment by ozhtdong** [comment]
Thanks for your application. I want to know more basic information of you and your company. Please answer following question:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?

**Comment by quinn463** [comment]
Ok.

My name is Huang Xiaohong.  I am the legal person.

We mainly engaged in the development and operation of photovoltaic power stations and wind power and asset trading. We have WeChat official account: 天宏阳光HongSolar.

Business license:
![图片1](https://user-images.githubusercontent.com/79658535/109605868-c9580d80-7b60-11eb-923d-83669b67d5ef.png)

**Comment by ozhtdong** [comment]
Thanks for your quick reply and detailed information.
I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency? Could you please show me your cloud usage evidence?

**Comment by quinn463** [comment]
Ok.

We want to store Photovoltaic and wind power station, power generation and equipment operation data, meteorological data. You can find the demo here:
![src=http___pic carnoc com_file_110512_1105121134543 jpg refer=http___pic carnoc](https://user-images.githubusercontent.com/79658535/109934056-09f18b80-7d07-11eb-8210-ef3fd9e4b425.jpeg)
And the file need to be smaller than 10 MB, so I can send you other demos via E-mail.

Our company used cloud like Qiniu Yun. About 20 TiB/ year.

**Comment by ozhtdong** [comment]
I would appreciate if you send me more demos. I haven't got it yet.

I also want to know more about your allocation strategy.

1.How many miners do you want to store your data to? How much data for each miner? 
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect? 
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by quinn463** [comment]
I haven't allocated before. We would like to inspect miners' storage space, past status of fault and recovery sectors,  seal speed, industry reputation and so on. Maybe find 3-4 miners in different regions. And record my allocation decision in https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/218.

**Comment by ozhtdong** [comment]
Hi. 
Thanks for your information.
The last step, please show me your company searching consequence in the local business license searching website.

**Comment by quinn463** [comment]
![1614936628(1)](https://user-images.githubusercontent.com/79658535/110096075-843e1080-7dd8-11eb-93aa-593129b10f2b.png)

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebgin2fgfrg7efslynhck5nebohzybpxw7kcr3lh6smhd44u5zzz6 
#### Address 
> f1akfbnyuemagwocknlqbx3nbzmrhcfyzx3wtxsci
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebgin2fgfrg7efslynhck5nebohzybpxw7kcr3lh6smhd44u5zzz6
