### ISSUE TITLE
Client Allocation Request for: 厦门机云网络科技有限公司

### ISSUE THREAD

**Issue by Zhang619** [filecoin-project/filecoin-plus-client-onboarding#220]
---

# Client Allocation Questions 

## Core Information
- Name: 厦门机云网络科技有限公司
- Website / Social Media: http://tfpass.cn/
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1jpsviafwjnwx43g72xyqtj74muolxyvkvbxzg5a
- Notary Requested: ozhtdong

**Comment by ozhtdong** [comment]
Thanks for your application. I want to know more basic information of you and your company. Please answer following question:

**1.What's your name? What's your position? Can you introduce yourself?
2.What's your company's business? Any other social media link? Please introduce your company.
3.Could you show me your company's business license?**

**Comment by Zhang619** [comment]
Yes, I would love to introduce my company and I for you.

I am the **CTO** named **Zhao Dingshan** from  Xiamen Jiyun Network Technology Co., Ltd. 

**Xiamen Jiyun Network Technology Co., Ltd., as a typical digital marketing technology company, follows the changes of digital marketing technology and software industry, constantly adjusts and improves the company's SaaS product line, from programmed advertising (RTB, API) to data platform (DMP, CDP, data center), and then to private domain operation, conforming to the digital marketing industry from extensive operation to refined operation The development and evolution of human beings.
The product system of cloud computing network includes one middle platform and three front platforms. The middle platform integrates data collection, data processing, data modeling, data utilization and other data related functions and services on one platform. The three front ends are, in turn, the smart marketing cloud with public domain drainage, the smart business SCRM system with private domain operation, and the smart store social e-commerce platform to help enterprises quickly online.**

You can learn more detailed information from following links:

**https://mbd.baidu.com/newspage/data/landingshare?preview=1&pageType=1&isBdboxFrom=1&context=%7B%22nid%22%3A%22news_8976920065838266102%22%2C%22sourceFrom%22%3A%22bjh%22%7D

https://zhuanlan.zhihu.com/p/350356969**

![2](https://user-images.githubusercontent.com/79349534/110279168-9bb50d80-8013-11eb-89c8-7dd748415009.jpg)

**Comment by ozhtdong** [comment]
Thanks for your quick reply and detailed information.

I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?

**Comment by Zhang619** [comment]
1. E-commerce data. Demos later via E-mail.
2. Yes. Ali cloud. About 10 TiB/month.

**Comment by ozhtdong** [comment]
I also want to know more about your allocation strategy.

1.How many miners do you want to store your data to? How much data for each miner? 
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect? 
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by ozhtdong** [comment]
The last step, please show me your company searching consequence in the local business license searching website.

**Comment by Zhang619** [comment]
1.  I only want to store my data to one miner.  
2. Yes. Github.
3. I will check the miner's industry reputation. 
4. No.

**Comment by Zhang619** [comment]
![1615537136(1)](https://user-images.githubusercontent.com/79349534/110912326-c1f9e680-834e-11eb-9eca-e07728935579.png)

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecsrt7wku45id3ot47hitrvst2kvyhj72mpvxmok2x47rgbpnhbla 
#### Address 
> f1jpsviafwjnwx43g72xyqtj74muolxyvkvbxzg5a
#### Datacap Allocated
> 5TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecsrt7wku45id3ot47hitrvst2kvyhj72mpvxmok2x47rgbpnhbla
