### ISSUE TITLE
Client Allocation Request for: 上海东朔信息科技有限公司

### ISSUE THREAD

**Issue by Charles20210220** [filecoin-project/filecoin-plus-client-onboarding#221]
---

# Client Allocation Questions 

## Core Information
- Name: 上海东朔信息科技有限公司
- Website / Social Media: http://www.eastego.com/
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1gdj2m7s5we67yaze5m6ylqki3imizc4uz3g5z4y
- Notary Requested: steven004

**Comment by steven004** [comment]
Hey @Charles20210220  , thanks for your request. Can you kindly add more information / context here on:

1. yourself/ your organization (with links to official website/social media/news mentions etc)
2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners)
5. How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it? 
6. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
7. Would you be OK in posting deal transactions here?

Thanks

**Comment by steven004** [comment]
Hey @Charles20210220 , please let me know if you still need the data-cap, or I will close this issue. Thanks.

**Comment by steven004** [comment]
Closed due to no response in one week. 

@Charles20210220 , please feel free to resubmit a request if you still need datacap.
