### ISSUE TITLE
Client Allocation Request for: 苏州拍拍淘信息技术有限公司

### ISSUE THREAD

**Issue by onezhao** [filecoin-project/filecoin-plus-client-onboarding#222]
---

# Client Allocation Questions 

## Core Information
- Name: 苏州拍拍淘信息技术有限公司
- Website / Social Media: http://www.taopaipai.com/
- Region: Greater China
- DataCap Requested: 20TiB
- Addresses to be Notarized: f1kg7estn3wg3a6cjb7immyxrjihg5jsrab3lha2i
- Notary Requested: ozhtdong

**Comment by ozhtdong** [comment]
@onezhao Hello. You have asked for 10 PiB DataCap, we don't have that much. And we also want to know why you need so much DataCap. What kind of data do you want to store?

**Comment by TzmDong** [comment]
@ozhtdong 
Dear Notary,
Taopaipai is the biggest travel photography company around the world. Headquartered in Suzhou, we also have offline experience centers in Beijing, Sanya, Lijiang, Xiamen, Huanggang, Qujing, Huzhou Anji, Ningbo Beilun, Linyi, Baoji and Maanshan, etc.
As leader of China's O2O wedding photography, we have large demands of storage. And then IPFS came into my eyes, its security and its low-cost attarct us a lot.

**Comment by ozhtdong** [comment]
Thanks for your detailed information.

Could you show me more information about you and your company: What's your name? What's your position? Can you introduce yourself?What's your company's business? Any other social media link?Could you show me your company's business license?

**Comment by onezhao** [comment]
Dear Notary,
Taopaipai is the biggest travel photography company around the world. Headquartered in Suzhou, we also have offline experience centers in Beijing, Sanya, Lijiang, Xiamen, Huanggang, Qujing, Huzhou Anji, Ningbo Beilun, Linyi, Baoji and Maanshan, etc.
As leader of China's O2O wedding photography, we have large demands of storage. And then IPFS came into my eyes, its security and its low-cost attarct us a lot.

**Comment by onezhao** [comment]
I the founder of TaoPaipai, you can call me Wang Chong 王冲. I am full of the experience of traditional Photography and have provided marketing, management, technical support and guidance to nearly 700 studios in China. I have 5 studios, 3 photography bases with single investment of more than 10 million, 1 training and consulting company, 1 film and television base, studio planning, design and construction company.

**Comment by onezhao** [comment]
Social media link: https://www.sohu.com/a/152311679_776138

**Comment by onezhao** [comment]
Business license:
&nbsp;

**Comment by ozhtdong** [comment]
Thanks. Could you please send me some demos of your data? Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?

**Comment by onezhao** [comment]
Hi, I have sent you demos through Github, can you receive it? Yes, our company use cloud such as Ali, Baidu, Tencent, Qiniu, etc. We have 10 PiB data to store now. We almost use cloud everyday.

**Comment by ozhtdong** [comment]
I also want to know more about your allocation strategy.

1.How many miners do you want to store your data to? How much data for each miner? 
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect? 
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by ozhtdong** [comment]
The last step, please show me your company searching consequence in the local business license searching website.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceduvnvj7mcrkkm3ye5izb4cpxszaqau5s2ceocgozysfm7g56srag 
#### Address 
> f1kg7estn3wg3a6cjb7immyxrjihg5jsrab3lha2i
#### Datacap Allocated
> 20TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceduvnvj7mcrkkm3ye5izb4cpxszaqau5s2ceocgozysfm7g56srag
