### ISSUE TITLE
Client Allocation Request for: 杭州讯酷科技有限公司

### ISSUE THREAD

**Issue by TzmDong** [filecoin-project/filecoin-plus-client-onboarding#223]
---

# Client Allocation Questions 

## Core Information
- Name: 杭州讯酷科技有限公司
- Website / Social Media: www.xunkukeji.com
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1wninfaoogdihtbqntlhjanb3z5bswqvjcestuuq
- Notary Requested: ozhtdong

**Comment by TzmDong** [comment]
@ozhtdong Hi. I have answered your questions before and my account is suspended since I used it to participate in Huobi projects. I don't know if you have my information backup or not.

**Comment by ozhtdong** [comment]
![1614746079(1)](https://user-images.githubusercontent.com/69976222/109765454-d5f76700-7c2f-11eb-9e5e-b20e94dd5af0.png)
![1614746125(1)](https://user-images.githubusercontent.com/69976222/109765460-d98aee00-7c2f-11eb-88de-8f6aa01bb4f1.png)

@TzmDong I checked my Mail-Box. Are these your replies?

**Comment by ozhtdong** [comment]
If yes, I still need to know more details about your allocation strategy. 

1.How many miners do you want to store your data to? How much data for each miner? 
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to insperct miners? Which aspect of miners will you inspect? 
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by TzmDong** [comment]
Yes,these are indeed my replies.
1.Maybe I will store my data to 2 miners. I have tentatively decided to store 15 TB of data for each miner.
2.Yes,I will record my allocation decision on this page.
3.I don't have a definite idea yet，but the credibility of a miner within the industry is an important indicator.
4.Nope.

**Comment by ozhtdong** [comment]
Good. The last step, please show me your company searching consequence in the local business license searching website.

**Comment by TzmDong** [comment]
![讯酷](https://user-images.githubusercontent.com/64239711/109941018-a323a080-7d0d-11eb-97ff-bc7f4defc4d8.png)


Thank you very much for your patient reply.Looking forward to your good news.

**Comment by ozhtdong** [comment]
![1614916163(1)](https://user-images.githubusercontent.com/69976222/110064838-dff0a580-7da8-11eb-8127-630111253825.png)

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceccsujzyt3ld6z5pgwviuz4jjpjf2zlds32vlz3cppvogwhxm7qiw 
#### Address 
> f1wninfaoogdihtbqntlhjanb3z5bswqvjcestuuq
#### Datacap Allocated
> 5TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceccsujzyt3ld6z5pgwviuz4jjpjf2zlds32vlz3cppvogwhxm7qiw
