### ISSUE TITLE
Client Allocation Request for: Net366

### ISSUE THREAD

**Issue by wwjuts** [filecoin-project/filecoin-plus-client-onboarding#2256]
---

# Client Allocation Questions 

## Core Information
- Name: Net366
- Website / Social Media: http://www.net366.net/
- Region: North America
- DataCap Requested: 25TiB
- Addresses to be Notarized: f1pzhzcjrh6zafz4e6klprnwyzkbvlcbq2waqsg3i
- Notary Requested: xingjitansuo

@wwjuts Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by xingjitansuo** [comment]
Thanks for your request.  Let's clarify the below questions first to move forward. 
1. Can you please briefly describe the business entity? 
2. Please Explain your relationship with Net366. 
3. Please describe the data type onboarded to Filecoin, and can you share a sample link?  
4. Explain your distribution plan.

**Comment by raghavrmadya** [comment]
@wwjuts any update here?
