### ISSUE TITLE
Client Allocation Request for: 深圳市华创致远科技有限公司

### ISSUE THREAD

**Issue by dataccc3** [filecoin-project/filecoin-plus-client-onboarding#226]
---

# Client Allocation Questions 

## Core Information
- Name: 深圳市华创致远科技有限公司
- Website / Social Media: http://www.hczyit.com/
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1jtqlf45zl2a74mbpcsv6elkdxoa7xa3nsrhyo7a
- Notary Requested: steven004

**Comment by steven004** [comment]
Hey @dataccc3 , thanks for your request. Can you kindly add more information / context here on:

1. yourself/ your organization (with links to official website/social media/news mentions etc)
2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners)
5. How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
6. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
7. Would you be OK in posting deal transactions here?

Thanks

**Comment by dataccc3** [comment]
Hey, @steven004 
 
I am very glad to give you detailed information.
 
1. I am 彭利芳, the founder of 华创致远, which is a solution and service provider of professional information system with various resources. 华创致远 aims to offer solutions covered servers, storage, network application, network application, information encryption, IT Resource Management and so on. We also have services such as self-innovating services, value-added services, IT outsourcing, project integration and IT information consulting.
2. Actually, we haven't worked on IPFS/ Filecoin yet. We are just finding new storage solution and we really would love to try.
3. We plan to store Server run log on Filecoin first. And if it works, we intend to store some customers’ data.
4. We intend to allocate DataCap to 2-3 miners who charge for less and has less fault.
5. We would like to try Filecoin official retrieval.
6. Not profit, just try.
7. Yes.

**Comment by steven004** [comment]
@dataccc3 , Welcome to the Filecoin world. 

Since it is just a start for you to store data in Filecoin, and for a try first, I would like to grant you 512GB for your test. After you have done some test, please do not hesitate to request more if needed. 

And, if you need any help no matter for developing support, or miner support, please let me know.

**Comment by steven004** [comment]
Hey @dataccc3 , Your Datacap Allocation Request has been approved

**Message sent to Filecoin Network**
> [f1qoxqy3npwcvoqy7gpstm65lejcy7pkd3hqqekna](https://filscan.io/tipset/message-detail?cid=bafy2bzacedtbpxe4asm6vdd4kyitjqj4eo5zcreneosj4jfejd3ygzlxr5fji) 

**Address**
> [f1jtqlf45zl2a74mbpcsv6elkdxoa7xa3nsrhyo7a](https://filscan.io/tipset/address-detail?address=f1jtqlf45zl2a74mbpcsv6elkdxoa7xa3nsrhyo7a)

Datacap Allocated
> 256 GiB 


Please check.
