### ISSUE TITLE
Client Allocation Request for: 上海鲸翼信息科技有限公司

### ISSUE THREAD

**Issue by lindazhuang123** [filecoin-project/filecoin-plus-client-onboarding#229]
---

# Client Allocation Questions 

## Core Information
- Name: 上海鲸翼信息科技有限公司
- Website / Social Media: https://www.jing-yi.com.cn/
- Region: Greater China
- DataCap Requested: 7TiB
- Addresses to be Notarized: f1hnlwy7swr7lyjf3pmuryqkoih6smvcapbxdkp6y
- Notary Requested: ozhtdong

**Comment by ozhtdong** [comment]
Thanks for your application! @lindazhuang123 

I want to know more basic information of you and your company. Please answer following question:

1.What's your name? What's your position? Can you introduce yourself?
2.What's your company's business? Any other social media link? Please introduce your company.
3.Could you show me your company's business license?

**Comment by lindazhuang123** [comment]
1.What's your name? What's your position? Can you introduce yourself?
Hello, I’m Yunfei Shen, the CEO of Shanghai Jingyi Information Technology Co., Ltd.

2.What's your company's business? Any other social media link? Please introduce your company.
Since its establishment, Shanghai Jingyi Information Technology Co., Ltd. has been focusing on Internet brand building. It is a network service organization focusing on high-end website construction, technology development and brand communication, and is committed to providing enterprises with comprehensive and rich network solutions. He has rich experience in website construction creativity enhancement, software development technology innovation, and brand communication effect enhancement.

 https://zhuanlan.zhihu.com/p/352777674  


3.Could you show me your company's business license?
<img width="386" alt="图片 1fh" src="https://user-images.githubusercontent.com/79966014/111273928-588c1780-866f-11eb-8cfb-b2e7a48a81a3.png">

**Comment by ozhtdong** [comment]
Thanks for your  detailed information.
I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?

**Comment by lindazhuang123** [comment]
1、Enterprise e-commerce data，Of course, I will email you later

2、Ali Cloud, self-built cloud，About 8TiB per month

**Comment by lindazhuang123** [comment]
1、Enterprise e-commerce data，Of course.

2、Ali Cloud, self-built cloud，About 8TiB per month

DataDemo:

https://user-images.githubusercontent.com/79966014/111432078-85a3fd00-8737-11eb-9f25-ef5d82d0b809.mp4

**Comment by lindazhuang123** [comment]
1、Enterprise e-commerce data，Of course
Data Demo:
![G31](https://user-images.githubusercontent.com/79966014/111432939-a02aa600-8738-11eb-9acc-a966bed53e14.jpeg)


2、Ali Cloud, self-built cloud，About 8TiB per month

**Comment by ozhtdong** [comment]
Hi. 
I also want to know more about your allocation strategy.

1.How many miners do you want to store your data to? How much data for each miner? 
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect? 
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by lindazhuang123** [comment]
Hi,ozthdong

1.If approved, I will divide the 5TB data capacity equally between three miners.

2.Yes,I will paste a screenshot of the assignment information on the GitHub conversation page.

3.I already know some of the miners.I will make my choice based on the miner's power and the blocks mined.

4.Never.


THANKS

**Comment by ozhtdong** [comment]
Thanks for your information.
The last step, please show me your company searching consequence in the local business license searching website.

**Comment by lindazhuang123** [comment]
Here is our  searching consequence
<img width="1238" alt="截屏2021-03-18 上午11 29 29" src="https://user-images.githubusercontent.com/79966014/111569285-4cbe6380-87dd-11eb-9a60-6b487cda54fb.png">
