### ISSUE TITLE
Client Allocation Request for: shh

### ISSUE THREAD

**Issue by Cats-On-Mars** [filecoin-project/filecoin-plus-client-onboarding#2298]
---

# Client Allocation Questions 

## Core Information
- Name: shh
- Website / Social Media: slack: shh
- Region: North America
- DataCap Requested: 1TiB
- Addresses to be Notarized: f1ssft3rqegbn3l4foo6yfklr2qxs7pwgfcdidnzq
- Notary Requested: PluskitOfficial

@Cats-On-Mars Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by PluskitOfficial** [comment]
Hi, @Cats-On-Mars happy to receive your application and welcome to Filecoin. Please anwser following questions.
1.Are you an individual or a business/organization? If an individual, please specify the name, date of birth, and nationality; if a company/organization, please specify the company name, registration time, and registration area. At the same time, please provide the corresponding supporting documents (individuals provide ID cards, enterprises/organizations provide licenses, which can be sent by E-mail. Our email adress is pluskitofficial@163.com).
2.What is your industry? What data will be stored? How much do you plan to store? Can the data be made public (if not, are we allowed to conduct random checks at any time?)
3.Please share information and relevant supporting documents or links that illustrate your industry status.
4.Did you get any honors? Please provide relevant supporting documents or links.
5.Please provide your social media account and indicate the number of followers.
6.Please describe the duration of your involvement in your industry and give a brief description of your industry.
7.Please specify the storage location, miner ID and storage proportion of your data to be stored. We require any data to be stored on the same node no more than 30% of the same batch of DataCap acquisitions.
8.If you get a DataCap, do you agree to send the storage record back here within 15 days of storage?
9.Did you get a DataCap? If yes, please attach all application links and inform the current remaining amount.

**Comment by raghavrmadya** [comment]
No response. Please open a new application.
