### ISSUE TITLE
Client Allocation Request for: dlahum

### ISSUE THREAD

**Issue by goodvvvboogg** [filecoin-project/filecoin-plus-client-onboarding#2308]
---

# Client Allocation Questions 

## Core Information
- Name: dlahum
- Website / Social Media: http://www.dlahum.cn/
- Region: Greater China Region
- DataCap Requested: 1TiB
- Addresses to be Notarized: f17hw3txvdmzid3xaa7cn7eee7rxg3m3tbjdirv7i
- Notary Requested: MRJAVAZHAO

@goodvvvboogg Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MRJAVAZHAO** [comment]
@goodvvvboogg Please provide the following materials.

if you are an organization, Please describe your organization, such as established time, business scale, social media accounts&follwers, the number of employees, users volumn and business license (could be sent by email, [1625821971@qq.com](mailto:1625821971@qq.com)); if you are an individual, please provide name, date of birth, working company and scale, employment certificate, social media accounts&follwers, and ID card (can be sent by email, [1625821971@qq.com](mailto:1625821971@qq.com));

When did you start learning about Filecoin? Please give a description about the projects you have participated in ? What do you want to get from Filecoin? Any suggestions or expectations for the Filecoin Network?

Is there any law risk? What percentage of questions are yours?

How about your data volume, source and later planning? Please describe the type, format, source, storage capacity, publicity (and if data could be public, how can others retrieve it?) of the data to be stored in Filecoin.

In which area do you plan to store you data? How many miners do you want to find ? Please list the miner ID. How about the proportion of the storage for each miner? What are the requirements about miners? At last, please state your redundancy plan.

Do you agree to disclose transaction information? If you get DataCap, please make the transaction information public on the Issue in time.

**Comment by goodvvvboogg** [comment]
I am a freelancer, You can call me wang, and you can find me in https://github.com/doctorwangliua.

I have known about Filecoin since last March and do some develop work about Filecoin mining. Most sectors in Filecoin are CC sectors that waste to much, How to store real data needs to be considered.

There is no legal risk.

I am building a data service application, The data comes from public information on public websites, including structured data and unstructured data.

Amount of data: about 1T
Data format: Unstructured data
All data is publicly available.

Miner: no restrictions on storage areas and I hope to find more than three miners, require miners to ensure full data security.

I agree.

**Comment by MRJAVAZHAO** [comment]
If you are an individual, please provide name, date of birth, working company and scale, employment certificate, social media accounts&follwers, and ID card (can be sent by email, [1625821971@qq.com](mailto:1625821971@qq.com));
Can you provide some data samples of the data you will store? Or share the data service application to me?

**Comment by claydrone** [comment]
> I am a freelancer, You can call me wang, and you can find me in https://github.com/doctorwangliua.
> 
> I have known about Filecoin since last March and do some develop work about Filecoin mining. Most sectors in Filecoin are CC sectors that waste to much, How to store real data needs to be considered.
> 
> There is no legal risk.
> 
> I am building a data service application, The data comes from public information on public websites, including structured data and unstructured data.
> 
> Amount of data: about 1T Data format: Unstructured data All data is publicly available.
> 
> Miner: no restrictions on storage areas and I hope to find more than three miners, require miners to ensure full data security.
> 
> I agree.

hello Wang ,I just know GitHub a a freelancer and just sign up recently as well.
And I am interested if you have a code repo

**Comment by MRJAVAZHAO** [comment]
Please open it when you want to apply again.
