### ISSUE TITLE
Client Allocation Request for: KIMS-KOREA

### ISSUE THREAD

**Issue by domms9911** [filecoin-project/filecoin-plus-client-onboarding#2313]
---

# Client Allocation Questions 

## Core Information
- Name: KIMS-KOREA
- Website / Social Media: WWW.KIMS-KOREA.CO.KR
- Region: Asia (excl. Greater China)
- DataCap Requested: 50TiB
- Addresses to be Notarized: f1ll4zafrefwklbuwbuptmz67ifemc62xapfaqm3q
- Notary Requested: psh0691

@domms9911 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by raghavrmadya** [comment]
Please update another open app with the total app requested.
