### ISSUE TITLE
Client Allocation Request for: 上海大智慧基金销售有限公司

### ISSUE THREAD

**Issue by Jyyyy7** [filecoin-project/filecoin-plus-client-onboarding#233]
---

# Client Allocation Questions 

## Core Information
- Name: 上海大智慧基金销售有限公司
- Website / Social Media: https://www.wg.com.cn/
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1rlmxljkvuazvtneoppo47anprg44gjandqniw6q
- Notary Requested: Fenbushi-Filecoin

**Comment by Fenbushi-Filecoin** [comment]
> # Client Allocation Questions
> ## Core Information
> * Name: 上海大智慧基金销售有限公司
> * Website / Social Media: https://www.wg.com.cn/
> * Region: Greater China
> * DataCap Requested: 10TiB
> * Addresses to be Notarized: f1rlmxljkvuazvtneoppo47anprg44gjandqniw6q
> * Notary Requested: Fenbushi-Filecoin

We have published our Client onboarding guidelines (Filecoin plus notary) on GitHub. Please check our link https://github.com/filecoin-project/filecoin-plus-client-onboarding/tree/main/Fenbushi%20Capital.
