### ISSUE TITLE
Client Allocation Request for: blubluck

### ISSUE THREAD

**Issue by BLUBLUCK** [filecoin-project/filecoin-plus-client-onboarding#2334]
---

# Client Allocation Questions 

## Core Information
- Name: blubluck
- Website / Social Media: blubluck.com
- Region: Asia (excl. Greater China)
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3vfiwqzmfevdbmrxiha6v4buspmfoo3xgqrjy7odbh66y3jecpnaqsqvt2bvnipn4lc46d3yikaictgsunuvq
- Notary Requested: Alex11801

@BLUBLUCK Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by raghavrmadya** [comment]
Update this application with the total amount of DC requested. Other applications have been closed.
