### ISSUE TITLE
Client Allocation Request for: siart

### ISSUE THREAD

**Issue by bongsu11** [filecoin-project/filecoin-plus-client-onboarding#2335]
---

# Client Allocation Questions 

## Core Information
- Name: siart
- Website / Social Media: https://siart.swiss/en/areas/
- Region: Europe
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1raq3tbv6k2keotawldn2gmf5ygxu2n72dohfsji
- Notary Requested: cryptowhizzard

@bongsu11 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by cryptowhizzard** [comment]
Hello @bongsu11 

Can you please contact me on slack (wijnandschouten) . 

Can you let me know what kind of data is stored? Are the owners of the website involved / aware?

**Comment by cryptowhizzard** [comment]
Hello? Please respond.
