### ISSUE TITLE
Client Allocation Request for: [Personal or Organization Name]

### ISSUE THREAD

**Issue by wqy2706113** [filecoin-project/filecoin-plus-client-onboarding#2338]
# Client Allocation Questions 

## Core Information
- Name: qianyi wan
- Website / Social Media: [Evidence of Real world Identity]
- Region: china
- DataCap Requested: 1
- Addresses to be Notarized: [fxxxx OR TBD]
- Notary Requested: [choose one notary]

-------------------------

**Comment by Carohere** [comment]
@raghavrmadya flagging this app
