### ISSUE TITLE
Client Allocation Request for: NAPAI

### ISSUE THREAD

**Issue by zhuyinjieigoe** [filecoin-project/filecoin-plus-client-onboarding#2381]
---

# Client Allocation Questions 

## Core Information
- Name: NAPAI
- Website / Social Media:  https://beijing.napai.cn/
- Region: Greater China Region
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1y7qv5fxkowmyf7wqffrlfnmdvdmzddrct2het3i
- Notary Requested: steven004

@zhuyinjieigoe Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by steven004** [comment]
Hey @zhuyinjieigoe , would you please provide the deal list for #2149 ? so that we could go through the validation process before moving forward, thanks.

**Comment by zhuyinjieigoe** [comment]
@steven004 Hi Steven, this shoud be the list you need. 
![image](https://user-images.githubusercontent.com/108451806/186861868-ad3040f5-0d03-4d18-8fb0-3c3831a1e8b2.png)

**Comment by steven004** [comment]
I'm closing this one. 
It's most likely one applier submitted a few applications. 

Please submit a new one if you think you still need datacap, I will request more information to validate the legality of the applications. Sorry for the inconvenience.
