### ISSUE TITLE
Client Allocation Request for: BLOCK GLOBAL

### ISSUE THREAD

**Issue by liyanhahahah** [filecoin-project/filecoin-plus-client-onboarding#2383]
---

# Client Allocation Questions 

## Core Information
- Name: BLOCK GLOBAL
- Website / Social Media: https://www.blockglobal.pro/
- Region: Greater China Region
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1joqydiliofrcmvktxzump6bnnnjt6ttxo3ovq3i
- Notary Requested: steven004

@liyanhahahah Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by liyanhahahah** [comment]
@steven004 Hi, this request hadn't got update before it was closed #2108. Could you check it out? Thanks!

**Comment by liyanhahahah** [comment]
@steven004 Hi any updates here? Thx

**Comment by steven004** [comment]
Closing this one due to a doubt of multiple applications submitted by one applier.
