### ISSUE TITLE
Client Allocation Request for: Big Nautical Image

### ISSUE THREAD

**Issue by huangwenfengwieng** [filecoin-project/filecoin-plus-client-onboarding#2384]
---

# Client Allocation Questions 

## Core Information
- Name: Big Nautical Image
- Website / Social Media: https://www.0755dhh.com/
- Region: Greater China Region
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1znansfgebzncmf6whw6rp5ix3quovunyf2jqquy
- Notary Requested: steven004

@huangwenfengwieng Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by huangwenfengwieng** [comment]
@steven004 Hi notary, this request hadn't seen responses until it was closed #2144. Please have a look and feel free to ask for information. Thanks!

**Comment by huangwenfengwieng** [comment]
@steven004 Hi this request needs progress. Please have a look thx~

**Comment by steven004** [comment]
Closing this one due to a doubt of multiple applications submitted by one applicant.
