### ISSUE TITLE
Client Allocation Request for: Decentral Tech

### ISSUE THREAD

**Issue by DecentralTech** [filecoin-project/filecoin-plus-client-onboarding#239]
---

# Client Allocation Questions 

## Core Information
- Name: Decentral Tech
- Website / Social Media:https://ipfsdrop.com/
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1e3vyhnfmpnetodevdky5vkfp6qmrhzidgjvnana
- Notary Requested: ozhtdong

**Comment by ozhtdong** [comment]
Thanks for your application. I want to know more basic information of you and your company. Please answer following question:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?

**Comment by ozhtdong** [comment]
We are still discussing whether to accept the miners' request or not. And I will get back to you if any decision.
