### ISSUE TITLE
Client Allocation Request for: renderhelp

### ISSUE THREAD

**Issue by Cats-On-Mars** [filecoin-project/filecoin-plus-client-onboarding#2394]
---

# Client Allocation Questions 

## Core Information
- Name: renderhelp
- Website / Social Media: http://www.renderhelp.com
- Region: Greater China Region
- DataCap Requested: 3TiB
- Addresses to be Notarized: f17tfc4dkjfohvwwzlwnf5xuhqascym27puurrxea
- Notary Requested: MasaakiNawatani

@Cats-On-Mars Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MasaakiNawatani** [comment]
Hi @Cats-On-Mars thanks for reaching out. I believe this is best handled by a Notary in the Greater China Region. Please resubmit your request again. Thank you.

**Comment by Cats-On-Mars** [comment]
ok, thank you
