### ISSUE TITLE
Client Allocation Request for: the9

### ISSUE THREAD

**Issue by serafimey** [filecoin-project/filecoin-plus-client-onboarding#240]
---

# Client Allocation Questions 

## Core Information
- Name: the9
- Website / Social Media: www.the9.com
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1bodegkwcdjofy55wli23jidxg2v3wbftrg3itey
- Notary Requested: ozhtdong

**Comment by ozhtdong** [comment]
Thanks for your application. I want to know more basic information of you and your company. Please answer following question:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?

**Comment by serafimey** [comment]
thanks for your reply. I am glad to introduce my company and I here.

My name is 朱皓 as “tony” , the BD director of The9 Limited。I was in charge of  business development department。
The9 Limited (The9) is an Internet company based in China listed on Nasdaq in 2004. The9 aims to become a diversified high-tech Internet company. The9 has stepped into blockchain-related business in 2018。And The9 signed a legally binding cooperation and Investment term sheet with cryptocurrencies mining investors led by Jianping Kong to start the cryptocurrencies business。
I have a Weibo account：https://weibo.com/24709697/
I will send you the business license through the e-mail

**Comment by ozhtdong** [comment]
Hi.

I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency? Could you please show me your cloud usage evidence?

**Comment by serafimey** [comment]
1: Video ( video of game streaming), pictures (game arts, commodity, advertisement, ), access log data, etc. Over 100 TiB.
I will send you the demo through the e-mail.
2:Our company always use cloud, such as Ali Cloud,We used Ali Cloud 10T/month.

**Comment by ozhtdong** [comment]
Thanks for your quick response. I also want to know more about your allocation strategy.

1.How many miners do you want to store your data to? How much data for each miner? 
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect? 
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by serafimey** [comment]
1. We want to store our data to 2-3 miners who are active in the community. We will not store data on one miner above 70%.
2. Yes. We will record our allocation decision in public, in Github.
3. We will find the miners who are active in the community.and we will inspect miners' storage space, past status of fault and recovery sectors,  seal speed, industry reputation .
4. No.

**Comment by ozhtdong** [comment]
Hi. @serafimey 
Thanks for your information.
The last step, please show me your company searching consequence in the local business license searching website.

**Comment by ozhtdong** [comment]
Hi, since your company is a listed company, I would love to give you 10 TiB.

You can find your score here:

https://docs.qq.com/sheet/DVnlmRWlod0p3eXd6

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec26tq56rufpy4tt5sgcd3zuqoq2d3takp3f4lo3p2nnanufstjg2 
#### Address 
> f1bodegkwcdjofy55wli23jidxg2v3wbftrg3itey
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec26tq56rufpy4tt5sgcd3zuqoq2d3takp3f4lo3p2nnanufstjg2
