### ISSUE TITLE
Client Allocation Request for: Jingyi

### ISSUE THREAD

**Issue by Foster15** [filecoin-project/filecoin-plus-client-onboarding#2433]
---

# Client Allocation Questions 

## Core Information
- Name: Jingyi
- Website / Social Media: https://www.jing-yi.com.cn/
- Region: Greater China Region
- DataCap Requested: 50TiB
- Addresses to be Notarized: f1pj6n7u2e4opxgmovmsu4vyw6cimgds3razxeaxi
- Notary Requested: 1475Notary

@Foster15 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by 1475Notary** [comment]
Thanks for the request! Please answer the following questions giving as much detail as possible.
1. Please introduce yourself and the organization you represent, what is its name, nature, country of incorporation and date of establishment?
2. How many employees does the company currently have?
3. In which region do you plan to use DataCap?
4. How did you hear about the FIL+ project?
5. What kind of data do you plan to store? Can you share any kind of sample data?
6. Please provide the business license of your company.
7. Are you willing to store data outside of Greater China?

**Comment by Foster15** [comment]
Thanks @1475Notary. 
1. My name is Sam, working in the infomation vision of Jingyi. Our full company name is Jingyi Information Technology Co. It was founded in 2014 and has been engaged in high-end website design and production, network operation and promotion, HTML5 responsive website development, mobile website and app for 8 years.
2. Around 70.
3. Greater China.
4. From fellow technology business partner. 
5. Most are images and videos. Maybe some code after we confirm the security of here. 
6. We would like to send you in person. 
7. Yes.

**Comment by Foster15** [comment]
Thanks @1475Notary.

1. My name is Foster, working in the infomation vision of Jingyi. Our full company name is Jingyi Information Technology Co. It was founded in 2014 and has been engaged in high-end website design and production, network operation and promotion, HTML5 responsive website development, mobile website and app for 8 years.
2. Around 70.
3. Greater China.
4. From fellow technology business partner.
5. Most are images and videos. Maybe some code after we confirm the security of here.
6. We would like to send you in person.
7. Yes.

**Comment by 1475Notary** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec3dzcxygq7q4vdf2ujtorqkwecltj754y6qjyblkmbmkq32ebhx6 
#### Address 
> f1pj6n7u2e4opxgmovmsu4vyw6cimgds3razxeaxi
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec3dzcxygq7q4vdf2ujtorqkwecltj754y6qjyblkmbmkq32ebhx6
