### ISSUE TITLE
Client Allocation Request for: My Offer

### ISSUE THREAD

**Issue by Sandy9032** [filecoin-project/filecoin-plus-client-onboarding#2439]
---

# Client Allocation Questions 

## Core Information
- Name: My Offer
- Website / Social Media: www.myoffer.com
- Region: Greater China Region
- DataCap Requested: 30TiB
- Addresses to be Notarized: f15ivaxfcnyyb26wds6dfaxluxnye6qjysqfbapba
- Notary Requested: swatchliu

@Sandy9032 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Sandy9032** [comment]
@swatchliu Hello notary, I used to apply datacap from you. https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/1895 Hope you can agree this application!

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.),
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?
Would you like to submit more company information on [www.bytebase.cn](http://www.bytebase.cn/)?
Would you like to accept our face-to-face visit?

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecorrvv3wydbik4yuxhmxzzbhukoupz4vhngvlmsdecrgpluh67ne 
#### Address 
> f15ivaxfcnyyb26wds6dfaxluxnye6qjysqfbapba
#### Datacap Allocated
> 30.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecorrvv3wydbik4yuxhmxzzbhukoupz4vhngvlmsdecrgpluh67ne
