### ISSUE TITLE
Client Allocation Request for: Etile

### ISSUE THREAD

**Issue by Etile0** [filecoin-project/filecoin-plus-client-onboarding#2455]
---

# Client Allocation Questions 

## Core Information
- Name: Etile
- Website / Social Media: https://keybase.io/Etile0
- Region: Europe
- DataCap Requested: 20TiB
- Addresses to be Notarized: f1shjlc4hfvgvo2a25htew5g4ow2la6hlyei663vy
- Notary Requested: cryptowhizzard

@Etile0 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by cryptowhizzard** [comment]
Hi There,

Thanks for your application!

Can you tell me what data you want to store on filecoin? What is your relationship with Keybase?

**Comment by Etile0** [comment]
Hello!

Keybase is just a secure messaging platform I use, it's not a website I own.

I would like to use filecoin to store some encrypted personal data (backups and such) and probably some videos and/or music me or my friends make which we want to archive (most of that is probably going to be unencrypted)

Thank you for your reply!
