### ISSUE TITLE
Client Allocation Request for: Ruten

### ISSUE THREAD

**Issue by west621** [filecoin-project/filecoin-plus-client-onboarding#2460]
---

# Client Allocation Questions 

## Core Information
- Name: Ruten
- Website / Social Media: https://www.ruten.com.tw/
- Region: Greater China Region
- DataCap Requested: 30TiB
- Addresses to be Notarized: f14kmgzplvwg2zsv4m544f35kauvc7b5bufh7evjq
- Notary Requested: 1475Notary

@west621 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by 1475Notary** [comment]
Thanks for the request! Please answer the following questions giving as much detail as possible.

Please introduce yourself and the organization you represent, what is its name, nature, country of incorporation and date of establishment?
How many employees does the company currently have?
In which region do you plan to use DataCap?
How did you hear about the FIL+ project?
What kind of data do you plan to store? Can you share any kind of sample data?
Please provide the business license of your company.
Are you willing to store data outside of Greater China?

**Comment by west621** [comment]
@1475Notary Thanks for getting back to us. 
1. Ruten market/Open air auction is a joint venture of PChome Online and eBay. Our official site ruten.com was launched in September 2006 and is the most popular auction site in Taiwan, as well as the AI e-commerce platform with the largest number of members and a wide variety of items. Our official name is PChome eBay Co., Ltd, registered in Taiwan, China on August 10, 2006. I'm Emma working in international cooperation department. Due to language issues, I was asked by the technical department on behalf of our company to make this application.
2. Approximately 220 employees. 
3. Greater China. 
4. In April 2019 through joint development and cooperation with both eBay teams in technology and services, we launched " platform-integrated cross-border e-commerce to import items from eBay in the U.S. In July, we also introduced Japan Lottee into our platform. The ultimate goal of the Internet is to synchronize with the world's information. As the world's first platform to enable innovative cross-border e-commerce, our need for storage is growing. We have learned about various storage methods through the technical department. Filecoin is a new and innovative method that we have recently learned about. We are not too familiar with decentralized storage and will compare it carefully with cloud storage through this application.
5. Item pictures and videos.
6. Because we don't know much about filecoin, we don't feel comfortable disclosing the license. We have sent it to you privately through the email that the system informed us in the application.
7. Yes. 
8. 
Please let me know if there's anything more you would like to know about our company. Thanks!

**Comment by 1475Notary** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebrdoug7malqonltfkjrkjbkshgcveeovuuwe2244gzppvvfdrhx4 
#### Address 
> f14kmgzplvwg2zsv4m544f35kauvc7b5bufh7evjq
#### Datacap Allocated
> 30.00TiB
#### Signer Address
> f1ofq4mngy7ggcp755pfquq2gphjjnlydolf6awtq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebrdoug7malqonltfkjrkjbkshgcveeovuuwe2244gzppvvfdrhx4
