### ISSUE TITLE
Client Allocation Request for: Chomsio

### ISSUE THREAD

**Issue by EmilyChom** [filecoin-project/filecoin-plus-client-onboarding#2473]
---

# Client Allocation Questions 

## Core Information
- Name: Chomsio
- Website / Social Media: https://chomsio.com/
- Region: Greater China Region
- DataCap Requested: 50TiB
- Addresses to be Notarized: f1kpnihqdtmp5lh636rnjbje7xkdn4gek7conxvny
- Notary Requested: swatchliu

@EmilyChom Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.),
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?
Would you like to submit more company information on [www.bytebase.cn](http://www.bytebase.cn/)?
Would you like to accept our face-to-face visit?

**Comment by EmilyChom** [comment]
Thanks for your quick response. Yes, our company is located in China.
Duration of establishment,
1 year and 8 months.
Number of employees,
10-15.
Business scope and products or services, 
Chomsio is an artist owned and operated  brand offering a fun selection of gifts and apparel for men, women, and kids. Our products are designed and hand printed in our  using eco-friendly water-based inks. We focus on the western market and We aim to create High-quality affordable products featuring on-trend with original designs. 
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.),
Due to the targeting market is different, we don't have any regular media. You can check more on our website and blogs. https://chomsio.com/blogs/why-people-choose-custom-shirts-the-top-5-reasons
Data size to be stored,
Around 50TiB.
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?
No
Would you like to submit more company information on http://[www.bytebase.cn](http://www.bytebase.cn/)/?
Yes
Would you like to accept our face-to-face visit?
Yes. You can contact us through support@chomsio.com for more information. Please mention Filecoin in the email subject and schedule the visit at least three weeks earlier.

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamjrvlf5dqrz66jsxoh3tpqjj5t6crx7ajqnzuj7ujtz272npahq 
#### Address 
> f1kpnihqdtmp5lh636rnjbje7xkdn4gek7conxvny
#### Datacap Allocated
> 50.00TiB
#### Signer Address
> f1yh6q3nmsg7i2sys7f7dexcuajgoweudcqj2chfi
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamjrvlf5dqrz66jsxoh3tpqjj5t6crx7ajqnzuj7ujtz272npahq
