### ISSUE TITLE
Client Allocation Request for: Kitchenidea

### ISSUE THREAD

**Issue by MI1ca** [filecoin-project/filecoin-plus-client-onboarding#2478]
---

# Client Allocation Questions 

## Core Information
- Name: Kitchenidea
- Website / Social Media: http://www.kitchenidea.com.cn/
- Region: Greater China Region
- DataCap Requested: 30TiB
- Addresses to be Notarized: f16b66qtvazuwx2wan324oe2fuzv3gtzazjq5kzgy
- Notary Requested: PluskitOfficial

@MI1ca Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by PluskitOfficial** [comment]
Hi, @MI1ca  happy to receive your application and welcome to Filecoin. Please anwser following questions.
1.Are you an individual or a business/organization? If an individual, please specify the name, date of birth, and nationality; if a company/organization, please specify the company name, registration time, and registration area. At the same time, please provide the corresponding supporting documents (individuals provide ID cards, enterprises/organizations provide licenses, which can be sent by E-mail. Our email adress is [pluskitofficial@163.com](mailto:pluskitofficial@163.com)).
2.What is your industry? What data will be stored? How much do you plan to store? Can the data be made public (if not, are we allowed to conduct random checks at any time?)
3.Please share information and relevant supporting documents or links that illustrate your industry status.
4.Did you get any honors? Please provide relevant supporting documents or links.
5.Please provide your social media account and indicate the number of followers.
6.Please describe the duration of your involvement in your industry and give a brief description of your industry.
7.Please specify the storage location, miner ID and storage proportion of your data to be stored. We require any data to be stored on the same node no more than 30% of the same batch of DataCap acquisitions.
8.If you get a DataCap, do you agree to send the storage record back here within 15 days of storage?
9.Did you get a DataCap? If yes, please attach all application links and inform the current remaining amount.

**Comment by MI1ca** [comment]
Hi, @PluskitOfficial very glad to receive your reply. Here are our answers.
1. Zhejiang Kitchen Idea Technology Co., Ltd., founded in 2011, is a technology enterprise focusing on AI intelligent technology and highly integrated technology, headquartered in Binjiang District, Hangzhou City, Zhejiang Province.
The relevant supporting documents have been sent to you via email.
2. Kitchenidea is a leading brand in the cooking robot industry, integrating AI intelligence, Internet and IoT technology.
We currently have about 1.5PiB of data, and we plan to store 30TiB at first. The planned data storage includes public data such as brand publicity, product graphics/videos, and user feedback.
3. Kitchenidea currently occupies more than 70% of the foreign market.
4. We have received many honors.
In 2020, we won the title of 2020 Hangzhou export famous brand
In March 2021, chairman Fang Zhihua won the best practice case award and the TOP10 most potential young entrepreneurial leaders of zhejiang businessmen awards at the annual awards ceremony of times Zheshang.
https://baijiahao.baidu.com/s?id=1695546947026937850&wfr=spider&for=pc
In December 2021, we won the 2021 China Home Appliance Industry Rock Award - Industry Leading Award
https://baijiahao.baidu.com/s?id=1718722733288545236&wfr=spider&for=pc
![1](https://user-images.githubusercontent.com/106941803/190392432-0d9dacdb-4e82-4c29-be01-82309907f08d.jpg)
![2](https://user-images.githubusercontent.com/106941803/190392449-df3e4472-80ff-49e5-a477-66f7cfe7ad0f.png)
![3](https://user-images.githubusercontent.com/106941803/190392462-35273cd4-20fd-4201-9353-2548b61df67a.png)

5.We have 63,000 followers on Weibo
      Weibo：田螺云厨
6.Kitchenidea is the head brand of cooking robot industry. Through the cutting-edge Internet technology IoT, it provides consumers with intelligent and convenient technology kitchen new experience and makes cooking more relaxed.
7.We will store the storage in mainland China, and the storage ratio of the same node will not exceed 30%. 
      We now have no cooperative node but we would find the storage node through 
      friends' introduction and other ways.
8.Yes, we agree.
9.None.

**Comment by PluskitOfficial** [comment]
@MI1ca Glad to have companies like yours to Filecoin/IPFS. After vetting, we agree to your application. However, there are several points for attention before approval, please confirm again:

- Ensure that the storage ratio of one node does not exceed 30%. Storage nodes can be found via Slack.

- Please be sure to send the storage record back here within 15 days after storage.

- Re-request DataCap only if the remaining DataCap is less than 25% of the your  total data.

**Comment by MI1ca** [comment]
Thank you! @PluskitOfficial 
We confirm the storage ratio of one node will not exceed 30% and will put our storage record here in time.

**Comment by MI1ca** [comment]
@PluskitOfficial Thank you so much! 
We have received the DataCap.
