### ISSUE TITLE
Client Allocation Request for: Penglaiju

### ISSUE THREAD

**Issue by PengLaiJu2017** [filecoin-project/filecoin-plus-client-onboarding#2484]
---

# Client Allocation Questions 

## Core Information
- Name: Penglaiju
- Website / Social Media: http://www.weiminsu.cn/
- Region: Greater China Region
- DataCap Requested: 50TiB
- Addresses to be Notarized: f1cuboogcwais57dljrpeltoy6ja2itb7wvwmrl3q
- Notary Requested: PluskitOfficial

@PengLaiJu2017 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by PluskitOfficial** [comment]
Hi, @PengLaiJu2017  happy to receive your application and welcome to Filecoin. Please anwser following questions.
1.Are you an individual or a business/organization? If an individual, please specify the name, date of birth, and nationality; if a company/organization, please specify the company name, registration time, and registration area. At the same time, please provide the corresponding supporting documents (individuals provide ID cards, enterprises/organizations provide licenses, which can be sent by E-mail. Our email adress is [pluskitofficial@163.com](mailto:pluskitofficial@163.com)).
2.What is your industry? What data will be stored? How much do you plan to store? Can the data be made public (if not, are we allowed to conduct random checks at any time?)
3.Please share information and relevant supporting documents or links that illustrate your industry status.
4.Did you get any honors? Please provide relevant supporting documents or links.
5.Please provide your social media account and indicate the number of followers.
6.Please describe the duration of your involvement in your industry and give a brief description of your industry.
7.Please specify the storage location, miner ID and storage proportion of your data to be stored. We require any data to be stored on the same node no more than 30% of the same batch of DataCap acquisitions.
8.If you get a DataCap, do you agree to send the storage record back here within 15 days of storage?
9.Did you get a DataCap? If yes, please attach all application links and inform the current remaining amount.

**Comment by PengLaiJu2017** [comment]
1.Are you an individual or a business/organization? If an individual, please specify the name, date of birth, and nationality; if a company/organization, please specify the company name, registration time, and registration area. At the same time, please provide the corresponding supporting documents (individuals provide ID cards, enterprises/organizations provide licenses, which can be sent by E-mail. Our email adress is [pluskitofficial@163.com](mailto:pluskitofficial@163.com)).
```
Penglaiju is a professional short-term rental agency affiliated to Beijing Yiqun Information Technology Co., Ltd. As a senior Internet expert and homestay expert, Penglaiju has divided urban homestays or country homestays into two parts: online hosting and offline hosting, to provide homestay owners with the operation management of the online platform and the promotion and operation of each platform to maximize the customer's house to stand out in the market and increase the occupancy rate.
Beijing Yiqun Information Technology Co., LTD., founded in 2009, located in Beijing, is a software and information technology services based enterprises.  The registered capital of the enterprise is 1 million RMB, and the paid-in capital is 1 million RMB.
```
2.What is your industry? What data will be stored? How much do you plan to store? Can the data be made public (if not, are we allowed to conduct random checks at any time?)
```
Penglaiju has been engaged in the Internet industry for more than ten years, and has many experienced Internet experts. In terms of network marketing and brand promotion, Penglaiju can establish resource advantages that ordinary landlords do not have for customers to invest in homestay.
We will mainly store photos and videos of some houses and the surrounding environment since 2017.
In addition, we will also try to store part of the online system access and business data after desensitization.
We are going to store 2PiB of public dataset
```
3.Please share information and relevant supporting documents or links that illustrate your industry status.
```
In 2017, Penglaiju started the exploration of urban homestays in Xi'an, the first homestay city to test the water. At present, the operation of these homestays is stable. Under the condition of low initial investment cost, the occupancy rate has been about 85%, and the monthly turnover is about 100,000.
```
4.Did you get any honors? Please provide relevant supporting documents or links.
```
It's our honor to have no complaints
```
5.Please provide your social media account and indicate the number of followers.
```
We provide software services for companies that have followers
```
6.Please describe the duration of your involvement in your industry and give a brief description of your industry.
```
Penglaiju mainly provides homestay management system, which provides customers with personalized independent brand, completely independent website management, easy maintenance without technology, multi-terminal support and other services. 
1.Home Stay Room Supply Management: quickly edit and release rooms through background listing management and manage room status with visual calendar.
2.User Order Management: convenient and fast order management and order notification function; strong membership system.
3.Local Specialty Mall: combine the characteristics of local homestays to promote local specialty products; users can easily purchase local specialty products.
4.Personalized Independent Brand: independent website that can bind independent domain name and design brand LOGO.
5.Multi-Terminal Integration: PC/ HTML5 / Official Account /APP
6.WeChat Marketing: built-in HTML5 version, which can quickly access Official Accounts and small programs.
```
7.Please specify the storage location, miner ID and storage proportion of your data to be stored. We require any data to be stored on the same node no more than 30% of the same batch of DataCap acquisitions.
```
We will store the data in China, we have already cooperated with service providers before, we will look for more SPs to ensure the storage in accordance with the allocated proportion.
```
8.If you get a DataCap, do you agree to send the storage record back here within 15 days of storage?
```
Yes
```
9.Did you get a DataCap? If yes, please attach all application links and inform the current remaining amount.
```
We applied for LDN
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/400
```

**Comment by PengLaiJu2017** [comment]
@PluskitOfficial We hope to receive your reply as soon as possible

**Comment by PluskitOfficial** [comment]
Hi, @PengLaiJu2017  there are two more questions, please confirm in time:
1. Please provide descriptions and supporting documents related to industry reputation, such as industry status, honor level, social media and followers.
2. You said you have applied for LDN, why do you still want to apply for DataCap in this way?
