### ISSUE TITLE
Client Allocation Request for: China Tianying INC.

### ISSUE THREAD

**Issue by HowardAce** [filecoin-project/filecoin-plus-client-onboarding#2485]
---

# Client Allocation Questions 

## Core Information
- Name: China Tianying INC.
- Website / Social Media: https://www.ctyi.com.cn/index.html
- Region: Greater China Region
- DataCap Requested: 60TiB
- Addresses to be Notarized: f14uxcyaoab3qhn42kaquqysga6f6zfry3x4nk3ca
- Notary Requested: MatrixStorage

@HowardAce Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MatrixStorage** [comment]
Hey @HowardAce, thank you for choosing IPFS. In order to ensure that I know enough about your company, please reply to my following questions, so that I can correctly judge whether DC can be assigned to you.
- Could you please introduce the term, nature and scale of your company in detail?
```
```
- What industries/how many people does the company mainly serve?
```
```
- Can you tell me about your future business or technology plans?
```
```
- Can you explain the data type and copyright ownership in detail?    How much data does your company store?
```
```
- Does your company need to invoke stored data, and if so, how often does this happen?
```
```
- How many miners do you want to select to store data?    How many DataCap will be assigned to each miner?
```
```
Looking forward to your reply.

**Comment by HowardAce** [comment]
Thanks.
- Could you please introduce the term, nature and scale of your company in detail?
```
China Tianying Inc.(stockcode:000035)(hereinafter referred to as“CNTY”)is a listed international company engaged in zero-carbon clean energy technologies, smart urban environmental services and resource recycling and recovery.

China Tianying (CNTY) is an international environmental management corporation. Our urban service is featuring a “5A” model—All settings, All types, All smart, All processes, All treatments—covering the entire industrial chain of solid waste management. Our businesses extend from industrial R&D, urban services, waste disposal, equipment manufacturing to developing intelligent management platforms. With global wisdom and professional expertise at our disposal, we are committed to further improving the environment and recycling the resources on our planet.
```
- What industries/how many people does the company mainly serve?
```
Our scope of business expands from smart urban environmental services, Waste-to-Energy power generation, renewable energy power generation, regional enerqy centers, hydrogen energy centers, the investment, construction, and operation of circular economy industrial parks, to the reduction, recycling, and harmless treatment of kitchen waste, hazardous waste, construction, and demolition waste, as well as the research, development, and manufacturing of environmental protection equipment and energy storage systems.
```
- Can you tell me about your future business or technology plans?
```
Driven by innovation and backed by top-notch equipment manufacturing and R&D capabilities, CNTY strives to lead renewable energy upgrades and business model transformation through information, automation, and industrialization solutions including plasma technology, automated sorting system, environmental service cloud platform, zero-carbon energy network centers, and smart loT centers, making due contribution to the objectives for carbon peaking and carbon neutrality of China.

Leveraging our advanced technologies, global talent pool, and capital resources, CNTY cultivates the renewable energy industry through designing, investing, constructing, and operating activities in the fields of distributed photovoltaic systems, nearshore photovoltaic systems, gravity energy storage and offshore wind power generation. In meeting the demand for regionalenergy centers and needs along the industry chain, we have embarked on an innovative developing path that is unique to our strenaths and in line with the national carbon peaking and carbon neutrality strategies.
```
- Can you explain the data type and copyright ownership in detail? How much data does your company store?
```
It mainly contains operation and management data of zero-carbon clean energy technologies, smart urban environmental services and resource recycling and recovery;business solution data and reports data , etc.The data is our own business data and open solutions& reports data provided by third parties.So far we have stored nearly 2PiB of data.

```
- Does your company need to invoke stored data, and if so, how often does this happen?
```
We will conduct retrieval during the annual audit.
About once a year.
```
- How many miners do you want to select to store data? How many DataCap will be assigned to each miner?
```
We have service providers that can securely store our data.  In addition, we will continue to look for storage providers.
```

**Comment by HowardAce** [comment]
We have applied for LDN before and provided all the information about our company.  If you need to know anything else, please click:https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/426
We don't need much DC at present, so we would like to apply for some for the time being.
