### ISSUE TITLE
Client Allocation Request for: Environmental Information Center

### ISSUE THREAD

**Issue by Jonas923** [filecoin-project/filecoin-plus-client-onboarding#2491]
---

# Client Allocation Questions 

## Core Information
- Name: Environmental Information Center
- Website / Social Media: https://e-info.org.tw/
- Region: Greater China Region
- DataCap Requested: 80TiB
- Addresses to be Notarized: f1x64wt2wxuerpnsktrh33k4gnta6acj4bj2pghpa
- Notary Requested: swatchliu

@Jonas923 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

Is your company located in Greater China？

Please give the following information and provide links to social media/news mentions.

Duration of establishment,
Number of employees,
Business scope and products or services,
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.),
Data size to be stored,
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?
Would you like to submit more company information on [www.bytebase.cn](http://www.bytebase.cn/)?
Would you like to accept our face-to-face visit?

**Comment by Jonas923** [comment]
Is your company located in Greater China？
Yes
Please give the following information and provide links to social media/news mentions.
Duration of establishment,
Since 2000
Number of employees,
20-25
Business scope and products or services,
The Environmental Information Center (EIC) is a non-profit online media founded by the Taiwan Environmental Information Association. We are committed to providing comprehensive domestic and international environmental reports, and hope to speak for the mountains, forests and oceans. We believe that any action begins with knowing what is going on around us. Only by making information available and accessible, and through the participation of the public, we can promote harmony between people and nature and achieve sustainable development.
Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter, Linkedin, e.g.),
https://zh-cn.facebook.com/enc.teia/
Data size to be stored,
About three replicas of 27TiBs. But because we are a non-profit organization, we have very little budget for storage. If storage here meets our expectations, we will apply for more.
Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?
No. We just heard about this project from friend last month and this's our first application.
Would you like to submit more company information on http://[www.bytebase.cn](http://www.bytebase.cn/)/?
Yes
Would you like to accept our face-to-face visit?
We'll be able to host you in late October but I'm not sure the travel policy between taiwan and mainland due to COVID-19.

**Comment by Jonas923** [comment]
Thanks

**Comment by swatchliu** [comment]
Granted manually.
