### ISSUE TITLE
Client Allocation Request for: 360Social marketing

### ISSUE THREAD

**Issue by Wooden92** [filecoin-project/filecoin-plus-client-onboarding#2506]
---

# Client Allocation Questions 

## Core Information
- Name: 360Social marketing
- Website / Social Media: https://www.asia-360.net/
- Region: Greater China Region
- DataCap Requested: 50TiB
- Addresses to be Notarized: f1qt6s3mdo4rcneph5vwpjikptsa6ejbu73jsdt3i
- Notary Requested: 1475Notary

@Wooden92 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by 1475Notary** [comment]
Thanks for the request! Please answer the following questions giving as much detail as possible.

Please introduce yourself and the organization you represent, what is its name, nature, country of incorporation and date of establishment?
How many employees does the company currently have?
In which region do you plan to use DataCap?
How did you hear about the FIL+ project?
What kind of data do you plan to store? Can you share any kind of sample data?
Please provide the business license of your company.
Are you willing to store data outside of Greater China?

**Comment by Wooden92** [comment]
> Please introduce yourself and the organization you represent, what is its name, nature, country of incorporation and date of establishment?

Hi, I'm Tim working in the planning department. Our official name is "全方位社群行銷有限公司" which is All-round Social Marketing Ltd in english. We focus on software and network related industries.The company was founded in November 17, 2020.
ment? 

>How many employees does the company currently have? 

30-35

>In which region do you plan to use DataCap? 

Greater China

>How did you hear about the FIL+ project? 

From youtube

>What kind of data do you plan to store? Can you share any kind of sample data?

With years of experience and strategies in online marketing, we are in line with international digital marketing companies especially specializing marketing, KOL, blogger/net celebrity and community management services to effectively increase product exposure and brand awareness. That said we have a lot videos and pictures that we have designed for our clients. However, due to the pandemic our budget on data storage is not suficient enough. 

> Please provide the business license of your company. 

Our unified number is 83300778 please check.

>Are you willing to store data outside of Greater China?

Yes but we prefer offline transfer for the safety of our data. 

@1475Notary thanks for your time!

**Comment by 1475Notary** [comment]
bot error. Approved by lotus.
