### ISSUE TITLE
Client Allocation Request for: Himelight

### ISSUE THREAD

**Issue by Selina665** [filecoin-project/filecoin-plus-client-onboarding#2513]
---

# Client Allocation Questions 

## Core Information
- Name: Himelight
- Website / Social Media: https://www.himelight.com/
- Region: Greater China Region
- DataCap Requested: 50TiB
- Addresses to be Notarized: f1e6gxhnb7dwcmcdauz6hmxsxf64nmvtne746nxsa
- Notary Requested: 1475Notary

@Selina665 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by 1475Notary** [comment]
Thanks for the request! Please answer the following questions giving as much detail as possible.

Please introduce yourself and the organization you represent, what is its name, nature, country of incorporation and date of establishment?
How many employees does the company currently have?
In which region do you plan to use DataCap?
How did you hear about the FIL+ project?
What kind of data do you plan to store? Can you share any kind of sample data?
Please provide the business license of your company.
Are you willing to store data outside of Greater China?
