### ISSUE TITLE
Client Allocation Request for: Filscan

### ISSUE THREAD

**Issue by timguo-ipfs** [filecoin-project/filecoin-plus-client-onboarding#253]
# Client Allocation Questions 

## Core Information
- Name: Filscan
- Website / Social Media: filscan.io
- Region: Greater China
- DataCap Requested: 15 TiB
- Addresses to be Notarized: f1tsu3p55c746zhigfinao6ay7ewenquem6tssjhy
- Notary Requested: philippbanhardt

-----------------------------

**Comment by dkkapur** [comment]
@timguo-ipfs as FYI, @philippbanhardt is no long accepting applications. Closing this issue out for the time being. Would recommend you apply to a different notary. Thanks!
