### ISSUE TITLE
Client Allocation Request for: chetan katke

### ISSUE THREAD

**Issue by chetankatke** [filecoin-project/filecoin-plus-client-onboarding#2542]
---

# Client Allocation Questions 

## Core Information
- Name: chetan katke
- Website / Social Media: https://www.facebook.com/ckatke1
- Region: Asia (excl. Greater China)
- DataCap Requested: 1TiB
- Addresses to be Notarized: f1j5vqgdrcxkczbmvjwmud57v5fi37gumrhs5d6da
- Notary Requested: swatchliu

@chetankatke Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Please choose the notary in your district. Thank you!
