### ISSUE TITLE
Client Allocation Request for: Yuxue Education Technology Co., Ltd.

### ISSUE THREAD

**Issue by colago00** [filecoin-project/filecoin-plus-client-onboarding#2576]
---

# Client Allocation Questions 

## Core Information
- Name: Yuxue Education Technology Co., Ltd.
- Website / Social Media: http://www.colago.com
- Region: Greater China Region
- DataCap Requested: 60TiB
- Addresses to be Notarized: f1qducuo4tspe3ikxv4o5putxu4v5ciskr66fha6i
- Notary Requested: 1475Notary

@colago00 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by 1475Notary** [comment]
Thanks for the request! Please answer the following questions giving as much detail as possible.

Please introduce yourself and the organization you represent, what is its name, nature, country of incorporation and date of establishment?
How many employees does the company currently have?
In which region do you plan to use DataCap?
How did you hear about the FIL+ project?
What kind of data do you plan to store? Can you share any kind of sample data?
Please provide the business license of your company.
Are you willing to store data outside of Greater China?

**Comment by colago00** [comment]
hello. I work in the technical department in charge of media production, my company is Shanghai Yuxue Educational Information Consulting Co., Ltd. It was established in December 2016.

There are 48 employees.

Greater China

I got a subtotal from a colleague and learned the details through YouTube.


We distribute and manage graphic animation, photography, digital graphics, etc. for public relations purposes. Check out the samples.
http://www.colago.com/media/enterReading.mp4

The business license can be sent via email.

If possible

**Comment by 1475Notary** [comment]
Thanks for your reply. Please send the business license to simon686@protonmail.com through the company mail.

**Comment by colago00** [comment]
sent by email.

**Comment by 1475Notary** [comment]
![1666927521183](https://user-images.githubusercontent.com/103022086/198495489-6834f851-4f81-4e80-ab7c-dd55956bdc4f.png)
Please send it from your business email address,  either colago or yuxue's domain name.

**Comment by colago00** [comment]
@1475Notary  We do not have corporate domain emails.
