### ISSUE TITLE
Client Allocation Request for: continental

### ISSUE THREAD

**Issue by tangyang100** [filecoin-project/filecoin-plus-client-onboarding#2586]
---

# Client Allocation Questions 

## Core Information
- Name: continental
- Website / Social Media:  https://www.continental.com.hk/
- Region: Asia (excl. Greater China)
- DataCap Requested: 100TiB
- Addresses to be Notarized: f1g6kef5vs57di4uu6o6hj6vz35wnbqbhrnnz5kuq
- Notary Requested: fireflyHZ

@tangyang100 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by fireflyHZ** [comment]
Thank you for your interest and application.
Please answer the question：

1 Why do you plan to store data to filecoin?
2 Please include some sample data as much as possible？
3 Please tell us more about your company？
4 What you know about FileCoin storage providers and how you plan to store your data？
5 Please state your relationship with the company？

**Comment by tangyang100** [comment]
Hi @fireflyHZ Thanks for your reply.
1 We are a traditional jewelry maker and designer who is now just beginning to touch the business model of the Internet combined with traditional business. In the process we learned that FileCoin is a web 3.0-based network. We are also currently exploring whether we can make some breakthroughs in business based on the Internet or even blockchain. 
Filecoin was chosen because it is currently the easiest and least costly way for us to access, use, and participate in Web3 networks. So we decided to try to store some data on it in preparation for more web3 or blockchain-based business participation in the future.

2 You can visit our website: https://www.continental.com.hk/ . And I'll upload more sample resources to make them public later.

3 Continental Holdings Limited, a publicly listed company, is an investment holding operation based in Hong Kong and founded by Dr. Chan Sing Chuk, Charles. Its subsidiary, Continental Jewellery (MFG) Ltd., is dedicated to designing, manufacturing, and exporting fine jewellery to customers all over the world.

Continental has had its core business in the jewellery industry for over four decades. We carry this experience and expertise as we continue to grow our operation. Today, Continental maintains a diverse investment portfolio, including property investments and mining.

4 I've joined filecoin's slack community and found SPs in a lot of different regions, and we'll be connecting with some SPs on slack to store data on their nodes。
Our current data types are mainly sample display pictures, existing promotional multimedia resources, and certification and other resources. The total amount is about 10T, and we plan to store 5 copies. Therefore, we plan to apply for a 50T quota to encapsulate this data

5 I am the head of Continental's Chinese mainland agency and am fully responsible for the operation, sales and management of Continental in Chinese mainland.

Please give us support， thank you verify much！

**Comment by tangyang100** [comment]
Hi @fireflyHZ Please review our application. And I added some sample data:
https://drive.google.com/file/d/1GRLkDrQqC7QjZ7IVlXxht6ogoJaz9m_B/view?usp=share_link
https://drive.google.com/file/d/1a5yLuzvF0bE3rrXiWwX_ihaHqiTCyQr7/view?usp=share_link
https://drive.google.com/file/d/1cKmIABSOOiIRdtSdft8mwjAtjqsrRENu/view?usp=share_link
https://drive.google.com/file/d/1WFTUrZEr_fh2VlEyz0AbEBQxJvoV-oG9/view?usp=share_link
https://drive.google.com/file/d/1hTq4gF9wwpGeoOggWctEm2bw7gblKWEG/view?usp=share_link
https://drive.google.com/file/d/10TqcRaDH94debztwqEoAqgaYQbVtfSlM/view?usp=share_link

**Comment by fireflyHZ** [comment]
Hi @tangyang100 ,Please outline your quota allocation plan and give it as much detail as possible.

**Comment by tangyang100** [comment]
Hi @fireflyHZ , I plan to find some SPs from the Slack community and communicate with them to determine which ones to choose. We are also looking at more platforms such as filswan, where there are also many reliable SPs worth choosing. We plan to select at least 5 SPs, each of which does not exceed 25%. 
Please ask if you have any other requests or suggestions to us, and look forward to your support, Thank your!

**Comment by fireflyHZ** [comment]
Thank you for replying so quickly, your app looks great and I will give you support this time.

**Comment by fireflyHZ** [comment]
https://filfox.info/zh/message/bafy2bzacedz3bu4aw54e3frg4w26rqafyme5f54fxw4fmhbsjeuflwrvpapbu
