### ISSUE TITLE
Client Allocation Request for: TopSchools

### ISSUE THREAD

**Issue by melodyweb3** [filecoin-project/filecoin-plus-client-onboarding#2596]
# Client Allocation Questions 

## Core Information
- Name: TopSchools
- Website / Social Media: http://www.topschools.cn/?_l=en
- Region: Greater China Region
- DataCap Requested: 50T
- Addresses to be Notarized: f1zvybqxoz4airjgiyfwwgado7rt266yqua5ktj4y
- Notary Requested: fireflyHZ
- Email: ivan.ma@topschools.cn

@fireflyHZ  Hello, I'm a company that integrates educational resources. I overheard that IPFS technology is interested in permanent storage because my company has a lot of data to store. I hope you can give me 50T space to store some company file data. Thank you very much!

**Comment by fireflyHZ** [comment]
Hi @melodyweb3 , Thank you very much for your application, I am an Asian non-Chinese mainland notary public and in principle I cannot give you support for the application of application. But I'm very interested in your application. Can you contact me directly on Slack?
