### ISSUE TITLE
Client Allocation Request for: Xinshu

### ISSUE THREAD

**Issue by Xinshu01** [filecoin-project/filecoin-plus-client-onboarding#2597]
---

# Client Allocation Questions 

## Core Information
- Name: Xinshu
- Website / Social Media: Wechat: 拾时相册
- Region: Greater China Region
- DataCap Requested: 100TiB
- Addresses to be Notarized: f16y7rzirf5xuhzvunhrcorc657tvekugfjl6c3qq
- Notary Requested: UnionLabs2020

@Xinshu01 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by UnionLabs2020** [comment]
Thanks for the request! Please answer the following questions giving as much detail as possible.
Please introduce yourself and the organization you represent.
How many employees does the company currently have?
In which region do you plan to use DataCap?
What kind of data do you plan to store? Can you share any kind of sample data?

**Comment by Xinshu01** [comment]
@UnionLabs2020 
I'm an employee of Xinshu. Shanghai Xinshu Information Technology Co., Ltd. was founded in March 2018. The company is committed to becoming a leading provider of image management solutions for the mobile Internet. The company's mission is to promote people to develop the habit of video recording and pick up the passing years. The brand of Shishi Photo Album is named after it. In May 2019, the company launched the Shishi Photo Album mobile app, officially entering the Internet industry. Shanghai Xinshu will promote Shishi photo albums into the daily life of every ordinary person, and let beautiful images record everyone's life.
Now we remain having more than 50 staffs.
We plan connected with sp 
I plan to communicate with sp to cooperate on BDE platform. Welcome sp from different regions to recieve our deals.
This is our dataset, it's pictures from our platform.
[dataset.zip](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/9927595/dataset.zip)
