### ISSUE TITLE
Client Allocation Request for: Magik6k

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/filecoin-plus-client-onboarding#2622]
---

# Client Allocation Questions 

## Core Information
- Name: Magik6k
- Website / Social Media: 
- Region: Europe
- DataCap Requested: 96TiB
- Addresses to be Notarized: f1cpjril27nptd7qvjy72kpmxboghlkyon2bv5ruq
- Notary Requested: s0nik42

@magik6k Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by magik6k** [comment]
This is for filecoin chain backup on filecoin. 96 TiB should be good for ~3 copies of raw blocks + full node mirrors.

**Comment by s0nik42** [comment]
@galen-mcandrew any reason, I cannot see it on plus.fil.org ?
