### ISSUE TITLE
Client Allocation Request for: Decentral Tech

### ISSUE THREAD

**Issue by IpfsStore** [filecoin-project/filecoin-plus-client-onboarding#263]
---

# Client Allocation Questions 

## Core Information
- Name: Decentral Tech
- Website / Social Media: https://ipfsdrop.com/
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1e3vyhnfmpnetodevdky5vkfp6qmrhzidgjvnana
- Notary Requested: steven004

**Comment by steven004** [comment]
Hey @IpfsStore  , thanks for your request. Can you kindly add more information / context here on:

1. yourself/ your organization (with links to official website/social media/news mentions etc)
2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners)
5. How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
6. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
7. Would you be OK in posting deal transactions here?

Thanks

**Comment by steven004** [comment]
Hey @IpfsStore , please let me know if you still need the datacap, or I will close this issue. thanks.

**Comment by steven004** [comment]
Closed due to no recent update. 

@IpfsStore Please feel free to re-apply datacap if you still need it.
