### ISSUE TITLE
Client Allocation Request for: 

### ISSUE THREAD

**Issue by orvn** [filecoin-project/filecoin-plus-client-onboarding#2634]
---

# Client Allocation Questions 

## Core Information
- Name: 
- Website / Social Media: 
- Region: North America
- DataCap Requested: 1TiB
- Addresses to be Notarized: 
- Notary Requested: Joss-Hua

@orvn Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by orvn** [comment]
Sorry, this issue was an accidental submission from the Filecoin Plus website due to a bug (I used the submit button but it threw an error, however it seems that, unknown to me, this issue was opened anyway).

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
