### ISSUE TITLE
Client Allocation Request for: Ganku Co., Ltd.

### ISSUE THREAD

**Issue by Ganku112211** [filecoin-project/filecoin-plus-client-onboarding#2636]
---

# Client Allocation Questions 

## Core Information
- Name: Ganku Co., Ltd.
- Website / Social Media: https://www.ganku.net/
- Region: Greater China
- DataCap Requested: 100TiB
- Addresses to be Notarized: f1i2igpiu5nlmcjbo2tyrcd5w7kdgtlgif2bb6vka
- Notary Requested: NDLabs

@Ganku112211 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by NDLABS-OFFICE** [comment]
I have received your application, please send the data sample and data storage plan to slack: ND LABS - OFFICE
