### ISSUE TITLE
Client Allocation Request for: 蒙特沃德学院上海分校

### ISSUE THREAD

**Issue by 375785353** [filecoin-project/filecoin-plus-client-onboarding#264]
---

# Client Allocation Questions 

## Core Information
- Name: 蒙特沃德学院上海分校
- Website / Social Media: http://www.mvashanghai.org/
- Region: Greater China
- DataCap Requested: 50TiB
- Addresses to be Notarized: f3qqah4csnixfjvfkyxkitgdta3ksetjm6bm36ti6b5qgk3yets2gwokquce4w2m23tc2t6jsckee3miqkgbla
- Notary Requested: Fenbushi-Filecoin

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebkjdsmmibqqa2bew2wdjvymfpkhlfz5olkrk7iplramugrhwms6c 
#### Address 
> f3qqah4csnixfjvfkyxkitgdta3ksetjm6bm36ti6b5qgk3yets2gwokquce4w2m23tc2t6jsckee3miqkgbla
#### Datacap Allocated
> 50TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebkjdsmmibqqa2bew2wdjvymfpkhlfz5olkrk7iplramugrhwms6c
