### ISSUE TITLE
Client Allocation Request for: MongoStorage

### ISSUE THREAD

**Issue by amughal** [filecoin-project/filecoin-plus-client-onboarding#2662]
---

# Client Allocation Questions 

## Core Information
- Name: MongoStorage
- Website / Social Media: 
- Region: North America
- DataCap Requested: 100TiB
- Addresses to be Notarized: f1ktvy56lqhtlo754tcna7sy2iwtvn6saz26wkeya
- Notary Requested: jamerduhgamer

@amughal Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by amughal** [comment]
Large Hadron Collidor is the largest experiment at CERN that made happen the discovery of many areas in the field of physics. CERN has made certain datasets open to the world through Opendata initiative opendata.cern.ch. Placing these datasets over to the FILE COIN infrastructure will provider accessibility to the broader audience.

**Comment by jamerduhgamer** [comment]
90 TiBs have been approved as I do not have enough datacap remaining to fulfil the complete 100 TiBs. Client messaged and told them if needed they can request an additional 10 TiBs from another notary to finish their dataset.

`lotus filplus check-client-datacap f1ktvy56lqhtlo754tcna7sy2iwtvn6saz26wkeya
98956046499840`

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
