### ISSUE TITLE
Client Allocation Request for: Test

### ISSUE THREAD

**Issue by simonkim0515** [filecoin-project/filecoin-plus-client-onboarding#2699]
# Client Allocation Questions

## Core Information
- Name: Test
- Website / Social Media: [Test](Test), (Test, Test)
- Region: North America
- DataCap Requested: 700 GiB
- Addresses to be Notarized: f12314
- Notary Requested: Xinan Xu

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
