### ISSUE TITLE
Client Allocation Request for: 成都煜麟信息技术有限公司

### ISSUE THREAD

**Issue by febtwe** [filecoin-project/filecoin-plus-client-onboarding#270]
---

# Client Allocation Questions 

## Core Information
- Name: 成都煜麟信息技术有限公司
- Website / Social Media: https://www.perfectsign.com.cn/#/index
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f166ed72nf7jjtm2ditkpmsuoxvgjtqqxtfclitci
- Notary Requested: ozhtdong

**Comment by ozhtdong** [comment]
Thanks for your application. I want to know more basic information of you and your company. Please answer following question:
1.What's your name? What's your position? Can you introduce yourself?
2.What's your company's business? Any other social media link? Please introduce your company.
3.Could you show me your company's business license?

**Comment by febtwe** [comment]
1.What's your name? What's your position? Can you introduce yourself?
Hello, I’m Hu Zhaoming,the CTO of the company

2.What's your company's business? Any other social media link? Please introduce your company.
Chengdu Yulin Information Technology Co., Ltd. focuses on the research and development of traditional application-oriented business and domestic independent controllable products.
The company has a professional software customization development, product research and development, system integration, operation planning and after-sales service team. 80% of its management team have more than 10 years of work experience, and the technology research and development and operation service experience are at the leading level in the industry.

3.Could you show me your company's business license?
<img width="386" alt="图片 1fyjy" src="https://user-images.githubusercontent.com/79354067/111430890-0235dc00-8736-11eb-96e6-68b35360895f.png">

**Comment by ozhtdong** [comment]
Thanks for your quick reply and detailed information.
I have further more questions about data and storing.

1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?

**Comment by febtwe** [comment]
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
Data：Corporate Internet Marketing Promotional Materials（video、picture）
Size：about 15 TiB
Demos：I will send you via email


2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?
Basically use local and cloud services for backup and storage and rental cloud services include Ali, Baidu, and Huawei
Approximately 20TiB per month

**Comment by ozhtdong** [comment]
Hi. 
I also want to know more about your allocation strategy.
1.How many miners do you want to store your data to? How much data for each miner? 
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect? 
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by ozhtdong** [comment]
Hi. 
I also want to know more about your allocation strategy.
1.How many miners do you want to store your data to? How much data for each miner? 
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect? 
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by febtwe** [comment]
Hi

1.How many miners do you want to store your data to? How much data for each miner? 
Hello, we are going to distribute the data to three miners for storage,less than 40% for each miner.

2.Will you record your allocation decision in public? Which platform will you use?
Yes, of course. We'll post the results on our website

3.What method/tool will you use to inspect miners? Which aspect of miners will you inspect? 
We are  concerned with the scale of the miners, credibility, and the location to our IDCs.

4 .Have you ever allocated before? If yes, how did you do when you were questioned? 
None.
