### ISSUE TITLE
Client Allocation Request for: Jim

### ISSUE THREAD

**Issue by apojii** [filecoin-project/filecoin-plus-client-onboarding#2714]
# Client Allocation Questions

## Core Information
- Name: Jim
- Website / Social Media: [oanode.com](oanode.com), (@apojii, Twitter)
- Region: Greater China
- DataCap Requested: 1 TiB
- Addresses to be Notarized: f1jjtc2tdy7svnsaqcgxlauta455iwqjbbjiulddi
- Notary Requested: Neo Ge

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
