### ISSUE TITLE
Client Allocation Request for: OasisNode

### ISSUE THREAD

**Issue by apojii** [filecoin-project/filecoin-plus-client-onboarding#2715]
# Client Allocation Questions 

## Core Information
- Name: Oasis Node
- Website / Social Media: oanode.com, apojii@twitter
- Region: Asia excl. GCN
- DataCap Requested: 10 TB
- Addresses to be Notarized: f1jjtc2tdy7svnsaqcgxlauta455iwqjbbjiulddi
- Notary Requested: Irene Young

-------------------------

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
