### ISSUE TITLE
Client Allocation Request for: TEST

### ISSUE THREAD

**Issue by dkkapur** [filecoin-project/filecoin-plus-client-onboarding#2720]
# Client Allocation Questions

## Core Information
- Name: TEST
- Website / Social Media: [TEST](TEST), (test, test)
- Region: North America
- DataCap Requested: 225 GiB
- Addresses to be Notarized: f41023123fssfsdfsdfqew23141wq
- Notary Requested: Gary Gao

**Comment by orvn** [comment]
Closing as not planned
