### ISSUE TITLE
Client Allocation Request for: SCVSoft

### ISSUE THREAD

**Issue by benjioh5** [filecoin-project/filecoin-plus-client-onboarding#2737]
# Client Allocation Questions 

## Core Information
- Name: SCVSoft
- Website / Social Media: www.scvsoft.net
- Region: Asia minus GCR
- DataCap Requested: 2 PiB
- Addresses to be Notarized: TBD
- Notary Requested: IPFS Japan Consortium, BlockchainWorld

-------------------------

**Comment by benjioh5** [comment]
wtf

**Comment by kernelogic** [comment]
amen brother

**Comment by benjioh5** [comment]
@kernelogic HELP ME

**Comment by kernelogic** [comment]
It seems you applied for 2PB datacap but this is regular application for 1~100TB.

You can try re-apply here https://filplus.storage/apply it should route you to the proper channel.

**Comment by benjioh5** [comment]
@kernelogic Oh tanks

**Comment by benjioh5** [comment]
@kernelogic https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/1956 thx
