### ISSUE TITLE
Client Allocation Request for: This is a test application - Please ignore

### ISSUE THREAD

**Issue by timelytree** [filecoin-project/filecoin-plus-client-onboarding#2751]
# Client Allocation Questions

## Core Information
- Name: This is a test application - Please ignore
- Website / Social Media: [This is a test application - Please ignore](This is a test application - Please ignore), (This is a test application - Please ignore, Twitter)
- Region: Africa
- DataCap Requested: 512 GiB
- Addresses to be Notarized: This is a test application - Please ignore
- Notary Requested: Andress Sarria

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
