### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by orvn** [filecoin-project/filecoin-plus-client-onboarding#2752]
# Client Allocation Questions 

## Core Information
- Name: [Individual / Organization]
- Website / Social Media: [Evidence of Real world Identity]
- Region: [North America / Africa / Oceania / Europe / Asia excl. GCN / Asia excl. Greater China / Asia excl. Japan / Asia Japan / Greater China  / None]
- DataCap Requested: [123]
- Addresses to be Notarized: [fxxxx OR TBD]
- Notary Requested: [choose one notary]

-------------------------

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
