### ISSUE TITLE
Client Allocation Request for: IMRE Hosting Ltd

### ISSUE THREAD

**Issue by imreltd** [filecoin-project/filecoin-plus-client-onboarding#2753]
# Client Allocation Questions

## Core Information
- Name: IMRE Hosting Ltd
- Website / Social Media: [http://imrehost.technology/](http://imrehost.technology/), ([at]imreltd, [at]imreltd)
- Region: Europe
- DataCap Requested: 8.4 TiB
- Addresses to be Notarized: f1nlhouj6cwctb4lijgh4tej7hhvdlwc5oc3byp5y
- Notary Requested: Wijnand Schouten

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by cryptowhizzard** [comment]
Approved
