### ISSUE TITLE
Client Allocation Request for: TitanNetwork

### ISSUE THREAD

**Issue by TitanNet** [filecoin-project/filecoin-plus-client-onboarding#2780]
# Client Allocation Questions

## Core Information
- Name: TitanNetwork
- Website / Social Media: [https://www.titannet.io/](https://www.titannet.io/), (https://Filecoinproject.slack.com/archives/C03QG9433HA, https://twitter.com/FilecoinTitan)
- Region: China
- DataCap Requested: 1 TiB
- Addresses to be Notarized: f1iup6srjczdstdnsh5zkso4u3xij7ofe3qnyzuvq
- Notary Requested: llifezou

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by Tom-OriginStorage** [comment]
Prior to this, I had a good understanding of the Titan network and confirmed it,
The limit application is for testing the loading of enterprise data into Filecoin.
So willing to provide support.
