### ISSUE TITLE
Client Allocation Request for: Frantisek Mantlik

### ISSUE THREAD

**Issue by mantlik** [filecoin-project/filecoin-plus-client-onboarding#2783]
# Client Allocation Questions

## Core Information
- Name: Frantisek Mantlik
- Website / Social Media: [https://github.com/mantlik](https://github.com/mantlik), (https://www.linkedin.com/in/frantisek-mantlik-85b98193/, Linkedin)
- Region: Canada
- DataCap Requested: 10 TiB
- Addresses to be Notarized: f3st32m24bvdp7cqty3nmtxahqx63phfnu6ux5ge5kdthp65sdqvkd3yntbx4enailmhromwb5lb4al4lw24sq
- Notary Requested: Benny

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
