### ISSUE TITLE
Client Allocation Request for: Frantisek Mantlik

### ISSUE THREAD

**Issue by mantlik** [filecoin-project/filecoin-plus-client-onboarding#2793]
# Client Allocation Questions

## Core Information
- Name: Frantisek Mantlik
- Website / Social Media: [ https://github.com/mantlik]( https://github.com/mantlik), (https://www.linkedin.com/in/frantisek-mantlik-85b98193/, LinkedIn)
- Region: Canada
- DataCap Requested: 10 TiB
- Addresses to be Notarized: f3st32m24bvdp7cqty3nmtxahqx63phfnu6ux5ge5kdthp65sdqvkd3yntbx4enailmhromwb5lb4al4lw24sq
- Notary Requested: llifezou

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)

**Comment by mantlik** [comment]
Hi Lifezou
The purpose is backing up data in cold storage using Filecoin over Powergate. The idea is to migrate my current cold storage backups at Storj network to Filecoin. 
The Python scripts for backup data are currently under development and I need some space to alpha test the process. Once passed alpha testing, the scripts will be open sourced on Github.
For alpha testing I will use data from my network, couple of Linux servers backups created using Borg, and couple of Windows machine image backups created by UrBackup. Overall about 3-4TB of data not including replication overhead.
Please let me know if more clarification is needed.
Thanks
Frantisek

**Comment by llifezou** [comment]
Customers add valuable data to Filecoin in order to test, and we are willing to provide support. 
As the first application, we first grant you 5T data, please use it correctly, after the correct use, we will grant you the subsequent 5T

**Comment by llifezou** [comment]
@mantlik 
![image](https://github.com/filecoin-project/filecoin-plus-client-onboarding/assets/46102475/6ec424e7-8364-48f3-a176-e9cdbc33976c)

**Comment by mantlik** [comment]
Thank you for fast processing. The proposed approach will work. Confirming successful allocation from my side.

**Comment by llifezou** [comment]
I close it first, please reopen it when applying again
