### ISSUE TITLE
Client Allocation Request for: MetaKey

### ISSUE THREAD

**Issue by Metakeyofficial** [filecoin-project/filecoin-plus-client-onboarding#2794]
# Client Allocation Questions

## Core Information
- Name: MetaKey
- Website / Social Media: [https://twitter.com/MetaKey_Web3](https://twitter.com/MetaKey_Web3), ([at]MetaKey_Web3, Twitter)
- Region: Malaysia
- DataCap Requested: 20 TiB
- Addresses to be Notarized: f1m5jxf7mvcp4gzxdsozpty6h742va7m4ae7nr5ia
- Notary Requested: Mona

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
