### ISSUE TITLE
Client Allocation Request for: getpancake

### ISSUE THREAD

**Issue by RaminNietzsche** [filecoin-project/filecoin-plus-client-onboarding#2797]
# Client Allocation Questions

## Core Information
- Name: getpancake
- Website / Social Media: [https://ossolutions.ir](https://ossolutions.ir), ([at]Pancakedatabase, Twitter)
- Region: Iran
- DataCap Requested: 2 TiB
- Addresses to be Notarized: f1kctjbv4mxdcunderluqnjcyhnr3izs3qcb5tnia
- Notary Requested: Tracy

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
