### ISSUE TITLE
Client Allocation Request for: pancakedatabase

### ISSUE THREAD

**Issue by RaminNietzsche** [filecoin-project/filecoin-plus-client-onboarding#2798]
# Client Allocation Questions

## Core Information
- Name: pancakedatabase
- Website / Social Media: [https://getpancake.com](https://getpancake.com), ([at]pancakedatabase, Twitter)
- Region: Iran
- DataCap Requested: 1 TiB
- Addresses to be Notarized: f1kctjbv4mxdcunderluqnjcyhnr3izs3qcb5tnia
- Notary Requested: Olivier Molenkamp

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
