### ISSUE TITLE
Client Allocation Request for: General Data Testing

### ISSUE THREAD

**Issue by pwrepo** [filecoin-project/filecoin-plus-client-onboarding#2816]
# Client Allocation Questions

## Core Information
- Name: General Data Testing
- Website / Social Media: [https://fil.org](https://fil.org), ([at]tiktok, Tik Tok)
- Region: Singapore
- DataCap Requested: 10 TiB
- Addresses to be Notarized: f1y3fr5obpt2dfyubdjeagfivhgbasgfebzpq7yki
- Notary Requested: n/a

_Application created via [filplus.storage](https://filplus.storage)_

**Comment by pwrepo** [comment]
This application is to test deals in the APAC region.

**Comment by cryptowhizzard** [comment]
Granted.
