### ISSUE TITLE
Client Allocation Request for: Dong Fong Technologies Vietnam Company Limited

### ISSUE THREAD

**Issue by uglyboy123** [filecoin-project/filecoin-plus-client-onboarding#293]
---

# Client Allocation Questions 

## Core Information
- Name: Dong Fong Technologies Vietnam Company Limited
- Website / Social Media: http://vn.dongfong.com.tw/about.html
- Region: Asia excl. Greater China
- DataCap Requested: 2TiB
- Addresses to be Notarized: f17chz2xuedput42kfhfs722f7q6lk7ue4ioi2zyi
- Notary Requested: ericfish

**Comment by rayshitou** [comment]
Hi @uglyboy123 
I am a colleague of @ericfish ([here](https://github.com/filecoin-project/notary-governance/issues/26#issuecomment-749307151)). 
Sorry for the delay in processing your application because our Datacap is still in [progress](https://github.com/filecoin-project/notary-governance/issues/107). If you don’t mind acquiring Datacap a little later, please let me know some infomation of you and your company: 
1. What's your name and your position in your company?
2. What's your company's business? and could you show me your company's business license?

**Comment by rayshitou** [comment]
Hi, @uglyboy123. Can we go on this verifying?

**Comment by uglyboy123** [comment]
Sorry, please let us continue with the verifying

1. I am Mia Nguyen,  in charge of Dongfong Technology Vietnam.

2. Dongfong Technology is a famous transnational IDC technical service provider in Taiwan and Southeast Asia. Since its establishment, Dongfong Technology has been committed to providing customers with one-stop IDC room and network services.

Here is our business license
![1](https://user-images.githubusercontent.com/79346019/115487311-07cd9700-a28b-11eb-8ae8-70d7a521b6fd.jpg)
![2](https://user-images.githubusercontent.com/79346019/115487315-09975a80-a28b-11eb-805a-6073bbbbca2a.jpg)

**Comment by rayshitou** [comment]
Thanks for your introduction. 
What kind of data do your company want to store and have you ever use any cloud to store these data? What's your usage volume and frequency?
And do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners? What method will you use to insperct miners?

**Comment by uglyboy123** [comment]
Hi,rayshitou
1.We want to  store some live video as a backup in the Filecoin network,About 5TiB.

2.We plan t0 divide it up among several miners,distance is our primary consideration.

**Comment by rayshitou** [comment]
OK.
Will you record your allocation decision in public? Which platform will you use?
And, i want to know that have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision?

**Comment by uglyboy123** [comment]
Yes.

**Comment by rayshitou** [comment]
Sorry, maybe my question is not clear enough, can you answer it separately.
1. Will you record your allocation decision in public? Which platform will you use?
2. Have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision?

**Comment by uglyboy123** [comment]
Hi,rayshitou
1.We will post the result of the application on Github.
2.None.

**Comment by rayshitou** [comment]
Thanks for your quick response.  Finally, Can you guarantee that all these data you mentioned above abides by local regulations and in compliance with the recipient miner's terms of service?

**Comment by uglyboy123** [comment]
Yes, we promise to abide by local regulations and comply with the terms of service of the receiver miner.

**Comment by rayshitou** [comment]
@uglyboy123 ，I have noticed that you have applied for 5T DataCap, but we only have 2T left. I have modified the DataCap, please be aware.

**Comment by rayshitou** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedl57bljad5zhkkiqhaykvz6cgyyx3bmnsizesxjpu7qizf5a2y3s 
#### Address 
> f17chz2xuedput42kfhfs722f7q6lk7ue4ioi2zyi
#### Datacap Allocated
> 2TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedl57bljad5zhkkiqhaykvz6cgyyx3bmnsizesxjpu7qizf5a2y3s
