### ISSUE TITLE
Client Allocation Request for: 火星区块链

### ISSUE THREAD

**Issue by huoxing24** [filecoin-project/filecoin-plus-client-onboarding#295]
---

# Client Allocation Questions 

## Core Information
- Name: 火星区块链
- Website / Social Media: huoxing24.com
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1kzyw5ii3ivxb4iteswrheuklwn3mmjvizllrmky
- Notary Requested: ozhtdong

**Comment by ozhtdong** [comment]
Thanks for your application. I want to know more basic information of you and your company. Please answer following question:
1.What's your name? What's your position? Can you introduce yourself?
2.What's your company's business? Any other social media link? Please introduce your company.
3.Could you show me your company's business license?

**Comment by huoxing24** [comment]
hi，Thanks for your question，
1.What's your name? What's your position? Can you introduce yourself?
Hi,I‘m Tony Tang.Currently serving as the business director of Mars finance and Mclouds  of Hainan Tianchen Network Technology Co.

2.What's your company's business? Any other social media link? Please introduce your company.
  Mars finance is founded in 2018 by Wang Feng, founder of Linekong Interactive (HK.8267), it is the country's largest blockchain media outlet, connecting more than 6,000 blockchain companies in China and has more than 3 million users.It has received investments from well-known VCs such as Binance, IDG Capital, OKEx, Huobi Eco, etc., and its 2019 valuation has surpassed $200 million.
  Mclouds is a one-stop provider of cloud mining services ranging from product selection to electronic payments, asset management, and third-party financial services. With strong industry integration and back-end service capabilities, Mclouds provides its customers with the industry‘s most secure and efficient services and is committed to taking responsibility for its customers’ assets and providing the best after-sales service in the industry.


3.Could you show me your company's business license?
<img width="863" alt="mars blockchain" src="https://user-images.githubusercontent.com/80936343/112312388-b957c780-8ce1-11eb-9cdf-ddc0a1ff9137.png">

**Comment by ozhtdong** [comment]
Thanks for your quick reply and detailed information.
I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?

**Comment by huoxing24** [comment]
1、What kind of data do you want to store and how much? Could you please send me some demos of your data?

As a large blockchain media in China, Mars Finance will store all published media content, including articles, interviews, live videos, and summit materials, in the form of text, images, audio and video.

Mars Cloud Mining is an arithmetic asset service platform, which requires more secure storage services for such contents as mining machine details, customer information, platform operation documents, backend data, asset management data, etc.

2、Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?
Yes, we have used some cloud storage platform such as Baidu cloud, Tencent cloud and Ali cloud .About 10 TiB/Month.

**Comment by ozhtdong** [comment]
I also want to know more about your allocation strategy.

1.How many miners do you want to store your data to? How much data for each miner? 
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect? 
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by huoxing24** [comment]
Hi,ozhtdong
1.How many miners do you want to store your data to? How much data for each miner? 
1.We will give the data to 2-5 miners, each miner is less than 50%

2. Will you record your allocation decision in public? Which platform will you use?
2.Of course, we will post on Github，under this issue.

3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect? 
3.I already know some of the miners.I will make my choice based on the miner's power and industry reputation.

4. Have you ever allocated before? If yes, how did you do when you were questioned? 
4.None.

**Comment by ozhtdong** [comment]
Hi. 
Thanks for your information.
The last step, please show me your company searching consequence in the local business license searching website.

**Comment by huoxing24** [comment]
Thanks for your quick reply, here is the company searching consequence.

<img width="1241" alt="截屏2021-03-31 14 27 17" src="https://user-images.githubusercontent.com/80936343/113100193-a8e9a480-922d-11eb-93d3-ef982b737455.png">

**Comment by ozhtdong** [comment]
[1475 allocation table_Mars.xlsx](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/6234380/1475.allocation.table_Mars.xlsx)

**Comment by ozhtdong** [comment]
Please kindly find your score here.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedcuwrnv62n4owg2ouj5k3koaz2fbgthpvzriki5pkeeobr4q7osc 
#### Address 
> f1kzyw5ii3ivxb4iteswrheuklwn3mmjvizllrmky
#### Datacap Allocated
> 5TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedcuwrnv62n4owg2ouj5k3koaz2fbgthpvzriki5pkeeobr4q7osc
