### ISSUE TITLE
Client Allocation Request for: 上海旺付科技集团有限公司

### ISSUE THREAD

**Issue by dgrgsth** [filecoin-project/filecoin-plus-client-onboarding#296]
---

# Client Allocation Questions 

## Core Information
- Name: 上海旺付科技集团有限公司
- Website / Social Media: http://www.woropay.cn/index.html
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1tkvicjoonu5a5c6uamikz2iabzfvon3ka3x5qyq
- Notary Requested: ozhtdong

**Comment by ozhtdong** [comment]
Thanks for your application. I want to know more basic information of you and your company. Please answer following question:
1.What's your name? What's your position? Can you introduce yourself?
2.What's your company's business? Any other social media link? Please introduce your company.
3.Could you show me your company's business license?

**Comment by dkkapur** [comment]
@dgrgsth - @ozhtdong is currently out of DataCap to allocate. Would recommend you reach out to another notary that still has DataCap available or wait 2-3 weeks till the next round of notary elections is completed. Thank you!
