### ISSUE TITLE
Client Allocation Request for: Alyale Philippines, Inc.

### ISSUE THREAD

**Issue by michik0y** [filecoin-project/filecoin-plus-client-onboarding#3]
---

# Client Allocation Questions 

## Core Information
- Name: Alyale Philippines, Inc.
- Website / Social Media: https://weraveyou.ipfssys.info/
- DataCap Requested: 100GiB
- Addresses to be Notarized: f3qqhbwhgorbtymzhq5wxnointwl4tl5riqvxv35utyuhlisbz4247io32oshff2emysu5fzc2t4msh64ahlpq
- Notary Requested: philippbanhardt

**Comment by michik0y** [comment]
https://user-images.githubusercontent.com/35400025/104253091-a1c4bd00-54ae-11eb-8f79-1ca766423d15.mp4

sample video upload to https://weraveyou.ipfssys.info/ and stored using Filecoin network

**Comment by philippbanhardt** [comment]
Hey @michik0y - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc 
- your relationship with the data, especially with regard to copyright 
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
