### ISSUE TITLE
Client Allocation Request for: 北京中经天平科技有限公司

### ISSUE THREAD

**Issue by bjzjtp** [filecoin-project/filecoin-plus-client-onboarding#307]
---

# Client Allocation Questions 

## Core Information
- Name: 北京中经天平科技有限公司
- Website / Social Media: https://www.bjzjtp.com
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1sfq74iqhoseslc7vofvbdfknfo6tbtj2gnimgni
- Notary Requested: ozhtdong

**Comment by ozhtdong** [comment]
Thanks for your application. I want to know more basic information of you and your company. Please answer following question:
1.What's your name? What's your position? Can you introduce yourself?
2.What's your company's business? Any other social media link? Please introduce your company.
3.Could you show me your company's business license?

**Comment by bjzjtp** [comment]
Thanks for your quick response and here are our informations:
**_1.What's your name? What's your position? Can you introduce yourself?_**
**Name**:  Wang Bo
**Position**: Director of Depository Services
**Self-introduction**: I have been engaged in judicial related industries for more than 10 years and participated in a large number of evidence collection work such as CCTV Spring Festival Gala forensics, World Cup forensics, World Internet Conference depositing evidences, Jinri toutiao Short Video forensics, Oriental IC picture forensics, Tencent audio book forensics, Baidu News forensics, etc.

**_2.What's your company's business? Any other social media link? Please introduce your company._**
**Company’s Business**：Our business is to solidify the electronic data generated in various industries such as wills, finance, copyright, proof, electronic contracts, safety transportation, and judicial enforcement into electronic data evidence, which provides important reference value for the parties' rights protection, exemption, and traceability.
**Social Media**: zjtpyzx (WeChat Official Account)
**Company Profile**：
Beijing Zhongjing Tianping Technology Co., Ltd. (hereinafter referred to as Zhongjing Tianping), founded in 2017, is a joint-stock enterprise subordinate to the State Information Center (China Economic Network) and a strategic partner of the National Internet Emergency Response Center. With the approval of the Ministry of Justice, Zhongjing Tianping has established the Electronic Material Evidence Forensic Identification Center.
Zhongjing Tianping focuses on product research and development in the field of national legal system construction and information construction. As an Internet technology company,our company is supported by core technologies and driven by participating in and promoting the construction of intelligent justice. At the same time, Zhongjing Tianping is also the first batch of domestic blockchain information service filing enterprise in China, the participating enterprise of the two high-level and one key special project (litigation risk result prediction platform based on multi-party evidence correlation analysis), the participating enterprise for writing version 1.0 of the White Paper on Blockchain Judicial Depository Application, and the Shuxin chain ecological application enterprise .
At present, Zhongjing Tianping has served more than 300 courts in 15 provinces and municipalities directly under the central government, and our business covers many industries such as will, finance, copyright, proof production, electronic contract, traffic safety, judicial execution, etc.     

- In May 2018, Zhongjing Tianping, National Time Service Center of Chinese Academy of Sciences and Law Branch of China Information Association held a joint press conference on "Judicial Electronic Evidence Cloud Platform" and "Trusted Time Authentication Service Platform" at the State Information Center.
http://www.xinhuanet.com/politics/2018-05/25/c_1122888756.htm)
https://www.chinacourt.org/article/detail/2018/05/id/3318363.shtml)
https://baijiahao.baidu.com/s?id=1601423212828948507&wfr=spider&for=pc)

- In March 2019, Zhongjing Tianping obtained the first batch of domestic blockchain information service records of the Cyberspace Administration of China.
http://www.cac.gov.cn/2019-03/30/c_1124305122.htm)

- In June 2019, Zhongjing Tianping  participated in writing version 1.0 of the White Paper on Blockchain Judicial Depository Application.
http://www.caict.ac.cn/kxyj/qwfb/bps/201906/t20190614_201169.htm)

**_3.Could you show me your company's business license?_**
Yes, of course. Below is our company business license.
![QQ图片20210325184720](https://user-images.githubusercontent.com/80804381/112461075-8c1b2000-8d9a-11eb-9f24-0b2e16d9596f.jpg)

**Comment by bjzjtp** [comment]
Hi,  ozhtdong, sorry to bother you~

We haven't heard from you for several days.  We are wondering the processing progress and look forward to receiving your reply as soon as possible. Thanks a lot.

**Comment by bjzjtp** [comment]
@ozhtdong Hi,  ozhtdong, sorry to bother you~

We haven't heard from you for several days.  We are wondering the processing progress and look forward to receiving your reply as soon as possible. Thanks a lot.
