### ISSUE TITLE
Client Allocation Request for: Speedium

### ISSUE THREAD

**Issue by philippbanhardt** [filecoin-project/filecoin-plus-client-onboarding#31]
# Client Allocation Questions 

## Core Information
- Name: Speedium
- Website / Social Media: https://www.speedium.network
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3qfjtedox66c3x6dgqt45e364ht3ydcfymcx6xucoy34s22y6jttatbcatsuppesupanb5476npnt5tdasrqa

- Notary Requested: philippbanhardt 

-----------------------------

**Comment by philippbanhardt** [comment]
This request was filed in the old repo and full diligence thread can be found there: https://github.com/keyko-io/filecoin-clients-onboarding/issues/165

**Comment by cryptowhizzard** [comment]
Hi Philipp,

Thanks. Please note that we applied for 1 TB daily.

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced6fcgap6s7qyflucufmojzehyc4idf2m72b4rldk66hp6xjz73s4 
#### Address 
> f3qfjtedox66c3x6dgqt45e364ht3ydcfymcx6xucoy34s22y6jttatbcatsuppesupanb5476npnt5tdasrqa
#### Datacap Allocated
> 5 TiB

**Comment by cryptowhizzard** [comment]
Hi Philipp,

f3s5qozdyocudxtt2ekvcbu34dj2ubt3b4fqdzjqla7gj7442xckmlntcsmzibru6zkpiqlwflgn554cdhw6va.

Cheers!
