### ISSUE TITLE
Client Allocation Request for: the9 singapore pte ltd

### ISSUE THREAD

**Issue by serafimey** [filecoin-project/filecoin-plus-client-onboarding#334]
---

# Client Allocation Questions 

## Core Information
- Name: the9 singapore pte ltd
- Website / Social Media: https://www.the9.com/en/
- Region: Asia excl. Greater China
- DataCap Requested: 3TiB
- Addresses to be Notarized: f14gv3lvndhfzpo5imltbmeysagpknrexbi6e3nua
- Notary Requested: ericfish

**Comment by rayshitou** [comment]
Hi, @serafimey.  Thanks for your application.
I am a colleague of @ericfish ([here](https://github.com/filecoin-project/notary-governance/issues/26#issuecomment-749307151)) , and I am responsible for this application.
If you don’t mind [acquiring Datacap a bit later,](https://github.com/filecoin-project/notary-governance/issues/107),please let me know some infomation of you and your company:
1. What's your name and your position in your company?
2. What's your company's business? and could you show me your company's business license?

**Comment by serafimey** [comment]
My name is tony zhu  , the BD director of The9 Singapore pte ltd.I was in charge of business development department。
The9 Singapore pte ltd(The9) is an Internet company based in Singapore listed on Nasdaq in 2004. The9 aims to become a diversified high-tech Internet company. The9 has stepped into blockchain-related business in 2018。And The9 signed a legally binding cooperation and Investment term sheet with cryptocurrencies mining investors led by Jianping Kong to start the cryptocurrencies business。
I will send you the business license through the e-mail

**Comment by rayshitou** [comment]
Thanks for your introduction. 
What kind of data do your company want to store and have you ever use any cloud to store these data? What's your usage volume and frequency?
And do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners? What method will you use to insperct miners?

**Comment by serafimey** [comment]
1: Video ( video of game streaming), pictures (game arts, commodity, advertisement, ), access log data, etc. Our company always use cloud, such as Ali Cloud,We used Ali Cloud 10T/month.
2:We want to store our data to 2-3 miners who are active in the community. We will find the miners who are active in the community.and we will inspect miners' storage space, past status of fault and recovery sectors, seal speed, industry reputation .

**Comment by rayshitou** [comment]
Nice.
Will you record your allocation decision in public? Which platform will you use?

**Comment by serafimey** [comment]
Yes, in github, under this issue.

**Comment by rayshitou** [comment]
Ok, have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision?

**Comment by serafimey** [comment]
No , we didn’t.

**Comment by rayshitou** [comment]
Finally, Can you guarantee that all these data you mentioned above abides by local regulations and in compliance with the recipient miner's terms of service?

**Comment by serafimey** [comment]
Yes,we can guarantee.

**Comment by rayshitou** [comment]
Hi, @serafimey
Our DataCap is finally assigned. 
It prompts "verified client already exists" when i allocate DataCap to your address on plus.fil.org. And i have checked that your address aready have 7TB DataCap.  I know that a lot of changes occurred while waiting for our DataCap. At present, it is not allowed to increase datacap for an already verified address([here](https://github.com/filecoin-project/specs-actors/issues/899)), so could you please provide another address for this application? Meantime, i need to know the details about the application you already got. Please attach the link here. Thanks!

**Comment by serafimey** [comment]
sorry，The9 singapore  haven't  made an application before.We posted the wrong address,The correct address should be f14gv3lvndhfzpo5imltbmeysagpknrexbi6e3nua. Thanks

**Comment by rayshitou** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7ikg7da54oaaydhu7gtynch6ur3ugbcb4rxszz3dkc37fnrcqde 
#### Address 
> f14gv3lvndhfzpo5imltbmeysagpknrexbi6e3nua
#### Datacap Allocated
> 3TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7ikg7da54oaaydhu7gtynch6ur3ugbcb4rxszz3dkc37fnrcqde
