### ISSUE TITLE
Client Allocation Request for: Filecoin Discover

### ISSUE THREAD

**Issue by ribasushi** [filecoin-project/filecoin-plus-client-onboarding#336]
---

# Client Allocation Questions 

## Core Information
- Name: Filecoin Discover
- Website / Social Media: https://store.filecoin-discover.com/
- Region: North America
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3vi5y7ykd4rlcjfhd6eyjuuvhqn2g52cx7elufvv4xmkfyjbo5epfurf3443ww3jaghy4po2yfjsl53xaysvq
- Notary Requested: ann-shin

**Comment by ann-shin** [comment]
Hi, nice to meet you. Thanks for your request. Can you kindly add more information here.
1.Are you representing for yourself or your company？
2.If you are representing for your company, Please give the following informations, duration of etablishment, number of employees, business scope, users volume, number of social media followers, data size to be stored, products or projects, and so on. If you are representing for yourself , please introduce yourself,such as number of social media followers, filecoin activities partipation with links, data size to be stored. Provide links to social media/news mentions. 
3.The history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time, etc.
Type, size, and source of the data you will be store on Filecoin,e.g. public data or private data, etc. Is there any sensitive or illegal content?
4.How do you intend to store the data on Filecoin, e.g. redundancy, location/miner preferences, etc
5.Have you already apply for DataCap to another notary, and whether it is accepted or rejected. Is there any reliable DataCap left?
6.Would you like to post real transactions on Github?

**Comment by ann-shin** [comment]
@ribasushi 
Hi, I haven't received your reply for a long time. 
The issue will be closed in two days.
If you want to continue, please submit your information as soon as possible.
Looking forward to your reply.
