### ISSUE TITLE
Client Allocation Request for: 上海冰塔信息科技有限公司

### ISSUE THREAD

**Issue by 163dong** [filecoin-project/filecoin-plus-client-onboarding#338]
---

# Client Allocation Questions 

## Core Information
- Name: 上海冰塔信息科技有限公司
- Website / Social Media: http://www.bytebase.cn/
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f12bw7aryzwrzzaty6r5ebooxgbezvbd62jj5dvoy
- Notary Requested: Fenbushi-Filecoin

Please make sure to check out the guidelines and criteria to accept Datacap request for [Fenbushi Capital](https://github.com/filecoin-project/filecoin-plus-client-onboarding/tree/main/Fenbushi%20Capital)

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced6ry2u7efzrrl62o5aqo3rzhfcbaibu3eiym2qhmv4qinqu5nisc 
#### Address 
> f12bw7aryzwrzzaty6r5ebooxgbezvbd62jj5dvoy
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced6ry2u7efzrrl62o5aqo3rzhfcbaibu3eiym2qhmv4qinqu5nisc
