### ISSUE TITLE
Client Allocation Request for: John McLaughlin/McKurz Capital Inc. RE #252

### ISSUE THREAD

**Issue by georgemac510** [filecoin-project/filecoin-plus-client-onboarding#341]
• Name: John McLaughlin, McKurz Capital Inc.
    • Website / Social Media: https://fin-file.herokuapp.com/ , https://mckurzcapital.com/
    • Region: North America
    • DataCap Requested: 1TiB
    • Addresses to be Notarized: 
                     f3suazi33hryyhksjtr6egyrtkusozjapk3gyke42np45yormcpjkgxx2mddccqu7ko4weeyzr4c6ekff2djwa
    • Notary Requested: andrewxhill

-----------------------------

**Comment by georgemac510** [comment]
• Name: John McLaughlin, McKurz Capital Inc.
• Website / Social Media: https://fin-file.herokuapp.com/ , https://mckurzcapital.com/
• Region: North America
• DataCap Requested: 1TiB
• Addresses to be Notarized: 
                 f3suazi33hryyhksjtr6egyrtkusozjapk3gyke42np45yormcpjkgxx2mddccqu7ko4weeyzr4c6ekff2djwa
• Notary Requested: andrewxhill

**Comment by georgemac510** [comment]
Hey @georgemac510, thanks for the request. To help with the verification process, could you please provide as thorough of answers as you can to the following questions.
1. Can you introduce yourself? Where can I find you online? Examples include Github, Twitter, LinkedIn, WeChat, etc., and more than one is encouraged.
2. If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?
3. In which region(s) do you intend to use the DataCap?
4. What is your use case for the DataCap being requested?
5. Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.
6. How many miners do you plan on allocating the DataCap? Please specify if you have a specific miner(s) you would like to allocate the DataCap.
7. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing? If so, how will you plan to report it?
8. Will your organization be responsible for allocating the full DataCap? Examples where this might not be the case, include app builders where the application end-users may have access to storage backed by the DataCap. Please read our full proposal for details on this approach. Unfortunately, our proposed multisig enabled DataCap provider is not ready today, but when it is, we will provider further documentation.
Hi Andrew,
Please find the responses to the above questions:
    1. I have been involved in blockchain development for nearly 4 years and specifically Filecoin since its ICO in 2017. I have participated in the ETHGlobal Filecoin hackathon last summer and continue to participate in Slingshot 2.1, 2.2 and now 2.3. I have and continued to use a hosted Powergate instance as well as two Hub instances for my Slingshot work.
A bit more about me and my experiences in blockchain development can be found at my LinkedIn address, https://www.linkedin.com/in/john-mclaughlin-981989a5/ and my firm's website, https://mckurzcapital.com/. One of my two Twitter accounts, thoroughly demonstrates my dedication to blockchain development, https://twitter.com/GeorgeMac510/with_replies. Please also reference our firm Twitter account @mckurz.
    2. I, John T McLaughlin III, represent McKurz Capital Inc. as its CEO. We are in the business of developing Ethereum and Tezos platform DeFi apps. McKurz Capital Inc. was incorporated in Delaware on 4/27/2020 and our business address is 8 The Green, Ste. A, Dover, DE 19901, USA. We have two other officers, Daniel Kurzweil, our Treasurer and John T. McLaughlin IV, our secretary.
    3. We intend to use the DataCap in North America and possibly Europe, if upload and retrieval with miners is efficient.
    4. Our use case is to continue to build our financial and digital asset investment datastore through our app Fin-File ( https://fin-file.herokuapp.com/) and to expand the functionality of the app for better data upload and retrieval through Textile Hub.
    5. As mentioned in #4, we ultimately would like to utilize Textile Hub using two other addresses to improve upload and retrieval for the Fin-File app.
    6. From recent experience, it is difficult to find available miners who are willing to store data for 1 year according to the Slingshot rules, so the list of miners changes regularly. we do have a preference to store with f01278, as his service is consistent and fairly priced. We do not mine on our own.
    7. I do agree on providing transparency of DataCap allocation and execution details to the public through posting a detailed .csv file which is required by the Slingshot competition for reward eligibility. It breaks down every transaction by data CID, miner, file name and type and start epoch. This will also be accessible when retrieving data through the Fin-File app.
    8. We as an organization will be solely responsible for allocating the entire DataCap. We are not reliant on end-users to allocate the DataCap.
    9. We have not been granted or applied for a DataCap before this application. We intend to verify two additional addresses so that we may be able use the Textile Hub, which will allow us to harness its great capabilities and we can further build our two datastores Fin-File Crypto and Fin-File Stock Market.
Thank you for your consideration. Please let us know, if you require any additional info/data.
Best regards,
John McLaughlin
McKurz Capital Inc.
Fin-File project

**Comment by andrewxhill** [comment]
Thanks @georgemac510. Your application looks good, happy to assign you the 1TiB datacap.

https://filfox.info/en/message/bafy2bzacebizdan5vtllohhd55v5shhyu2icyqmfpkipzxdb2dfzskqjgiwig

you can confirm that on https://verify.glif.io/ using the second form for "check".

for those other datacaps, since you are planning to use accounts on the hub, it's probably better if you apply through a notary other than Textile.
