### ISSUE TITLE
Client Allocation Request for: Eliovp!

### ISSUE THREAD

**Issue by Eliovp** [filecoin-project/filecoin-plus-client-onboarding#345]
# Client Allocation Questions 

## Core Information
- Name: Eliovp
- Website / Social Media: Eliovp / Filecoin.be
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3uzckly5va5fxwww3h6qmkj7yuys3umkv4m6jf5el3wv64gugw3aw5eoejmojykkfqijv7giumjk3c7erb7dq
-----------------------------

**Comment by Eliovp** [comment]
So what's going on here?

Requested datacap more than 2 weeks ago, no reply whatsoever.

Why are there certain parties receiving weekly datacap or more?

Is this a political program?

**Comment by dkkapur** [comment]
@Eliovp - as discussed on Slack, @philippbanhardt is not accepting applications for DataCap at the moment. Would suggest reaching out to different notaries. Thanks!
