### ISSUE TITLE
Client Allocation Request for: 上海没羞草文化传播有限公司

### ISSUE THREAD

**Issue by NicoleXiao-daling** [filecoin-project/filecoin-plus-client-onboarding#348]
# Client Allocation Questions 

## Core Information
- Name: 上海没羞草文化传播有限公司
- Website / Social Media: wechat account: gh_083b7ef19d08
- DataCap Requested: 50TiB
- Region: Greater China 
- Addresses to be Notarized: f1a5ofw7hbzqtybvaba2u4diz57e2utqje37zooka
- Notary Requested: ozhtdong

-----------------------------

**Comment by NicoleXiao-daling** [comment]
@ozhtdong Hi ozhtdong, it seems like my request is not assigned automatically to you, could you please process my request? Really appreciate it!

**Comment by dkkapur** [comment]
@NicoleXiao-daling - this notary is currently out of DataCap to allocate, would recommend you apply to another notary for the time being!
