### ISSUE TITLE
Client Allocation Request for: 北京中经天平科技有限公司

### ISSUE THREAD

**Issue by bjzjtp** [filecoin-project/filecoin-plus-client-onboarding#349]
---

# Client Allocation Questions 

## Core Information
- Name: 北京中经天平科技有限公司
- Website / Social Media: https://www.bjzjtp.com
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1sfq74iqhoseslc7vofvbdfknfo6tbtj2gnimgni
- Notary Requested: steven004

**Comment by steven004** [comment]
Hey @bjzjtp  , thanks for your request. Can you kindly add more information / context here on:

1. yourself/ your organization (with links to official website/social media/news mentions etc)
2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners)
5. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
6. Would you be OK in posting deal transactions here?

Thanks

**Comment by bjzjtp** [comment]
Hi,  @steven004 thank you very much for your quick response. Here are our information.

> Q1、Yourself/ your organization (with links to official website/social media/news mentions etc)

My name is Wang Bo, the Director of Depository Business of Zhongjing Tianping. I have been engaged in judicial related industries for more than 10 years and participated in a large number of evidence collection work such as CCTV Spring Festival Gala forensics, World Cup forensics, World Internet Conference depositing evidences, Jinri toutiao Short Video forensics, Oriental IC picture forensics, Tencent audio book forensics, Baidu News forensics, etc.
 
Beijing Zhongjing Tianping Technology Co., Ltd. (hereinafter referred to as Zhongjing Tianping), founded in 2017, is a joint-stock enterprise subordinate to the State Information Center (China Economic Network) and a strategic partner of the National Internet Emergency Response Center. With the approval of the Ministry of Justice, Zhongjing Tianping has established the Electronic Material Evidence Forensic Identification Center. Our business is to solidify the electronic data generated in various industries such as wills, finance, copyright, proof, electronic contracts, safety transportation, and judicial enforcement into electronic data evidence, which provides important reference value for the parties' rights protection, exemption, and traceability. Our WeChat official account is **zjtpyzx**.
 
Zhongjing Tianping focuses on product research and development in the field of national legal system construction and information construction. As an Internet technology company,our company is supported by core technologies and driven by participating in and promoting the construction of intelligent justice. At the same time, Zhongjing Tianping is also the first batch of domestic blockchain information service filing enterprise in China, the participating enterprise of the two high-level and one key special project (litigation risk result prediction platform based on multi-party evidence correlation analysis), the participating enterprise for writing version 1.0 of the White Paper on Blockchain Judicial Depository Application, and the Shuxin chain ecological application enterprise .

At present, Zhongjing Tianping has served more than 300 courts in 15 provinces and municipalities directly under the central government, and our business covers many industries such as will, finance, copyright, proof production, electronic contract, traffic safety, judicial execution, etc.

- In May 2018, Zhongjing Tianping, National Time Service Center of Chinese Academy of Sciences and Law Branch of China Information Association held a joint press conference on "Judicial Electronic Evidence Cloud Platform" and "Trusted Time Authentication Service Platform" at the State Information Center.
http://www.xinhuanet.com/politics/2018-05/25/c_1122888756.htm
https://www.chinacourt.org/article/detail/2018/05/id/3318363.shtml
https://baijiahao.baidu.com/s?id=1601423212828948507&wfr=spider&for=pc

- In March 2019, Zhongjing Tianping obtained the first batch of domestic blockchain information service records of the Cyberspace Administration of China.
http://www.cac.gov.cn/2019-03/30/c_1124305122.htm

- In June 2019, Zhongjing Tianping  participated in writing version 1.0 of the White Paper on Blockchain Judicial Depository Application.
http://www.caict.ac.cn/kxyj/qwfb/bps/201906/t20190614_201169.htm
 

> Q2、Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc) 

We haven't worked on IPFS/ Filecoin yet  but we're deeply interested indistributed storage so that we'd like to give it a try.
 

> Q3、Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin

Data types mainly include will, finance, copyright, proof, electronic contract, traffic safety, judicial execution, etc. These data are mainly from user deposit and collection of evidence, totaling about 3000TiB, and the data forms include video, audio, picture, document, compressed package, etc.
 

> Q4、Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners)

**Redundancy:** About 3 copies
**Location**: China
**Proportion**: 2~3 miners with proportion of 30%~70%.
**Requirements**: We intend to choose those who have good reputation, ability of high RawBytePower and less exceptional conditions.

> Q5、What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?

These data will be used for the user's electronic evidence retention and for forensic evidence presentation.The existing evidence adopts the "use" payment mode, which will be charged when the customer requests to use. No call no charge.
 

> Q6、Would you be OK in posting deal transactions here?

Yes, of course.

**Comment by steven004** [comment]
Hey @bjzjtp, it is so great to see you are interested by storing electronic evidence data in Filecoin network. I believe it is a wonderful and perfect scenario Filecoin could serve even in the earliest stage. 

One more question: I would think the data will not be publicly available, but only for evidence for judges or corresponding lawyers, is that right? I need to figure out a way to verify those data are what you mentioned, which is useful and valuable. If the data is private data, could I randomly check and ask your help for verification? 

And, it would be great if you could provide your business certificate, e.g. business license or any material which can prove your company. You can send me a mail for this from privacy point of view. 

Once I got your response, we can move forward to grant you the data-cap and I will see how to support your trial with Filecoin.

**Comment by bjzjtp** [comment]
Hi, @steven004 

Our data includes not only evidence for judges or corresponding lawyers but also pre-storage evidence to prevent lawsuits, such as dash cam recorders.  It is not convenient to disclosed for the privacy of evidence and we will encrypt it before we store.

To prove those data are what we mentioned, we would be happy to send you a sample of our data, the screenshots of our business and a copy of our business license via email. May I have your email address?

**Comment by bjzjtp** [comment]
@steven004 Dear Steven, haven't heard from you for days. If there is any problem with my information or documents? If so, please don't hesitate to tell us. Thank you very much.

**Comment by steven004** [comment]
@bjzjtp , since the data are private and will be encrypted before storing, we can not follow the normal way as public date to judge if the data is useful and valuable. 

Could you send me a sample via email? and then we can have more discussion on how to proceed with this kind of useful but non-disclosed data storing. Thanks for your patience and sorry for the inconvenience.

**Comment by bjzjtp** [comment]
@steven004 Thank you so...much. We have sent you the relevant documents via Email. Please fell free to contact if there is any problem.

**Comment by steven004** [comment]
Hey @bjzjtp , Your Datacap Allocation Request has been approved

**Message sent to Filecoin Network**
> [bafy2bzaceauhcy7hxq45pingne2bsuvakrkzphyhs2y2y4rhwnznjp2uh4zsu](https://filscan.io/tipset/message-detail?cid=bafy2bzaceauhcy7hxq45pingne2bsuvakrkzphyhs2y2y4rhwnznjp2uh4zsu) 

**Address**
> [f1sfq74iqhoseslc7vofvbdfknfo6tbtj2gnimgni](https://filscan.io/tipset/address-detail?address=f1sfq74iqhoseslc7vofvbdfknfo6tbtj2gnimgni)

**Datacap Allocated**
> 2 TiB

**Comment by bjzjtp** [comment]
| Deal ID  | Miner ID | Piece Size  | Start Epoch | End Epoch |
| ------- | ------------ | ---------- | ------------ | ------------ |
| 2008614 | f0142723     | 32.00 GiB  | 841628       | 2372094      |
| 2008613 | f0142723     | 32.00 GiB  | 841547       | 2372094      |
| 2008612 | f0142723     | 128.00 MiB | 841540       | 2372094      |
| 2003575 | f0142723     | 32.00 GiB  | 840688       | 2369214      |
| 2002930 | f0142723     | 32.00 GiB  | 840009       | 2369214      |
| 2002817 | f0142723     | 32.00 GiB  | 839930       | 2369214      |
| 2002816 | f0142723     | 32.00 GiB  | 839871       | 2369214      |
| 2002659 | f0142723     | 32.00 GiB  | 839812       | 2369214      |
| 2002658 | f0142723     | 32.00 GiB  | 839742       | 2369214      |
| 1997653 | f0142723     | 32.00 GiB  | 839162       | 2369214      |
| 1933982 | f0144313     | 32.00 GiB  | 782002       | 2312207      |
| 1933922 | f0144313     | 32.00 GiB  | 781170       | 2312207      |
| 1933912 | f0144313     | 16.00 GiB  | 781078       | 2312207      |
| 1933911 | f0144313     | 32.00 GiB  | 781036       | 2312207      |
| 1933910 | f0144313     | 16.00 GiB  | 781054       | 2312207      |
| 1933908 | f0144313     | 32.00 GiB  | 781000       | 2312207      |
| 1933896 | f0144313     | 32.00 GiB  | 780959       | 2312207      |
| 1933895 | f0144313     | 32.00 GiB  | 780938       | 2312207      |
| 1933894 | f0144313     | 32.00 GiB  | 780899       | 2312207      |
| 1933893 | f0144313     | 32.00 GiB  | 780877       | 2312207      |
| 1933892 | f0144313     | 32.00 GiB  | 780849       | 2312207      |
| 1933880 | f0144313     | 32.00 GiB  | 780160       | 2309327      |
| 1933879 | f0144313     | 32.00 GiB  | 780162       | 2309327      |
| 1933877 | f0144313     | 32.00 GiB  | 780114       | 2309327      |
| 1933876 | f0144313     | 16.00 GiB  | 780064       | 2309327      |
| 1933874 | f0144313     | 32.00 GiB  | 779741       | 2309327      |
| 1933873 | f0144313     | 32.00 GiB  | 779729       | 2309327      |
| 1933868 | f0144313     | 32.00 GiB  | 779509       | 2309327      |
| 1933867 | f0144313     | 32.00 GiB  | 779493       | 2309327      |
| 1933864 | f0144313     | 32.00 GiB  | 779046       | 2309327      |
| 1933382 | f0142723     | 32.00 GiB  | 767643       | 2297214      |
| 1917839 | f0142723     | 32.00 GiB  | 752213       | 2282814      |
| 1917464 | f0142723     | 32.00 GiB  | 751370       | 2279934      |
| 1917463 | f0142723     | 32.00 GiB  | 751346       | 2279934      |
| 1917158 | f0142723     | 32.00 GiB  | 751292       | 2279934      |
| 1916061 | f0142723     | 32.00 GiB  | 751076       | 2279934      |
| 1915718 | f0142723     | 16.00 GiB  | 751009       | 2279934      |
| 1915294 | f0142723     | 32.00 GiB  | 750586       | 2279934      |
| 1907577 | f0142723     | 32.00 GiB  | 744665       | 2274174      |
| 1907171 | f0142723     | 32.00 GiB  | 744642       | 2274174      |
| 1906664 | f0142723     | 16.00 GiB  | 744527       | 2274174      |
| 1906663 | f0142723     | 32.00 GiB  | 744151       | 2274174      |
| 1906440 | f0142721     | 32.00 GiB  | 742109       | 2270128      |
| 1903519 | f0142721     | 32.00 GiB  | 741848       | 2270128      |
| 1902678 | f0142721     | 32.00 GiB  | 740876       | 2270128      |
| 1902677 | f0142721     | 32.00 GiB  | 740871       | 2270128      |
| 1896948 | f0142721     | 32.00 GiB  | 736831       | 2264368      |
| 1896463 | f0142721     | 32.00 GiB  | 736811       | 2264368      |
| 1896056 | f0142721     | 32.00 GiB  | 736765       | 2264368      |
| 1895666 | f0142721     | 32.00 GiB  | 736713       | 2264368      |
| 1895363 | f0142721     | 32.00 GiB  | 736681       | 2264368      |
| 1894691 | f0142721     | 32.00 GiB  | 736625       | 2264368      |
| 1893992 | f0142721     | 32.00 GiB  | 736579       | 2264368      |
| 1893269 | f0142721     | 32.00 GiB  | 736524       | 2264368      |
| 1892635 | f0142721     | 32.00 GiB  | 736497       | 2264368      |
| 1891881 | f0142721     | 32.00 GiB  | 736468       | 2264368      |
| 1891191 | f0142721     | 32.00 GiB  | 736411       | 2264368      |
| 1888891 | f0142721     | 32.00 GiB  | 734950       | 2264368      |
| 1865193 | f0142721     | 32.00 GiB  | 729424       | 2258608      |
| 1861548 | f0442383     | 32.00 GiB  | 725467       | 2252877      |
| 1860870 | f0442383     | 32.00 GiB  | 725442       | 2252877      |
| 1860040 | f0442383     | 32.00 GiB  | 725432       | 2252877      |
| 1859273 | f0442383     | 32.00 GiB  | 725396       | 2252877      |
| 1858599 | f0442383     | 32.00 GiB  | 725326       | 2252877      |
| 1857963 | f0442383     | 32.00 GiB  | 725308       | 2252877      |
| 1857479 | f0442383     | 32.00 GiB  | 725252       | 2252877      |
| 1856892 | f0442383     | 32.00 GiB  | 725193       | 2252877      |
