### ISSUE TITLE
Client Allocation Request for: Qoptronics

### ISSUE THREAD

**Issue by will20210319** [filecoin-project/filecoin-plus-client-onboarding#350]
---

# Client Allocation Questions 

## Core Information
- Name: Qoptronics
- Website / Social Media: http://www.qoptronics.com/
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1r64svtdarpe3vqottqhpgskddnvnx52r6p5fsky
- Notary Requested: Broz221

**Comment by Broz221** [comment]
Thanks for your application. @will20210319 

We have finished long-term preparation and start to accept application. 

Please answer following questions:
1. What's your name? What's your duty in this company? Please give me your E-mail address and your brief introduction.
2. Please give me simple overview of your company. (Company scale, establish time, project, use case, etc.)
3. What's you/your company's contribution to Filecoin? (If exsit)
4. What kind of data do you want to store? And how much? How about  copy right of data?
5. How many miners do you want to store data to? Which aspect will you inspect these miners?
6. Could please you introduce your past usage of cloud storage?

**Comment by will20210319** [comment]
1、Hello, I'am  Gengpu Zhou, the CEO of this company. This is my E-mail, gengp_ zhou@qoptronics.com

2、Our company founded on January 3, 2017, which is a high-tech enterprise specializing in the R & D, production and sales of optical passive devices, optical testing equipment, laser light source, optical fiber amplifier and related products, and is committed to becoming a domestic production base of optical devices and optical communication systems. At present, the company has R & D expert from a number of domestic research institutes and well-known enterprises, engaged in research and development of communication industry for more than 10 years.

3、Not yet

4、Test data can be made public

5、It is estimated that it will be stored in 5 miners, each less than 30%, mainly depending on the location, scale and reputation of miners

6、We are currently using Ali cloud

**Comment by Broz221** [comment]
Hi. I sent E-mail to you to get private information such as Business license, certificate of authorization, your ID information, etc.

**Comment by will20210319** [comment]
Thank you so much,I have sent the email to you.

**Comment by Broz221** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedx56e66vsqze3b7brg3h6vnwjpwri2ix7qp3yrr2gf35fmjdif6i 
#### Address 
> f1r64svtdarpe3vqottqhpgskddnvnx52r6p5fsky
#### Datacap Allocated
> 5TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedx56e66vsqze3b7brg3h6vnwjpwri2ix7qp3yrr2gf35fmjdif6i
