### ISSUE TITLE
Client Allocation Request for: https://storage.market

### ISSUE THREAD

**Issue by jimmylee** [filecoin-project/filecoin-plus-client-onboarding#353]
<img width="1557" alt="Screen Shot 2021-04-07 at 1 39 20 PM" src="https://user-images.githubusercontent.com/310223/113930879-b01d2f00-97a6-11eb-8bea-69a9c0b1dc14.png">

# Client Allocation Questions 

## Core Information
- Name: ARG - Storage Market
- Website / Social Media: https://arg.protocol.ai, https://storage.market
- DataCap Requested: 20TB
- Region: North America
- Addresses to be Notarized: f3u5qyehz6vsr2sub3r7bvp7ag33yzwvrd6icz3kj7a2ppvpk7mayeswhjfswdbapeyxx43i7rltgzr7viq6oq
- Notary requested: @neogeweb3 

### Can you introduce yourself? Where can I find you online? Examples include Github, Twitter, LinkedIn, WeChat, etc., and more than one is encouraged.

The Application Research group at Protocol Labs has a website here: https://arg.protocol.ai, we also have a GitHub repository growing in popularity here: https://github.com/application-research, the website that will be engaging with the address is here http://storage.market.

People involved are @whyrusleeping @cwaring and @jimmylee

### If you represent an organization, what is the name, nature, registration country, time since inception, and named officers of your organization?

We work for Protocol Labs, more information can be found here https://protocol.ai

### In which region(s) do you intend to use the DataCap?

I am located in North America, but we will try to make deals with miners anywhere in the world. Currently we have made successful storage deals in North America, Oslo, and the UK.

### What is your use case for the DataCap being requested?

We are going to store meaningful open data sets on Filecoin.

### Do you plan to specify advanced features when utilizing a DataCap in your storage deal? If so, please specify the feature.

No we are unaware of what those advanced features may be.

### How many miners do you plan on allocating the DataCap? Please specify if you have a specific miner(s) you would like to allocate the DataCap.

Many miners will have personal pages on https://storage.market so it is hard to predict, but I will be working with https://file.app to find miners that Textile already works with.

### Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing? If so, how will you plan to report it?

Yes, every aspect of our code outside of secret keys is open source. The repo for this project is located at https://github.com/application-research

### Will your organization be responsible for allocating the full DataCap? Examples where this might not be the case, include app builders where the application end-users may have access to storage backed by the DataCap. Please read our full proposal for details on this approach. Unfortunately, our proposed multisig enabled DataCap provider is not ready today, but when it is, we will provider further documentation.

I am responsible.

### Please share any other information you believe is relevant to your application. If you or your org has received DataCap previously, could you share details on how this project differs or is an extension of those others.

I was the original founder of Slate up until February 2021 and the formation of https://arg.protocol.ai. https://storage.market is a way to take anything pinned to IPFS to make a storage deal. This is an easy way to get Slate buckets onto the Filecoin network, if the user chooses to.

**Comment by jimmylee** [comment]
**New!! Storage miner pages**
Today I released an early concept of a storage miner page, where a miner can share their storage miner page and make a Filecoin storage deal as long as they have a pinned IPFS CID they can reference. 

https://storage.market/f08403 ➝ TippyFlits ➝ Oxford, UK
https://storage.market/f01278 ➝ stuberman ➝ Michigan, USA
https://storage.market/f019551 ➝ NeonixAF f019551 ➝ Birmingham, UK
https://storage.market/f014768 ➝ Funk ➝ Singapore
https://storage.market/f01240 ➝ Wijnand Schouten @Hidde - Amsterdam, NL
https://storage.market/f023971 ➝ Brian Y ➝ Florida
https://storage.market/f023467 ➝ Phi-rjan ➝ Oslo, Norway
https://storage.market/f022142 ➝ Nelson ➝ New York, USA

It is super fun to work with an international group of miners, I'm sharing this because this is part of the reason I need the data cap.

**Comment by jimmylee** [comment]
I forgot to specify a notary, I'm hoping that @neogeweb3 or @andrewxhill will be willing to take this request?

**Comment by neogeweb3** [comment]
Thanks @dkkapur - Yes, I'd love to take this application.

**Comment by neogeweb3** [comment]
Let me know when this is assigned over to me, thank you.

**Comment by dkkapur** [comment]
@neogeweb3 - assigned it to you. Thanks for the quick response!

**Comment by neogeweb3** [comment]
@dkkapur - no problem, thanks. @jimmylee - love your work, the Datacap is on the way.

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedmkxhjatdqvgcirrm2ab5aueqrpwltd3uynaponnvpr2ovbaen6g 
#### Address 
> f3u5qyehz6vsr2sub3r7bvp7ag33yzwvrd6icz3kj7a2ppvpk7mayeswhjfswdbapeyxx43i7rltgzr7viq6oq
#### Datacap Allocated
> 20TB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmkxhjatdqvgcirrm2ab5aueqrpwltd3uynaponnvpr2ovbaen6g
