### ISSUE TITLE
Client Allocation Request for: Alyale Philippines, Inc.

### ISSUE THREAD

**Issue by michik0y** [filecoin-project/filecoin-plus-client-onboarding#4]
---

# Client Allocation Questions 

## Core Information
- Name: Alyale Philippines, Inc.
- Website / Social Media: https://www.alyale.com/
- DataCap Requested: 100GiB
- Addresses to be Notarized: f3qqhbwhgorbtymzhq5wxnointwl4tl5riqvxv35utyuhlisbz4247io32oshff2emysu5fzc2t4msh64ahlpq
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Closing this issue as it appears to be a duplicate to https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/3
