### ISSUE TITLE
Client Allocation Request for: Chengdu Digital Media Industry Base Co., Ltd.

### ISSUE THREAD

**Issue by cdsmlhw** [filecoin-project/filecoin-plus-client-onboarding#401]
# Client Allocation Questions 

## Core Information
- Name: Chengdu Digital Media Industry Base Co., Ltd.
- Website / Social Media: www.cd-szmt.com
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1b7so6mamjawgr2j74ptqbbge5pnme6ocp2puxlq
- Region: Greater China

-----------------------------

**Comment by dkkapur** [comment]
@cdsmlhw  as FYI, @philippbanhardt is no long accepting applications. Closing this issue out for the time being. Would recommend you apply to a different notary. Thanks!
