### ISSUE TITLE
Client Allocation Request for: AetherWorks, LLC

### ISSUE THREAD

**Issue by rmacinnis** [filecoin-project/filecoin-plus-client-onboarding#404]
---

# Client Allocation Questions 

## Core Information
- Name: AetherWorks, LLC
- Website / Social Media: https://www.AetherWorks.com/
- Region: North America
- DataCap Requested: 260TiB
- Addresses to be Notarized: f3xdlovm6hxjb2nobtuv22lxuzc6tii34xron5xgtr5o24xqubi73euxseozzk3g3646jmzgs7nynlxilhz7aq
- Notary Requested: ann-shin

@rmacinnis Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ann-shin** [comment]
Hi, nice to meet you. Thanks for your request. Can you kindly add more information here.
1.Are you representing for yourself or your company？
2.If you are representing for your company, Please give the following informations, duration of etablishment, number of employees, business scope, users volume, number of social media followers, data size to be stored, products or projects, and so on. If you are representing for yourself , please introduce yourself,such as number of social media followers, filecoin activities partipation with links, data size to be stored. Provide links to social media/news mentions.
3.The history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time, etc.
Type, size, and source of the data you will be store on Filecoin,e.g. public data or private data, etc. Is there any sensitive or illegal content?
4.How do you intend to store the data on Filecoin, e.g. redundancy, location/miner preferences, etc
5.Have you already apply for DataCap to another notary, and whether it is accepted or rejected. Is there any reliable DataCap left?
6.Would you like to post real transactions on Github?

**Comment by rmacinnis** [comment]
Hi Dr. Shin:

I expect that you will have some follow-up questions, so I have found your previous question lists and endeavored to answer them below. Please let me know if you would like any more info - thank you!

-Dr. Robert MacInnis



1.Are you representing for yourself or your company？
My R&D company, AetherWorks.

2.If you are representing for your company, Please give the following informations, duration of etablishment, number of employees, business scope, users volume, number of social media followers, data size to be stored, products or projects, and so on. If you are representing for yourself , please introduce yourself,such as number of social media followers, filecoin activities partipation with links, data size to be stored. Provide links to social media/news mentions.

Founded in 2010, AetherWorks is a software research & venture development firm. We design, patent, develop & commercialize IP assets, with a particular focus on fault tolerant distributed systems. As AetherWorks's founder & CEO, I hold a Ph.D. in computer science and have been granted multiple patents in the areas of distributed storage and fog computing. 

AetherWorks was an early investor in Filecoin back in 2017.

One of our first products was AetherStore, a fault-tolerant distributed storage system. AetherStore pools spare storage from existing hardware to create a private local cloud, reducing IT hardware expense and management. Consumer-friendly, commercial-grade. 34,000+ users in 162 countries

Our most recent product, developed & launched before AetherWorks significantly wound down operations in 2019, is ActiveAether - a global serverless computing platform for microservices & pre-trained neural networks that automatically utilizes the most geographically appropriate computing resources available, from edge to cloud, with a focus on enabling 5G use-cases and enabling individuals to get paid to rent out their spare computing power. 
ActiveAether co-sponsored (with Cisco) Fog World Congress 2018, the premiere global event of the OpenFog Consortium (now a part of the Industrial IoT ‘IIoT’ Consortium) where I was the keynote speaker. (15.2k followers @ https://twitter.com/ActiveAether)

3.The history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time, etc.

AetherWorks was an early investor in Filecoin back in 2017.

Type, size, and source of the data you will be store on Filecoin,e.g. public data or private data, etc. Is there any sensitive or illegal content?

All of our datasets are from the curated list for the Slingshot competition.
We have downloaded, sliced up, and Reed-Solomon encoded three datasets: 1) Huge Stock Market Dataset (772MB - this was for practice), 2) Open Images Dataset (18TB), and 3) CCAFS-Climate Data. As per the suggestion of the competition organizers, we intend to store roughly 10 copies of each 32GB sector, utilizing miners from around the globe. The data will be served from a multi-zone AWS bucket, so will have excellent bandwidth, and we have also procured physical disks (16TB 2.5in SATA) in order to do offline deals as well - mostly to see how that whole process works in practice!

In addition to the Slingshot curated datasets, an Aetherworks organization called "MooseDar" has compiled roughly 85GB of moose, elk, mule deer, and black bear photographs that have been used to train up a CNN to detect and alert drivers to the presence of these animals using roadside IR cameras, jetson nano's, and some flashy lights. While not on the curated list, we feel like this is a valuable dataset and look forward to sharing it with the world.

4.How do you intend to store the data on Filecoin, e.g. redundancy, location/miner preferences, etc

Indicated above. Worth noting: we have messed around with setting up a mining rig (took 3 installs/configs to get it right!) using some cloud instances, but have never operated an actual miner and do not plan to do so.

5.Have you already apply for DataCap to another notary, and whether it is accepted or rejected. Is there any reliable DataCap left?

We have not applied to another notary, but in order to understand the process better we requested the 32GB 'automatic validation' option from fil.org/filplus for a different address earlier today.

6.Would you like to post real transactions on Github?

I believe they'll all be posted in the Slingshot results, but yeah - absolutely. I hope the instructions in our documentation will help people get over some of the hurdles that we've had to struggle through in order to get to this point - and we're super excited to help contribute to reaching the overall Slingshot goal of 10PiB!!

**Comment by XnMatrixSV** [comment]
Hi, Dr. Robert.
We want to confirm with you before allocating.
Whether the Slingshot data you intend to store is your own data?
We prefer to the client who can generate valid and reliable data.
you can find it in our classification rules(https://docs.google.com/spreadsheets/d/1LjVLLmV0GxEDZf4eH5hv3m2v00qDzbKlez9g0-t95RY/edit?usp=sharing)

**Comment by rmacinnis** [comment]
Hi Dr. Shin,

Thank you for your note.

We intend to store two types of data - #1) is from the Slingshot 'curated storage sets' list, and #2) is generated by an AetherWorks company called 'MooseDar'.

#1) Slingshot rules require the selection and storage of one (or more) of the datasets listed at the following URL: https://github.com/filecoin-project/slingshot/blob/master/datasets.md

We intend to store three of these datasets with 10x replication split amongst a globally-diverse set of miners: 1) Huge Stock Market Dataset (772MB [x10=7.5TB] - small, for practice), 2) Open Images Dataset (18TB [x10=180TB]), and 3) CCAFS-Climate Data (6.8TB [x10=67TB]). 

Links to each as follows: 1) Huge Stock Market Dataset (https://www.kaggle.com/borismarjanovic/price-volume-data-for-all-us-stocks-etfs), 2) Open Images Dataset (https://storage.googleapis.com/openimages/web/index.html), and 3) CCAFS-Climate Data (http://www.ccafs-climate.org/).

#2) In addition, our organization has a number of data-centric projects for which we will look forward to utilizing Filecoin to store the datasets in perpetuity & make available to the masses.

MooseDar is one such project: a project for alerting drivers to the presence of large wildlife on the roadway in real time. We have collected an 85GB dataset thus far, of infrared images of animals crossing roadways, and used these to train up a neural network that can detect these events in real-time. We presently have a pilot that utilizes this neural net on a roadside trailer and, upon an inference, alerts drivers to the presence of large animals on the road. As we continue to take video and photos of each such event this dataset will grow and we look forward to adding to it continually. This can be a benefit in training other such systems, as well as training the detection systems of autonomous vehicles, and generally reducing traffic fatalities (for both humans & animals) worldwide.

Yours sincerely,

-Rob

**Comment by XnMatrixSV** [comment]
#2) In addition, our organization has a number of data-centric projects for which we will look forward to utilizing Filecoin to store the datasets in perpetuity & make available to the masses.
Sounds perfect.
Your organization is an L2 with a score of 2, 5 TiB will be granted this time.
Please check Addresses to be Notarized: f3xdlovm6hxjb2nobtuv22lxuzc6tii34xron5xgtr5o24xqubi73euxseozzk3g3646jmzgs7nynlxilhz7aq

**Comment by rmacinnis** [comment]
That's terrific, thank you!

Address confirmed: f3xdlovm6hxjb2nobtuv22lxuzc6tii34xron5xgtr5o24xqubi73euxseozzk3g3646jmzgs7nynlxilhz7aq

**Comment by XnMatrixSV** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceajovmaetaavzprva4zcn3bdcvtrrebpcqhh2io4lydqvlc5obh2c 
#### Address 
> f3xdlovm6hxjb2nobtuv22lxuzc6tii34xron5xgtr5o24xqubi73euxseozzk3g3646jmzgs7nynlxilhz7aq
#### Datacap Allocated
> 5TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajovmaetaavzprva4zcn3bdcvtrrebpcqhh2io4lydqvlc5obh2c
