### ISSUE TITLE
Client Allocation Request for: ALO360

### ISSUE THREAD

**Issue by chuanfu2021** [filecoin-project/filecoin-plus-client-onboarding#405]
---

# Client Allocation Questions 

## Core Information
- Name: ALO360
- Website / Social Media: https://alo360.com/
- Region: Asia excl. Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1qtnta4wlrx4s6lkm23kzacdo46gw5lehw2fjn4i
- Notary Requested: ericfish

@chuanfu2021 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by rayshitou** [comment]
Hi, @chuanfu2021 , glad to see you. 
As a normal procedure, I need to ask you some questions:
What's your name and your position in your company?
What's your company's business? and could you show me your company's business license?

**Comment by chuanfu2021** [comment]
Hi，rayshitou
1. My name is Phuong Phan the technical development director of ALO360.com
2. ALO360.COM Joint Stock Company was established in 2014. With the professional team, who have many years of experience in the field of Digital Signage solutions integrated software. Our service process is closed from the consulting step to the solution development, installation and project warranty. 
<img width="386" alt="图片 091" src="https://user-images.githubusercontent.com/81168786/116210909-e4688780-a775-11eb-9d70-b60b105aba0c.png">

**Comment by rayshitou** [comment]
Thanks for your introduction.
What kind of data do your company want to store and have you ever use any cloud to store these data? What's your usage volume and frequency?
And do you plan on allocating a substantial portion of your DataCap to a single miner, or will you spread it across many miners? What method will you use to insperct miners?

**Comment by chuanfu2021** [comment]
Hi,rayshitou
1.We want to be able to store some e-commerce merchandise information in the Filecoin network,About 5TiB
2.We will distribute the data across multiple miners,the scale and distance of the miners is a major concern for us.

**Comment by rayshitou** [comment]
Will you record your allocation decision in public? Which platform will you use?

**Comment by chuanfu2021** [comment]
Hi,rayshitou
Yes,we will record our allocation decision in Github.

**Comment by rayshitou** [comment]
Ok, have you been approved for a DataCap previously? If so, can you share the details of the last allocation decision?

**Comment by chuanfu2021** [comment]
None.

**Comment by rayshitou** [comment]
OK. 
Finally, can you guarantee that all these data you mentioned above abides by local regulations and in compliance with the recipient miner's terms of service?

**Comment by chuanfu2021** [comment]
Yes.

**Comment by rayshitou** [comment]
Ok, I have no other questions, I will allocate DataCap for you.

**Comment by rayshitou** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced4wt2vqbdwodsg4mu35hfxzk2tccnu2hhzt5srleg2m4xxs3vtis 
#### Address 
> f1qtnta4wlrx4s6lkm23kzacdo46gw5lehw2fjn4i
#### Datacap Allocated
> 5TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced4wt2vqbdwodsg4mu35hfxzk2tccnu2hhzt5srleg2m4xxs3vtis
