### ISSUE TITLE
Client Allocation Request for: 苏州青云瑞晶生物科技有限公司

### ISSUE THREAD

**Issue by szqyrj** [filecoin-project/filecoin-plus-client-onboarding#406]
---

# Client Allocation Questions 

## Core Information
- Name: 苏州青云瑞晶生物科技有限公司
- Website / Social Media: www.readcrystal.com
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1rtfo4pmlvfo6a5sid3cfp7ikpm4s7p4ogvysjoq
- Notary Requested: steven004

@szqyrj Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by steven004** [comment]
Hey @szqyrj   , thanks for your request. Can you kindly add more information / context here on:

1. yourself/ your organization (with links to official website/social media/news mentions etc)
2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners)
5. How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
6. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
7. Would you be OK in posting deal transactions here?

Thanks

**Comment by szqyrj** [comment]
Hi, thanks a lot. Here are our answers.

1.Suzhou Qingyun Ruijing Biological Technology Co., Ltd. (hereinafter referred to as Qingyun Ruijing) was founded in 2019. Our main business is to provide customers with testing services and solutions in the fields of drug solid-state research, structural biology, new drug screening & optimization, etc. We currently have more than 30 million yuan of drug research and development experimental platform which includes advanced experimental equipment in the fields of cryo-transmission electron microscopy, protein expression purification & crystallization and solid-state drug research.

Qingyun Ruijing is a global leader in the field of MicroED and cryoelectron microscope single particles and has published more than 5 papers in Nature, Science and Cell as the first author and corresponding author in related fields.

Our website is  www.readcrystal.com and the following is  one of our media reports.
http://k.sina.com.cn/article_1750070171_684ff39b02000uq9y.html?sudaref=www.baidu.com&display=0&retcode=0

2.We have no experience on IPFS/Filecoin, neither have applications nor do any do experiments to store data on IPFS or Filecoin network, but we are now trying to understand more about it and participate actively.

3.Most of the data to be stored comes from experimental data , mainly including tif and mrc files, with a total amount of about 100TiB. We have no plan to make it public for privacy reseaon but we promise that the data to be stored conforms to national laws and regulations.

4.We plan to find 2-4 more cost-effective miners in China, and the storage proportion of a single miner is  about 25%-50%.

5.No, we don't have.

6.Non-profit.

7.Yes，of cource.

**Comment by szqyrj** [comment]
Dear Steven, haven't received your reply for 5 days. Is there anything wrong with my information or any further documents I need to supply?
One more thing, my filecoin address needs to be changed. I will give you later.

**Comment by szqyrj** [comment]
Dear @steven004 , our new adress is:
f3vuexiyzjdysxoiw6h3bprcil32kumrowhe35mu2pctq6cfi5ksg7ybbw43udkrzmryrkkkaluzz23x3vijra

**Comment by steven004** [comment]
Hey @szqyrj , it's so great to have companies like readcrystal  to join IPFS/Filecoin ecosystem, we believe we could build a great future together while a new distributed storage platform is set up.

To help you start, I would like to allocate 2TiB as an initial trial datacap for you to do some experiment immediately, please simply submit a new request if you need more. And, please let me know if you need any help on the IPFS/Filecoin storing development or miner information.

In the mean time, it would be great if you can share me your business certificate (you can share with me via email for privacy), thus we can move forward smoothly next when allocate much more datacap if needed. And, we can discuss your data's type in detail, and how to verify for different types.

**Comment by steven004** [comment]
Hey @szqyrj , Your Datacap Allocation Request has been approved

**Message sent to Filecoin Network**
> [bafy2bzacedem72jmxds4u56hkccjb2o52usftb6obdqbcppl6zvuh25hvbowi](https://filscan.io/tipset/message-detail?cid= bafy2bzacedem72jmxds4u56hkccjb2o52usftb6obdqbcppl6zvuh25hvbowi) 

**Address**
> [f3vuexiyzjdysxoiw6h3bprcil32kumrowhe35mu2pctq6cfi5ksg7ybbw43udkrzmryrkkkaluzz23x3vijra](https://filscan.io/tipset/address-detail?address= f3vuexiyzjdysxoiw6h3bprcil32kumrowhe35mu2pctq6cfi5ksg7ybbw43udkrzmryrkkkaluzz23x3vijra)

**Datacap Allocated**
> 2.0TiB
