### ISSUE TITLE
Client Allocation Request for: 成都数字媒体产业化基地有限公司

### ISSUE THREAD

**Issue by cdsmlhw** [filecoin-project/filecoin-plus-client-onboarding#407]
---

# Client Allocation Questions 

## Core Information
- Name: 成都数字媒体产业化基地有限公司
- Website / Social Media: www.cd-szmt.com
- Region: Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1b7so6mamjawgr2j74ptqbbge5pnme6ocp2puxlq
- Notary Requested: steven004

@cdsmlhw Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by steven004** [comment]
Hey @cdsmlhw  , thanks for your request. Can you kindly add more information / context here on:

1. yourself/ your organization (with links to official website/social media/news mentions etc)
2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners)
5. How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
6. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
7. Would you be OK in posting deal transactions here?

Thanks

**Comment by cdsmlhw** [comment]
Thank you, @steven004 according to your request, we would like to provide following information:

1.Chengdu Digital Media Industrialization Base Co., Ltd. was established on January 5, 2005 which is one of the four national digital media technology industrialization bases established by the Ministry of Science and Technology throughout the country. It's main features are digital games, including online games and mobile games. In 2012, the Chengdu Municipal Party Committee Propaganda Department, Science and Technology Bureau, Culture Bureau, and Guangxin Bureau jointly issued a base construction implementation plan, and recognized Chengdu Digital Media Industrialization Base Co., Ltd. as the executive agency of "Chengdu National Cultural and Technological Integration Demonstration Base".
Our website is www.cd-szmt.com and our Blog is 藏羌彝文化（the account is registered by Sichuan Huizhi Culture Communication Co., Ltd., a holding subsidiary of Chengdu Digital Media Industrialization Base Co., Ltd.）

2.No working history yet, but we do believe that decentralized storage can help us to store the relevant data generated in the process of work at a low cost. We are mainly looking for storage services.

3.At the beginning, we planned to store the intangible cultural heritage of the Tibetan, Qiang and Yi peoples, which recorded the cultural characteristics and heritage of China's ethnic minorities. It includes video, audio, photos and more......
These data are all produced by ourselves with independent intellectual property rights, and the total amount is about 1PiB.

4.We plan to allocate 2-3 Chinese miners, with a redundancy of 2-3, and the proportion is expected to be 4/6 or 2/2/6. At present, we have no clear target for storage and are looking for reliable miner with cost-effective services.

5.It will be available on the chain.

6.We plan to develop front-end application of data, revitalize our own data resources related to Tibetan, Qiang and Yi culture, and provide them to film& television lovers and film&television production institutions for downloading and usage.
It is profitable. We will charge when users download the data.

7.Yes

**Comment by cdsmlhw** [comment]
Dear @steven004 , there is something wrong with our filecoin address and we are checking the problem. Please confirm with us before allocating. Thank you very much.

**Comment by steven004** [comment]
Hey @cdsmlhw , what do you mean by "something wrong with the filecoin address"? 
I can find this address is already active here: https://filscan.io/tipset/address-detail?address=f1b7so6mamjawgr2j74ptqbbge5pnme6ocp2puxlq

**Comment by cdsmlhw** [comment]
Hey, @steven004, Thanks for your reply. We lost private key by accident and had applied for a new one as below:
f3ufjwdxayyld2adudldyvjfavywmptqwmcmd2otd7olwc4bsukwtnbmfeal4bglxpgmzfaribovnc6mvfp4za

**Comment by steven004** [comment]
One more question: 
> 3.At the beginning, we planned to store the intangible cultural heritage of the Tibetan, Qiang and Yi peoples, which recorded the cultural characteristics and heritage of China's ethnic minorities. It includes video, audio, photos and more......
These data are all produced by ourselves with independent intellectual property rights, and the total amount is about 1PiB.

I understand that the data are very valuable with independent intellectual property rights. The question is whether the data be uploaded into Filecoin encrypted for private access, or non-crypted for publicly available?

**Comment by cdsmlhw** [comment]
Non-crypted for publicly available.

**Comment by steven004** [comment]
Hey @cdsmlhw , Your Datacap Allocation Request has been approved

**Message sent to Filecoin Network**
> [bafy2bzaceav5xhz35zvjbgsxvsydleotpl24d55jkl5u6ouosw6r47ipq3v5o](https://filscan.io/tipset/message-detail?cid=bafy2bzaceav5xhz35zvjbgsxvsydleotpl24d55jkl5u6ouosw6r47ipq3v5o) 

**Address**
> [f3ufjwdxayyld2adudldyvjfavywmptqwmcmd2otd7olwc4bsukwtnbmfeal4bglxpgmzfaribovnc6mvfp4za](https://filscan.io/tipset/address-detail?address= f3ufjwdxayyld2adudldyvjfavywmptqwmcmd2otd7olwc4bsukwtnbmfeal4bglxpgmzfaribovnc6mvfp4za)

**Datacap Allocated**
> 5.0TiB
