### ISSUE TITLE
Client Allocation Request for: Julien NOEL - Twinquasar

### ISSUE THREAD

**Issue by s0nik42** [filecoin-project/filecoin-plus-client-onboarding#408]
---

# Client Allocation Questions 

## Core Information
- Name: Julien NOEL - Twinquasar
- Website / Social Media: @s0nik42
- Region: Europe
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3rpqqflz4bhyylporz3kjhejftvfs2gbjxv7gcw3imvviklmrqgee2jqsgp6hrl35ufckv76kdd245q352dtq
- Notary Requested: neogeweb3

@s0nik42 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by s0nik42** [comment]
Hi @neogeweb3 ,

We're uploading a public dataset to filecoin, We previously work with the Filecoin Fundation (Philipp)  in EU, but now, We're the only remaining notary in EU. That's the reason why we decided to apply to a notary in another region. 

Previous granted application : https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/145

Thank you,

Julien

**Comment by neogeweb3** [comment]
Hey @s0nik42, thanks for the request. I do see the difficulty while you are the only notary in EU, but I could only allocate 5TiB to you at this moment because I have already allocated quite a lot DataCap to the EU while I am the GCN notary. Do you mind issuing another 5TiB request after you used up the first 5TiB?

**Comment by s0nik42** [comment]
Hi @neogeweb3 , <e can split in 2 requests.5TiB is perfect for now.

Thank you,

Julien

**Comment by neogeweb3** [comment]
Great! Thanks for understanding, @s0nik42!

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecwv6m6jc3grs4twywjeab5du64ppcfkdtuvs53fmb7chmqr377mm 
#### Address 
> f3rpqqflz4bhyylporz3kjhejftvfs2gbjxv7gcw3imvviklmrqgee2jqsgp6hrl35ufckv76kdd245q352dtq
#### Datacap Allocated
> 5TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecwv6m6jc3grs4twywjeab5du64ppcfkdtuvs53fmb7chmqr377mm
