### ISSUE TITLE
Get The Secret Key of the grandted client address Lost.

### ISSUE THREAD

**Issue by LandsatFile20** [filecoin-project/filecoin-plus-client-onboarding#409]
In the process of forced upgrade  lotus1.6, (we have dozens of wallet addresses, only the part with assets were backed up)
We did not back up this wallet key which was granted datacaps.(forget the secret key)(**f3xcu5ykb4cfoeyhvgy57outenx4njndazzgakcoebjiuvxrpwpl3bpv7wzfbvplgdq3w4mn5ke6ek2zuzpiea**),
([Granted link](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/67) )

- How to destroy this address's datacaps.(We've made sure we can't retrieve the address)
- How to assigned to a new address. (Or reapply)

**Comment by dkkapur** [comment]
@LandsatFile20 - we should continue this discussion here: https://github.com/filecoin-project/notary-governance/issues/119. Closing this issue out for now.
