### ISSUE TITLE
Client Allocation Request for: 福州浩能云网络科技有限公司

### ISSUE THREAD

**Issue by LandsatFile20** [filecoin-project/filecoin-plus-client-onboarding#414]
# Client Allocation Questions 

## Core Information
- Name: 福州浩能云网络科技有限公司
- Website / Social Media: https://preview.filhub.com
- DataCap Requested: 6.8TiB
- Addresses to be Notarized: f3vdhnovvu3si7cjwwqgx36jw7gu557qozazkej77fm5si6a5sx4jpmzfwwnsljq2pycezlnthac6ryfbokxma
- Notary Requested: Fenbushi-Filecoin
- Reapply for datacaps : https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/409
- Email: hao@filhub.com
- Weichat : Gcaitou

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea45cwu7dzjec44gqdngnaonumqi5wcp3t3vkpead4tpf74mmnlua 
#### Address 
> f3vdhnovvu3si7cjwwqgx36jw7gu557qozazkej77fm5si6a5sx4jpmzfwwnsljq2pycezlnthac6ryfbokxma
#### Datacap Allocated
> 6.8TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea45cwu7dzjec44gqdngnaonumqi5wcp3t3vkpead4tpf74mmnlua
