### ISSUE TITLE
Client Allocation Request for: Textile.io

### ISSUE THREAD

**Issue by andrewxhill** [filecoin-project/filecoin-plus-client-onboarding#417]
---

# Client Allocation Questions 

## Core Information
- Name: Textile.io
- Website / Social Media: https://textile.io/ https://twitter.com/textileio https://www.linkedin.com/company/textile
- Region: North America
- DataCap Requested: 3TiB
- Addresses to be Notarized: f144zep4gitj73rrujd3jw6iprljicx6vl4wbeavi
- Notary Requested: ann-shin

@andrewxhill Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by andrewxhill** [comment]
Hi @XnMatrixSV, this is tagged to the wrong assignee currently but is intended for you. I wanted to share some project background here to get the application started.

1. We have an outstanding datacap on another address that was awarded by you here https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/234. We have about 1/2 of the datacap remaining.
2. We are applying for datacap on a new address because this is a different project using a different lotus node with a different use-case entirely, so we didn't want to mix them up today.

New project:

We are building a high-throughput deal-making system that will allow miners to connect to and receive deals easily. We aim to deploy the system at a much larger scale but are in a testing phase. We are performing tests using non-Mainnet miner setups now but are getting ready for Mainnet testing next. 

For our tests, we'll be connecting with 3-5 miners over the next month to ensure the full deal creation and storage workflow works properly on mainnet (including payments etc). For that, we'll be storing a mix of useful public data and some arbitrary data for testing purposes alone. I've had a few conversations to date to assess if this kind of testing should be eligible for datacap, and it seems that so far, the consensus is that it should, but let me know what you think. In the spirit of experimentation, though, I'm keeping the datacap request reasonably small.

**Comment by XnMatrixSV** [comment]
Hi，@andrewxhill 
Thanks for your application. I'm sorry that you cannot apply directly before allocated Datacap have been used up.
You could supplement the description of new project on the previous  issue. we would make a judgement and you can use part of Datacap for new project after that.
If you want to apply for more Datacap after using, you can open another issue.

**Comment by XnMatrixSV** [comment]
If you experience problems in practice, you can write to me, and I'm always ready to help you.

**Comment by andrewxhill** [comment]
If I understand your proposal it doesn't work that well in practice for a client. I think our setup will be common in larger FIL integrations. Let me explain our situtation.

1. We have a bunch of different Filecoin deployments in our infrastructure.
2. Different deployments are used for different tasks in our company. Some are deployed to our SAAS platform to manage storage queues, others we use in daily building/testing, others we use just to hold balances, etc. 
3. It's not so easy to take one address from one system and use it for another system.

The Datacap we applied for originally was for a project that involved our system backup and recovery systems. So it had a specific address that it uses to manage deals on Filecoin from that area of work. We plan to continue the backup and recovery project using that address and will continue to use that Datacap.

This new project, is using a new node that is run as part of a different stack unrelated to our SAAS systems. We cannot transfer the address in use to this new node. So, reassigning the existing datacap from one node to another isn't an option. This is a totally new project, so it made sense to me to apply for a totally different datacap. 

Happy to open the old ticket, but the old address isn't helpful. Let me know if you have any questions.

**Comment by XnMatrixSV** [comment]
1.Could you give a description of the cooperation mechanisms with miners you chose before, such as how do you find them, the reason why you choose them, and datacap allocation proportion, etc.
2.Would you be OK in posting deal transactions in the previous issue?
3.Is it convenient for users to retrieve and view data you stored? Can you provide detailed steps.

**Comment by andrewxhill** [comment]
> 1.Could you give a description of the cooperation mechanisms with miners you chose before, such as how do you find them, the reason why you choose them, and datacap allocation proportion, etc.

We focused on a list of small miners that were part of the first minerx fellowship. 

> 2.Would you be OK in posting deal transactions in the previous issue?

Sure, for continuity of the other proposal, I've added it as a comment here https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/234#issuecomment-833763127. 

The summary is that we used 13 miners. They each received a portion of the deals between 4.5% and 13.6% of all the deals we created. 

> 3.Is it convenient for users to retrieve and view data you stored? Can you provide detailed steps.

Not really. As mentioned in the first grant

> The data is already publically available on the IPFS DHT. However, we will encrypt the content contained in each deal as it isn't inteded for public use, the aim is to add data security to our platform. We have other ways that individual users of our services can store their data in public deals that wont be included in the use of this datacap.

**Comment by XnMatrixSV** [comment]
One more question:

>  We cannot transfer the address in use to this new node. 

As we know, the same Filecoin address can be used for different nodes. We can't understand this statement. Could you give more explanation about that?

**Comment by andrewxhill** [comment]
This just reflects the architecture of our systems. We generally create new addresses for different jobs or different infrastructure, we don't mix them or transfer them.

**Comment by XnMatrixSV** [comment]
Considering the demand of the new project, we will still agree with your application this time
Please confirm your Filecoin address : f144zep4gitj73rrujd3jw6iprljicx6vl4wbeavi
