### ISSUE TITLE
Client Allocation Request for: Himelight

### ISSUE THREAD

**Issue by zxzccstor1** [filecoin-project/filecoin-plus-client-onboarding#423]
---

# Client Allocation Questions 

## Core Information
- Name: Himelight
- Website / Social Media: https://www.himelight.com/org/59a7d564c809aa474f41089c
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f14sxp3wifjn2vkk4svwvz7vhphps7u2yveagbw5i
- Notary Requested: Broz221

@zxzccstor1 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Broz221** [comment]
Thanks for your application.

Please answer following questions:

What's your name? What's your duty in this company? Please give me your E-mail address and your brief introduction.
Please give me simple overview of your company. (Company scale, establish time, project, use case, etc.)
What's you/your company's contribution to Filecoin? (If exsit)
What kind of data do you want to store? And how much? How about copy right of data?
How many miners do you want to store data to? Which aspect will you inspect these miners?
Could please you introduce your past usage of cloud storage?

**Comment by zxzccstor1** [comment]
1.Hello, I am Roy Chao, Deputy Technical Director of Himelight Taiwan,Responsible for the related research on the application of blockchain technology.
Roy_Chao@himelight.com

2.Our company is specialized in career consulting and digital talent management in Taiwan.

3.None.

4.We have a lot of live activity photos and videos to store,about 5TiB

5.Size and location are our top concerns

6.MicroSoft Azure

**Comment by Broz221** [comment]
Hi. I have sent you E-mail to get more private detailed information. Please check.

**Comment by zxzccstor1** [comment]
I have received it. I have replied to the relevant information.
