### ISSUE TITLE
Client Allocation Request for: netease

### ISSUE THREAD

**Issue by jiejiewo** [filecoin-project/filecoin-plus-client-onboarding#424]
---

# Client Allocation Questions 

## Core Information
- Name: netease
- Website / Social Media: http://www.netease2000.com/
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1drs65lemecr62sbap72o24rrrjdpv4mygqxwofy
- Notary Requested: Broz221

@jiejiewo Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Broz221** [comment]
Thanks for your application.

Please answer following questions:

What's your name? What's your duty in this company? Please give me your E-mail address and your brief introduction.
Please give me simple overview of your company. (Company scale, establish time, project, use case, etc.)
What's you/your company's contribution to Filecoin? (If exsit)
What kind of data do you want to store? And how much? How about copy right of data?
How many miners do you want to store data to? Which aspect will you inspect these miners?
Could please you introduce your past usage of cloud storage?

**Comment by jiejiewo** [comment]
1.I am Rico Cao, the director of the storage division of Netease. Mainly responsible for the storage and management of the company's data.
Rico-Cao@netease.com

2.Netease was founded in 2010, mainly engaged in software related and host hosting, network information security and other services,Customer first, service first for the purpose of the enterprise, hope to bring customers a complete solution with a full range of services.

3.None.

4.We hope to try to store some backup data in the filecoin network, about 10TiB.

5.About five miners, mainly depending on the credibility of the miners.

6.Self built cloud

**Comment by Broz221** [comment]
Hi. I have sent you E-mail to get more private detailed information. Please check.

**Comment by jiejiewo** [comment]
I have sent it, you can have a look

**Comment by Broz221** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebnazumoclyilyrdhtqxmjf3u6ee73apc6rq7362mv6wvggn2simq 
#### Address 
> f1drs65lemecr62sbap72o24rrrjdpv4mygqxwofy
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebnazumoclyilyrdhtqxmjf3u6ee73apc6rq7362mv6wvggn2simq
