### ISSUE TITLE
Client Allocation Request for: asia-360

### ISSUE THREAD

**Issue by FVJSJhfhe4747** [filecoin-project/filecoin-plus-client-onboarding#426]
---

# Client Allocation Questions 

## Core Information
- Name: asia-360
- Website / Social Media: https://www.asia-360.net/
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1k2rph4tjkz2bnbyjjhscb6cgds2e4zwjelb3c6i
- Notary Requested: Broz221

@FVJSJhfhe4747 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Broz221** [comment]
Thanks for your application.

Please answer following questions:

What's your name? What's your duty in this company? Please give me your E-mail address and your brief introduction.
Please give me simple overview of your company. (Company scale, establish time, project, use case, etc.)
What's you/your company's contribution to Filecoin? (If exsit)
What kind of data do you want to store? And how much? How about copy right of data?
How many miners do you want to store data to? Which aspect will you inspect these miners?
Could please you introduce your past usage of cloud storage?

**Comment by FVJSJhfhe4747** [comment]
Hi,Broz221

1.I'm Stephen, the technical director of asia-360,Mainly responsible for the company's SaaS system development and maintenance, as well as some cutting-edge technology exploration.
Stephen-c@asia360.com

2.Our company has been established in Taiwan for more than 10 years, focusing on providing a full range of digital zero-system services for domestic and overseas small and medium-sized enterprises

3.None

4. Recent years, live video is very popular, and our platform also retains a large number of customers' video files, which we plan to upload 5TiB first.

5.Size and credibility are the main factors

6.Mainly Amazon cloud

**Comment by FVJSJhfhe4747** [comment]
Hi,Broz221

1.I'm Stephen, the technical director of asia-360,Mainly responsible for the company's SaaS system development and maintenance, as well as some cutting-edge technology exploration.
Stephen-c@asia360.com

2.Our company has been established in Taiwan for more than 10 years, focusing on providing a full range of digital zero-system services for domestic and overseas small and medium-sized enterprises

3.None

4.Recent years, live video is very popular, and our platform also retains a large number of customers' video files, which we plan to upload 5TiB first.

5.Size and credibility are the main factors

6.Mainly Amazon cloud

**Comment by Broz221** [comment]
Hi. I have sent you E-mail to get more private detailed information. Please check.

**Comment by FVJSJhfhe4747** [comment]
I have sent it.
