### ISSUE TITLE
Client Allocation Request for: Zhejiang Allian Testing Technology Service Co. Ltd

### ISSUE THREAD

**Issue by raullefu** [filecoin-project/filecoin-plus-client-onboarding#439]
---

# Client Allocation Questions 

## Core Information
- Name: Zhejiang Allian Testing Technology Service Co. Ltd
- Website / Social Media: www.anliantest.com/
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3vsnyrlzthdklgverpzaqwlnt5zlbij4znbzb5y5h57omnbb5vj3maiwv67kg3s24ne5usijrhlcnzer3tnba
- Notary Requested: steven004

@raullefu Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by steven004** [comment]
Hey @raullefu  , thanks for your request. Can you kindly add more information / context here on:

1. yourself/ your organization (with links to official website/social media/news mentions etc)
2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners)
5. How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
6. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
7. Would you be OK in posting deal transactions here?

Thanks

**Comment by raullefu** [comment]
Hi, @steven004, thanks for your reply. Please see our information below.

1.yourself/ your organization (with links to official website/social media/news mentions etc)
Zhejiang Allianz Testing Technology Service Co., Ltd. is a professional technical service organization committed to occupational health technical services, public health testing and evaluation, environmental water quality testing.The company was established in April 2011 with a registered capital of 15 million yuan. Its service scope covers the whole province of Zhejiang. Mainly engaged in Recognition, Assessment, Control and other related technical services under special environment such as industrial enterprises and public places.

2.Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
No working history. As required by the regulatory authorities, our data needs to be stored for a long time, and we are looking for a storage service with low cost. And we do believe that decentralized storage can help us to store the relevant data generated in the process of work at a low cost. 

3.Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
At the beginning, we planned to store the multiple types of data, which include the Image, text, video and so on.  These data are all produced by ourselves , and the total amount is about 5TB.

4.Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners)
We plan to allocate 2-3 Chinese miners, and the proportion is expected to be no more than 50% for each miner. At present, we have no clear target for storage and are looking for reliable miner with cost-effective services.

5.How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
We will plant to develop a tool, which will support the data retrieval and download. 

6.What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
At this stage this batch of data belongs to the privacy of the enterprise, only free of charge to provide the enterprise itself.

7.Would you be OK in posting deal transactions here?
Yes.

**Comment by steven004** [comment]
Hey @raullefu ,  thanks for your clarification, and welcome to the Filecoin world. IPFS/Filecoin network is distributed and decentralized.

Based on what you mentioned, I would think you need to do some test or experiments for storing data to and retrieving from IPFS/Filecoin network, and you need to try to find some miners to support you for doing this. 

I would grant you 1TiB as a start for your testing. 

And next, when you need to store more data in Filecoin network, I need to do more verification, including your business entity, data validation, etc. Thanks.

**Comment by steven004** [comment]
Your Datacap Allocation Request has been approved

**Message sent to Filecoin Network**
> [bafy2bzacectqbpg44crhuavuir7qa3togyow6ba373la52jpq3jftresqant4](https://filscan.io/tipset/message-detail?cid=bafy2bzacectqbpg44crhuavuir7qa3togyow6ba373la52jpq3jftresqant4)

**Address**
> [f3vsnyrlzthdklgverpzaqwlnt5zlbij4znbzb5y5h57omnbb5vj3maiwv67kg3s24ne5usijrhlcnzer3tnba](https://filscan.io/tipset/address-detail?address=f3vsnyrlzthdklgverpzaqwlnt5zlbij4znbzb5y5h57omnbb5vj3maiwv67kg3s24ne5usijrhlcnzer3tnba)

**Datacap Allocated**
> 1 TiB
