### ISSUE TITLE
Client Allocation Request for: 2b.cn

### ISSUE THREAD

**Issue by fgnfhdfhd** [filecoin-project/filecoin-plus-client-onboarding#441]
---

# Client Allocation Questions 

## Core Information
- Name: 2b.cn
- Website / Social Media: http://www.2b.cn/
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1b7jchlgo6nkkv3l5nouyn72af6bplwk5vkdqonq
- Notary Requested: Broz221

@fgnfhdfhd Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Broz221** [comment]
Thanks for your application.

Please answer following questions:

What's your name? What's your duty in this company? Please give me your E-mail address and your brief introduction.
Please give me simple overview of your company. (Company scale, establish time, project, use case, etc.)
What's you/your company's contribution to Filecoin? (If exsit)
What kind of data do you want to store? And how much? How about copy right of data?
How many miners do you want to store data to? Which aspect will you inspect these miners?
Could please you introduce your past usage of cloud storage?

**Comment by fgnfhdfhd** [comment]
Dear Notary

1、I'm the co-founder of this company,You can call me Alex.I look at emerging market technologies, and I'm very bullish on the Filecoin network
Alexxu@tob.com

2.Toby, the most professional vertical media and industry service platform in B2B industry, was founded in October 2012, led by professional B2B We Media person Ningbo Liu. With Toby as the core, it focuses on industry research and industry service. The annual "China B2B E-commerce Conference" hosted by Toby has a huge influence in B2B industry.

3.We mainly generate some e-commerce data,It would be best if you could give us 10TiB.

4.We think 3 miners is reasonable, and we mainly focus on the network distance.

5.We mainly use Ali.

**Comment by Broz221** [comment]
Hi. I have sent you E-mail to get more private detailed information. Please check.

**Comment by fhncfch** [comment]
OK, I have sent the email

**Comment by fgnfhdfhd** [comment]
OK, I have sent the email

**Comment by Broz221** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceciosmj4wxrioofo5kldgdtkzze3ciuk3fjykovfzgy7wjbnuz4fy 
#### Address 
> f1b7jchlgo6nkkv3l5nouyn72af6bplwk5vkdqonq
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceciosmj4wxrioofo5kldgdtkzze3ciuk3fjykovfzgy7wjbnuz4fy
