### ISSUE TITLE
Client Allocation Request for: tfpass

### ISSUE THREAD

**Issue by fhncfch** [filecoin-project/filecoin-plus-client-onboarding#444]
---

# Client Allocation Questions 

## Core Information
- Name: tfpass
- Website / Social Media: http://tfpass.cn/
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1j7xkzmchl4zufoqlgbbmdqqhxwvpimnh6t2vscy
- Notary Requested: Broz221

@fhncfch Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Broz221** [comment]
Thanks for your application.

Please answer following questions:

What's your name? What's your duty in this company? Please give me your E-mail address and your brief introduction.
Please give me simple overview of your company. (Company scale, establish time, project, use case, etc.)
What's you/your company's contribution to Filecoin? (If exsit)
What kind of data do you want to store? And how much? How about copy right of data?
How many miners do you want to store data to? Which aspect will you inspect these miners?
Could please you introduce your past usage of cloud storage?

**Comment by fhncfch** [comment]
Hi,Broz221
1. I'm the deputy general manager of Tfpass. You can call me Jacky.We've been looking at the Filecoin network for storage
E-mail: Jacky-zz@tfpass.cn

2.Tfpass as a typical digital marketing technology company, following the digital marketing technology and the changes of the software industry, constantly adjust and improve the company's SaaS product line and from advertising (RTB, API) stylized to data platform (China) DMP, CDP, data, and then to the private domain, complied with the digital marketing industry from extensive operation to the development of the fine operation evolution.

3.We want to store some e-commerce data,about 10 tib

4.We think 4 is more reasonable, mainly depends on the size of the miners.

5.Tencent Cloud is our most used.

Thanks.

**Comment by Broz221** [comment]
Hi. I have sent you E-mail to get more private detailed information. Please check.

**Comment by fhncfch** [comment]
Thank you very much. I have replied the email

**Comment by Broz221** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecf7e4kmrbnutuu3aqdsn2z5ssd36h6ytzfezvhvi3qfxty4i73lo 
#### Address 
> f1j7xkzmchl4zufoqlgbbmdqqhxwvpimnh6t2vscy
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecf7e4kmrbnutuu3aqdsn2z5ssd36h6ytzfezvhvi3qfxty4i73lo
