### ISSUE TITLE
Client Allocation Request for: Julien NOEL

### ISSUE THREAD

**Issue by s0nik42** [filecoin-project/filecoin-plus-client-onboarding#445]
---

# Client Allocation Questions 

## Core Information
- Name: Julien NOEL
- Website / Social Media: @s0nik42
- Region: Europe
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3rpqqflz4bhyylporz3kjhejftvfs2gbjxv7gcw3imvviklmrqgee2jqsgp6hrl35ufckv76kdd245q352dtq
- Notary Requested: neogeweb3

@s0nik42 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by s0nik42** [comment]
Hi, @neogeweb3, that datacap should be the last one for me. 

Thank you for your support,

Julien

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacearfsl5pvxto4xzwztns3oah75jlk4wmzj3az3g7mna2rze3si2yg 
#### Address 
> f3rpqqflz4bhyylporz3kjhejftvfs2gbjxv7gcw3imvviklmrqgee2jqsgp6hrl35ufckv76kdd245q352dtq
#### Datacap Allocated
> 5TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacearfsl5pvxto4xzwztns3oah75jlk4wmzj3az3g7mna2rze3si2yg
