### ISSUE TITLE
Client Allocation Request for: AetherWorks, LLC

### ISSUE THREAD

**Issue by rmacinnis** [filecoin-project/filecoin-plus-client-onboarding#446]
---

# Client Allocation Questions 

## Core Information
- Name: AetherWorks, LLC
- Website / Social Media: https://www.AetherWorks.com
- Region: North America
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3sw6yug5mvulr4m4fugqvdmai52tsnhemoo26lzpd3ozdp6ot24ynxo3ucdvheleu37gcx7bqsd3doxeyr6wq
- Notary Requested: XnMatrixSV

@rmacinnis Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by rmacinnis** [comment]
Hi there - this is a re-up request following our previous allocation referenced [here](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/404).

We have about 100GiB of DataCap left as of this submission, but we are executing at a rate that means we should be through that by tomorrow.

We have found a quite diverse group of miners to use, although there continue to be some configuration & deal-conclusion challenges. I have been engaging a fair amount on slack regarding these issues and look forward to helping share some of our solutions to them. In addition I will be presenting tomorrow during the FILPlus day event in order to share some of our techniques for providing more resilient data encoding.

Per the guidelines we have distributed storage as geographically as possible, including in: Norway, Netherlands, China, Korea, USA and Canada. We have tried some miners from other regions, and don't want to rag on them, but some were found to switch their deal rates periodically, and we almost fell victim to a single sector deal for 16FIL. It has been good to find some reliable miners though and we'll continue to expand our list of globally trustworthy folks.

**Comment by XnMatrixSV** [comment]
Hi，@rmacinnis, we are pleased to receive your new application, and good luck with your projects.
There are some problems,we hope to hear from you soon. 
1.Is this issue applied for the project of the previous issue or for the new project?
2.Could you give a description of the cooperation mechanisms with miners you chose before, such as how do you find them, the reason why you choose them, and datacap allocation proportion, etc.
3.Would you be OK in posting deal transactions in the previous issue?
4.Is it convenient for users to retrieve and view data you stored? Can you provide detailed steps.

**Comment by rmacinnis** [comment]
Hi there! Thank you for your prompt reply, I really appreciate it. Each question is addressed below!

> 1.Is this issue applied for the project of the previous issue or for the new project?
This is for the same projects as listed in the previous issue [here](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/404).

> 2.Could you give a description of the cooperation mechanisms with miners you chose before, such as how do you find them, the reason why you choose them, and datacap allocation proportion, etc.
Absolutely - and this has been very interesting. We have found that Slack has been the most productive in terms of finding & interacting with miners that are a) live, b) interested in deals, and c) can communicate back & forth regarding the success/failure of deals, and collaboratively work together to solve problems and get things to work. The network is young and the software is evolving, and there continue to be bugs. In the current state it is useful to be actively in touch with miners. It has been incredibly good that miners are so interested in chatting with clients - this is very, very positive. We have also used FilSwan, as well as the list provided on FilPlus.org and the github repo, primarily in order to locate miners in other countries / to support our commitment to geographical distribution. We have found that a large proportion of these miners are a) not accepting deals [whether verified or non-verified], b) have not updated their pricing in a while and so are asking orders of magnitude higher than other miners, and c) are on versions no longer compatible with the current network requirements.

To put a finer point on it: we have proposed over 1,000 deals to miners, transferred over 644 sectors of 32GBs to miners, of which roughly 140 have succeeded. Roughly 115 of the successful deals have been through miners that we met via Slack.

> 3.Would you be OK in posting deal transactions in the previous issue?
100% - DealId's are pasted below.

> 4.Is it convenient for users to retrieve and view data you stored? Can you provide detailed steps.
Not yet - we are not finished storing the data. As indicated during our presentation today during FilPlus day, we are experimenting with different data encoding mechanisms in order to bolster the robustness of the stored data and provide mechanisms that improve upon simple raw replication. We look forward to contributing this work (via guides & code) back to the community, in addition to providing the useful documentation for easy retrieval.

(If interested, please find today's presentation [here](https://youtu.be/wP4Bk8lBNUc?t=2997)).

(DealIds: 1853695, 1862573, 1862136, 1866015, 1885807, 1885806, 1889339, 1888432, 1890229, 1889341, 1889621, 1890230, 1889340, 1889343, 1896019, 1896025, 1891773, 1896021, 1891775, 1893085, 1904486, 1895308, 1895310, 1896022, 1903850, 1904371, 1907275, 1904703, 1904447, 1904708, 1907185, 1905847, 1907188, 1905849, 1907187, 1905848, 1912514, 1905851, 1906958, 1906525, 1912512, 1905850, 1906526, 1912513, 1905901, 1905979, 1912515, 1905852, 1906528, 1906534, 1906704, 1906705, 1907213, 1907216, 1906967, 1906968, 1907218, 1906969, 1907796, 1907797, 1907798, 1908071, 1907799, 1908072, 1908031, 1908037, 1908073, 1908032, 1908033, 1908036, 1908077, 1908038, 1908291, 1908079, 1908080, 1908290, 1908081, 1908293, 1909169, 1909172, 1909380, 1909790, 1909789, 1912421, 1909791, 1912422, 1912423, 1912296, 1912297, 1912672, 1912673, 1912576, 1912577, 1912674, 1912578, 1912580, 1913120, 1913121, 1913133, 1913457, 1913179, 1913122, 1913232, 1913134, 1913458, 1913180, 1913381, 1913444, 1913526, 1913445, 1913527, 1914945, 1914946, 1914344, 1914345, 1914947, 1914948, 1914949, 1914346, 1914950, 1914661, 1914951, 1914662, 1914663, 1914952, 1914953, 1916071, 1914665, 1916072, 1914954, 1914666, 1914955, 1915037, 1914956, 1914957)

**Comment by XnMatrixSV** [comment]
@rmacinnis Hi, Dr. Robert.
We watched your presentation on FilPlus day, and projects is impressive and awesome.
We will still support your application this time.
If there's any progress on the project, you can communicate with us via Slack(@XnMatrix SV).
Please check Addresses to be Notarized: f3sw6yug5mvulr4m4fugqvdmai52tsnhemoo26lzpd3ozdp6ot24ynxo3ucdvheleu37gcx7bqsd3doxeyr6wq

**Comment by rmacinnis** [comment]
That's terrific, thank you!

Address confirmed: f3sw6yug5mvulr4m4fugqvdmai52tsnhemoo26lzpd3ozdp6ot24ynxo3ucdvheleu37gcx7bqsd3doxeyr6wq

**Comment by XnMatrixSV** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedu6yuzpqp7sy42qwudhoo7g2vvkn2dpaijb5zl5a7hz34eatlhlu 
#### Address 
> f3sw6yug5mvulr4m4fugqvdmai52tsnhemoo26lzpd3ozdp6ot24ynxo3ucdvheleu37gcx7bqsd3doxeyr6wq
#### Datacap Allocated
> 5TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedu6yuzpqp7sy42qwudhoo7g2vvkn2dpaijb5zl5a7hz34eatlhlu
