### ISSUE TITLE
Client Allocation Request for: Myserver

### ISSUE THREAD

**Issue by dengdai789** [filecoin-project/filecoin-plus-client-onboarding#447]
---

# Client Allocation Questions 

## Core Information
- Name: Myserver
- Website / Social Media: https://www.myserver.asia
- Region: Greater China
- DataCap Requested: 30TiB
- Addresses to be Notarized: f1tmuircaaenwvffdmyuydcqlidfxvgvg2wsj344i
- Notary Requested: Broz221

@dengdai789 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Broz221** [comment]
Thanks for your application.

Please answer following questions:

What's your name? What's your duty in this company? Please give me your E-mail address and your brief introduction.
Please give me simple overview of your company. (Company scale, establish time, project, use case, etc.)
What's you/your company's contribution to Filecoin? (If exsit)
What kind of data do you want to store? And how much? How about copy right of data?
How many miners do you want to store data to? Which aspect will you inspect these miners?
Could please you introduce your past usage of cloud storage?

**Comment by dengdai789** [comment]
1.Hello, I am Yang Hemei, the R&D director of myserver.We've been looking at a number of blockchain storage technologies
Yang-Hemei@myserver.com

2."MyServer Technology Co., Ltd." (MyServer Excellent Cloud) is the only subsidiary company of Taiwan game giant Intelligent Crown Technology, which holds 100% shares.
With powerful resources in Taiwan's digital content industry, "Zhiyun Technology" is committed to becoming the strongest backing for game companies by providing various back-end services needed by game companies, such as IDC room rental and services, cloud services, CDN services, etc. A single service provider can meet all the needs of game companies.
Intelligent crown technology combined to provide one-stop game services, services including cash flow, delivery, art, cloud services, on-site computer room and many other projects.
Each service scheme is combined with each other, not only eliminating the game business due to the expansion of business, and looking for resources around the trouble, but also the group will include Zhiyun technology
More preferential treatment, it is the best shortcut that game business goes to overseas development.

3.None.

4.We will store some video related to the game to see how Filecoin is used and the entire operation process. The total capacity is expected to be 30TiB.

5.Five miners is ideal. We focus on the pricing and distance of miners.

**Comment by Broz221** [comment]
Hi. I have sent you E-mail to get more private detailed information. Please check.

**Comment by dengdai789** [comment]
Ok,I have sent it to you.

**Comment by Broz221** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebcxt6f22lrkayw2zv76w3a74irfa7kiarfhhvvtv6zzriitnsvcm 
#### Address 
> f1tmuircaaenwvffdmyuydcqlidfxvgvg2wsj344i
#### Datacap Allocated
> 30TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebcxt6f22lrkayw2zv76w3a74irfa7kiarfhhvvtv6zzriitnsvcm
