### ISSUE TITLE
Client Allocation Request for: Speedium.network

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/filecoin-plus-client-onboarding#456]
---

# Client Allocation Questions 

## Core Information
- Name: Speedium.network
- Website / Social Media: www.speedium.network
- Region: North America
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3vejsdwficdsp6pz2y3diuxsbvu6z3onozir6yvylnntbvfhpwfdbgzqcrz5rwge5ktgueoxipcxl4drljega
- Notary Requested: andrewxhill

@cryptowhizzard Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by cryptowhizzard** [comment]
As per issue [393](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/393)

Attached an overview of the deals we sent out.

[deals-andrew.csv](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/6465725/deals-andrew.csv)

**Comment by andrewxhill** [comment]
hey @cryptowhizzard thanks for that. here are just a few questions for the record.

### Usage

1. What portion of the originally granted datacap have you used to date? 
2. If less than 100% could you provide a short justification for why the early application?
3. If less than 100% and using a new target address, do you still plan on utilizing the original datacap too?

### Deployment

1. Can you provide any information on the deals you've created and miners you've used with your previously allocated datacap? (thanks for this already, above)
2. Are there any significant changes to your original application in terms of use-case, data inputs, or miner allocation?

thanks!

**Comment by cryptowhizzard** [comment]
Hi @andrewxhill 

1 - almost 100%. I guess some 32 to 100 GB is left ( when deals fail the cap gets released after a few days again.)

1 - I have uploaded files from our populair cache of speedium. I used 3 miners from the EU and 3 from the US. I worked with N+ 3.

2 - no changes unless you want me to make ones.

Ps. The latest few deals when I switched from 1.8 to 1.9 lotus had some fuzz and errors. I have been working with dirkmc to iron out some bugs who are fixed now. 

See here : https://github.com/filecoin-project/lotus/issues/6265

**Comment by andrewxhill** [comment]
Thanks @cryptowhizzard. You're all set.

**Comment by dkkapur** [comment]
@andrewxhill - for the Fil+ dashboard here: https://filplus.d.interplanetary.one/, trying to get the message ID for this particular allocation. Are you able to share it by any chance?

**Comment by dkkapur** [comment]
I think its this but I'm not sure https://filfox.info/en/message/bafy2bzacecpboldswjf7dgr4nnjhmixxb64zieaoewnu2ttttm4c3oleivyg2

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
