### ISSUE TITLE
Client Allocation Request for: 

### ISSUE THREAD

**Issue by yihuazhai** [filecoin-project/filecoin-plus-client-onboarding#460]
---

# Client Allocation Questions 

## Core Information
- Name: 
- Website / Social Media: 
- Region: North America
- DataCap Requested: 1TiB
- Addresses to be Notarized: f12dzo2k2gayiyrxaqh5j6wxuxbt4aeqaapqxgc7a
- Notary Requested: neogeweb3

@yihuazhai Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by neogeweb3** [comment]
Closed due to incomplete request.
