### ISSUE TITLE
Client Allocation Request for: Panyuan Technology Co., Ltd.

### ISSUE THREAD

**Issue by Arnoldzx** [filecoin-project/filecoin-plus-client-onboarding#5]
---

# Client Allocation Questions 

## Core Information
- Name: Panyuan Technology Co., Ltd.
- Website / Social Media: https://infclouds.net
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1dcrtmyiqtgkj45lmxsjwhmjedf7qvku5igkktga
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @Arnoldzx - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- your relationship with the data, especially with regard to copyright
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by Arnoldzx** [comment]
1.yourself , e.g. include links to social media / news mentions etc
I am the director of technology in Panyun Technology R & D department. We focuse on blockchain services in the financial sector, based on the leading core technologies of blockchain and cloud computing.The company has now built a financial product full life cycle for blockchain management platform, assisting financial institutions in creating a "trusted system" for internal and external collaboration and sharing, and providing overall blockchain solutions from deployment to operation and maintenance to support various practical applications in financial companies.

Here is some news about our company:
https://www.sohu.com/a/434638570_403354
http://suxian.cc/article/24850.html

2.your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
As you can see, we are a company specializing in applying blockchain technology to the financial sector. We combine the insurance policy of the financial insurance business with the IPFS network. Using blockchain technology to effectively preserve electronic evidence.After the IPFS/Filecoin mainnet went live in 2020, we hope to participate in it.

3.type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
We will conduct some data storage experiments on the network. More than 500GiB of data is generated every day. Different types and sizes of data will be packaged to compare the computing performance of the IPFS network.The data used for the experiment is related to finance, and the information in it is desensitized, but for the actual application scenarios of the model, we will encrypt all information.


4.your relationship with the data, especially with regard to copyright
This data belongs to the company and does not wish to be made public


5.how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
We will select active and reputable miners according to ranking, cost, location. 
Redundancy: 4 copies

**Comment by philippbanhardt** [comment]
Hey @Arnoldzx - thanks. Unfortunately the Foundation does not accept client requests for non-public data at this time, however please bear in mind that other notaries may have different policies. 

Philipp
