### ISSUE TITLE
Client Allocation Request for: [上海弗莱云科技有限公司]

### ISSUE THREAD

**Issue by moonlight233** [filecoin-project/filecoin-plus-client-onboarding#515]
# Client Allocation Questions 

## Core Information
- Name: [上海弗莱云科技有限公司]
- Website / Social Media: [https://mp.weixin.qq.com/s/RhJ5GhH7qaXdIEN1he65Wg]
- DataCap Requested: [8T]
- Addresses to be Notarized: [TBD]

-----------------------------

**Comment by dkkapur** [comment]
@moonlight233 - @philippbanhardt is no longer accepting applications at this time. Would recommend reaching out to a different notary if possible. I can help with this if you can share any additional info about your use case. Thank you!
