### ISSUE TITLE
Client Allocation Request for: Everimaging Science & Technology Inc.

### ISSUE THREAD

**Issue by Fotortoday** [filecoin-project/filecoin-plus-client-onboarding#518]
---

# Client Allocation Questions 

## Core Information
- Name: Everimaging Science & Technology Inc.
- Website / Social Media: www.fotor.com
- Region: North America
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3usqiahcnn2ys22tr3xuaua7hdiv7rbojpuzsnb2idw2ho6zyergerlbp6mbqpsujn3yl37ful5kqhips46cq
- Notary Requested: XnMatrixSV

@Fotortoday Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by XnMatrixSV** [comment]
Hi, @Fotortoday.
Thanks for your request. Can you kindly add more information here.
1.Is your company located in North America？
2.Please give the following informations, duration of etablishment, number of employees, business scope, users volume, number of social media followers, data size to be stored, products or projects, and so on. Provide links to social media/news mentions.
3.The history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time, etc.
Type, size, and source of the data you will be store on Filecoin,e.g. public data or private data, etc. Is there any sensitive or illegal content?
4.How do you intend to store the data on Filecoin, e.g. redundancy, location/miner preferences, etc
5.Have you already apply for DataCap to another notary, and whether it is accepted or rejected. Is there any reliable DataCap left?
6.Would you like to post real transactions on Github?

**Comment by Fotortoday** [comment]
Firstly, I'm sorry for mistaking the region.
Our region belongs to Europe. But there is not enough DataCap in notaries of Europe.
We provide services to global customers, which include customers from North America.
###
Our company was establish in November 2011. We have around 100 employees.
Powerful, user-friendly and globally accessible, Fotor is an online photo editing suite, utilizing exclusive technology to bring an unprecedented level of editing control to anyone and everyone. While the ‘collage’ and ‘edit’ features are already enjoyed by millions of users, daily, the new ‘design’ feature gives the common user the ability to design any form of graphics and cover, limited only by imagination.
Streamlined with a number of social media channels, Fotor’s exponentially growing user base is comprised of hundreds of millions of users across the globe. Initially graining great popularity with its optimized and user-friendly desktop suit for both Windows and Mac, Fotor now supports every major mobile and desktop platform from Android to iOS, with a specialized ‘Fotor for Messenger’ version, streamlined with Facebook for greater connectivity and convenience. Fotor’s mobile versions receive frequent updates and new features, not only providing the common user the ability to take and edit amazing photos, but also the convenience of having images shared and uploaded on all major social media platforms.
On top of being an established utility app with a range of design features, Fotor also supports international photographic competitions. Currently supported on the mobile platforms, but soon to be accessible to all versions including desktop, Fotor’s competitions are a key element in user interaction. With a number of simultaneous competitions every week, spanning a number of topics and photographic styles, these events are judged by an official panel of professional photographers, whose input maintains a consist influx of high quality, creative images.
The combination and integration of specialized image editing technologies, coupled with unique features and community competitions allows for Fotor’s continual growth and development. Fotor is a cross platform editor and designer, available on every major mobile device, desktop computer and online. ‘One-Tap Enhance’, a tool designed to improve the most common imaging problems in the shortest period of time is just one of the many unique features. RAW file processing, allowing for unparalleled definition quality is a key feature of the desktop platform, while the patented HDR (High Dynamic Range) is available on many versions, including mobile.
There are more than 49 thousand followers on Instagram(https://www.instagram.com/fotor_apps/) and  more than 31 thousand followers on Pinterest(https://www.pinterest.com/fotor2012/).
There are about 200TiB we intend to store.
###

###
We have no contribution in IPFS / Filecoin before. We think the concept of Filecoin's distributed storage network sounds pretty well. 
###

###
We intend to store pictures on Filecoin network, including png/jpg/svg/bmp/, about 170 TiB.Our data generates from customers, so it is private data.There is no sensitive or illegal content.
###

###
We'll make 3 copies of data. We have no special regional tendency and we will choose the miner around the world who have experience and good reputation in transaction.
###

###
We have never applied for DataCap before.
###

###
Yes, We'd like to post all transactions detail on Github.
###

**Comment by XnMatrixSV** [comment]
Hi,@Fotortoday. Glad to receive your reply. 
You need to wait for four more days(a total of seven days) because of the region of your organization. You can find it in our allocation strategy(https://github.com/filecoin-project/notary-governance/issues/27).
We will continue our verification on 8, June.

**Comment by XnMatrixSV** [comment]
Hi, @Fotortoday  
Your project sounds pretty well, we'll give you 5TiB to start to storeon Filecoin network. If you have any questions, please contact me.
You can apply to us again when DataCap is used up.

Here is the link to the updated rubric, which shows information about allocation decision:
https://github.com/XnMatrixSV/Bookkeeping

(If ready) Please confirm the address that should receive DataCap.

**Comment by Fotortoday** [comment]
Thanks for your prompt reply.
Addresses : f3usqiahcnn2ys22tr3xuaua7hdiv7rbojpuzsnb2idw2ho6zyergerlbp6mbqpsujn3yl37ful5kqhips46cq

**Comment by XnMatrixSV** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedfx534d5qhnap43agnvq2bbmxilouyqwlpgtsc5tce54sblizmgq 
#### Address 
> f3usqiahcnn2ys22tr3xuaua7hdiv7rbojpuzsnb2idw2ho6zyergerlbp6mbqpsujn3yl37ful5kqhips46cq
#### Datacap Allocated
> 5TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedfx534d5qhnap43agnvq2bbmxilouyqwlpgtsc5tce54sblizmgq

**Comment by XnMatrixSV** [comment]
Hello, my email: notary@XnMatrixs.com
I want to know your usage of DataCap allocated before.
