### ISSUE TITLE
西安博骋时空数据科技有限公司

### ISSUE THREAD

**Issue by ridde** [filecoin-project/filecoin-plus-client-onboarding#521]
# Client Allocation Questions 

## Core Information
- Name: 西安博骋时空数据科技有限责任公司
- Website / Social Media:
- DataCap Requested: 8T
- Addresses to be Notarized: t017001

-----------------------------

**Comment by dkkapur** [comment]
@ridde - @philippbanhardt is no longer accepting applications at this time. Would recommend reaching out to a different notary if possible. I can help with this if you can share any additional info about your use case. Thank you!
