### ISSUE TITLE
Client Allocation Request for: Voodfy inc

### ISSUE THREAD

**Issue by Leeaandrob** [filecoin-project/filecoin-plus-client-onboarding#524]
# Client Allocation Questions 

## Core Information
- Name: Voodfy inc
- Website / Social Media: https://app.voodfy.com
- DataCap Requested: 10TB
- Addresses to be Notarized: f3wfovmet4goxalkks7mobcgeraxy5ln5qfwchx2aqvlb2hsykjsxiufkyjuznlertgjnl4ezmdq2chj3w67ia

-----------------------------

**Comment by dkkapur** [comment]
@ridde - @philippbanhardt is no longer accepting applications at this time. Would recommend reaching out to a different notary if possible. I can help with this if you can share any additional info about your use case. Thank you!
