### ISSUE TITLE
Client Allocation Request for: TJIDC

### ISSUE THREAD

**Issue by AidanKR** [filecoin-project/filecoin-plus-client-onboarding#555]
# Client Allocation Questions 

## Core Information
- Name: TJIDC
- Website / Social Media: https://www.tjidc.io
- DataCap Requested: 80TiB
- Addresses to be Notarized: f0984905

-----------------------------

**Comment by dkkapur** [comment]
@AidanKR what region are you in? Is there a specific notary you were looking to apply to based on https://github.com/filecoin-project/notary-governance/blob/main/notaries/README.md#current-active-notaries
