### ISSUE TITLE
Client Allocation Request for: anyidata

### ISSUE THREAD

**Issue by CadeWhitehead** [filecoin-project/filecoin-plus-client-onboarding#560]
---

# Client Allocation Questions 

## Core Information
- Name: anyidata
- Website / Social Media: www.anyidata.com
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1l2rbo2gqizerr2qmh7gfl3cvsfw4azxdrnkf42i
- Notary Requested: Fenbushi-Filecoin

Please make sure to check out the guidelines and criteria to accept Datacap request for [Fenbushi Capital](https://github.com/filecoin-project/filecoin-plus-client-onboarding/tree/main/Fenbushi%20Capital)

@CadeWhitehead Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecv5gbtj3pfp4zjanpu3x4cq4hdsju37uz4n3h2bvuroc6fjjkfro 
#### Address 
> f1l2rbo2gqizerr2qmh7gfl3cvsfw4azxdrnkf42i
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecv5gbtj3pfp4zjanpu3x4cq4hdsju37uz4n3h2bvuroc6fjjkfro
