### ISSUE TITLE
Client Allocation Request for: 上海鲸翼信息科技有限公司

### ISSUE THREAD

**Issue by lindazhuang123** [filecoin-project/filecoin-plus-client-onboarding#570]
---

# Client Allocation Questions 

## Core Information
- Name: 上海鲸翼信息科技有限公司
- Website / Social Media: https://www.jing-yi.com.cn/
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1hnlwy7swr7lyjf3pmuryqkoih6smvcapbxdkp6y
- Notary Requested: ozhtdong

@lindazhuang123 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application! Previous link: https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/229

**Comment by ozhtdong** [comment]
You have mentioned that you would like to allocate DataCap to 3 miners, please show the evidence. Besides, please describe why you need more datacap, have you finish using all of last time?

**Comment by lindazhuang123** [comment]
No problem. miners and links: f01028659、f0395994、f01118499  https://filplus.info/#/
The amount of data storage is relatively large, so applying datacap for the second time,
current quota is still 64 Gib.

**Comment by ozhtdong** [comment]
Hi, @lindazhuang123  I suggest that you need to choose miners with good reputation.
And I also would like to know why you need more DataCap this time? And also your allocation decision.

**Comment by lindazhuang123** [comment]
Thank you to your suggestion.
We have a lot of data to store,so we need more DataCap.
I already know some of the miners,and I will distribute equally.

**Comment by ozhtdong** [comment]
Hi. @lindazhuang123 
We would like to allocate 5 TiB to you this time. But Please make sure you allocate the datacap equally.

**Comment by lindazhuang123** [comment]
Ok,thank you.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedpxyin5gs7bqr674bs72fyy6uifatppif2yqarsb5sfencsu3fqy 
#### Address 
> f1hnlwy7swr7lyjf3pmuryqkoih6smvcapbxdkp6y
#### Datacap Allocated
> 5TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedpxyin5gs7bqr674bs72fyy6uifatppif2yqarsb5sfencsu3fqy
