### ISSUE TITLE
Client Allocation Request for: HELIOS

### ISSUE THREAD

**Issue by DonaldMowbray106** [filecoin-project/filecoin-plus-client-onboarding#571]
---

# Client Allocation Questions 

## Core Information
- Name: HELIOS
- Website / Social Media: https://www.huilianyi.com/
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1n7jfmtls4l3gqy23d3nhjgvxjca6kxkt4dkb5wq
- Notary Requested: Fenbushi-Filecoin

Please make sure to check out the guidelines and criteria to accept Datacap request for [Fenbushi Capital](https://github.com/filecoin-project/filecoin-plus-client-onboarding/tree/main/Fenbushi%20Capital)

@DonaldMowbray106 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceahtrbs33pvkv36iatd7hyas2hroyr7mxo36ys764hkimrqfc2vu6 
#### Address 
> f1n7jfmtls4l3gqy23d3nhjgvxjca6kxkt4dkb5wq
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceahtrbs33pvkv36iatd7hyas2hroyr7mxo36ys764hkimrqfc2vu6
