### ISSUE TITLE
Client Allocation Request for: Seoul Walkman

### ISSUE THREAD

**Issue by noelawton** [filecoin-project/filecoin-plus-client-onboarding#590]
---

# Client Allocation Questions 

## Core Information
- Name: Seoul Walkman
- Website / Social Media: https://youtube.com/user/bogartha / http://instagram.com/seoulwalkman
- Region: Asia excl. Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3q4zgcmra5rtjficg2742u4qidwk5mwqpcoys4vuvynyzybmsjmhwarypx5ykresumnowawiooxm7it6p6iuq
- Notary Requested: steven004

@noelawton Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by steven004** [comment]
Hey @noelawton  , thanks for your request. Can you kindly add more information / context here on:

1. yourself/ your organization (with links to official website/social media/news mentions etc)
2. Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
3. Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
4. Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners), if you are working with a service provider to store your data to Filecoin network, please name the provider.
5. How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
6. What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
7. Would you be OK in posting deal transactions here?

Thanks

**Comment by noelawton** [comment]
1.yourself/ your organization (with links to official website/social media/news mentions etc)
Youtube: https://youtube.com/user/bogartha 
Github: @noelawton
Our team is a team whos trying to make a new start in the web3 ecosystem.
We have experience in producing advertisements/promotional materials that inform Korea's unique culture, history, and tourist attractions.
With this experience, we have a goal of creating new content on our own and sharing it with many people around the world.
As you know, due to growing interest in Korea around the world, we think that the content/data we want to share is likely to be used by many people.
And because our team is made up of young 20s, we are pretty sure that the content we create will be more sensuous and sophisticated than other content.

2.Your history working on IPFS/Filecoin (notable contributions to the community, type of engagement shown over time etc)
Not much working history. We are producing content ourselves about Korea with the profits obtained by building Filecoin Storage Miner.
Junepyder - 01 : f043376
Junepyder - 02 : f0214334
Junepyder - 03 : f0422737

3.Use case: type/source/quantity/diversity/scarcity of the data you plan to store on Filecoin
We will save text, images, videos, etc. Among them, videos that are all produced by ourselves will account for the largest proportion.

4.Miners you intend to allocate DataCap with allocation proportion(with redundancy/location/specific requirement of storage miners)
Miners from as many other continents as possible, including Korea. 

5.How could people retrieve the data you store in Filecoin Network, do you have a tool/app for it?
We will plant to develop a tool, which will support the data retrieval and download.

6.What's your next plan for the data you plan to store in Filecoin Network? For-profit or not?
We aim to increase the number of users of our channel by providing self-produced content for free. That is, data is not directly used for revenue.

7.Would you be OK in posting deal transactions here?
Yes.


-------------------------------------------------

Roadmap of our team

Step 1. In-house production of contents about Korea with the profits obtained by building 
Filecoin Storage Miner(current)
Junepyder - 01 : f043376
Junepyder - 02 : f0214334
Junepyder - 03 : f0422737

Step2. Distributing storage of self-generated data in the IPFS ecosystem
(1/3 of the content we create will be stored in our miner, and the rest will be distributed across as many continents as possible.)

Step3 When a certain level of data/content is accumulated, we will develop and run our channel.

Currently we're not so great like other clients. However we think the potential of our team is very high, and therefore please watch our team grow! We know we can't expect a lot of Data Cap from the start, but we need at least 1TB to store our content, so I hope you can allocate it. :)

**Comment by steven004** [comment]
@noelawton It's great to have you joining in Filecoin ecosystem. The great thing is that you have a roadmap and the ambition to grow. I am supportive for this. 

And I suppose the data you will store will be publicly available. Please let me know if it is not. 

I would like to allocate you 2TiB for you to start, please let me know if you need more. You could inform me in advance, since I need to validate the deals you placed before I issue another one. 

One more question, are you running this personally, or as a business? if you are running a business, I would like to see your business certificate. You can share with me via Email. Thanks.

**Comment by steven004** [comment]
Hey @noelawton, Your Datacap Allocation Request has been approved

**Message sent to Filecoin Network**
> [bafy2bzacec64evrp6zd4xied3xhvfea7nekmkp3ign4uegzvqv7uptinoj6ho](https://filscan.io/tipset/message-detail?cid=bafy2bzacec64evrp6zd4xied3xhvfea7nekmkp3ign4uegzvqv7uptinoj6ho)

**Address**
> [f3q4zgcmra5rtjficg2742u4qidwk5mwqpcoys4vuvynyzybmsjmhwarypx5ykresumnowawiooxm7it6p6iuq](https://filscan.io/tipset/address-detail?address=f3q4zgcmra5rtjficg2742u4qidwk5mwqpcoys4vuvynyzybmsjmhwarypx5ykresumnowawiooxm7it6p6iuq)

**Datacap Allocated**
> 2.0TiB

**Comment by noelawton** [comment]
Thanks for your approval. And I'm running this as a business. I sent an e-mail to steven004@gmail.com with proof of business. Again, Thank you:D
