### ISSUE TITLE
Client Allocation Request for: 广东中科智云科技有限公司

### ISSUE THREAD

**Issue by zhiyun11** [filecoin-project/filecoin-plus-client-onboarding#593]
---

# Client Allocation Questions 

## Core Information
- Name: 广东中科智云科技有限公司
- Website / Social Media: http://www.gdzkzy.cn/
- Region: Greater China
- DataCap Requested: 20TiB
- Addresses to be Notarized: f3tct62bxuqrmunacbnuq464q4kineqyvo36mca54dtek35rkvh2afdkt4h7jno5vearn26o4stcflbvkoxj6a
- Notary Requested: IPFSUnion

@zhiyun11 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by IPFSUnion** [comment]
Thank you for the first to apply to me after I become a notary. I'd like to know more about your business. Can you kindly answer some my following questions?
* individual and organization  
    1.	Please introduce yourself and your team briefly, and show me some your social media accounts such as GitHub, email address, WeChat official account etc.
    2.	For your organization, Please describe its time since inception, registration country，scale, named officers, project, industry reputation etc.
* track record
    1.	Regarding your data you intend to store, What’s the original source of those data, and do you have any proof of ownership or authorization?
    2. Has your organization obtained DataCap before? 
    3. Please list any of your honor and disputes in the field of Filecoin.
* use plan
    1.	Please describe your plan to use DataCap briefly? (such as use case, miner etc.)

**Comment by zhiyun11** [comment]
**Thank you for the first to apply to me after I become a notary. I'd like to know more about your business. Can you kindly answer some my following questions?**
Yes. As a professional digital ecological high-tech enterprise, Guangdong Zhongke Zhiyun Technology Co., Ltd. follows the national development strategies, such as "New Infrastructure Plan", "Calculate eastern data from western data centers", etc. We take an active part in the digital transformation and chain reform of traditional industries together with the Software technology application research and development department of The Chinese Academy of Sciences.  We have reached a data storage service cooperation with Guangzhou Zhongke Yide Technology Co., LTD.  So, We will provide the information of Guangzhou Zhongke Yide Technology Co., LTD.

**individual and organization
Please introduce yourself and your team briefly, and show me some your social media accounts such as GitHub, email address, WeChat official account etc.
For your organization, Please describe its time since inception, registration country，scale, named officers, project, industry reputation etc.**
Its time since inception:	2018.08.22
Registration country: Guangzhou
Scale:cover all china
Project:Guangzhou Zhongkeyide Technology Co., Ltd. (hereinafter referred to as "Zhongkeyide") is a high-tech enterprise incubated by the Institute of Software of the Chinese Academy of Sciences in Guangzhou, focusing on the construction of traceability system for edible agricultural products.With the support of key technologies such as big data, artificial intelligence and block chain, it has been committed to providing the overall solutions of electronic traceability of food and drug safety for civil, government and enterprises.
In recent years, with the national, provincial, city, district market supervision departments at all levels, the traceability as a solution to a new type of food and drug safety and trust industry supply chain management system, the division francois gradually establish a drug safety electronic traceability series products as the core, the formation of software development, business consulting and technology service three big business module,Provide a total solution covering the whole traceability from the source to the consumer.
In the traceability field, Zhongkeeedec has applied for dozens of invention patents and software Copyrights.  Zhongke Yide is leading in the industry with mature food electronic traceability technology. We have provided overall solutions of electronic traceability of food and drug safety for civil, government and enterprises.
Guangdong Zhongke Zhiyun Technology Co., Ltd. have in-depth cooperated with Zhongke Yide to build a joint blockchain laboratory of traceability data storage, and carry out in-depth cooperation in data storage and blockchain application development.
Industry reputation:
Key Technology Innovation Award  of China Internet of Things 
Excellent Product Award of the 14th CHTF  
Guangdong High-tech Product Award  
The 8th China "Kechuang Cup" Innovation and Entrepreneurship Competition electronic information industry start-up group winning prize 
Guangdong "Mass Innovation Cup" entrepreneurship and Innovation Competition, Doctoral and postdoctoral innovation Competition, enterprise group winning prize 
Vice president unit of Guangdong Food Circulation Association  
Outstanding Project Award of Financial Technology Innovation Competition of Guangdong Financial High-tech Zone

**track record
Regarding your data you intend to store, What’s the original source of those data, and do you have any proof of ownership or authorization?**
The data types we intend to store in the Filecoin network are transaction notes and blockchain traceability certificates (corporate privacies are hided). These data play an important role in the company and we want to store them in a way that prevents loss and alteration.
Format: PDF
Source: Business generation (Guangdong Intelligent Food and Drug Administration System, https://qy.gdfda.gov.cn/)
**Has your organization obtained DataCap before?**
None
**Please list any of your honor and disputes in the field of Filecoin.**
None

**use plan**
**Please describe your plan to use DataCap briefly? (such as use case, miner etc.)**
Use case:transaction notes and blockchain traceability certificates (corporate privacies are hided)
Redundancy:2-4copies
Location:China
Specific requirement of storage miners: famous and responsible

**Comment by IPFSUnion** [comment]
Looks good. I decide to approve 100GiB for you in the first time. Based on your subsequent performance, I may allocate more next time.

**Comment by zhiyun11** [comment]
@IPFSUnion thanks.

**Comment by IPFSUnion** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedxsdu37z7gxgezwvrpyvzeq6orgte7kz5a4rlrkngvruqmrgdhsq 
#### Address 
> f3tct62bxuqrmunacbnuq464q4kineqyvo36mca54dtek35rkvh2afdkt4h7jno5vearn26o4stcflbvkoxj6a
#### Datacap Allocated
> 20TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedxsdu37z7gxgezwvrpyvzeq6orgte7kz5a4rlrkngvruqmrgdhsq
