### ISSUE TITLE
Client Allocation Request for: NHN KCP CORP.

### ISSUE THREAD

**Issue by choibs95** [filecoin-project/filecoin-plus-client-onboarding#594]
---

# Client Allocation Questions 

## Core Information
- Name: NHN KCP CORP.
- Website / Social Media: "https://www.kcp.co.kr/main.do"  part of NHN CORP.  "https://www.nhn.com/en/index.nhn"
- Region: Asia excl. Greater China
- DataCap Requested: 500TiB
- Addresses to be Notarized: f3wi7p7plkdzeyq5mjfjjvgztv757tzzibqd5sfr5xgoj7snsp4y34x67khduur43tutwj4cp5diyfihs2h6aa
- Notary Requested: Fenbushi-Filecoin

Please make sure to check out the guidelines and criteria to accept Datacap request for [Fenbushi Capital](https://github.com/filecoin-project/filecoin-plus-client-onboarding/tree/main/Fenbushi%20Capital)

@choibs95 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
Hi @choibs95 ! Would you like to continue with this allocation request with me, or with @Fenbushi-Filecoin ?

For 500TiB, I suggest you apply for a large datacap request: [see here](https://github.com/filecoin-project/filecoin-plus-large-datasets).

**Comment by choibs95** [comment]
> Hi @choibs95 ! Would you like to continue with this allocation request with me, or with @Fenbushi-Filecoin ?
> 
> For 500TiB, I suggest you apply for a large datacap request: [see here](https://github.com/filecoin-project/filecoin-plus-large-datasets).

Thank you for the advise, i will re-submit with large datacap application. 

Best Regards,
