### ISSUE TITLE
Client Allocation Request for: Noknok

### ISSUE THREAD

**Issue by giggy22** [filecoin-project/filecoin-plus-client-onboarding#595]
---

# Client Allocation Questions 

## Core Information
- Name: Noknok
- Website / Social Media: http://www.noknok.co.kr/
- Region: Asia excl. Greater China
- DataCap Requested: 100TiB
- Addresses to be Notarized: f3uabycbcjbizjnhvkfh3vyodjotznh5qn6c5o4enmgxy4fc7xycbnqnhkq3qwmevhmvrrzbrvnybpoksp7swq
- Notary Requested: ericfish

@giggy22 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by rayshitou** [comment]
@giggy22 Glad to see you. 
Are you applying Datacap in the name of a company? Could you please give me a brief introduction about your company? And I want to know more about your business, cause the Datacap you application is not a small one.

**Comment by giggy22** [comment]
Hi. @rayshitou. Thank you for your reply. 
First, let me introduce our company. 
NOKNOK is Korea’s TOP Casual Simulation Game Company.
The history of games made by NOKNOK is as follows:

History of NOKNOK
2018. 09 – “Happy Delivery for Kakao” launched on KaKao games, Popularity Rank #1
2018. 05 – "Inn of Heroes" launched on Google Play.
2015.08 – “Happy Delivery for Kakao” launched on Google Play.
2015.06 – “Take Care of My Family “ launched. Google Play, Top Revenue Rank #54
2015.12 – "Chef Over Flower" launched. Google Play, Top Revenue Rank #34
2014.11 – "Happy Happy Bread Mobile” signs with Thai Publisher( True Digital Plus ) 
2014.09 – "Happy Happy Bread" launched. Google Play Japan, Revenue Rank # 40 ( Casual games Chart )
2014.04 – "Take Care of my Pet” launched. Google Play, Popularity Rank #1
2014.01 – "Happy Happy Bread for Kakao” launched. Google Play, Revenue Rank 28
2013.11 – "I Love Style for Kakao” launched. Google Play, Revenue Rank #26
2012.09 – "Fashion City Mobile” launched. Google Play, Top Revenue Rank #19
2012.07 – "Fashion City Mobile” launched. Apple App. Store, Top Revenue Rank #4
2012.03 – "Fashion City” Ranked #5 on Japan’s Mixi SNG ( PC ) 
2011.10 – "Fashion City” Ranked #1 on Taiwan’s SNS platform Yahoo Minik ( PC )
2011.03 – "Fashion City" Ranked #1 on Naver App. Store ( PC )
2009.12 – Noknok founded * Korea market ranking

In addition to the representative games of NOKNOK mentioned above, we have created various games. 
Even now, we are developing various games. AND In the future, we hope to develop games based on the IPFS ecosystem. :D
We know that the DataCap we applied for is not small, but the data capacity we currently have is close to 1PB. 
Please take that into consideration.

**Comment by rayshitou** [comment]
Great! 
With such a large demand for capacity, would you consider applying for large datasets? The related link: https://github.com/filecoin-project/filecoin-plus-large-datasets
Of course, we will continue to participate as one of your notaries in your large datasets applications.

**Comment by giggy22** [comment]
As you suggested, we applied for the Large Datasets DataCap Application. 
[https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/25](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/25)
We did our best to answer the necessary questions.

**Comment by rayshitou** [comment]
Well, I'll close this application.
