### ISSUE TITLE
Client Allocation Request for: NHN KCP CORP.

### ISSUE THREAD

**Issue by choibs95** [filecoin-project/filecoin-plus-client-onboarding#596]
---

# Client Allocation Questions 

## Core Information
- Name: NHN KCP CORP
- Website / Social Media: "https://www.kcp.co.kr/main.do" member of NHN CORP  "https://www.nhn.com/en/index.nhn"
- Region: Asia excl. Greater China
- DataCap Requested: 500TiB
- Addresses to be Notarized: f3wi7p7plkdzeyq5mjfjjvgztv757tzzibqd5sfr5xgoj7snsp4y34x67khduur43tutwj4cp5diyfihs2h6aa
- Notary Requested: philippbanhardt

@choibs95 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
Hi @choibs95, this may better be dealt with as a large datacap application. You can either resubmit [a smaller datacap request here](https://plus.fil.org/), or [start the process to get a larger datacap (500TiB and up) here.](https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/new/choose)
