### ISSUE TITLE
Client Allocation Request for: 福州达内信息科技有限公司

### ISSUE THREAD

**Issue by abcde12390** [filecoin-project/filecoin-plus-client-onboarding#598]
---

# Client Allocation Questions 

## Core Information
- Name: 福州达内信息科技有限公司
- Website / Social Media:https: http://www.tedu.cn/
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1ynk2lrlksum4mxkrmivzf3iudgquuevlyilwvoa
- Notary Requested: swatchliu

@abcde12390 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Hi, @abcde12390 

Thanks for your request. Can you kindly add more information here?

**1.** Is your company located in the Greater China？

**2.** Please give the following information and provide links to social media/news mentions.
1.Duration of establishment,

2.Number of employees, 

3.Business scope and products or services,

4.Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter e.g.)

5.Data size to be stored, 

**3.** Have you already apply for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?

**4.** Would you like to submit more real company information on www.bytebase.cn ?

**5.** Would you like to accept our face-to-face visit?

**Comment by abcde12390** [comment]
> # Client Allocation Questions
> ## Core Information
> * Name: 福州达内信息科技有限公司
> * Website / Social Media:https: http://www.tedu.cn/
> * Region: Greater China
> * DataCap Requested: 10TiB
> * Addresses to be Notarized: f1ynk2lrlksum4mxkrmivzf3iudgquuevlyilwvoa
> * Notary Requested: swatchliu
> 
> @abcde12390 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

We  can provide business license of the company.

**Comment by abcde12390** [comment]
> Hi, @abcde12390
> 
> Thanks for your request. Can you kindly add more information here?
> 
> **1.** Is your company located in the Greater China？
> Yes.
> **2.** Please give the following information and provide links to social media/news mentions.
> 1.Duration of establishment,
> 9 years.
> 2.Number of employees,
> more than 800 employees
> 3.Business scope and products or services,
> We cultivate middle and high-end software talents in Java, C, c# /.Net, testing, embedded and PHP oriented to telecommunication and finance.After 9 years of operation, we have achieved 98% professional employment rate and 78% public praise enrollment rate. At present, we have developed into a high-tech group company integrating traing, consulting, development and talent service. 
> 4.Social media link (Weibo, WeChat, Douyin, Zhihu, Facebook, Twitter e.g.)
> Weibo: https://weibo.com/u/2335414587
> 5.Data size to be stored,
> 10 TiB.
> **3.** Have you already apply for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left?
> Not yet.
> **4.** Would you like to submit more real company information on [www.bytebase.cn](http://www.bytebase.cn) ?
> Okay. Fine.
> **5.** Would you like to accept our face-to-face visit?
Yes.

**Comment by swatchliu** [comment]
Dear, @abcde12390 
According to our allocation strategy, we will grant you a maximum of 5TiB.

Please confirm the following information.

1. The Addresses : f1ynk2lrlksum4mxkrmivzf3iudgquuevlyilwvoa

2. Scoring Result : 1.75
![image](https://user-images.githubusercontent.com/46444977/127008128-d97776bb-791a-4298-8384-af32dc070e72.png)

**Comment by abcde12390** [comment]
> Dear, @abcde12390
> According to our allocation strategy, we will grant you a maximum of 5TiB.
> 
> Please confirm the following information.
> 
> 1. The Addresses : f1ynk2lrlksum4mxkrmivzf3iudgquuevlyilwvoa
> 2. Scoring Result : 1.75
>    ![image](https://user-images.githubusercontent.com/46444977/127008128-d97776bb-791a-4298-8384-af32dc070e72.png)

OK, many thanks.

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedtiiwwoox4axfdidnnyqrqxjfwxxtsu67quwq5r5cedib54ixdys 
#### Address 
> f1ynk2lrlksum4mxkrmivzf3iudgquuevlyilwvoa
#### Datacap Allocated
> 5TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedtiiwwoox4axfdidnnyqrqxjfwxxtsu67quwq5r5cedib54ixdys
