### ISSUE TITLE
Client Allocation Request for: Actiontec

### ISSUE THREAD

**Issue by DennisPope** [filecoin-project/filecoin-plus-client-onboarding#599]
---

# Client Allocation Questions 

## Core Information
- Name: Actiontec
- Website / Social Media: https://www.actiontec.com/
- Region: North America
- DataCap Requested: 1TiB
- Addresses to be Notarized: f1zhuddbzcxfwepnibcovfaw477m4kx5ikob35twa
- Notary Requested: DarnellWashington

@DennisPope Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by DarnellWashington** [comment]
Hello, Actiontec. I want to know more about your organization and project. So, please provide the following informations.

1.Please describe you and your organization, e.g. include establish time, history, etc.
2.Whether you fit the use case?
(Use Cases: Technological related documentation, video, audio, etc. especially focus on data emergency processing technology and mobile wireless communication technology, intellectual property technology，Filecoin application tecnnology)
3.Please describe the data you need to store, e.g. amount/source/type/property conditions.
4.What is the relationship between your business and the data to be stored? e.g.data generates from users.
5.Is your data public available? How could other people retrive it? e.g. there is a tool or manual inspection for retriving.
6.What is your allocation proportion to each miner? How will you find them? e.g. Slack
7.Do you agree to disclose  the transaction?
Thanks

Darnell

**Comment by DennisPope** [comment]
Hi,Darnell

1.Actiontec has been established for more than 10 years.We take the in-home Internet and Wi-Fi experience to the next level. Our groundbreaking Optim Managed Service Assurance Platform enables service providers to remotely manage, diagnose, optimize and secure home networks. With Optim, families can enjoy fast, reliable and safe Internet throughout the home, while providers can improve customer loyalty and lower operating costs. 

2.Yes,mainly videos.

3.Video files for testing.

4.Since Filecoin is currently a relatively mature blockchain storage system,We want to try to see if transferring video files via Filecoin can reduce costs. And video files are generated by us.

5.Yes.

6.We will find 3 suitable miners and divide the amount equally.

7.Yes.

**Comment by DarnellWashington** [comment]
I advocate my clients for storing real and valid data. Video files for testing may not be very suitable for requirements. 
Is there any valid data you'd like to store in the Filecoin network?

**Comment by DennisPope** [comment]
We decided to replace the test video data with video footage files, mainly some publicly copyrighted 4K videos , including cityscapes, time-lapse photography, and nature scenes.

**Comment by DarnellWashington** [comment]
@DennisPope 
I'll allocate you 200 GiB at first , hope you can know more about Filecoin storage and like it.
Thanks

**Comment by DennisPope** [comment]
Thank you very much!
