### ISSUE TITLE
Client Allocation Request for: 了凡超算

### ISSUE THREAD

**Issue by luhui123123** [filecoin-project/filecoin-plus-client-onboarding#6]
---

# Client Allocation Questions 

## Core Information
- Name: 了凡超算
- Website / Social Media: 
- DataCap Requested: 1TiB
- Addresses to be Notarized: f03482
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @luhui123123 - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- your relationship with the data, especially with regard to copyright
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
