### ISSUE TITLE
Client Allocation Request for: Fleek

### ISSUE THREAD

**Issue by jsonsivar** [filecoin-project/filecoin-plus-client-onboarding#607]
---

# Client Allocation Questions 

## Core Information
- Name: Fleek
- Website / Social Media: Fleek.co
- Region: North America
- DataCap Requested: 3TiB
- Addresses to be Notarized: f1u77wemzteznm5zar3dyyi4ybithzoite7f4sqky
- Notary Requested: s0nik42

@jsonsivar Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by jsonsivar** [comment]
Re-applying for 3TiB since the last one didn't work (https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/161). Spoke to @s0nik42 re: this.

**Comment by s0nik42** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaaeqvqrbx7ue3qemubu35k2bolp7jn5kjogqcnc2r4paht5gk7di 
#### Address 
> f1u77wemzteznm5zar3dyyi4ybithzoite7f4sqky
#### Datacap Allocated
> 3TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaaeqvqrbx7ue3qemubu35k2bolp7jn5kjogqcnc2r4paht5gk7di
