### ISSUE TITLE
Client Allocation Request for: Phi-Rjan

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/filecoin-plus-client-onboarding#62]
---

# Client Allocation Questions 

## Core Information
- Name: Phi-Rjan
- Website / Social Media: PhiMining.io / Phi-Rjan @slack
- DataCap Requested: 3TiB
- Addresses to be Notarized: f3v2bujmjhxugk3wtwwqha3za7vxmetyvd5rfj2dxff7zekibcclmbhd2ytrmrfls7bb2bz53ehcpl5npss5hq
- Notary Requested: s0nik42

**Comment by s0nik42** [comment]
Hi @rjan90  ,

Thanks for your request. Can you kindly add more information / context here on:

The region you are based and the one you physically operate
Yourself , e.g. include links to social media / news mentions etc
Your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
Type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
Your relationship with the data, especially with regard to copyright
How you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
Have you already ask datacap to another notary that have been accepted or rejected.
Thanks

Julien

**Comment by rjan90** [comment]
Hi @s0nik42! I got a datacap already from Philip! And as discussed on the call earlier today, I will keep it to one notary for now.

**Comment by s0nik42** [comment]
Thank you !
