### ISSUE TITLE
Client Allocation Request for: Arlo Technologies, Inc

### ISSUE THREAD

**Issue by yipie123** [filecoin-project/filecoin-plus-client-onboarding#620]
---

# Client Allocation Questions 

## Core Information
- Name: Arlo Technologies, Inc
- Website / Social Media: www.arlo.com
- Region: North America
- DataCap Requested: 10TiB
- Addresses to be Notarized: f16jobv4473xywqjvhbyocbsjwpzh5n4wemhs3vhy
- Notary Requested: Broz221

@yipie123 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Broz221** [comment]
@yipie123 

Thanks for your application!

Could you please introduce you and your company?

**Comment by yipie123** [comment]
> @yipie123
> 
> Thanks for your application!
> 
> Could you please introduce you and your company?

**Comment by yipie123** [comment]
Thanks for your response

I will introduce myself and my company.

I am a Program Manager in Arlo Technologies.I mainly work with product marketing, various engineering teams, as well as Operations, Marketing and Sales to coordinate and finalize the product requirements in functionality and schedule.

My company , Arlo is an award-winning, market leader in the smart home IoT category that is focused on bringing together deep expertise in product design, wireless connectivity and RF engineering, cloud infrastructure and leading-edge AI capabilities to create a seamless smart home experience for Arlo users that's easy to setup and a joy to interact with every day.

**Comment by Broz221** [comment]
@yipie123 

Hi. Then I would like to know your data related information.

1. Could you please send me some data demo?
2. What kind of data do you want to store?
3. Why you need 10 TiB datacap?

**Comment by yipie123** [comment]
@Broz221 
Hi，Broz221
1.I will show two videos on twitter and youtube , they are shoot by our product
https://twitter.com/ArloSmartHome/status/1425878019353321479
https://www.youtube.com/watch?v=VlnWp_ZPFOg
2.We mainly want to store some user's camera video data recorded by our product in the filecoin network.
3.Because we have a lot of data need to store ,so we plan to upload 10TiB first.

**Comment by Broz221** [comment]
@yipie123 

Hi. I also want to know your allocation decision. 
1. How many miners do you want to store? For how many regions?
2. What questions would you ask the miners?
3. What do you do to prevent overallocation?

**Comment by yipie123** [comment]
@Broz221 
Thanks for your question.
1.We consider 4 is more reasonable, mainly depends on the size and price of the miners.
2.Their price , location ,time can spend on our program.
3.We will check our datacap frequently ,limit the size that miners can mine to prevent overallocation.

**Comment by Broz221** [comment]
@yipie123 

Hi. I would like to give you 10 TiB first. Please be sure that you do the allocation according to your allocation decision.

**Comment by yipie123** [comment]
@Broz221 
Hi,I confirm , thank you for your help

**Comment by Broz221** [comment]
Hi, I can't see the public request in app now. I will give the DataCap to you when I can see it.

**Comment by Broz221** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedyu4hvycd7tpnxdnpm3am2i5ckl3xpizoex6l6n2evzhxuhjbugo 
#### Address 
> f16jobv4473xywqjvhbyocbsjwpzh5n4wemhs3vhy
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedyu4hvycd7tpnxdnpm3am2i5ckl3xpizoex6l6n2evzhxuhjbugo
