### ISSUE TITLE
Client Allocation Request for: PDX

### ISSUE THREAD

**Issue by Prapetrice** [filecoin-project/filecoin-plus-client-onboarding#621]
# Client Allocation Questions 

## Core Information
- Name: PDX
- Website / Social Media: [www.onbuff.com](www.onbuff.com)
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3w6wjjbelc2hcp2uptm4avwv7lfqc4r7cna77kf5giyattcffkdlbfxh53efsafiuec5jqyfrcf3sxet4hv5a
- Notary Requested: Broz221

-----------------------------

**Comment by Broz221** [comment]
@Prapetrice Hi, thanks for your application! Please introduce you and your company to me.
