### ISSUE TITLE
Client Allocation Request for: 江西融链数据有限公司

### ISSUE THREAD

**Issue by ipfslab** [filecoin-project/filecoin-plus-client-onboarding#627]
---

# Client Allocation Questions 

## Core Information
- Name: 江西融链数据有限公司
- Website / Social Media: http://www.jxrchain.pro/
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3q5l6njc2ruiruysp7ertgga6q3fk5km3ylx5eh4phzn3xznu4xs3pu2qirfs47q2ay3rsqkeuhw5tmmrwzya
- Notary Requested: ozhtdong

@ipfslab Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I want to know more basic information of you and your company. Please answer following question:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?

**Comment by ipfslab** [comment]
1.I'm a developer at 江西融链数据有限公司, responsible for storage technology development.
2.We focus on IPFS Application Development & Filecoin Tools development.This is our wechat official account:
![Wechat](https://z3.ax1x.com/2021/08/23/hCoV0O.jpg)
3.Our Business License:
![License](https://z3.ax1x.com/2021/08/23/hCTpb8.jpg)

**Comment by ozhtdong** [comment]
Hi.

I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency? Could you please show me your cloud usage evidence?
