### ISSUE TITLE
Client Allocation Request for: AIFS GROUP PTY LTD

### ISSUE THREAD

**Issue by graceonline9** [filecoin-project/filecoin-plus-client-onboarding#628]
---

# Client Allocation Questions 

## Core Information
- Name: AIFS GROUP PTY LTD
- Website / Social Media: @graceonline9 on GitHub
- Region: Oceania
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3vfhs75ongskrubmaxiditqtku2ew3nkkha33hxwaudc5hswriqo3xb2xk7ahvkac47f3bluwyscqdjidyilq
- Notary Requested: MegTei

@graceonline9 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MegTei** [comment]
HI @graceonline9 I'll run through some application triage questions with you, can you answer as best as possible, ping me if anything is unclear

**Comment by MegTei** [comment]
DATACAP REQUEST
1. In which region(s) do you intend to use the DataCap?
2. How did you hear about the Filecoin Datacap? Do you have a good understanding of the network and/or are involved in the web3.0 community?
3. What is your registered business name & address?
4. Provide a description of your business, the industry you work in and what you do.
5. What type/ category of data is being stored? (E.g Public data - back-up files, private encrypted files etc)
6. How much data will you onboard each week?
7. For how long do you intend to store your data with Filecoin? 
8. Have you previously received DataCap? If so, please link to any previous requests/ github issues.
9. Are you aware of and do you intend to use any advanced features (e.g. Fast Retrieval) with your storage deals? If so, please specify the feature.
10. How frequently do you intend to retrieve data stored on Filecoin e.g. monthly, a couple times a year, infrequently.

MINER DETAILS
11. How many miners do you plan on using to distribute the data, providing their ID's?
12. Are any of those miners controlled by yourself / your organization and if so, what is the percentage?
13. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?

**Comment by MegTei** [comment]
HI @graceonline9 would you still like to progress this datacap request?
