### ISSUE TITLE
Client Allocation Request for: 8x8, Inc.

### ISSUE THREAD

**Issue by Michelleo1** [filecoin-project/filecoin-plus-client-onboarding#637]
---

# Client Allocation Questions 

## Core Information
- Name: 8x8, Inc.
- Website / Social Media: www.8x8.com
- Region: North America
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1f5nlsvqkwpm5de74ig5iapgnfytcucti6b6b7yq
- Notary Requested: Broz221

@Michelleo1 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Broz221** [comment]
@Michelleo1 Hi, thanks for application!

Could you please introduce you and your company?

**Comment by Michelleo1** [comment]
@Broz221 
Thank you for your questions.
I am the data operation director of the company's video conference department, mainly responsible for the sorting and monitoring of video conference data to ensure the normal operation pf the whole system.

8x8, Inc. is a provider of cloud-based, enterprise-class software solutions that transform the way businesses communicate and collaborate globally. The Company's comprehensive software platform brings together the power of cloud, mobile, collaboration, video and data science technologies to enhance the way employees communicate with each other, and how they connect and interact with their customers.

**Comment by Broz221** [comment]
@Michelleo1 
Hi. Then I would like to know your data related information.

Could you please send me some data demo?
What kind of data do you want to store?
Why you need 10 TiB datacap?

**Comment by Michelleo1** [comment]
@Broz221 
Hi，Broz221，
1.data demo：
https://www.youtube.com/watch?v=7LZ97DrOuio
https://twitter.com/8x8/status/1430996836739915785
2.We mainly want to store some users‘ movie recorded by our product in the filecoin network.
3. We have so much  data need to store ,and we plan to upload 10TiB first.

**Comment by Broz221** [comment]
@Michelleo1 
Hi. I also want to know your allocation decision.

How many miners do you want to store? For how many regions?
What questions would you ask the miners?
What do you do to prevent overallocation?

**Comment by Michelleo1** [comment]
@Broz221
Thanks for your  responde.
1.We believe 3-4 is ok.
2.I will ask them about their price , location ,time can spend on our program.
3.We will check our datacap frequently ,limit the size that miners can mine to prevent overallocation.

**Comment by Broz221** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebwkdp5ife3cgfuzctxw4tvceuww7ibyxigfzp3wmgueaaxfdrvu6 
#### Address 
> f1f5nlsvqkwpm5de74ig5iapgnfytcucti6b6b7yq
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebwkdp5ife3cgfuzctxw4tvceuww7ibyxigfzp3wmgueaaxfdrvu6
