### ISSUE TITLE
Client Allocation Request for: 22nd Century Group, Inc.

### ISSUE THREAD

**Issue by Carinali1** [filecoin-project/filecoin-plus-client-onboarding#638]
---

# Client Allocation Questions 

## Core Information
- Name: 22nd Century Group, Inc.
- Website / Social Media: www.xxiicentury.com
- Region: North America
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1awef73heaulp2542qh4zjmzz3bjjhfk6wkaxpqi
- Notary Requested: Broz221

@Carinali1 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Broz221** [comment]
@Carinali1 

Hi, thanks for application!

Could you please introduce you and your company?

**Comment by Carinali1** [comment]
@Broz221 
Thank you for your question.
I am the market leader of the company. I am mainly responsible for investigating market demand and marketing new products. I have a lot of company product information and data.

My company，22nd Century Group, Inc. is a plant biotechnology company focused on technology which allows it to increase or decrease the level of nicotine in tobacco plants and the level of cannabinoids in cannabis plants through genetic engineering and plant breeding. My Company’s primary mission is to reduce the harm caused by smoking. 22nd Century currently owns or exclusively controls more than 200 issued patents and more than 50 pending patent applications around the world. The Company’s strong IP position led to a licensing agreement with British American Tobacco (“BAT”), the world’s second largest tobacco company.

**Comment by Broz221** [comment]
@Carinali1 
Hi. Then I would like to know your data related information.

Could you please send me some data demo?
What kind of data do you want to store?
Why you need 10 TiB datacap?

**Comment by Carinali1** [comment]
@Broz221 
Hi，Broz221
1.About data demo：
https://twitter.com/Joep1811/status/1429442264208527361
https://www.youtube.com/watch?v=Zm74IFiAHNI

2.We mainly store the data of some tobacco products, involving the composition, number and price of tobacco.

3.We have a lot of product, their composition is various, so we plan to upload 10TiB first.

**Comment by Broz221** [comment]
@Carinali1 
Hi. I also want to know your allocation decision.

How many miners do you want to store? For how many regions?
What questions would you ask the miners?
What do you do to prevent overallocation?

**Comment by Carinali1** [comment]
@Broz221 
Thanks for your questions .
1.We consider 3 or more is reasonable, mainly depends on the ability of the miners.
2.The miners‘  price , location ,time can spend on my program.
3.We will check our datacap frequently ,limit the size that miners can mine to prevent overallocation.

**Comment by Broz221** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedryqab37iq6dd6tztm2n3c2jxyagmvdeo6jujproqe35otwdyghw 
#### Address 
> f1awef73heaulp2542qh4zjmzz3bjjhfk6wkaxpqi
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedryqab37iq6dd6tztm2n3c2jxyagmvdeo6jujproqe35otwdyghw
