### ISSUE TITLE
Client Allocation Request for: Ipzoe

### ISSUE THREAD

**Issue by Shuri-rr** [filecoin-project/filecoin-plus-client-onboarding#640]
---

# Client Allocation Questions 

## Core Information
- Name: Ipzoe
- Website / Social Media: www.ipzoe.com
- Region: Greater China
- DataCap Requested: 3TiB
- Addresses to be Notarized: f1k46ibag6ot374ckvp3253x7trtf7a2fl5aby4ii
- Notary Requested: dannyob

@Shuri-rr Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
Hi @Shuri-rr ! Please remember to distribute this allocation among multiple miners, and please no miners you have a direct connection with. Your use of this datacap could affect your ability to receive further datacap. Thank you!

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamwhkmqbyrt5ff6ngous6kivl3ldutsdrewkzdtr7kozqbmpc3re 
#### Address 
> f1k46ibag6ot374ckvp3253x7trtf7a2fl5aby4ii
#### Datacap Allocated
> 3TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamwhkmqbyrt5ff6ngous6kivl3ldutsdrewkzdtr7kozqbmpc3re

**Comment by chicChang** [comment]
I'll see if I can comment

**Comment by chicChang** [comment]
> ## 请求已获批准
> 您的 Datacap 分配请求已获得公证人的批准
> 
> #### 消息发送到 Filecoin 网络
> > bafy2bzaceamwhkmqbyrt5ff6ngous6kivl3ldutsdrewkzdtr7kozqbmpc3re
> 
> #### 地址
> > f1k46ibag6ot374ckvp3253x7trtf7a2fl5aby4ii
> 
> #### 分配的数据上限
> > 3TiB
> 
> #### 您可以在此处查看消息状态：[https](https://filfox.info/en/message/bafy2bzaceamwhkmqbyrt5ff6ngous6kivl3ldutsdrewkzdtr7kozqbmpc3re) : [//filfox.info/en/message/bafy2bzaceamwhkmqbyrt5ff6ngous6kivl3ldutsdrewkzdtr7kozqbmpc3re](https://filfox.info/en/message/bafy2bzaceamwhkmqbyrt5ff6ngous6kivl3ldutsdrewkzdtr7kozqbmpc3re)

What are you doing

**Comment by chicChang** [comment]
> ## 请求已获批准
> 您的 Datacap 批准请求已获得公证人的批准
> 
> #### 消息发送到 Filecoin 网络
> > bafy2bzaceamwhkmqbyrt5ff6ngous6kivl3ldutsdrewkzdtr7kozqbmpc3re
> 
> #### 地址
> > f1k46ibag6ot374ckvp3253x7trtf7a2fl5aby4ii
> 
> #### 分配的数据资源
> > 3TiB
> 
> #### 您可以在此处查看消息状态：[https](https://filfox.info/en/message/bafy2bzaceamwhkmqbyrt5ff6ngous6kivl3ldutsdrewkzdtr7kozqbmpc3re) : [//filfox.info/en/message/bafy2bzaceamwhkmqbyrt5ff6ngous6kivl3ldutsdrewkzdtr7kozqbmpc3re](https://filfox.info/en/message/bafy2bzaceamwhkmqbyrt5ff6ngous6kivl3ldutsdrewkzdtr7kozqbmpc3re)

What are you doing
