### ISSUE TITLE
Client Allocation Request for: Fin-File Crypto

### ISSUE THREAD

**Issue by georgemac510** [filecoin-project/filecoin-plus-client-onboarding#641]
---

# Client Allocation Questions 

## Core Information
- Name: Fin-File Crypto
- Website / Social Media: https://twitter.com/mckurz
- Region: North America
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3woyrzyn634jgelyt4tj4hzw7mp7lxpacxbvaav3f7jnb4jrowjzl4mjadlpxgvxdiu36w23fzlizc5vs2bqa
- Notary Requested: andrewxhill

@georgemac510 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by georgemac510** [comment]
Anyone home?

**Comment by georgemac510** [comment]
Hi Textile team. Is there any chance I have another TB verified for the above address?  Thanks in advance.

**Comment by andrewxhill** [comment]
hey @georgemac510 sorry for the delay, I was OOO last week. just catching up. A few questions for you to answer, given that this is the extension of a previous request (https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/341).

### Usage

1. What portion of the originally granted datacap have you used to date? 
2. If less than 100% could you provide a short justification for why the early application?
3. If less than 100% and using a new target address, do you still plan on utilizing the original datacap too?

### Deployment

1. Can you provide any information on the deals you've created and miners you've used with your previously allocated datacap? (thanks for this already, above)
2. Are there any significant changes to your original application in terms of use-case, data inputs, or miner allocation?

thanks!

**Comment by georgemac510** [comment]
Hi Andrew,

Thank you for the speedy response from earlier today.

*Usage*
1) Of the 3 addresses that I use via Textile, each of their addresses and
status follow:
     a) hosted Powergate instance = not verified (interesting because I
thought it had been)

 f3suazi33hryyhksjtr6egyrtkusozjapk3gyke42np45yormcpjkgxx2mddccqu7ko4weeyzr4c6ekff2djwa
     b) Hub address for ***@***.*** = 24 GiB

 f3vn6ehbqdfsw36272obqpmekuswz5pqs47mtk27h56tmgaltmderm5g5sfj77unb47oiyef4zeszbtqu4lt6a
     c) Hub address for ***@***.*** = 2 GiB

 f3woyrzyn634jgelyt4tj4hzw7mp7lxpacxbvaav3f7jnb4jrowjzl4mjadlpxgvxdiu36w23fzlizc5vs2bqa

2) With two addresses left with verified datacap and so little datacap
remaining, it would be difficult to make many in one case and any in the
other verified deals.

3)  Yes I do wish to use all remaining datacap and with two distinctly
different projects, Fin-File-Crypto and Disco-Rock-Repo that utilize Hub
and/or hosted Powergate, I will have a reason to.

*Deployment*
1) Please navigate to:
https://docs.google.com/spreadsheets/d/e/2PACX-1vT5jRhrfA9TMr55GsX6dEE10rf-GNtZ_jRZmdjhyuWqhAswM_DJlaQuwdUEDgNyLVrfEtxN6xFiZPdg/pubhtml
to view all completed deals made during the Sligshot 2.4 competition.

2) My case now includes two apps as mentioned above that will be deployed
to the web tomorrow. Since both are datastores where adding inventory of
media on to IPFS/Filecoin is critical to their success, the verified
datacap will be important in accomplishing this. I have no particular miner
requirement aside from updating my storage config files regularly to have
the freshest list of willing miners.

Thank you so much for your consideration. I look forward to further success
with Textile.

Best regards,

John McLaughlin
***@***.***
***@***.***

**Comment by georgemac510** [comment]
Hi Andrew,

I wanted to touch base regarding a 1 TiB verified datacap for
f3woyrzyn634jgelyt4tj4hzw7mp7lxpacxbvaav3f7jnb4jrowjzl4mjadlpxgvxdiu36w23fzlizc5vs2bqa
(request #641). Can I supply any additional data to you to expedite the
granting of the datacap?

Thanks very much,

John mcLaughlin

**Comment by andrewxhill** [comment]
You are GTG

<img width="725" alt="Screen Shot 2021-08-23 at 12 25 59 PM" src="https://user-images.githubusercontent.com/370259/130507357-11c86c3b-ac46-453e-87a9-756a5b79316e.png">

**Comment by georgemac510** [comment]
Great news! Thank you so much Andrew.
