### ISSUE TITLE
Client Allocation Request for: OneChao

### ISSUE THREAD

**Issue by Titfordjaseph** [filecoin-project/filecoin-plus-client-onboarding#643]
---

# Client Allocation Questions 

## Core Information
- Name: OneChao
- Website / Social Media: http://www.1-zhao.com/
- Region: Greater China
- DataCap Requested: 3TiB
- Addresses to be Notarized: f1wyktymbfso7ps3ejna2nhxu4ksovfj2ddaikzza
- Notary Requested: dannyob

@Titfordjaseph Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Titfordjaseph** [comment]
Yes,I am the CEO of this company.  info@1-zhao.com

**Comment by dannyob** [comment]
Hi, I've sent you an email at that address. Could you reply to it please (to danny@fil.org)

**Comment by persisdezirea** [comment]
Hi,@dannyob
I have already confirmed.

**Comment by Titfordjaseph** [comment]
Hi，@dannyob
I have sent you the email.

**Comment by dannyob** [comment]
Great! Happy to allocate your datacap -- and if you need any more, please ask.

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaz2enpolesqxv37mstaragxoxznasynpoyufgzfrd356x6kv4zi2 
#### Address 
> f1wyktymbfso7ps3ejna2nhxu4ksovfj2ddaikzza
#### Datacap Allocated
> 3TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaz2enpolesqxv37mstaragxoxznasynpoyufgzfrd356x6kv4zi2

**Comment by mr-spaghetti-code** [comment]
Hi,

It looks like you received 3TiBs of DataCap to date but have spent less than 20% of it so far.

We would love to understand if there's anything holding you back. We are working hard to make the data onboarding process easier for clients like you and your feedback is very valuable. If you have a moment, please fill in this survey: https://forms.gle/s6AuTXZPZSMokscLA

If you have any feedback or would like to consult with an expert, please let me know. 

Thanks,

João Fiadeiro
Product Manager, Large Data Client Onboarding
Protocol Labs
