### ISSUE TITLE
Client Allocation Request for: Hetzner

### ISSUE THREAD

**Issue by Emmalin3** [filecoin-project/filecoin-plus-client-onboarding#646]
---

# Client Allocation Questions 

## Core Information
- Name: Hetzner
- Website / Social Media: https://www.hetzner.com/de/
- Region: Europe
- DataCap Requested: 3TiB
- Addresses to be Notarized: f1z3mm4b7oiyyxhkz7tiqlwqi4nwu7xooe5n4772i
- Notary Requested: dannyob

@Emmalin3 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
Hi @Emmalin3, could you give us a contact address at Hetzner (or an organization working for Hetzner) so we can confirm that this data is either stored with their permission, or is liberally licensed? Thanks!
