### ISSUE TITLE
Client Allocation Request for: Strato

### ISSUE THREAD

**Issue by Clara521** [filecoin-project/filecoin-plus-client-onboarding#647]
---

# Client Allocation Questions 

## Core Information
- Name: Strato
- Website / Social Media: https://www.strato.de
- Region: Europe
- DataCap Requested: 3TiB
- Addresses to be Notarized: f1l3fh2kydye2gtldelwl4xw6um2fpc2y2siploci
- Notary Requested: dannyob

@Clara521 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
Hello @Clara521 --- could you give us a good point of contact at www.strato.de so we can confirm you have the rights to store this data?
