### ISSUE TITLE
Client Allocation Request for: Domain Factory

### ISSUE THREAD

**Issue by schofieldresha** [filecoin-project/filecoin-plus-client-onboarding#649]
---

# Client Allocation Questions 

## Core Information
- Name: Domain Factory
- Website / Social Media: www.Df.eu
- Region: Europe
- DataCap Requested: 3TiB
- Addresses to be Notarized: f162po2nlneqbwmnxn4s3ej4jbf3dtc7fnd6ky75q
- Notary Requested: dannyob

@schofieldresha Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
Guten Tag, @schofieldresha ! Please ensure that you have the rights to store the data you're using on Filecoin, and use storage providers that you do not have any pre-existing relationship with. Your access to future datacap could be affected by these factors.

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceauebl6pyecb5saqfvhhqppxjhr7boccdco5zgrezdu7cjhhirake 
#### Address 
> f162po2nlneqbwmnxn4s3ej4jbf3dtc7fnd6ky75q
#### Datacap Allocated
> 3TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceauebl6pyecb5saqfvhhqppxjhr7boccdco5zgrezdu7cjhhirake
