### ISSUE TITLE
Client Allocation Request for: channeul

### ISSUE THREAD

**Issue by ckssmf0045** [filecoin-project/filecoin-plus-client-onboarding#655]
---

# Client Allocation Questions 

## Core Information
- Name: channeul
- Website / Social Media: www.redfox.gift
- Region: Asia excl. Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3xhkfkpiic35xrnzsyklgthys3po3c2dfidveg2syg3kqv3lmoqmo6dadlnmoxwupyal3s6maswnhtrvggeha
- Notary Requested: dannyob

@ckssmf0045 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
Hi, this looks like you are asking on behalf of a Filecoin storage provider (miner)? Datacap is for those wishing to store on the Filecoin network. Do you have a particular client? Or is this for offering datacap to potential clients?
'
안녕하세요, 이것은 Filecoin 저장소 제공자(광부)를 대신하여 묻는 것 같습니까? Datacap은 Filecoin 네트워크에 저장하려는 사람들을 위한 것입니다. 특정 고객이 있습니까? 아니면 잠재 고객에게 데이터 캡을 제공하기 위한 것입니까?

**Comment by dannyob** [comment]
@ckssmf0045  are you still interested in this datacap?

**Comment by hank-crypto** [comment]
Hi.  We are a company that produces karaoke VR contents. Our business goal is to spread K-POP, a part of The korean wave
(Hallyu) content, to the world through VR. In implementing the service, apply for a DATA CAP to actively review of IPFS.

**Comment by dannyob** [comment]
Okay! Please distribute your datacap with  miners who are unconnected with you. Thank you.

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebsosvhf2vyi4um2bg7gixqe33ljajruenbe34yxsjwazk4xjjkwq 
#### Address 
> f3xhkfkpiic35xrnzsyklgthys3po3c2dfidveg2syg3kqv3lmoqmo6dadlnmoxwupyal3s6maswnhtrvggeha
#### Datacap Allocated
> 1TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebsosvhf2vyi4um2bg7gixqe33ljajruenbe34yxsjwazk4xjjkwq

**Comment by ckssmf0045** [comment]
Thank you very much for allocated datacap.
