### ISSUE TITLE
Client Allocation Request for: future

### ISSUE THREAD

**Issue by ckssmf0045** [filecoin-project/filecoin-plus-client-onboarding#656]
---

# Client Allocation Questions 

## Core Information
- Name: future
- Website / Social Media: www.future.com
- Region: Africa
- DataCap Requested: 1TiB
- Addresses to be Notarized: 1111111
- Notary Requested: MasaakiNawatani

@ckssmf0045 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MasaakiNawatani** [comment]
This request does not have complete information. Closing this ticket.
