### ISSUE TITLE
Client Allocation Request for: weightofthenation

### ISSUE THREAD

**Issue by swatchliu** [filecoin-project/filecoin-plus-client-onboarding#657]
---

# Client Allocation Questions 

## Core Information
- Name: weightofthenation
- Website / Social Media: https://www.weightofthenation.org/
- Region: North America
- DataCap Requested: 2TiB
- Addresses to be Notarized: f1uzrraqusfe3sobkuu3abpr5ljpidcc63ymvkdaq
- Notary Requested: dannyob

@swatchliu Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
