### ISSUE TITLE
Client Allocation Request for: Chinese Institute of Digital Assets

### ISSUE THREAD

**Issue by liyue634** [filecoin-project/filecoin-plus-client-onboarding#66]
---

# Client Allocation Questions 

## Core Information
- Name: Chinese Institute of Digital Assets
- Website / Social Media: https://www.cida.ac.cn/
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1vaxz47wmq5ne6ph7rc4yi66lmrlhxeijebogvuy
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @liyue634 - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- your relationship with the data, especially with regard to copyright
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
