### ISSUE TITLE
Client Allocation Request for: Ancientgreek

### ISSUE THREAD

**Issue by VaggerXX** [filecoin-project/filecoin-plus-client-onboarding#662]
---

# Client Allocation Questions 

## Core Information
- Name: Ancientgreek
- Website / Social Media: http://www.ancientgreekwomen.com/gracesd02d.html
- Region: North America
- DataCap Requested: 1TiB
- Addresses to be Notarized: f1gtpgfpa5aan4kqxz24eigbba4qyj4ful7gby42a
- Notary Requested: dannyob

@VaggerXX Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
Hi, @VaggerXX , I'm not sure what you're looking for datacap for here. Could you explain further?

**Comment by VaggerXX** [comment]
Hey,  @dannyob  please allow me to introduce my project to you

From the website you can see that it is about ancient Greek culture,the content is mainly female oriented.This kind of theme is extremely rare.We have compiled a collection of public documents from around the world about ancient Greece.The data is cleaned, initially analyzed by Ai, and then edited by human.In this way we have compiled information about ancient Greece and divided it into nearly 200 sections.

The unique character of ancient Greek literature has made it one of the most important sources of world literature. With mythology, epic and tragedy as the most outstanding achievements, ancient Greek literature embodies the creative power and hope of the primitive ancestors to transcend reality and pursue the ideal of freedom. During this history women experienced a change in role from goddess-slave -woman. This is also the source of the development of female consciousness.

Our aim in making this project is to be able to preserve this history better, and we also hope that more people will use the information , especially for movies, TV shows, and games. It will be very helpful to them.
we intend to store some amount of rawdata that we have collected before.

**Comment by dannyob** [comment]
Okay. Please ensure you store your data with multiple storage providers that you have no relationship with.  This helps us to ensure that datacap is spread across the ecosystem. Good luck!

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceau6yvdzklafy2t7mev3rocpjc55pud2wlmfhqtzbcliddzixn4zk 
#### Address 
> f1gtpgfpa5aan4kqxz24eigbba4qyj4ful7gby42a
#### Datacap Allocated
> 1TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceau6yvdzklafy2t7mev3rocpjc55pud2wlmfhqtzbcliddzixn4zk
