### ISSUE TITLE
Client Allocation Request for: 福州浩能云网络科技有限公司

### ISSUE THREAD

**Issue by LandsatFile20** [filecoin-project/filecoin-plus-client-onboarding#67]
---

# Client Allocation Questions 

## Core Information
- Name: 福州浩能云网络科技有限公司
- Website / Social Media: https://preview.filhub.com
- DataCap Requested: 6.8TiB
- Addresses to be Notarized: f3xcu5ykb4cfoeyhvgy57outenx4njndazzgakcoebjiuvxrpwpl3bpv7wzfbvplgdq3w4mn5ke6ek2zuzpiea
- Notary Requested: Rin-huang

**Comment by 1am5UP3RasM4R10** [comment]
> # Client Allocation Questions
> ## Core Information
> * Name: LandSatFile
> * Website / Social Media: https://slingshot.filecoin.io/project/5fc274a7bb7b32dc2a0841d2
> * DataCap Requested: 5TiB
> * Addresses to be Notarized: f3wtftfpyxqyc4geuvca72k6o7ctkn4b7urbavnlizujtrow3qtdjzzpbc4mp7z4327mkzzqnfykzm333fk6sa
> * Notary Requested: Rin-huang

Can you provide me the email of the person in charge of your company's Filecoin + project? We will contact you soon. Thanks!

**Comment by LandsatFile20** [comment]
hao@filhub.com
my weichat : Gcaitou


Zhehao chen <notifications@github.com> 于 2021年2月19日周五 下午4:45写道：

**Comment by Fenbushi-Filecoin** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacec46qs7muqkw7zhqlaogaykmu5ushhx2prlkslhcteikmzfrpw7dq 
#### Address 
> f3xcu5ykb4cfoeyhvgy57outenx4njndazzgakcoebjiuvxrpwpl3bpv7wzfbvplgdq3w4mn5ke6ek2zuzpiea
#### Datacap Allocated
> 6.8TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacec46qs7muqkw7zhqlaogaykmu5ushhx2prlkslhcteikmzfrpw7dq

**Comment by LandsatFile20** [comment]
[Due to loss of secret key
](https://github.com/filecoin-project/filecoin-plus-client-onboarding/issues/409)
We want to set this address (**f3xcu5ykb4cfoeyhvgy57outenx4njndazzgakcoebjiuvxrpwpl3bpv7wzfbvplgdq3w4mn5ke6ek2zuzpiea**) datacaps to 0 .

## check this address remain datacaps
```
lotus-shed verifreg  check-client  f3xcu5ykb4cfoeyhvgy57outenx4njndazzgakcoebjiuvxrpwpl3bpv7wzfbvplgdq3w4mn5ke6ek2zuzpiea
7476679068877
```

**Comment by LandsatFile20** [comment]
Rereply  #414
