### ISSUE TITLE
Client Allocation Request for: Medindia

### ISSUE THREAD

**Issue by Karidhal** [filecoin-project/filecoin-plus-client-onboarding#670]
---

# Client Allocation Questions 

## Core Information
- Name: Medindia
- Website / Social Media: https://hi.medindia.net/index.asp
- Region: Asia excl. Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1gtpgfpa5aan4kqxz24eigbba4qyj4ful7gby42a
- Notary Requested: rayshitou

@Averalln Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by rayshitou** [comment]
@Karidhal Thanks for your application. Please answer the following questions to let me know you and your company.

1.What's your name and your position in your company?What's your company's business?
2.Could you show me your company's business license? And please show me your company searching consequence in the local business license searching website.
3.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?Could you please show me your cloud usage evidence?

**Comment by rayshitou** [comment]
@Karidhal Thanks for your introduction. 
Please let me know:
1.What kind of data do you want to store and how much?
2.Could you please send me some demos of your data?
3.Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner's terms of service?
and please send  your company's business license and the searching consequence to my [email](dlleig@gmail.com). I can't see you responding to the prompt email.

**Comment by Karidhal** [comment]
Dear@rayshitou

1.We want to store some articles and videos about health care.
2.OK I have sent you the email, together with the business license and search results.
3.Yes I agree

**Comment by rayshitou** [comment]
Nice. About the allocation of Datacap, i want to confirm:
1.How many miners do you want to store your data to? How much data for each miner?
2.What method/tool will you use to insperct miners? Which aspect of miners will you inspect?
3.Will you record your allocation decision in public? Which platform will you use?
4.Have you ever allocated before? If yes, how did you do when you were questioned? Any links?

**Comment by Karidhal** [comment]
Dear@rayshitou

1.We will choose at least 3 miners，Try to keep equal distribution.
2.We will go through the block browser to see the miners' history, mainly including their scale and technical experience.
3.We will post the distribution records on Github.
4.No.

**Comment by rayshitou** [comment]
Sorry, I have received your demo data, but I have not received your business license and search results. Could you please check it?

**Comment by Karidhal** [comment]
Dear@rayshitou

I resent you the email.

**Comment by Karidhal** [comment]
Dear@rayshitou

What else I need to do?

**Comment by Karidhal** [comment]
Hello, Is there something wrong with the process?

**Comment by Karidhal** [comment]
Hello, I have rechecked and resent the email to you.

**Comment by rayshitou** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebnj4w2dgp332ohs7v7ml5ryli22sufk7e5a4v6jlu3occ6e4fres 
#### Address 
> f1gtpgfpa5aan4kqxz24eigbba4qyj4ful7gby42a
#### Datacap Allocated
> NaNB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebnj4w2dgp332ohs7v7ml5ryli22sufk7e5a4v6jlu3occ6e4fres
