### ISSUE TITLE
Client Allocation Request for: Estuary

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/filecoin-plus-client-onboarding#671]
---

# Client Allocation Questions 

## Core Information
- Name: Estuary
- Website / Social Media: https://estuary.tech
- Region: North America
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3vnq2cmwig3qjisnx5hobxvsd4drn4f54xfxnv4tciw6vnjdsf5xipgafreprh5riwmgtcirpcdmi3urbg36a
- Notary Requested: neogeweb3

@whyrusleeping Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by neogeweb3** [comment]
Hey @whyrusleeping, thanks for the request. I hope this would help you get through the gap in the LDN application.

**Comment by neogeweb3** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceak5ueay7ecm4hg4kn5zk4vmxsxbvxm6unxygoxdo5d4wf3thbdqe 
#### Address 
> f3vnq2cmwig3qjisnx5hobxvsd4drn4f54xfxnv4tciw6vnjdsf5xipgafreprh5riwmgtcirpcdmi3urbg36a
#### Datacap Allocated
> 5TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceak5ueay7ecm4hg4kn5zk4vmxsxbvxm6unxygoxdo5d4wf3thbdqe
