### ISSUE TITLE
Client Allocation Request for: Gameguess

### ISSUE THREAD

**Issue by Nashiyar** [filecoin-project/filecoin-plus-client-onboarding#672]
---

# Client Allocation Questions 

## Core Information
- Name: Gameguess
- Website / Social Media: https://www.its-ok-i-guess.com/
- Region: North America
- DataCap Requested: 4TiB
- Addresses to be Notarized: f1i7l42sbxdbiisql3pzvaz6zuncs6dd66r33jgoq
- Notary Requested: dannyob

@Nashiyar Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
Looks good! Please remember to store your datacap data with multiple miners.

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceajoinmy6dib2svu6pgitugrtsds3jwdgip5oom62b6vf6niw2bf4 
#### Address 
> f1i7l42sbxdbiisql3pzvaz6zuncs6dd66r33jgoq
#### Datacap Allocated
> 4TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceajoinmy6dib2svu6pgitugrtsds3jwdgip5oom62b6vf6niw2bf4

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced7z6y2fqbpe7v6so4loygzsxybpywjfjxm7pu722potmmyvz4dbi 
#### Address 
> f1i7l42sbxdbiisql3pzvaz6zuncs6dd66r33jgoq
#### Datacap Allocated
> 4TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced7z6y2fqbpe7v6so4loygzsxybpywjfjxm7pu722potmmyvz4dbi
