### ISSUE TITLE
Client Allocation Request for: Hengli

### ISSUE THREAD

**Issue by Esmer1** [filecoin-project/filecoin-plus-client-onboarding#678]
---

# Client Allocation Questions 

## Core Information
- Name: Hengli
- Website / Social Media: http://www.baacebattery.com/en/
- Region: Asia excl. Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1i7l42sbxdbiisql3pzvaz6zuncs6dd66r33jgoq
- Notary Requested: rayshitou

@Esmer1 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by rayshitou** [comment]
@Esmer1 Thanks for your application. Please answer the following questions to let me know you and your company.

1.What's your name and your position in your company?What's your company's business?
2.Could you show me your company's business license? And please show me your company searching consequence in the local business license searching website.
3.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?Could you please show me your cloud usage evidence?

**Comment by Esmer1** [comment]
Hi,rayshitou

1.What's your name and your position in your company?What's your company's business?
Sorry for taking so long to reply to you，I work at Hengli as the Director of Innovative Technology Development, you can call me Nguyễn Xuân Đường(Harris)

Our company is called JIANGXI HENGLI TECHNOLOGY BATTERY CO., LTD. Our office is a branch in Vietnam. As you can see our company is a professional battery research and development to produce manufacturing.Our batteries not only are sold in more than 30 provinces and cities in China, but also exported to the Europe, USA, Japan, South Asia and other countries which has a high reputation amount our clients.
The innovation department I work in is mainly to explore some new technologies to lay the foundation for the diversification of the company,Filecoin is also one of our research projects.

2.Could you show me your company's business license? And please show me your company searching consequence in the local business license searching website.
Yes, I will send the above information to you by Email later.

3.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?Could you please show me your cloud usage evidence?
We are mainly some self-built clouds, it is not convenient to send you the evidence.

**Comment by rayshitou** [comment]
It's ok.
1.What kind of data do you want to store and how much?
2.Could you please send me some demos of your data?
3.Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner's terms of service?

**Comment by Esmer1** [comment]
Hi,rayshitou

1.What kind of data do you want to store and how much?
We wanted to store some information about our products, including videos of factory manufacturing and outdoor use, in order to better test the performance of our products

2.Could you please send me some demos of your data?
Okay I will send it to you by email.

3.Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner's terms of service?
Yes I agree to comply

**Comment by rayshitou** [comment]
Sorry, i have not recived your company's business license and searching consequence, could you please confirm it had been sent right.
BTW, about the allocation of DataCap, i also want to know that:
1.How many miners do you want to store your data to? How much data for each miner?
2.What method/tool will you use to insperct miners? Which aspect of miners will you inspect?
3.Will you record your allocation decision in public? Which platform will you use?
4.Have you ever allocated before? If yes, how did you do when you were questioned? Any links?

**Comment by Esmer1** [comment]
Hi,rayshitou
There may have been some technical problems before, I have resent the email
1.We think 4-5 is appropriate.The maximum amount allocated to each miner will not exceed 30%.
2.We will look for a miner with a good reputation and consider the size of their storage capacity.
3.Yes,we will record our allocation decision in public,mainly Github.
4.Not yet.

**Comment by rayshitou** [comment]
Good. Finally, could you please check the business license you sent to me is right? The company has a different name.

**Comment by Esmer1** [comment]
Hi,rayshitou

Yes I checked, this is a branch in Vietnam

**Comment by Esmer1** [comment]
Hi,rayshitou
What should I do next?

**Comment by Esmer1** [comment]
I have resent it to you.

**Comment by rayshitou** [comment]
thanks, it's the one.

**Comment by rayshitou** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecxfys55th5fhtlvatjghqpbwg7ydq3m2gxzbt4apmcdq5vudmxgo 
#### Address 
> f1i7l42sbxdbiisql3pzvaz6zuncs6dd66r33jgoq
#### Datacap Allocated
> NaNB
#### Signer Address
> f136bz32l2hlyad4npmfg5dngcdw3jk3tpcpoz2ja
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecxfys55th5fhtlvatjghqpbwg7ydq3m2gxzbt4apmcdq5vudmxgo
