### ISSUE TITLE
Client Allocation Request for: Handetour

### ISSUE THREAD

**Issue by Janyiajia** [filecoin-project/filecoin-plus-client-onboarding#679]
---

# Client Allocation Questions 

## Core Information
- Name: Handetour
- Website / Social Media: https://handetour.crv.vn/
- Region: Asia excl. Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f13edakoidcbwhdnnxki6gz4sad67brhcpgxwexmq
- Notary Requested: rayshitou

@Janyiajia Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by rayshitou** [comment]
@Janyiajia Thanks for your application. Please answer the following questions to let me know you and your company.

1.What's your name and your position in your company?What's your company's business?
2.Could you show me your company's business license? And please show me your company searching consequence in the local business license searching website.
3.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?Could you please show me your cloud usage evidence?

**Comment by Janyiajia** [comment]
1.Hi rayshitou, I am Phuc Dat Bich you can call me Edwin,I have a technical job in this company.
This is our company profile
HANDETOUR with its head office situated in Hanoi capital, Vietnam, was established in early 2006 by Mr. Nguyen Tuan Anh and his team, soon becoming a Professional Inbound Tour Operator with thousands of travel agents and clients all over the world.
HANDETOUR, A real local, reliable Tour Operator and Travel Agency, specializes in High Quality and Luxury Travel in Vietnam, Laos and Cambodia.
HANDETOUR provides clients with classic culture and leisure packaged tours, luxury tours, cruises, set departure tours, daily excursions, customized tours, special interest tours and other travel services (quality accommodation booking, fast visa service, easy ticket booking, transportation arrangement, qualified tour guide/ interpreter hire and M.I.C.E planning) within Indochina countries.
HANDETOUR also provides clients with other Asian multi-countries tours including Thailand, Myanmar, Indonesia, Malaysia, Philippines, China…
Our business has taken a hit due to COVID-19 and we are exploring new directions. We recognize NFT and we are considering combining our distinctive local landscape with NFT to create new opportunities.

2.This is not quite suitable for public display, I will send you via email

3.We mainly use some local cloud services,such as CMC Cloud.It will store some local natural scenery as well as keep photos and videos for visitors. It is about 80T per year.

**Comment by rayshitou** [comment]
Please send your company's business license and searching consequence to dlleig@gmail.com.
Could you please send me some demos of your data?
And do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner's terms of service?

**Comment by Janyiajia** [comment]
Hi rayshitou
I've resent it to you with the demo.
Yes I agree

**Comment by rayshitou** [comment]
Okey. About the allocation of DataCap, i want to know:
1.How many miners do you want to store your data to? How much data for each miner?
2.What method/tool will you use to insperct miners? Which aspect of miners will you inspect?
3.Will you record your allocation decision in public? Which platform will you use?
4.Have you ever allocated before? If yes, how did you do when you were questioned? Any links?

**Comment by Janyiajia** [comment]
Hi rayshitou

1.We believe that the quota should not be overly concentrated in one miner, more than 3 miners are necessary and each miner should not be allocated more than 40% of the quota.
2.In addition to geographic location, the skill level of the miners is what we take into account.
3.Yes, we will publicly distribute the records and the block browser will record them.
4.None.

**Comment by rayshitou** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb4w24ua2dxbooffb47xbmhabmwwxyzagzlrjx374f6vqxw5cw4um 
#### Address 
> f13edakoidcbwhdnnxki6gz4sad67brhcpgxwexmq
#### Datacap Allocated
> 5TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb4w24ua2dxbooffb47xbmhabmwwxyzagzlrjx374f6vqxw5cw4um

**Comment by mr-spaghetti-code** [comment]
Hi,

It looks like you received 5TiBs of DataCap to date but have spent less than 20% of it so far.

We would love to understand if there's anything holding you back. We are working hard to make the data onboarding process easier for clients like you and your feedback is very valuable. If you have a moment, please fill in this survey: https://forms.gle/s6AuTXZPZSMokscLA

If you have any feedback or would like to consult with an expert, please let me know. 

Thanks,

João Fiadeiro
Product Manager, Large Data Client Onboarding
Protocol Labs
