### ISSUE TITLE
Client Allocation Request for: Cuuhoa

### ISSUE THREAD

**Issue by Logical22** [filecoin-project/filecoin-plus-client-onboarding#680]
---

# Client Allocation Questions 

## Core Information
- Name: Cuuhoa
- Website / Social Media: http://www.cuuhoa.vn/en/
- Region: Asia excl. Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1x4p42mx75zha5ziqma2ib2sx2wbblytwvtez56a
- Notary Requested: rayshitou

@Logical22 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by rayshitou** [comment]
@Logical22 Thanks for your application. Please answer the following questions to let me know you and your company.

1.What's your name and your position in your company?What's your company's business?
2.Could you show me your company's business license? And please show me your company searching consequence in the local business license searching website.
3.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?Could you please show me your cloud usage evidence?

**Comment by Logical22** [comment]
Q1:Hello sir,my name is Dao The Duc. For convenience you can call me Camron. I am the technical department manager of Cuuhoa.
Our Company  business scope covers all areas of urban construction and every aspect of project construction. It has built many classic landmarks that record the changes of the times and engrave economic and cultural development at home and abroad, and has a comprehensive leading edge in the field of super high-rise buildings. Many major infrastructure projects that serve the national economy and people's livelihood have been completed in the fields of rail transit, bridges, and urban integrated pipe corridors. We continue to optimize our business structure on the premise of maintaining the leading position in the super high-rise sector. While continuing to develop and grow, seek out fields that are compatible with the company.

Q2:I will send the above information to your email address

Q3:We usually use Azure, which is about 10TB per month.About the evidence in the company guidelines are not easy to provide

**Comment by rayshitou** [comment]
Please send your company's business license and searching consequence to dlleig@gmail.com.
And please let me know:
1.What kind of data do you want to store and how much?
2.Could you please send me some demos of your data?
3.Do you agree to use the DataCap to only store data that abides by local regulations and in compliance with the recipient miner's terms of service?

**Comment by Logical22** [comment]
Hello sir

1.We want to store some videos of the tour.Around 20Tb
2.I have sent you an email with the business license and searching consequence.
3.Of course I agree.

**Comment by rayshitou** [comment]
Nice. And:
1.How many miners do you want to store your data to? How much data for each miner?
2.What method/tool will you use to insperct miners? Which aspect of miners will you inspect?
3.Will you record your allocation decision in public? Which platform will you use?
4.Have you ever allocated before? If yes, how did you do when you were questioned? Any links?

**Comment by rayshitou** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebycgv4tpuhkp6rdlio4gb6yjmjcq6rdi3esdwoknidqrcpqrkn3o 
#### Address 
> f1x4p42mx75zha5ziqma2ib2sx2wbblytwvtez56a
#### Datacap Allocated
> 5TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebycgv4tpuhkp6rdlio4gb6yjmjcq6rdi3esdwoknidqrcpqrkn3o
