### ISSUE TITLE
Client Allocation Request for: LandSatFile

### ISSUE THREAD

**Issue by hao-filhub** [filecoin-project/filecoin-plus-client-onboarding#69]
---

# Client Allocation Questions 

## Core Information
- Name: LandSatFile
- Website / Social Media: https://slingshot.filecoin.io/project/5fc274a7bb7b32dc2a0841d2
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3wtftfpyxqyc4geuvca72k6o7ctkn4b7urbavnlizujtrow3qtdjzzpbc4mp7z4327mkzzqnfykzm333fk6sa
- Notary Requested: s0nik42

**Comment by LandsatFile20** [comment]
hi , there is landsatfile (Chenhao) , 
This is our result in [SR2 .1](https://filecoinproject.slack.com/archives/C01AK1J7TF1/p1608336171453800),

We store %100 data that can be retrieval, you can view the final ranking and the data validation list, and you want to be able to apply down. Save more meaningful data for Filecoin.

**Comment by s0nik42** [comment]
Hi @LandsatFile20  ,

Thanks for your request. Can you kindly add more information / context here on:

The region you are based and the one you physically operate
Yourself , e.g. include links to social media / news mentions etc
Your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
Type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
Your relationship with the data, especially with regard to copyright
How you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc
Have you already ask datacap to another notary that have been accepted or rejected.
Thanks

Julien
