### ISSUE TITLE
Client Allocation Request for: Pixelastic

### ISSUE THREAD

**Issue by rittme33** [filecoin-project/filecoin-plus-client-onboarding#694]
---

# Client Allocation Questions 

## Core Information
- Name: Pixelastic
- Website / Social Media: https://gamemaster.pixelastic.com/terrainbuilding/#
- Region: North America
- DataCap Requested: 6TiB
- Addresses to be Notarized: f1ydznwjwjcotx6gejbj2z4jyc3tyow5bwqnrdl3i
- Notary Requested: dannyob

@rittme33 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
Here's your datacap, @rittme33. Please remember that datacap should be used for material that is unencrypted and licensed to be distributed to the public. Please use your datacap to make deals with more than one miner. And please don't use a miner you have a pre-existing relationship with. Spread the love! Use your datacap for the public good! Any questions, mail me at danny@fil.org or @dannyob on the [Filecoin Project slack](https://filecoinproject.slack.com/)

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebg7abelpq2ohilwbhjbdvlnf3nl43fzedk4sh2sjy2dovnsoinu2 
#### Address 
> f1ydznwjwjcotx6gejbj2z4jyc3tyow5bwqnrdl3i
#### Datacap Allocated
> 6TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebg7abelpq2ohilwbhjbdvlnf3nl43fzedk4sh2sjy2dovnsoinu2

**Comment by mr-spaghetti-code** [comment]
Hi,

It looks like you received 6TiBs of DataCap to date but have spent less than 20% of it so far.

We would love to understand if there's anything holding you back. We are working hard to make the data onboarding process easier for clients like you and your feedback is very valuable. If you have a moment, please fill in this survey: https://forms.gle/s6AuTXZPZSMokscLA

If you have any feedback or would like to consult with an expert, please let me know. 

Thanks,

João Fiadeiro
Product Manager, Large Data Client Onboarding
Protocol Labs
