### ISSUE TITLE
Client Allocation Request for: Introverted

### ISSUE THREAD

**Issue by gladdix** [filecoin-project/filecoin-plus-client-onboarding#695]
---

# Client Allocation Questions 

## Core Information
- Name: Introverted
- Website / Social Media: https://your-introverted-space.com/
- Region: North America
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1m2ap4ba72mlvlqch44vpe5vrhx3qmqlgiuqhw5q
- Notary Requested: dannyob

@gladdix Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7jbhxpx4v4qa3ds33o3emk4j3thw3ulps2unhkancznb4bo2ybk 
#### Address 
> f1m2ap4ba72mlvlqch44vpe5vrhx3qmqlgiuqhw5q
#### Datacap Allocated
> 5TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7jbhxpx4v4qa3ds33o3emk4j3thw3ulps2unhkancznb4bo2ybk

**Comment by dannyob** [comment]
Hey @gladdix, here's your datacap. Please remember that datacap should be used for material that is unencrypted and distributable to the public. Please use your datacap to make deals with more than one miner. And please don't use a miner you have a pre-existing relationship with. Spread the love! Use your datacap for the public good! Any questions, mail me at danny@fil.org or @dannyob on the [Filecoin Project slack](https://filecoinproject.slack.com/)

**Comment by mr-spaghetti-code** [comment]
Hi,

It looks like you received 5TiBs of DataCap to date but have spent less than 20% of it so far.

We would love to understand if there's anything holding you back. We are working hard to make the data onboarding process easier for clients like you and your feedback is very valuable. If you have a moment, please fill in this survey: https://forms.gle/s6AuTXZPZSMokscLA

If you have any feedback or would like to consult with an expert, please let me know. 

Thanks,

João Fiadeiro
Product Manager, Large Data Client Onboarding
Protocol Labs
