### ISSUE TITLE
Client Allocation Request for: (Sample Request)

### ISSUE THREAD

**Issue by galen-mcandrew** [filecoin-project/filecoin-plus-client-onboarding#696]
---

# Client Allocation Questions 

## Core Information
- Name: (Sample Request)
- Website / Social Media: google.com
- Region: Greater China
- DataCap Requested: 1KiB
- Addresses to be Notarized: f1
- Notary Requested: IreneYoung

@galen-mcandrew Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by galen-mcandrew** [comment]
Hi @IreneYoung

Testing out that you are getting the requests from the plus.fil.org app.

**Comment by IreneYoung** [comment]
> Hi @IreneYoung
> 
> Testing out that you are getting the requests from the plus.fil.org app.

Yes, I have checked that I got the requests from the plus.fil.org app. Thank you @galen-mcandrew

**Comment by galen-mcandrew** [comment]
Great! Will close this request. Thanks!
