### ISSUE TITLE
Client Allocation Request for: Shanghai YueJia information technology Co.,Ltd.

### ISSUE THREAD

**Issue by rammellsamisha78** [filecoin-project/filecoin-plus-client-onboarding#697]
---

# Client Allocation Questions 

## Core Information
- Name: 上海跃伽信息科技有限公司
- Website / Social Media: http://www.hopsum.com/
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f12aznu3gvruorilyk3ldkuse3zm373gdpntzkf6i
- Notary Requested: ozhtdong

@rammellsamisha78 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I want to know more basic information of you and your company. Please answer following question:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?

**Comment by rammellsamisha78** [comment]
OK~I'm Wei Aimin. I'm the legal person in our company.

Our company integrates functions such as shopping malls, membership cards and coupons, payment for knowledge, and merchant platform intra-city forums. It adopts a drag-and-drop page layout and provides multiple sets of industry modules. We'd like to help merchants quickly build exclusive online micro mall or micro official website.

Our official website：http://www.hopsum.com/ 

This is our business license.
![yuejia](https://user-images.githubusercontent.com/89062264/130047206-ef62df39-7e31-41d6-9381-0980a8519a48.jpg)

**Comment by rammellsamisha78** [comment]
OK~I'm Wei Aimin. I'm the CTO in our company.
![yuejia](https://user-images.githubusercontent.com/89062264/130047729-9827cf49-5c1a-45b3-bc4c-083ebd095656.jpg)


Our company integrates functions such as shopping malls, membership cards and coupons, payment for knowledge, and merchant platform intra-city forums. It adopts a drag-and-drop page layout and provides multiple sets of industry modules. We'd like to help merchants quickly build exclusive online micro mall or micro official website.

Our official website：http://www.hopsum.com/

This is our business license.
![yuejia](https://user-images.githubusercontent.com/89062264/130047754-93a0efb7-b7d9-4340-b8a1-e33f5aa93d46.jpg)

**Comment by rammellsamisha78** [comment]
OK~I'm Wei Aimin. I'm the CTO in our company.

Our company integrates functions such as shopping malls, membership cards and coupons, payment for knowledge, and merchant platform intra-city forums. It adopts a drag-and-drop page layout and provides multiple sets of industry modules. We'd like to help merchants quickly build exclusive online micro mall or micro official website.

Our official website：http://www.hopsum.com/

This is our business license.
![yuejia](https://user-images.githubusercontent.com/89062264/130047832-57bb3bd2-09b4-4e3a-8c7c-adbdcea4bf0b.jpg)

**Comment by ozhtdong** [comment]
Thanks for your quick reply and detailed information.
I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?

**Comment by rammellsamisha78** [comment]
Our data is about E-commerce product information, such as their products’ presentations, pictures and videos of their daily activities. 
Ok~ I‘ll show you, like this.
[yuejia.zip](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/7019553/yuejia.zip)
Yes，we have ever used Ali Yun. It‘s about 100 TiB a year.

**Comment by ozhtdong** [comment]
Thanks for your quick response. I also want to know more about your allocation strategy.

1.How many miners do you want to store your data to? How much data for each miner?
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect?
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by rammellsamisha78** [comment]
I think 3-4 miners is better. And we want to divide to each miner equally~
Yes，I will. I use github to record it. 
I think we will use filfox to help us. We want to look forward to someone who are creditable.
No, we’ve never allocated.

**Comment by rammellsamisha78** [comment]
Here is the business license.

**Comment by ozhtdong** [comment]
Thanks for your information.
The last step, please show me your company searching consequence in the local business license searching website.

**Comment by rammellsamisha78** [comment]
I will show you.
![yuejia](https://user-images.githubusercontent.com/89062264/130565256-30901976-d95e-4189-ba50-d706575d4547.png)

**Comment by ozhtdong** [comment]
[1475 allocation table_yuejia.xlsx](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/7082583/1475.allocation.table_yuejia.xlsx)

**Comment by ozhtdong** [comment]
10 TiB allocation for 1.8 score.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecjqqenjn67b2n4qdrnalhkylsswldjat2owot35ysrlz7yjlgsh6 
#### Address 
> f12aznu3gvruorilyk3ldkuse3zm373gdpntzkf6i
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecjqqenjn67b2n4qdrnalhkylsswldjat2owot35ysrlz7yjlgsh6
