### ISSUE TITLE
Client Allocation Request for: Phi Mining

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/filecoin-plus-client-onboarding#7]
---

# Client Allocation Questions 

## Core Information
- Name: Phi Mining
- Website / Social Media: https://phimining.io/
- DataCap Requested: 2TiB
- Addresses to be Notarized: f3v2bujmjhxugk3wtwwqha3za7vxmetyvd5rfj2dxff7zekibcclmbhd2ytrmrfls7bb2bz53ehcpl5npss5hq
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @rjan90 - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- your relationship with the data, especially with regard to copyright
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by rjan90** [comment]
Hey @philippbanhardt!

- Here is a link to my personal social media: [https://twitter.com/orjanroren](https://twitter.com/orjanroren )
- I have been interested in IPFS for a while, and tested it early in it's days. I have contributed to translate parts of the IPFS webUI / Desktop / Companion to Norwegian [https://www.transifex.com/ipfs/public/](https://www.transifex.com/ipfs/public/). Regarding Filecoin I tested out the "Replication Game"! and tried to optimize the algorithm [https://replication-game.herokuapp.com/](https://replication-game.herokuapp.com/). I also participated in SR1 & SR2 as a miner.
- I want to store different types of economic data & datasets, targeted for machine learning. Example of data-source [https://www.imf.org/en/Data](https://www.imf.org/en/Data)
- The data is free to use and reuse for commercial or non-commercial purposes.
- I plan to store the data across regions, and with multiple miners.

**Comment by philippbanhardt** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceakurxfkrwxgb5yetjxc5gycbkuhq5rvydzwr77d7yjh4f3iiesxs 
#### Address 
> f3v2bujmjhxugk3wtwwqha3za7vxmetyvd5rfj2dxff7zekibcclmbhd2ytrmrfls7bb2bz53ehcpl5npss5hq
#### Datacap Allocated
> 2 TiB
