### ISSUE TITLE
Client Allocation Request for: PiKNiK

### ISSUE THREAD

**Issue by patrick-PiKNiK** [filecoin-project/filecoin-plus-client-onboarding#70]
---

# Client Allocation Questions 

## Core Information
- Name: PiKNiK
- Website / Social Media: 
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1i6hxp2y3fu5kwyrwd7giz3vx2hzscpcxnj2i7fa
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @patrick-PiKNiK - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- your relationship with the data, especially with regard to copyright
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
