### ISSUE TITLE
Client Allocation Request for: Shanghai chuangfei

### ISSUE THREAD

**Issue by allyahwonfar61** [filecoin-project/filecoin-plus-client-onboarding#702]
---

# Client Allocation Questions 

## Core Information
- Name: Shanghai chuangfei
- Website / Social Media: https://cchain.top/
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1aujgasdra3diklch5apfqatihwy57zlvdyhs5ca
- Notary Requested: ozhtdong

@allyahwonfar61 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I want to know more basic information of you and your company. Please answer following question:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?

**Comment by allyahwonfar61** [comment]
Jason
A promoter of Shanghai Blockchain Agglomeration Area, a founder of C chain Yunxiang Chain (an e-government service chain), and a director of China Blockchain Application Research Center.

The company is a high-tech, double-soft enterprise with the goal of full coverage of smart state systems and blockchain technology as the core. It owns 15 computer software copyrights and focuses on becoming a  technological innovation leader in the digital economy era.

Company website：https://cchain.top/
![创飞](https://user-images.githubusercontent.com/89069113/130169549-b9d82537-cfcf-4b19-8a6d-32cd9627c04a.jpg)

**Comment by ozhtdong** [comment]
Thanks for your quick reply and detailed information.
I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?

**Comment by allyahwonfar61** [comment]
byte、short、int、long、float、double、boolean、char
We need more than 15 TiB.
Let me show you.
[chuangfei.zip](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/7019671/chuangfei.zip)

Tencent. More than 50TiB.

**Comment by ozhtdong** [comment]
Thanks for your quick response. I also want to know more about your allocation strategy.

1.How many miners do you want to store your data to? How much data for each miner?
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect?
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by ozhtdong** [comment]
Also, 

> byte、short、int、long、float、double、boolean、char

What are these? I am quite confused.

**Comment by allyahwonfar61** [comment]
4 miners. Average per miner.
Yes. I use github.
I don’t use any tool. I think miners should be large-scale. And I also want to check their technical strength and storage capacity.
No.
Basic data types of Java.

**Comment by allyahwonfar61** [comment]
Business license.

**Comment by ozhtdong** [comment]
Thanks for your information.
The last step, please show me your company searching consequence in the local business license searching website.

**Comment by allyahwonfar61** [comment]
OK.
![chuangfei](https://user-images.githubusercontent.com/89069113/130564752-27b595f0-3f44-4ca6-915e-44cd0f196819.png)

**Comment by ozhtdong** [comment]
> Also,
> 
> > byte、short、int、long、float、double、boolean、char
> 
> What are these? I am quite confused.

We would love to give you 15 TiB, but we'd love to know what are these?

**Comment by ozhtdong** [comment]
[1475 allocation table_chuangfei.xlsx](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/7082538/1475.allocation.table_chuangfei.xlsx)

**Comment by ozhtdong** [comment]
10 TiB allocation with the score 1.78.

**Comment by allyahwonfar61** [comment]
Thank you.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebn3nxhlmvayfgtqtha3n754fuoix5ppbdstgtmaaexkgsxllbh2o 
#### Address 
> f1aujgasdra3diklch5apfqatihwy57zlvdyhs5ca
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebn3nxhlmvayfgtqtha3n754fuoix5ppbdstgtmaaexkgsxllbh2o
