### ISSUE TITLE
Client Allocation Request for: FIT2CLOUD

### ISSUE THREAD

**Issue by shantiviavince64** [filecoin-project/filecoin-plus-client-onboarding#704]
---

# Client Allocation Questions 

## Core Information
- Name: FIT2CLOUD
- Website / Social Media: https://www.fit2cloud.com/index.html
- Region: Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1o4vntqro77hwg7zj64c7yzpuqubxhrvf44bwr3a
- Notary Requested: ozhtdong

@shantiviavince64 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I want to know more basic information of you and your company. Please answer following question:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?

**Comment by shantiviavince64** [comment]
1.Sydney xu. VP of our company.
2.FIT2CLOUD is a cloud management platform (CMP) provider that helps enterprises to unify the integration of hybrid IT infrastructure, including physical machines (AIX), virtualization platforms (vSphere, FusionSphere, etc.), private clouds (Openstack, etc.) and public clouds (Amazon AWS, Alibaba Cloud, etc.), realize resource statistics and cost analysis, and deliver IT resources in a unified manner to the outside world in the form of service catalogs, and realize self-service IT.
3.Ok email you.

**Comment by shantiviavince64** [comment]
Business license

**Comment by ozhtdong** [comment]
Hi.

I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency? Could you please show me your cloud usage evidence?

**Comment by marfazyheir48** [comment]
1.CDN cache data（videos）; I think we need almost 15 TiB.
Ok, I can send it to you by email.
2.Self-build cloud. We need more than 30 TiB per year.

**Comment by shantiviavince64** [comment]
1.CDN cache data（videos）; I think we need almost 15 TiB.
Ok, I can send it to you by email.
2.Self-build cloud. We need more than 30 TiB per year.

**Comment by shantiviavince64** [comment]
You can check our data sample.
 201911 Jumpserver V1.5.0.mp4
<https://drive.google.com/file/d/1GX9xODkKNj1GMbLQV3_kz9wIZnbogXQH/view?usp=drive_web>

**Comment by ozhtdong** [comment]
Thanks for your quick response. I also want to know more about your allocation strategy.

1.How many miners do you want to store your data to? How much data for each miner?
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect?
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by shantiviavince64** [comment]
1. We need more than 3 miners. Each miner is allocated no more than 40%.
2. In fact it will be recorded. We will use github.
3. Filfox will be used by us. We would pay more attention to creditable miners.
4. No, we have never allocated before.

**Comment by ozhtdong** [comment]
Thanks for your information.
The last step, please show me your company searching consequence in the local business license searching website.

**Comment by shantiviavince64** [comment]
OK. Later I will show you by email. Please wait a minute.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecv6he3zgpaohsmctawjq3mlhb5orwv3qg2swro5hsdy6vqehujae 
#### Address 
> f1o4vntqro77hwg7zj64c7yzpuqubxhrvf44bwr3a
#### Datacap Allocated
> 15TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecv6he3zgpaohsmctawjq3mlhb5orwv3qg2swro5hsdy6vqehujae
