### ISSUE TITLE
Client Allocation Request for: books

### ISSUE THREAD

**Issue by zyranenedina55** [filecoin-project/filecoin-plus-client-onboarding#714]
---

# Client Allocation Questions 

## Core Information
- Name: books
- Website / Social Media: https://www.books.com.tw/
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1j2c7gfoko3erjqw2jdwyva4glt6ac6syjamfaby
- Notary Requested: rayshitou

@zyranenedina55 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by rayshitou** [comment]
@zyranenedina55 Thanks for your application. Please answer the following questions to let me know you and your company.

1.What's your name and your position in your company?What's your company's business?
2.Could you show me your company's business license? And please show me your company searching consequence in the local business license searching website.
3.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?Could you please show me your cloud usage evidence?

**Comment by zyranenedina55** [comment]
Pirong Lin. I'm the legal person in our company.

In 1996, the books came to the online bookstore. The bookstore officially started to operate. The CD music hall was established the following year. Through the 7-11 cooperation with the group, it jointly created the online bookstore to buy books, 7-11 pickup and payment mechanism, and merged the department store products. 7 pavilions including beauty and health care, clothing accessories, food and beverages, creative life, toys, 3C, home appliances, etc., provide consumers with more choices for bookstore purchases. Books is the earliest online bookstore established in the three regions of the Taiwan Strait. Good book recommends the website with the highest evaluation by netizens. Pick up every other day 24 hours a day, all year round. In 2011, it was selected as one of the top 100 websites in Taiwan by the Digital Times for three consecutive years and launched mobile shopping services. Won the first place among the top 50 e-commerce companies in Taiwan in 2011 by Digital Times.

Can I email you? I will email you.

No, we have never use any cloud.

**Comment by zyranenedina55** [comment]
The business license and searching consequence~

**Comment by zyranenedina55** [comment]
@rayshitou Hi. Do you have any questions about our company?

**Comment by rayshitou** [comment]
Please send your company's business license and searching consequence to dlleig@gmail.com.

**Comment by zyranenedina55** [comment]
I have sent them to you already. You can check it out

**Comment by rayshitou** [comment]
Yeah, it's okey

**Comment by rayshitou** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebv6ehlglm7aoztfj5ewh3l7haqbua6jielpay42ah72zrsu63522 
#### Address 
> f1j2c7gfoko3erjqw2jdwyva4glt6ac6syjamfaby
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebv6ehlglm7aoztfj5ewh3l7haqbua6jielpay42ah72zrsu63522
