### ISSUE TITLE
Client Allocation Request for: VSDC

### ISSUE THREAD

**Issue by keyerahbrook** [filecoin-project/filecoin-plus-client-onboarding#733]
---

# Client Allocation Questions 

## Core Information
- Name: VSDC
- Website / Social Media: https://www.videosoftdev.com/
- Region: North America
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1rfoftvo4mid7qffjb3dxrwckkyqlfledeatfk4y
- Notary Requested: dannyob

@keyerahbrook Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
Here's your datacap. Please remember that datacap should be used for material that is unencrypted and licensed to be distributed to the public. Please use your datacap to make deals with more than one miner. And please don't use a miner you have a pre-existing relationship with. Spread the love! Use your datacap for the public good! Any questions, mail me at danny@fil.org or @dannyob on the [Filecoin Project slack](https://filecoinproject.slack.com/)

**Comment by dannyob** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebe3oz3iz4u27s7llrne7eugdkqtophuwjvz4l2vsv2vb6etlymue 
#### Address 
> f1rfoftvo4mid7qffjb3dxrwckkyqlfledeatfk4y
#### Datacap Allocated
> 5TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebe3oz3iz4u27s7llrne7eugdkqtophuwjvz4l2vsv2vb6etlymue

**Comment by dannyob** [comment]
@keyerahbrook , could you mail me a contact at VSDC -- a name and/or email address would be enough. Thank you.
