### ISSUE TITLE
Client Allocation Request for: hbr

### ISSUE THREAD

**Issue by zhakirajosman** [filecoin-project/filecoin-plus-client-onboarding#734]
---

# Client Allocation Questions 

## Core Information
- Name: hbr
- Website / Social Media: https://hbr.org/
- Region: North America
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1tcnwx3hgrhnu3newgj67dp362wts6rjkarz2sry
- Notary Requested: dannyob

@zhakirajosman Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
Here's your datacap. Please remember that datacap should be used for material that is unencrypted and licensed to be distributed to the public. Please use your datacap to make deals with more than one miner. And please don't use a miner you have a pre-existing relationship with. Spread the love! Use your datacap for the public good! Any questions, mail me at danny@fil.org or @dannyob on the [Filecoin Project slack](https://filecoinproject.slack.com/)

**Comment by dannyob** [comment]
Also, @zhakirajosman , could you email me (at danny@fil.org) a contact email or person at the Harvard Business School? Thanks!
