### ISSUE TITLE
Client Allocation Request for: Thisissand

### ISSUE THREAD

**Issue by 2362044297** [filecoin-project/filecoin-plus-client-onboarding#746]
---

# Client Allocation Questions 

## Core Information
- Name: Thisissand
- Website / Social Media: https://thisissand.com/
- Region: North America
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1ldzhbaoh2rmfw66rnbou4z53jphwapwhg73j5gq
- Notary Requested: dannyob

@reacehargr Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by reacehargr** [comment]
Hi,dannyob,I have replied you
