### ISSUE TITLE
Client Allocation Request for: younchang

### ISSUE THREAD

**Issue by trunbyevi** [filecoin-project/filecoin-plus-client-onboarding#768]
---

# Client Allocation Questions 

## Core Information
- Name: younchang
- Website / Social Media: http://younchang.co.kr/en/
- Region: North America
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1igeqr2jbvdjozbw4yozdnixrzwpdamduv6negia
- Notary Requested: Broz221

@trunbyevi Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Broz221** [comment]
Thanks for your application!

Could you please introduce you and your company?

**Comment by Broz221** [comment]
Hi, I viewed your website and found out you are from a Korea company. So I suggest you to choose an Asia notary.
