### ISSUE TITLE
Client Allocation Request for: noormgharwal

### ISSUE THREAD

**Issue by sharadalo** [filecoin-project/filecoin-plus-client-onboarding#769]
---

# Client Allocation Questions 

## Core Information
- Name: noormgharwal
- Website / Social Media: https://www.noormgharwal.com/
- Region: North America
- DataCap Requested: 10TiB
- Addresses to be Notarized: f15535gwigwuu3cze7yfyswsgxsazs6dk6rij35mi
- Notary Requested: Broz221

@sharadalo Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by Broz221** [comment]
Thanks for your application!

Could you please introduce you and your company?

**Comment by Broz221** [comment]
Hi, I viewed your company website and found out it was a Kabul Afghanistan company. So I suggest you to choose an Asia notary.
