### ISSUE TITLE
Client Allocation Request for: winmyanmartravel

### ISSUE THREAD

**Issue by mirethla** [filecoin-project/filecoin-plus-client-onboarding#770]
---

# Client Allocation Questions 

## Core Information
- Name: winmyanmartravel
- Website / Social Media: www.winmyanmartravel.com
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1sr7skr2qwsfatufxqduu4jz33mwg7qygthsmuta
- Notary Requested: rayshitou

@mirethla Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by rayshitou** [comment]
@mirethla Thanks for your application. Please answer the following questions to let me know you and your company.

1.What's your name and your position in your company?What's your company's business?
2.Could you show me your company's business license? And please show me your company searching consequence in the local business license searching website.
3.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?Could you please show me your cloud usage evidence?
