### ISSUE TITLE
Client Allocation Request for: wangfu technology

### ISSUE THREAD

**Issue by edmonstoneanalyse25** [filecoin-project/filecoin-plus-client-onboarding#774]
---

# Client Allocation Questions 

## Core Information
- Name: wangfu technology
- Website / Social Media: http://www.woropay.cn/index.html
- Region: Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1uwldyrntykzt7uyji556v3qk6bthecoji3hk2ka
- Notary Requested: ozhtdong

@edmonstoneanalyse25 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by edmonstoneanalyse25** [comment]
> ## Request Approved
> Your Datacap Allocation Request has been approved by the Notary
> 
> #### Message sent to Filecoin Network
> > bafy2bzacecgokrqjyv5fgobt7gqskc5ws5jsptmisqc4qti4ee63fuh66ucpo
> 
> #### Address
> > f1uwldyrntykzt7uyji556v3qk6bthecoji3hk2ka
> 
> #### Datacap Allocated
> > 15TiB
> 
> #### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgokrqjyv5fgobt7gqskc5ws5jsptmisqc4qti4ee63fuh66ucpo

Sorry, I want to say that I did not receive the datacap. I am not sure what the reason is. Can you help me？
@ozhtdong @galen-mcandrew @dkkapur

**Comment by galen-mcandrew** [comment]
Checking verify.glif.io for the client address f1uwldyrntykzt7uyji556v3qk6bthecoji3hk2ka, and I'm seeing 15TiB of DataCap. I think we got this resolved! Thanks for your help @Broz221 and @ozhtdong
