### ISSUE TITLE
Client Allocation Request for: Enrichcoffee

### ISSUE THREAD

**Issue by Leomiazz** [filecoin-project/filecoin-plus-client-onboarding#779]
---

# Client Allocation Questions 

## Core Information
- Name: Enrichcoffee
- Website / Social Media: https://www.enrichcoffeeco.com/
- Region: North America
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1uzrraqusfe3sobkuu3abpr5ljpidcc63ymvkdaq
- Notary Requested: dannyob

@Leomiazz Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by mr-spaghetti-code** [comment]
Hi,

It looks like you received 5TiBs of DataCap to date but have spent less than 20% of it so far.

We would love to understand if there's anything holding you back. We are working hard to make the data onboarding process easier for clients like you and your feedback is very valuable. If you have a moment, please fill in this survey: https://forms.gle/s6AuTXZPZSMokscLA

If you have any feedback or would like to consult with an expert, please let me know. 

Thanks,

João Fiadeiro
Product Manager, Large Data Client Onboarding
Protocol Labs
