### ISSUE TITLE
Client Allocation Request for: Ilshinchemical

### ISSUE THREAD

**Issue by ilshinchemical** [filecoin-project/filecoin-plus-client-onboarding#799]
---

# Client Allocation Questions 

## Core Information
- Name: Ilshinchemical
- Website / Social Media: http://ischem.co.kr/
- Region: Asia excl. Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3vsofilk653op74w67zxtn4ed7dygpdyki2x5tilnclmf76troni7zsag3msfv4y64qwijpkca5inx736vq4q
- Notary Requested: Broz221

@ilshinchemical Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ilshinchemical** [comment]
Hi Broz221.

I'm Kim, the main manager of the ilshinchemical co. Founded in June 1987, it specializes in various industries such as electronics, automobiles, rubber, paint and textiles. We continue to develop eco-friendly products to protect our customers and social values.

I'll look forward to hearing from you.

**Comment by Broz221** [comment]
Hi, I viewed your website and found out you are from an Asia company. So I suggest you to choose an Asia notary.
