### ISSUE TITLE
Client Allocation Request for: Hunan Bluestorm Information Technology Co., Ltd.

### ISSUE THREAD

**Issue by Amy131419** [filecoin-project/filecoin-plus-client-onboarding#8]
---

# Client Allocation Questions 

## Core Information
- Name: Hunan Bluestorm Information Technology Co., Ltd.
- Website / Social Media: www.hnbluestorm.com
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3wn5evvch64nlyqmgolgzxijta7ktdplyc6beb4apvfpngw5b6ahrn4svd32tuiwoac3du3ukqauqypjg65ka
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @Amy131419 - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- your relationship with the data, especially with regard to copyright
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks

**Comment by Amy131419** [comment]
Here is a link to my social media: www.hnbluestorm.com
we have been following  IPFS for over 3 years, and also participated in SR1 & SR2 as a miner, now we have almost 30PB woking in the whole IPFS mining network.
I want to store different types of data. Example of data-source http://lsfb-dex-center.oss-cn-hangzhou.aliyuncs.com/xiaochengxu//image/4820a24f874b4e45b6fddc63e23324b4.jpg
The data is free to use and reuse for commercial or non-commercial purposes.
I plan to store the data across regions, and with multiple miners.

**Comment by Amy131419** [comment]
Here is a link to my social media: www.hnbluestorm.com
we have been following  IPFS for over 3 years, and also participated in SR1 & SR2 as a miner, now we have almost 30PB woking in the whole IPFS mining network.
I want to store different types of data. Example of data-source http://lsfb-dex-center.oss-cn-hangzhou.aliyuncs.com/xiaochengxu//image/4820a24f874b4e45b6fddc63e23324b4.jpg
The data is free to use and reuse for commercial or non-commercial purposes.
I plan to store the data across regions, and with multiple miners.

**Comment by Amy131419** [comment]
Here is a link to my social media: www.hnbluestorm.com
we have been following  IPFS for over 3 years, and also participated in SR1 & SR2 as a miner, now we have almost 30PB woking in the whole IPFS mining network.
I want to store different types of data. Example of data-source http://lsfb-dex-center.oss-cn-hangzhou.aliyuncs.com/xiaochengxu//image/4820a24f874b4e45b6fddc63e23324b4.jpg
The data is free to use and reuse for commercial or non-commercial purposes.
I plan to store the data across regions, and with multiple miners.

**Comment by Amy131419** [comment]
Here is a link to my social media: www.hnbluestorm.com
we have been following  IPFS for over 3 years, and also participated in SR1 & SR2 as a miner, now we have almost 30PB woking in the whole IPFS mining network.
I want to store different types of data. Example of data-source http://lsfb-dex-center.oss-cn-hangzhou.aliyuncs.com/xiaochengxu//image/4820a24f874b4e45b6fddc63e23324b4.jpg
The data is free to use and reuse for commercial or non-commercial purposes.
I plan to store the data across regions, and with multiple miners.

**Comment by philippbanhardt** [comment]
Hey @Amy131419 thanks for the clarification. Can you kindly add more specific information on key individuals behind your company and the type of data you want to store? Thanks

**Comment by Amy131419** [comment]
Type of data:  
The livelihood service platform is customized for government and enterprise users according to their needs. The platform stores the data collected during the use of the platform, including but not limited to text, voice, pictures, videos and other data. The specific functions include volunteer activity information, public demands, evaluation, etc.

The company focuses on the Internet and mobile Internet field, intelligent manufacturing, Internet of Things and computer technology consulting services, is a set of software development and hardware sales as one of the technical comprehensive service solutions provider.
As the research and development practice base of the intelligent police platform of Hunan public security industry, the company has jointly developed the intelligent police platform with a number of units. The platform is a public security command system based on the police integrated platform, information research and judgment platform, geographic information platform and big data center, assisted by video surveillance system, GPS satellite positioning system and image transmission system, and supported by functions such as mobile phone alarm positioning, police service management and modern communication technology.
The company has made outstanding achievements in intelligent manufacturing. It has jointly developed intelligent safe door locks with a number of enterprises in other provinces, set up factories to produce intelligent products and set up joint research and development laboratories with colleges and universities by adopting the technology combination mode of intelligent hardware and software matching. The company's intelligent lock products are applying for the municipal, provincial and national scientific and technological innovation and related software copyright and related product utility and invention patents.
The company is a provider of Internet and mobile Internet application products and solutions, providing a number of Internet product research and development based on the "mobile Internet + industry" based smart community, smart joint defense and other Internet products, set about to establish the "Internet +" as the core of the security service product system, to provide service information guarantee for the safety of the masses.
The company provides professional product research and development services, from product positioning, research and development to operation, focusing on customer communication needs and product design, aiming to let customers experience service in products, feel professional in service, feel sincere in professional. The company has Internet research and development experience, service in the province many city enterprises, government units, tailored for customers in line with the industry characteristics of the solution, we will always be committed to the innovation of professional technology to promote the sustainable development of society, and strive to become a respected company by the society, customers and employees.


Key individuals:
Yuan Liang, General Manager, Company's overall operation management and business;
He Lie, Product Director,  responsible for product design and guidance before sales;
Tang Jianhua, development technical director, responsible for technical development guidance and development progress management.

**Comment by philippbanhardt** [comment]
Hi @Amy131419, thank you for adding context to your application, however I am afraid that at this time I am not going to be able to accept - principal reason being that I end of the day I find it too difficult to verify the information you have provided and get a grab on what is the exact data you will be storing. Please keep in mind that there are a number of other notaries available, also some that are actually located in China and will likely find it much easier to diligence your request.

Thanks,
Philipp
