### ISSUE TITLE
Client Allocation Request for: Hyundaihousis

### ISSUE THREAD

**Issue by hyundaisis** [filecoin-project/filecoin-plus-client-onboarding#810]
---

# Client Allocation Questions 

## Core Information
- Name: Hyundaihousis
- Website / Social Media: https://m.place.naver.com/place/37493922/home?entry=pll
- Region: Asia excl. Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3vxnotfq64nkf5jxfy3shg5vcj5h45h3qsrodkggdgrfvbniqg22kgjfhheorb2htov3g3pdfu4xp74dnlo5q
- Notary Requested: DarnellWashington

@hyundaisis Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by DarnellWashington** [comment]
Hello, @hyundaisis 

1.Please describe you and your organization, e.g. include establish time, history, etc.
2.Whether you fit the use case?
(Use Cases: Technological related documentation, video, audio, etc. especially focus on data emergency processing technology and mobile wireless communication technology, intellectual property technology，Filecoin application tecnnology)
3.Please describe the data you need to store, e.g. amount/source/type/property conditions.
4.What is the relationship between your business and the data to be stored? e.g.data generates from users.
5.Is your data public available? How could other people retrive it? e.g. there is a tool or manual inspection for retriving.
6.What is your allocation proportion to each miner? How will you find them? e.g. Slack
7.Do you agree to disclose the transaction?
Thanks

Darnell

**Comment by hyundaisis** [comment]
Thanks for your reply.

1. My name is Park, and I am the general manager of the company. Established in 2002, Hyundai Housys consists of paint, construction materials, and indoor woodworking. There are about 21 employees, and glass and synthetic resin windows are the main projects.

2. Unfortunately, our company doesn't have wireless communication technology or APP technology. However, we will actively utilize product promotional videos and advertising materials related to our technology.

3. As I said above, we will store product promotional videos and advertising materials, and it will be public data. And we want the amount of 1 TiB.

4. When we store data such as promotional videos, other people find it and watch it.

5. Yes. They can retrive it with tools

6. I haven't thought about it yet. I'll let you know as soon as it's decided.

7. Yes

**Comment by DarnellWashington** [comment]
I‘m sorry for my late reply.
But I don't think product promotional videos and advertising materials need 1 TiB. Can you make a introduction of these data?

**Comment by hyundaisis** [comment]
Thank you for your answer.

In addition to promotional videos and advertisements, we have a vast number of internal detailed technology designs and performance data that we have had before. It can't be shown because it's an internal technical part, but other data can be attached.

**Comment by DarnellWashington** [comment]
Hi, @hyundaisis 
I will allocate 100GB this time, and you can try storage on the Filecoin network.

**Comment by hyundaisis** [comment]
Thank you so much for allocating.
Can I store in the actual data and request additional applications later?

**Comment by DarnellWashington** [comment]
Yes, your usage of past allocation will be checked on the next application.
DataCap allocation is currently unavailable. I will solve this problem and complete the allocation as soon as possible.

**Comment by hyundaisis** [comment]
Thank you for your quick response.
Please contact us anytime when the problem is solved.

**Comment by DarnellWashington** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedcshmy54tm7ujkgac22mkm6kfuzbpapymcblog3eol34d4drntlc 
#### Address 
> f3vxnotfq64nkf5jxfy3shg5vcj5h45h3qsrodkggdgrfvbniqg22kgjfhheorb2htov3g3pdfu4xp74dnlo5q
#### Datacap Allocated
> 100GiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedcshmy54tm7ujkgac22mkm6kfuzbpapymcblog3eol34d4drntlc

**Comment by DarnellWashington** [comment]
Hope you have a good experience with storage on Filecoin network.

**Comment by hyundaisis** [comment]
Thank you so much for your efforts.

We would like to request an additional capacity data cap. This is because it is more insufficient than the internally determined data cap. As you know, we are engaged in construction materials and indoor woodworking business. We will see vast amounts of photos related to this every business. And it will be public data. Additionally, the capacity of internal technical design data is not small. So if we can't provide up to 1TiB, we ask for at least 500 GiB.

Thank you.

**Comment by DarnellWashington** [comment]
You can apply to me when DataCap have been used up.
