### ISSUE TITLE
Client Allocation Request for: Ilshinchemical

### ISSUE THREAD

**Issue by ilshinchemical** [filecoin-project/filecoin-plus-client-onboarding#816]
---

# Client Allocation Questions 

## Core Information
- Name: Ilshinchemical
- Website / Social Media: http://ischem.co.kr/
- Region: Asia excl. Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3vsofilk653op74w67zxtn4ed7dygpdyki2x5tilnclmf76troni7zsag3msfv4y64qwijpkca5inx736vq4q
- Notary Requested: IPFSUnion

@ilshinchemical Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by IPFSUnion** [comment]
Thank you for your request. I'd like to know more about your business. Can you kindly answer my following questions?
* individual and organization  
    1.	Please introduce yourself and your team briefly, and show me some your social media accounts such as GitHub, email address, WeChat official account etc.
    2.	For your organization, Please describe its time since inception, registration country，scale, named officers, project, industry reputation etc.
* track record
    1.	Regarding your data you intend to store, What’s the original source of those data, and do you have any proof of ownership or authorization?
    2. Has your organization obtained DataCap before? 
    3. Please list any of your honor and disputes in the field of Filecoin.
* use plan
    1.	Please describe your plan to use DataCap briefly? (such as use case, miner etc.)

**Comment by ilshinchemical** [comment]
1. Hi, my name is Park, and I am the general manager of this company. We are continuing to grow by maintaining customer and social values by developing environmentally friendly products that are applied to various business areas such as electronics and automobiles.

2. Our company was established in 1987 and is registered in South Korea. We are developing eco-friendly products that are applied to various business areas such as electronics and automobiles.

3. We will store public data, and promotional data and advertising for our products are the main data. We have ownership because it is our product.

4. No

5. No

6. We will utilize business data such as promotional data and advertising for the product, and as mentioned above, we will actively utilize it to our customers as public data.

**Comment by IPFSUnion** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacectd7ubut6dtjq2ewqy26ki2llw3rlb5vteqbnmu4coedwtugr4lu 
#### Address 
> f3vsofilk653op74w67zxtn4ed7dygpdyki2x5tilnclmf76troni7zsag3msfv4y64qwijpkca5inx736vq4q
#### Datacap Allocated
> 1TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacectd7ubut6dtjq2ewqy26ki2llw3rlb5vteqbnmu4coedwtugr4lu
