### ISSUE TITLE
Client Allocation Request for: Thisissand 

### ISSUE THREAD

**Issue by reacehargr** [filecoin-project/filecoin-plus-client-onboarding#820]
---

# Client Allocation Questions 

## Core Information
- Name: Thisissand
- Website / Social Media: https://thisissand.com/
- Region: North America
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1ldzhbaoh2rmfw66rnbou4z53jphwapwhg73j5gq
- Notary Requested: dannyob

@reacehargr Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
Hi @reacehargr , could you mail me at danny@fil.org from  a contact email address at Thisissand? Thanks.

**Comment by reacehargr** [comment]
Hi danny ﻿Hi I have sent you an email
