### ISSUE TITLE
Client Allocation Request for: business.nextdoor

### ISSUE THREAD

**Issue by jonaeljaqui** [filecoin-project/filecoin-plus-client-onboarding#829]
---

# Client Allocation Questions 

## Core Information
- Name: business.nextdoor
- Website / Social Media: https://business.nextdoor.com/
- Region: North America
- DataCap Requested: 5TiB
- Addresses to be Notarized: f1ihysdts3ptodjp4hcahjk2b5vekft2attye6a3i
- Notary Requested: Broz221

@jonaeljaqui Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dkkapur** [comment]
Will be reassigning to @TimWilliams00. Awaiting repo settings update.
