### ISSUE TITLE
Client Allocation Request for: BenjaminH

### ISSUE THREAD

**Issue by benjaminh83** [filecoin-project/filecoin-plus-client-onboarding#83]
---

# Client Allocation Questions 

## Core Information
- Name: BenjaminH
- Website / Social Media: BenjaminH (only on slack)
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3wjorbskpwyjaqenrl5fwizsast7fnmp7tzon4gmpzvgr3y2nuzvp7qwzn65stp42pwsgnptfkga6n4jj424q
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @benjaminh83 - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- your relationship with the data, especially with regard to copyright
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
