### ISSUE TITLE
Client Allocation Request for: goin-tech

### ISSUE THREAD

**Issue by emilcemalley04** [filecoin-project/filecoin-plus-client-onboarding#841]
---

# Client Allocation Questions 

## Core Information
- Name: goin-tech
- Website / Social Media: www.goin-tech.com
- Region: Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1hvxl2ctghh2omzxj6saeuppgpruaklq7binuy6q
- Notary Requested: ozhtdong

@emilcemalley04 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I want to know more basic information of you and your company. Please answer following question:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?

**Comment by emilcemalley04** [comment]
1.YuanJie Zhang. I’m executive director and general manager.
2. Goin uses the science and technology to build a humanistic world, and is committed to becoming a technology company that uses blockchain and other high-tech to protect privacy.
The company will build a blockchain product project matrix in the future. The initial project is uefan, a close-range interest social software based on blockchain to protect privacy. Pridow, a community that inherits the cypherpunk spirit and focuses on privacy protection.
https://www.goin-tech.com/
This is our official website.
3.Can I post it by email? I will send to you later.

**Comment by ozhtdong** [comment]
Thanks for your quick reply and detailed information.
I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?

**Comment by emilcemalley04** [comment]
1. What we want to store is data such as system logs, program logs, blockchain currency information, etc. Because the data sample is too large, I still email to you.
2.No.We haven’t use any cloud.

**Comment by emilcemalley04** [comment]
data sample

**Comment by ozhtdong** [comment]
Thanks for your quick response. I also want to know more about your allocation strategy.

1.How many miners do you want to store your data to? How much data for each miner?
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect?
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by emilcemalley04** [comment]
1. We want about 5 miners and divide to each miner equally.
2. Yes. I think github is suitable.
3. I haven't learned about related tools before. I want to find some miners who are creditable.
4. No, this is the first time.

**Comment by ozhtdong** [comment]
Thanks for your information.
The last step, please show me your company searching consequence in the local business license searching website.

**Comment by emilcemalley04** [comment]
OK. Please wait a minute. I will send to your email.

**Comment by emilcemalley04** [comment]
Here is the searching consequence.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb7zkbwajqsu3vnzbzzpdpz4vp2ee7aouoazctylad7lvnibhmp2u 
#### Address 
> f1hvxl2ctghh2omzxj6saeuppgpruaklq7binuy6q
#### Datacap Allocated
> 15TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb7zkbwajqsu3vnzbzzpdpz4vp2ee7aouoazctylad7lvnibhmp2u
