### ISSUE TITLE
Client Allocation Request for: mayi888

### ISSUE THREAD

**Issue by magelinewesthofer15** [filecoin-project/filecoin-plus-client-onboarding#842]
---

# Client Allocation Questions 

## Core Information
- Name: mayi888
- Website / Social Media: http://www.mayi888.com
- Region: Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1z6vdlyvlbhi2jdfj546epordsael4kq6ops64ai
- Notary Requested: ozhtdong

@magelinewesthofer15 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I want to know more basic information of you and your company. Please answer following question:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?

**Comment by magelinewesthofer15** [comment]
WenBin Zhang. I am the legal person.

The company helps companies quickly establish a new retail platform, realize online and offline multi-brand, multi-organization and global sales management, offline store cashier, social e-commerce management, private domain traffic management, user fission distribution.
It helps companies obtain more traffic and sales leads through search, and uses corporate precipitation data to accurately promote to WeChat Moments, information flow, keywords and other advertisements.

http://www.mayi888.com   You can find more details in this website.

I will send it to you privately.

**Comment by magelinewesthofer15** [comment]
Here is the business license.

**Comment by ozhtdong** [comment]
Thanks for your quick reply and detailed information.
I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?

**Comment by magelinewesthofer15** [comment]
We need to store customer's product information. The type of information is shown in the figure.
![d2483f1bcf6f95b1420b18d0d320d49](https://user-images.githubusercontent.com/89563281/131954539-e1a232b5-8aab-433a-90f2-bd500c125c6f.png)

Yes. We have ever used Ali Yun. About 50Tib a year.

**Comment by ozhtdong** [comment]
Thanks for your quick response. I also want to know more about your allocation strategy.

1.How many miners do you want to store your data to? How much data for each miner?
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect?
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by magelinewesthofer15** [comment]
1. 4 miners. Average per miner.
2. Github.
3. Filfox. I think miners should be large-scale. I also want to check their technical strength. 
4. No.

**Comment by ozhtdong** [comment]
Thanks for your information.
The last step, please show me your company searching consequence in the local business license searching website.

**Comment by magelinewesthofer15** [comment]
Hi, I will email you.

**Comment by magelinewesthofer15** [comment]
Here is the information you requested.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedmhl5nee4wqvh6wqnfiygzrozh3wjjiginhubvrbhtdo2rlehdc2 
#### Address 
> f1z6vdlyvlbhi2jdfj546epordsael4kq6ops64ai
#### Datacap Allocated
> 15TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedmhl5nee4wqvh6wqnfiygzrozh3wjjiginhubvrbhtdo2rlehdc2
