### ISSUE TITLE
Client Allocation Request for: hoangkimvietpacific

### ISSUE THREAD

**Issue by kylyhorton** [filecoin-project/filecoin-plus-client-onboarding#847]
---

# Client Allocation Questions 

## Core Information
- Name: hoangkimvietpacific
- Website / Social Media: https://hoangkimvietpacific.com/
- Region: Oceania
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1bmkq2l6zhjk6l236m2qoscoucitzfqlimnboixi
- Notary Requested: MegTei

@kylyhorton Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MegTei** [comment]
HI @kylyhorton I'll run through some application triage questions with you, can you answer as best as possible, ping me if anything is unclear

DATACAP REQUEST

1. In which region(s) do you intend to use the DataCap?
2. How did you hear about the Filecoin Datacap? Do you have a good understanding of the network and/or are involved in the web3.0 community?
3. What is your registered business name & address?
4. Provide a description of your business, the industry you work in and what you do.
5. What type/ category of data is being stored? (E.g Public data - back-up files, private encrypted files etc)
6. How much data will you onboard each week?
7. For how long do you intend to store your data with Filecoin?
8. Have you previously received DataCap? If so, please link to any previous requests/ github issues.
9. Are you aware of and do you intend to use any advanced features (e.g. Fast Retrieval) with your storage deals? If so, please specify the feature.
10. How frequently do you intend to retrieve data stored on Filecoin e.g. monthly, a couple times a year, infrequently.

MINER DETAILS
11. How many miners do you plan on using to distribute the data, providing their ID's?
12. Are any of those miners controlled by yourself / your organization and if so, what is the percentage?
13. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?

**Comment by kylyhorton** [comment]
1.In which region(s) do you intend to use the DataCap?
Australia,  Vietnam and China

2.How did you hear about the Filecoin Datacap? Do you have a good understanding of the network and/or are involved in the web3.0 community?
Awareness through the Internet.
Web 3.0 is the future trend of the Internet.

3.What is your registered business name & address?
Hoang Kim Viet Pacific Group Ltd
Address: P.O Box R99 - Ranadi industrial area, Honiara, Solomon Islands

4.Provide a description of your business, the industry you work in and what you do.
Hoang Kim Viet Pacific Group Limited is a fish processing company, owned by experienced Solomon Islands, Tuvaluan and Vietnamese within the fishing industry. Our company is keen to assist with the social developments and economic aspect of the fishery sector in Pacific countries, particularly for the rural populace at the provincial level as well as your National Government.
The company’s intention is to provide professional business services relating to harvesting of seafood to local communities and to actively participate in the assistance of support for livelihood of indigenous people and local communities.
Our company has more than 10 years of experience of Fisheries industry in countries such as Solomon Islands, Vanuatu, Vietnam, Malaysia, etc. Hoang Kim Viet Pacific also successfully doing business and invest in many fields: sand export, steel trading, operating cargo vessels, etc.


4.What type/ category of data is being stored? (E.g Public data - back-up files, private encrypted files etc)
We want to store some data about the ocean that contains Public data - back-up files.


5.How much data will you onboard each week?
Approx. 1TiB

6.For how long do you intend to store your data with Filecoin?
We think the same as Filecoin contract duration

7.Have you previously received DataCap? If so, please link to any previous requests/ github issues.
None.

8.Are you aware of and do you intend to use any advanced features (e.g. Fast Retrieval) with your storage deals? If so, please specify the feature.
I have some knowledge of it, which requires a pretty high level of technical capability

9.How frequently do you intend to retrieve data stored on Filecoin e.g. monthly, a couple times a year, infrequently.
May be  a couple times a year.

MINER DETAILS
11. How many miners do you plan on using to distribute the data, providing their ID's?
We think about 5 is appropriate

12. Are any of those miners controlled by yourself / your organization and if so, what is the percentage?
We don't know the miners

13. Do you agree on providing transparency of DataCap allocation decisions & execution details in public to prevent excessive/unfair self-dealing?
Yes I would like to make the DataCap distribution records publicly available on Github.

**Comment by MegTei** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceabrzs4f7erjloxk2xk6izd2lg2bcwtuf2sfdozfkxz6rmi47kagm 
#### Address 
> f1bmkq2l6zhjk6l236m2qoscoucitzfqlimnboixi
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceabrzs4f7erjloxk2xk6izd2lg2bcwtuf2sfdozfkxz6rmi47kagm

**Comment by MegTei** [comment]
HI @kylyhorton I have allocated DataCap.
Please remember the following:

1. DataCap should be used for material that is unencrypted and licensed to be distributed to the public.
2. Please use your DataCap to make deals with more than one miner.
3. And please don't use a miner you have a pre-existing relationship with. Spread the love!
4. Use your DataCap for the public good!
Any questions, ping me or reach out us on the Filecoin Project slack
