### ISSUE TITLE
Client Allocation Request for: evs

### ISSUE THREAD

**Issue by shaunicelehemann33** [filecoin-project/filecoin-plus-client-onboarding#849]
---

# Client Allocation Questions 

## Core Information
- Name: evs
- Website / Social Media: https://www.pickfoto.com/
- Region: Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1dy7qyjwj6jwsentkdlar3g6etuxjmze3pfkgkma
- Notary Requested: ozhtdong

@shaunicelehemann33 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I want to know more basic information of you and your company. Please answer following question:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?

**Comment by shaunicelehemann33** [comment]
You can check it.

**Comment by shaunicelehemann33** [comment]
1. Hello, my name is Ping Shao. I am the legal person in the company.
2. Our company is engaged in technology development, technology services, technology consulting, technology transfer, technology promotion; photography services; computer graphic design; graphic production; computer animation design; corporate planning; public relations services; economic information consulting (excluding investment consulting, non- Including education consulting); agency, production, and advertising; trademark transfer and agency services; copyright transfer and agency services; Internet information services; engaged in Internet cultural activities.
3. Ok. I have sent you an email about it.

**Comment by ozhtdong** [comment]
Thanks for your quick reply and detailed information.
I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?

**Comment by shaunicelehemann33** [comment]
1.We mainly store various types of image data. It almost need 15 TiB. There are some pictures. I will email you some image data.
2.No. We didn’t use any cloud for storage.

**Comment by ozhtdong** [comment]
Thanks for your quick response. I also want to know more about your allocation strategy.

1.How many miners do you want to store your data to? How much data for each miner?
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect?
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by shaunicelehemann33** [comment]
1.We want 3 miners. We will devide to each miner equally.
2.Yes, we will use github.
3.No tools we have used before. I want to check miners’ technical strength and storage capacity. 
4.We have never allocated before

**Comment by ozhtdong** [comment]
Thanks for your information.
The last step, please show me your company searching consequence in the local business license searching website.

**Comment by shaunicelehemann33** [comment]
Sure. I can email you.

**Comment by shaunicelehemann33** [comment]
Here is the searching consequence.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedy62af3xv4rz4h5muonzf32a4wivx6y3btckc7taasrjp5alkgfu 
#### Address 
> f1dy7qyjwj6jwsentkdlar3g6etuxjmze3pfkgkma
#### Datacap Allocated
> 15TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedy62af3xv4rz4h5muonzf32a4wivx6y3btckc7taasrjp5alkgfu
