### ISSUE TITLE
Client Allocation Request for: zkkj

### ISSUE THREAD

**Issue by keseyjeanelle52** [filecoin-project/filecoin-plus-client-onboarding#850]
---

# Client Allocation Questions 

## Core Information
- Name: zkkj
- Website / Social Media: https://vr.justeasy.cn/micro/14801.html
- Region: Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1zppvqcwyhzoo4657p6ca2qz4kbdn6ynvpfm7l2i
- Notary Requested: ozhtdong

@keseyjeanelle52 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I want to know more basic information of you and your company. Please answer following question:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?

**Comment by keseyjeanelle52** [comment]
Hui Zhang. A shareholder.

The company was established in 2009, currently the largest and most technically efficient design service system in Mianyang, specializing in indoor and outdoor 3D renderings, CAD construction drawing deepening, commercial space photography and HTC-VR immersive design reporting; the company’s drawing efficiency High, self-provided 200 multi-threaded HP workstation server, focusing on information visualization reporting and digital simulation technology development!

I will email you.

**Comment by keseyjeanelle52** [comment]
Business license

**Comment by ozhtdong** [comment]
Thanks for your quick reply and detailed information.
I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?

**Comment by keseyjeanelle52** [comment]
We mainly store indoor and outdoor 3D renderings and CAD construction drawing construction drawing.
I will email you a compressed package about data.

We haven’t used cloud before.

**Comment by ozhtdong** [comment]
Thanks for your quick response. I also want to know more about your allocation strategy.

1.How many miners do you want to store your data to? How much data for each miner?
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect?
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by keseyjeanelle52** [comment]
4 miners. Average per miner.

Github is the first choice.

We used filfox. I think miners should be large-scale.

No, we haven't allocated before.

**Comment by ozhtdong** [comment]
Thanks for your information.
The last step, please show me your company searching consequence in the local business license searching website.

**Comment by keseyjeanelle52** [comment]
Hi. I have emailed it to you.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecgmzi6pm6exee3wpka4sueqilzdyzpr4arsocnvtrgsa2r27mzs2 
#### Address 
> f1zppvqcwyhzoo4657p6ca2qz4kbdn6ynvpfm7l2i
#### Datacap Allocated
> 15TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecgmzi6pm6exee3wpka4sueqilzdyzpr4arsocnvtrgsa2r27mzs2
