### ISSUE TITLE
Client Allocation Request for: Xinshu

### ISSUE THREAD

**Issue by omanniongionna14** [filecoin-project/filecoin-plus-client-onboarding#851]
---

# Client Allocation Questions 

## Core Information
- Name: Xinshu
- Website / Social Media: http://iaphoto.cn/
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1skxf7htm4hhk7muli2b5pafh4pptwn5iukrr7wy
- Notary Requested: swatchliu

@omanniongionna14 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

1、Is your company located in the Greater China ?

2、Please give the following information and provide links to social media/news mentions.
A. Duration of establishment;
B. Nubmer of employees;
C. Business scope and products or services;
D. Social media link (Weibo, WeChat, Douyin, Zhihu，Facebook，Twitter，Linkedin，eg）
E. Data size to be stored.

3、Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left ?

4、Would you like to submit more company information on www.bytebase.cn ?

5、Would you like to accept our face-to-face visit ?

**Comment by omanniongionna14** [comment]
1.Yes. We are located in shanghai.
2.A. Our company was established on May 11, 2017.
B. More than 50 employees.
C. Our company is committed to becoming a leading provider of image management solutions on the Internet. In May 2019, we launched the Shishi Photo Album mobile app, officially entering the Internet industry.
D. https://baijiahao.baidu.com/s?id=1687313788274398980&wfr=spider&for=pc
E.We need 10 TiB.
3.No.
4.Yes. As long as you need, we will provide.
5.Sure. We are looking forward to it.

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecjeh7fdf4juwship4nw2svdbyldvk3smpfwk6kxzggtfc22x4nve 
#### Address 
> f1skxf7htm4hhk7muli2b5pafh4pptwn5iukrr7wy
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecjeh7fdf4juwship4nw2svdbyldvk3smpfwk6kxzggtfc22x4nve
