### ISSUE TITLE
Client Allocation Request for: pchome

### ISSUE THREAD

**Issue by hunasdetunikolert** [filecoin-project/filecoin-plus-client-onboarding#852]
---

# Client Allocation Questions 

## Core Information
- Name: pchome
- Website / Social Media: https://www.pchome.com.tw
- Region: Asia excl. Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1rklgiyvg53wjyy2zv47wz3tmlrc2blek3jxy4na
- Notary Requested: ozhtdong

@hunasdetunikolert Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I want to know more basic information of you and your company. Please answer following question:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?

**Comment by hunasdetunikolert** [comment]
Hello，I’m HongZhi Zhan. I am the chairman of the company. The PChome Online website was founded in 1996 and is one of Taiwan’s portals. In July 1998,  PChome Online Inc. was formally established. In January 2005, it was listed on the OTC under the "PChome" code 8044. Became the first Internet service company listed on the Taiwan Stock Exchange. After more than ten years of hard work, PChome is now the leading integrated Internet service provider group in Taiwan, providing e-commerce and online financial services. Services such as portals and portals provide users with the most local and high-quality Internet services.
Sure, I can email you.

**Comment by hunasdetunikolert** [comment]
Our business license.

**Comment by ozhtdong** [comment]
Thanks for your quick reply and detailed information.
I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?

**Comment by hunasdetunikolert** [comment]
We want to store image data and merchant product information data. We will use more than 15TiB. OK, I can show you.
![04240](https://user-images.githubusercontent.com/90231373/132441183-41586f08-6f30-44ed-ac03-62aa5a89bd54.png)

No, we haven’t.

**Comment by ozhtdong** [comment]
Thanks for your quick response. I also want to know more about your allocation strategy.

1.How many miners do you want to store your data to? How much data for each miner?
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect?
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by hunasdetunikolert** [comment]
4miners I think. We will allocate a share of no more than 30% to each miner.
Github is the best choice. We will use filfox to inspect miners. We want creditable miners. 
No. This is the first time we allocate.

**Comment by ozhtdong** [comment]
Thanks for your information.
The last step, please show me your company searching consequence in the local business license searching website.

**Comment by hunasdetunikolert** [comment]
Got it. I will email you.

**Comment by hunasdetunikolert** [comment]
This is the searching consequence.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaip3dbixrjkddqo7bq25ikvw55rdcnqba75c4qdvnlv5voeawwfc 
#### Address 
> f1rklgiyvg53wjyy2zv47wz3tmlrc2blek3jxy4na
#### Datacap Allocated
> 15TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaip3dbixrjkddqo7bq25ikvw55rdcnqba75c4qdvnlv5voeawwfc
