### ISSUE TITLE
Client Allocation Request for: XMjiyun

### ISSUE THREAD

**Issue by gokhalesantos550187** [filecoin-project/filecoin-plus-client-onboarding#853]
---

# Client Allocation Questions 

## Core Information
- Name: XMjiyun
- Website / Social Media: http://www.tfpass.cn/
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1g23hnpdd5rvajmji5t6hecduw4daqxcckfkuajq
- Notary Requested: ozhtdong

@gokhalesantos550187 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I want to know more basic information of you and your company. Please answer following question:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?

**Comment by gokhalesantos550187** [comment]
1. DingShan Zhao. I‘m an employee of our company.
2. Xiamen Jiyun Network Technology Co., Ltd., as a typical digital marketing technology company, follows the changes in digital marketing technology and software industry, and constantly adjusts and improves the company's SaaS product line, from programmatic advertising (RTB, API) to data platform ( DMP, CDP, data center), and then to private domain operations, conform to the development and evolution of the digital marketing industry from extensive operations to refined operations.
The product system of Jiyun Network includes a middle office and three front desks. The middle station integrates data-related functions and services such as data collection, data processing, data modeling, and data utilization on one platform. The three front desks in turn are the smart marketing cloud for public domain drainage, the smart SCRM system for private domain operations, and the smart shop social e-commerce platform to help companies quickly go online.
3. Ok. An email will be sent to you.

**Comment by gokhalesantos550187** [comment]
This is the business license.

**Comment by ozhtdong** [comment]
Thanks for your quick reply and detailed information.
I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?

**Comment by gokhalesantos550187** [comment]
1.We want to store e-commerce data. I will send you a zip about it via email.
2.Yes. We have used Amazon Cloud, Ali Cloud and UCloud. It is almost 50TiB a year.

**Comment by ozhtdong** [comment]
Thanks for your quick response. I also want to know more about your allocation strategy.

1.How many miners do you want to store your data to? How much data for each miner?
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect?
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by gokhalesantos550187** [comment]
1.I think 4-5 miners is better. And we want to divide to each miner equally.
2.Sure. We use github.
3.There is nothing that we will use. We are looking forward to miners who are large-scale.
4.No. We have never allocated before.

**Comment by ozhtdong** [comment]
Thanks for your information.
The last step, please show me your company searching consequence in the local business license searching website.

**Comment by gokhalesantos550187** [comment]
Searching consequence.

**Comment by gokhalesantos550187** [comment]
Hi. I have emailed you. You can check it in the mailbox.

**Comment by ozhtdong** [comment]
[1475 allocation table_XMjiyun.xlsx](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/7135622/1475.allocation.table_XMjiyun.xlsx)

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceatsylrm52m36ru2jdwu57kkvc4eofwxhaoobkg3yahozmljzi3ow 
#### Address 
> f1g23hnpdd5rvajmji5t6hecduw4daqxcckfkuajq
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceatsylrm52m36ru2jdwu57kkvc4eofwxhaoobkg3yahozmljzi3ow
