### ISSUE TITLE
Client Allocation Request for: jiliantech

### ISSUE THREAD

**Issue by anelajennings204110** [filecoin-project/filecoin-plus-client-onboarding#855]
---

# Client Allocation Questions 

## Core Information
- Name: jiliantech
- Website / Social Media: www.videojj.com
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1ztll3caq5m3qivovzipywtzqc75ebgpz4vieyiq
- Notary Requested: swatchliu

@anelajennings204110 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

1、Is your company located in the Greater China ?

2、Please give the following information and provide links to social media/news mentions.
A. Duration of establishment;
B. Nubmer of employees;
C. Business scope and products or services;
D. Social media link (Weibo, WeChat, Douyin, Zhihu，Facebook，Twitter，Linkedin，eg）
E. Data size to be stored.

3、Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left ?

4、Would you like to submit more company information on www.bytebase.cn ?

5、Would you like to accept our face-to-face visit ?

**Comment by swatchliu** [comment]
Had a good chat in your office this morning~

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaqbns4kilbfss4wysshh4dxgxa5vmcguveq7enduhvkiglblrwqa 
#### Address 
> f1ztll3caq5m3qivovzipywtzqc75ebgpz4vieyiq
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaqbns4kilbfss4wysshh4dxgxa5vmcguveq7enduhvkiglblrwqa
