### ISSUE TITLE
Client Allocation Request for: ZhongChuangCheng Blockchain (Shenzhen) Co., Ltd

### ISSUE THREAD

**Issue by ZHONGblock** [filecoin-project/filecoin-plus-client-onboarding#860]
---

# Client Allocation Questions 

## Core Information
- Name: ZhongChuangCheng Blockchain (Shenzhen) Co., Ltd
- Website / Social Media: 
- Region: Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f3ug3yxcynl457skempulutx3rfoxjxdnjbpicjp3raockxzrtangwr6u4tsgo4lldi2tvzijhfx6xvhbm5xea
- Notary Requested: dannyob

@ZHONGblock Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by dannyob** [comment]
Hi, could you make this request to one of the notaries serving Greater China? You can find the full list here: https://plus.fil.org/verifiers

**Comment by ZHONGblock** [comment]
OK
