### ISSUE TITLE
Client Allocation Request for: Beijing Tuobi

### ISSUE THREAD

**Issue by zohracharles450378** [filecoin-project/filecoin-plus-client-onboarding#865]
---

# Client Allocation Questions 

## Core Information
- Name: Beijing Tuobi
- Website / Social Media: http://www.2b.cn/
- Region: Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1m4setoa3ne4h6i5omad6lcbslhiv4asbg4pnpai
- Notary Requested: ozhtdong

@zohracharles450378 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. @zohracharles450378 

I want to know more basic information of you and your company. Please answer following question:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?

**Comment by zohracharles450378** [comment]
1.Hi. I am Ningbo Liu. I am the legal person and shareholder of the company.
2. 2b.cn, the most professional vertical media and industry service platform in the B2B industry, was founded in October 2012, led by professional B2B self-media person Ningbo Liu. With 2b.cn as the core, it focuses on industry research and industry services. The annual "China B2B E-Commerce Conference" hosted by the company has a huge influence in the B2B industry.
3.Ok. I can email you at once.

**Comment by zohracharles450378** [comment]
Hi. This is our company's business license.

**Comment by ozhtdong** [comment]
Thanks for your quick reply and detailed information.
I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?

**Comment by zohracharles450378** [comment]
1. Corporate Internet Marketing Promotional Materials. Like images and videoes. These demos are relatively large, I will email them to you.
2.Yes. We have used Ali Yun. It almost 50TiB a year we used in the past.

**Comment by ozhtdong** [comment]
I also want to know more about your allocation strategy.

1.How many miners do you want to store your data to? How much data for each miner?
2. Will you record your allocation decision in public? Which platform will you use?
3. What method/tool will you use to inspect miners? Which aspect of miners will you inspect?
4. Have you ever allocated before? If yes, how did you do when you were questioned?

**Comment by zohracharles450378** [comment]
1. I think that we need 5 miners.  4 TiB for each miner.
2. Sure. We will record it by github.
3. I think filfox is suitable. We want miners who are large-scale and creditable.
4. No, we haven’t. We have never allocated before.

**Comment by ozhtdong** [comment]
Thanks for your information.
The last step, please show me your company searching consequence in the local business license searching website.

**Comment by zohracharles450378** [comment]
Please check it.

**Comment by ozhtdong** [comment]
[1475 allocation table_BeijingTuobi.xlsx](https://github.com/filecoin-project/filecoin-plus-client-onboarding/files/7166410/1475.allocation.table_BeijingTuobi.xlsx)

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecvvbg4uiobfvvrar6socpxjlmhsrxcqnxnefzlokgkifmxvlux7y 
#### Address 
> f1m4setoa3ne4h6i5omad6lcbslhiv4asbg4pnpai
#### Datacap Allocated
> 15TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecvvbg4uiobfvvrar6socpxjlmhsrxcqnxnefzlokgkifmxvlux7y
