### ISSUE TITLE
Client Allocation Request for: yahoo

### ISSUE THREAD

**Issue by sapirmelton034621** [filecoin-project/filecoin-plus-client-onboarding#866]
---

# Client Allocation Questions 

## Core Information
- Name: yahoo
- Website / Social Media: https://tw.buy.yahoo.com/
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1eqk45cnsh5f4clxeflairogyt3kkldpu6msnlcq
- Notary Requested: swatchliu

@sapirmelton034621 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by swatchliu** [comment]
Thanks for your request. Can you kindly add more information here?

1、Is your company located in the Greater China ?

2、Please give the following information and provide links to social media/news mentions.
A. Duration of establishment;
B. Nubmer of employees;
C. Business scope and products or services;
D. Social media link (Weibo, WeChat, Douyin, Zhihu，Facebook，Twitter，Linkedin，eg）
E. Data size to be stored.

3、Have you already applied for DataCap to another notary, and whether it is accepted or rejected? Is there any reliable DataCap left ?

4、Would you like to submit more company information on www.bytebase.cn ?

5、Would you like to accept our face-to-face visit ?

**Comment by sapirmelton034621** [comment]
Hello @swatchliu   Thank you for your questions.
1.Yes.
2. We were established in October 2001. Now we have more than 200 employees in our company. 
Yahoo provides high-quality and diversified network content and services, and creates a localized, easy-to-use and life-oriented network environment. Yahoo also provides various network services for enterprises, assisting large, small and medium-sized enterprises, micro-enterprises, and even traditional industry customers to enhance their corporate reputation and network services, such as full-service local keyword advertising, various interactive advertising, Virtual stores, online transaction services, overall solutions for corporate portals, etc.
Our facebook：Yahoo奇摩購物中心
There is almost 10TiB we need to stored.
3.No, we haven’t. This is the first time.
4.Sure. Any kinds of information we have can be provided to you.
5.Yes. If you need it, we will cooperate.

**Comment by swatchliu** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecqm6njetg6okjfbqo2ihydkkpxglirl2ssncauwlilnkrh7aw6hw 
#### Address 
> f1eqk45cnsh5f4clxeflairogyt3kkldpu6msnlcq
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecqm6njetg6okjfbqo2ihydkkpxglirl2ssncauwlilnkrh7aw6hw
