### ISSUE TITLE
Client Allocation Request for: ZhongChuangCheng Blockchain (Shenzhen) Co., Ltd

### ISSUE THREAD

**Issue by ZHONGblock** [filecoin-project/filecoin-plus-client-onboarding#867]
---

# Client Allocation Questions 

## Core Information
- Name: ZhongChuangCheng Blockchain (Shenzhen) Co., Ltd
- Website / Social Media: 
- Region: Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f3ug3yxcynl457skempulutx3rfoxjxdnjbpicjp3raockxzrtangwr6u4tsgo4lldi2tvzijhfx6xvhbm5xea
- Notary Requested: ozhtdong

@ZHONGblock Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Hi. Please show your website/social media.

**Comment by ZHONGblock** [comment]
OK，here is our website : http://zhongblock.com/, our Wechat official account : 中创诚区块链

**Comment by ozhtdong** [comment]
Hi. I can't see anything in this website.

**Comment by ZHONGblock** [comment]
Sorry, the server of our official website is under maintenance

**Comment by ozhtdong** [comment]
Do you have other social medias?

**Comment by ZHONGblock** [comment]
we don't have other media.
