### ISSUE TITLE
Client Allocation Request for: jkopay

### ISSUE THREAD

**Issue by jkopay1** [filecoin-project/filecoin-plus-client-onboarding#880]
---

# Client Allocation Questions 

## Core Information
- Name: jkopay
- Website / Social Media: https://www.jkos.com/
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f12spmdxmksn7p4pj7whk3qtdkalln5oddcur53ga
- Notary Requested: ozhtdong

@jkopay1 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application.
I want to know more basic information of you and your company. Please answer following question:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?

**Comment by jkopay1** [comment]
1.I am Yijia Hu. I am the founder of the company.
2.The company's main project is to support mobile payment functions. IT creates a personal store message wall by setting up a dynamic wall to keep abreast of the latest news of favorite stores. And we support delivery services and various payment services in life. And it helps ensure information security and safe payment.
website: https://www.jkos.com/

3.Ok. It can be provided as an email. Later I will send you.

**Comment by jkopay1** [comment]
I have sended business license to you.

**Comment by ozhtdong** [comment]
Thanks for your quick reply and detailed information.
I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?

**Comment by jkopay1** [comment]
1.It is about some business information and coupon advertising information. I have made a zip which will be sent to you.
2. Self-build cloud. 20TiB/year.

**Comment by jkopay1** [comment]
Check it please.

**Comment by ozhtdong** [comment]
Thanks for your information.
The last step, please show me your company searching consequence in the local business license searching website.

**Comment by jkopay1** [comment]
OK. It was emailed to you.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceasod664ku6wqqa4i6hm4zxwkcwdarw5gdx6nczqexomrrvzjwz6e 
#### Address 
> f12spmdxmksn7p4pj7whk3qtdkalln5oddcur53ga
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceasod664ku6wqqa4i6hm4zxwkcwdarw5gdx6nczqexomrrvzjwz6e
