### ISSUE TITLE
Client Allocation Request for: himelight

### ISSUE THREAD

**Issue by himelight** [filecoin-project/filecoin-plus-client-onboarding#881]
---

# Client Allocation Questions 

## Core Information
- Name: himelight
- Website / Social Media: https://www.himelight.com/org/59a7d564c809aa474f41089c
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1wwuty54bkquibpqor4xkuam334xme2rqwzmojqq
- Notary Requested: ozhtdong

@himelight Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. 

I want to know more basic information of you and your company. Please answer following question:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?

**Comment by himelight** [comment]
Kaijie Zhan. I am a legal person.

It is a team of capital workers who want to use the technology platform to benefit themselves, add interest, and change the habitual mode. Jidianshu is committed to developing the most interesting and spoof regular customer management platform. It digitizes the traditional marketing tools such as gathering points, coupons, birthday coupons, etc. to achieve customer management and big data analysis. Through gathering points, it records customer consumption profiles. Achieve better marketing efficiency and stream smart retail for stores.

https://www.himelight.com/org/59a7d564c809aa474f41089c
This is our official website.

Yes, I will show you via email.

**Comment by himelight** [comment]
Hi. This is our business license.

**Comment by ozhtdong** [comment]
Thanks for your quick reply and detailed information.
I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?

**Comment by himelight** [comment]
Our data is the information of the merchant discount plans. I will email you too.

No we haven’t use any cloud before.

**Comment by himelight** [comment]
Here are demos.

**Comment by ozhtdong** [comment]
Thanks for your information.
The last step, please show me your company searching consequence in the local business license searching website.

**Comment by himelight** [comment]
Check it please.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb342ggbpxwi6ci7jqlvdlsxpkgqn66eugnd6ruujca3kv23dkrb4 
#### Address 
> f1wwuty54bkquibpqor4xkuam334xme2rqwzmojqq
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb342ggbpxwi6ci7jqlvdlsxpkgqn66eugnd6ruujca3kv23dkrb4
