### ISSUE TITLE
Client Allocation Request for: hxmps

### ISSUE THREAD

**Issue by brassmendoza** [filecoin-project/filecoin-plus-client-onboarding#890]
---

# Client Allocation Questions 

## Core Information
- Name: hxmps
- Website / Social Media: https://www.hxmps.com.tw/about-us
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1rrxyo4twpydgqarwxyzhaqnobemiduj6so27eka
- Notary Requested: ozhtdong

@brassmendoza Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your request!

I want to know more basic information of you and your company. Please answer following question:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?

**Comment by brassmendoza** [comment]
Hi, I’m HuiZhi Lin, the chairman of our company.
Our company conducts community maintenance and professional property management of buildings. 
1. Provide a full range of community services, high-quality management system 2. Security service items: more than ten items such as residential building security guards, corporate building security guards, and government agency security guards. 3. Secret Service Security: Provide professional personal safety maintenance and can send secret service security personnel to perform all-weather (personal protection) security guard work
Yes, you can know us from it. https://www.hxmps.com.tw/about-us

I will send it to your email.

**Comment by brassmendoza** [comment]
Here it is.

**Comment by ozhtdong** [comment]
Thanks for your quick reply and detailed information.
I have further more questions about data and storing.
1.What kind of data do you want to store and how much? Could you please send me some demos of your data?
2.Have you/your company ever used cloud? Which platform do you use? What's your usage volume and frequency?

**Comment by brassmendoza** [comment]
We want to store surveillance videos and pictures. It needs almost 10 TiB. 
Yes. I can email you too.

No. We haven't use any cloud before.

**Comment by brassmendoza** [comment]
demos

**Comment by ozhtdong** [comment]
Thanks for your information.
The last step, please show me your company searching consequence in the local business license searching website.

**Comment by brassmendoza** [comment]
Sure. I can provide it via email.

**Comment by brassmendoza** [comment]
This is the searching consequence.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedy5xckhqir6drqe5ekkyjkdhk4hu74ds6dffttalzfxez72nvwwe 
#### Address 
> f1rrxyo4twpydgqarwxyzhaqnobemiduj6so27eka
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedy5xckhqir6drqe5ekkyjkdhk4hu74ds6dffttalzfxez72nvwwe
