### ISSUE TITLE
Client Allocation Request for: yblt01

### ISSUE THREAD

**Issue by lainayoung** [filecoin-project/filecoin-plus-client-onboarding#895]
---

# Client Allocation Questions 

## Core Information
- Name: yblt01
- Website / Social Media: www.10010.cn
- Region: Greater China
- DataCap Requested: 50TiB
- Addresses to be Notarized: f1nuo623xwfzrkhabpcmhze6kyipcgxywt6fxdayi
- Notary Requested: ozhtdong

@lainayoung Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thank you for your application. I have some questions for you.
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by lainayoung** [comment]
1.My name is Song Sang. I’m an employee of the company.
2.China Unicom's fixed communications services include broadband, IPTV, and fixed telephones. At the same time, in order to meet the needs of household information services such as "broadband, mobile communications, call, high-definition TV, home networking" and other home users, China Unicom provides home users with family integration packages.
3.Yes. I will send to you.
4.At least 5 miners. We will divide to each miner equally.
5. We will use github to record.
6.I don’t know what method we can choose. We inspect miners who are large scale.

**Comment by lainayoung** [comment]
Please check it.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecqrkq27evf3kuktfx7a7le4ku6a7tk3jtlgg43vjbqojq2tcfgc2 
#### Address 
> f1nuo623xwfzrkhabpcmhze6kyipcgxywt6fxdayi
#### Datacap Allocated
> 50TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecqrkq27evf3kuktfx7a7le4ku6a7tk3jtlgg43vjbqojq2tcfgc2
