### ISSUE TITLE
Client Allocation Request for: Beijing Evs

### ISSUE THREAD

**Issue by tannvance** [filecoin-project/filecoin-plus-client-onboarding#896]
---

# Client Allocation Questions 

## Core Information
- Name: Beijing Evs
- Website / Social Media: https://www.pickfoto.com/
- Region: Greater China
- DataCap Requested: 30TiB
- Addresses to be Notarized: f1ueampl73vfysovrn5etmbaewyjizoduewevjqyi
- Notary Requested: ozhtdong

@tannvance Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thank you for your application. I have some questions for you.
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by tannvance** [comment]
Ping Shao. I am the legal person in the company.
Our company is engaged in technology development, technology services, technology consulting, technology transfer, technology promotion; photography services; computer graphic design; graphic production; computer animation design; corporate planning; public relations services; economic information consulting (excluding investment consulting, non- Including education consulting); agency, production, and advertising; trademark transfer and agency services; copyright transfer and agency services; Internet information services; engaged in Internet cultural activities.
I will send you an email.
4-5miners. We will allocate a share of no more than 30% to each miner.
Yes. We want to use github.
Filfox. I think creditable miners are better.

**Comment by tannvance** [comment]
business license

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceco5uuzo4eaxrv4i3fni2ojc46v6wvmvcjaqaffsmzuzesefpgq2e 
#### Address 
> f1ueampl73vfysovrn5etmbaewyjizoduewevjqyi
#### Datacap Allocated
> 30TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceco5uuzo4eaxrv4i3fni2ojc46v6wvmvcjaqaffsmzuzesefpgq2e
