### ISSUE TITLE
Client Allocation Request for: Yahoo

### ISSUE THREAD

**Issue by Zachariah-lin** [filecoin-project/filecoin-plus-client-onboarding#903]
---

# Client Allocation Questions 

## Core Information
- Name: Yahoo
- Website / Social Media: https://tw.buy.yahoo.com/
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f16uug26enj5lq7zh4xnguyc4ikxlsmj3xx66olci
- Notary Requested: ozhtdong

@Zachariah-Sun Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application , some questions to you: 
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by Zachariah-Sun** [comment]
1.I’m Peter Lin. I am the person in charge of the company.
2.Yahoo provides high-quality and diversified network content and services, and creates a localized, easy-to-use and life-oriented network environment. Yahoo also provides various network services for enterprises, assisting large, small and medium-sized enterprises, micro-enterprises, and even traditional industry customers to enhance their corporate reputation and network services, such as full-service local keyword advertising, various interactive advertising, Virtual stores, online transaction services, overall solutions for corporate portals, etc.
Yes, here it is. https://tw.buy.yahoo.com/
3.I can show you via email.
4.I prefer 3miners to do this. We will allocate a share of no more than a quarter of data to each miner.
5.Yes, we will record it. We use github.
6.Filfox can be used to inspect miners. Large-scale miners.

**Comment by Zachariah-lin** [comment]
business license

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedi7cfw2yq5jh6m7gwsunu6dtuvoh3eiwb3xxjxxgvkibbekqqydi 
#### Address 
> f16uug26enj5lq7zh4xnguyc4ikxlsmj3xx66olci
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedi7cfw2yq5jh6m7gwsunu6dtuvoh3eiwb3xxjxxgvkibbekqqydi
