### ISSUE TITLE
Client Allocation Request for: Jiliantech

### ISSUE THREAD

**Issue by anelajennings** [filecoin-project/filecoin-plus-client-onboarding#905]
---

# Client Allocation Questions 

## Core Information
- Name: Jiliantech
- Website / Social Media: www.videojj.com
- Region: Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1w3rry66h73rujh5scdkuigj4islxs3tkqdiraji
- Notary Requested: ozhtdong

@anelajennings204110 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application , some questions to you:
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by anelajennings204110** [comment]
Ming Jin. I’m a legal person.

Jilian Technology Development Group Co., Ltd. was founded in October 2014 in Shanghai, China, focusing on technology and consumption. It owns Jilian AI Cloud, TAKIPLAY Script Killing, TakiToys Trendy Toys, TakiLucky Entertainment Retail, Video++ Linglian Marketing, and Jilian Technology. In addition to online businesses such as technology, the chain is actively deploying offline consumer entities and has 20+ physical brand stores directly operated by TakiLucky and TakiPlay. The main investors of Jilian Technology Group include Alibaba, Yunfeng Fund, Megvii Technology Face++, Ubisoft, SDIC Fund, K11 Hong Kong New World, etc. It has received nearly 1 billion yuan in financing and has grown into a company with leading technology, a comprehensive commercial technology company with a large number of users and comprehensive revenue capabilities.

https://www.sohu.com/a/463207264_179850  You can refer to it.

OK, I can. Email you.

We need 3-4 miners. We will divide to each miner equally.

No. We will record in private. Maybe we will use github.

I don’t know. We inspect creditable miners.

**Comment by anelajennings** [comment]
license you need

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebs5h646a2gg3ut2py34xh3mykan6faiwuy5cammguf26h5uaubdq 
#### Address 
> f1w3rry66h73rujh5scdkuigj4islxs3tkqdiraji
#### Datacap Allocated
> 15TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebs5h646a2gg3ut2py34xh3mykan6faiwuy5cammguf26h5uaubdq
