### ISSUE TITLE
Client Allocation Request for: 广州尚恩文化传播有限公司

### ISSUE THREAD

**Issue by kjhikyhikl** [filecoin-project/filecoin-plus-client-onboarding#906]
---

# Client Allocation Questions 

## Core Information
- Name: 广州尚恩文化传播有限公司
- Website / Social Media: https://baike.baidu.com/item/%E5%B9%BF%E5%B7%9E%E5%B0%9A%E6%81%A9%E6%96%87%E5%8C%96%E4%BC%A0%E6%92%AD%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8/1935243?fr=aladdin
- Region: Greater China
- DataCap Requested: 2TiB
- Addresses to be Notarized: f3sem57itahtgirqiuuodfbays55a6fy6zpd4d7ntze2sah55yba622lewvcorr245vvqpdytlng7ugni54cia
- Notary Requested: IPFSUnion

@kjhikyhikl Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by IPFSUnion** [comment]
```
Thank you for your request. I'd like to know more about your business. Can you kindly answer my following questions?
* individual and organization  
    1.	Please introduce yourself and your team briefly, and show me some your social accounts such as email address, WeChat official account and other evidence proving that you have the right to apply on behalf of the company.
    2.	For your organization, Please describe its time since inception, registration country，scale, named officers, project, industry reputation etc.
* track record
    1. How did you know about Filecoin? Please describe your understanding of Filecoin storage.
    2. Regarding your data you intend to store, What’s the original source of those data, and do you have any proof of ownership or authorization?
    3. Has your organization obtained DataCap before? 
* use plan
    1.	Please describe your plan to use DataCap briefly? (such as use case, miner etc.)
```

**Comment by kjhikyhikl** [comment]
@IPFSUnion Thanks for your request.
We have over 30 people in our team and we don't have a social media account yet.
Guangzhou Shangen Culture Communication Co., Ltd. was founded in January 23, 2010, the company specialized in undertaking a variety of auto shows, corporate annual meetings, gala, celebration activities, sales promotion, press releases, exhibitions, parties, competitive games, fashion shows, all kinds of meetings, groundbreaking,  opening festival celebration,etc. For enterprises to provide a set of project planning, design and activity implementation of one-stop services. The company has a huge performance resources, providing all kinds of outstanding performers, and a variety of special performances

We've been introduced to Filecoin by companies in the industry, and our understanding of Filecoin is that it provides cost-effective storage.
These data are all videos that we shot.
We didn't get it before.

We're going to start storing our video, and work with about three miners.

**Comment by IPFSUnion** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecdevgkzba244emveuzot4wqihm2pqkedgnrlxjqeyntmzcpf3hic 
#### Address 
> f3sem57itahtgirqiuuodfbays55a6fy6zpd4d7ntze2sah55yba622lewvcorr245vvqpdytlng7ugni54cia
#### Datacap Allocated
> NaNB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecdevgkzba244emveuzot4wqihm2pqkedgnrlxjqeyntmzcpf3hic
