### ISSUE TITLE
Client Allocation Request for: 四川弘和通讯有限公司

### ISSUE THREAD

**Issue by testusertest001** [filecoin-project/filecoin-plus-client-onboarding#907]
---

# Client Allocation Questions 

## Core Information
- Name: 四川弘和通讯有限公司
- Website / Social Media: www.sc66666.com 
- Region: Greater China
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3r4vxzqne5nlpj25ynqnj24k3rzjck52gy27oorhuzgyxcvp3rt36os7hfs5b4o2oodqsjlyadbxhqnwkr46a
- Notary Requested: MRJAVAZHAO

@testusertest001 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MRJAVAZHAO** [comment]
Hello, @testusertest001 
Please provide the following materials.

Organization name, business scale, social media accounts&follwers, and business license (could be sent by email); if you are an individual, please provide name, date of birth, working company and scale, employment certificate, social media accounts&follwers, and ID card (can be sent by email);

When did you start learning about Filecoin? Please give a description about the projects you have participated in ? What do you want to get from Filecoin? Any suggestions or expectations for the Filecoin Network?

Is there any law risk? What percentage of questions are yours?

Please describe your organization, such as established time, the number of employees, users volumn, the number of social media followers.

How about your data volume, source and later planning? Please describe the type, format, source, storage capacity, publicity (and if data could be public, how can others retrieve it?) of the data to be stored in Filecoin.

In which area do you plan to store you data? How many miners do you want to find ? Please list the miner ID. How about the proportion of the storage for each miner? What are the requirements about miners? At last, please state your redundancy plan.

Do you agree to disclose transaction information? If you get DataCap, please make the transaction information public on the Issue in time.

**Comment by testusertest001** [comment]
Sichuan Honghe Communication Co., LTD
Sichuan Honghe Communication Co., Ltd. was established in 2020, the registered address of the company is in Chengdu, Sichuan province. Company keep good communication and cooperation with China mobile, telecom, unicom and other telecommunications operators for a long time. The company has a group of highly educated high-quality management team and technical team, who are experienced in areas such as computer, communication, the Internet. We have collectivize company scale and management level.
Honghe Group owns more than 20 software and hardware products with independent intellectual property rights, 4 of which are invention patents, and owns the first and second level independent brands such as Changwang and Jiaxuntong. The group gathers a large number of experienced, skilled, high-quality, highly educated operation, planning and technical personnel, as a rare comprehensive service provider of the whole IT business chain, the whole application and communication value chain. The group's main business include system integration, telecom value-added, software research and development, communication agency, Internet and mobile Internet, cultural communication and advertising. The company has system integration level 3, Security Level 1, B telecom value-added service license, SP and ISP, call center and other professional qualifications, through IS9001 international standard quality management system and CMMI certification. The comany owns a large number of independent intellectual property rights and patents.
Wechat official account: Honghe Artificial Intelligence; Number of followers: 1000+
Business license sent by mail

We learned about Filecoin last year and wanted Filecoin to be truly secure and lossless.

We had some business disputes, which have been resolved so far, about 10% of the responsibility.

Sichuan Honghe Communication Co., Ltd. was established in 2010 with more than 50 employees. We serve more than 10,000 customers. Wechat official account: Honghe Artificial Intelligence; Number of followers: 1000+

Data use cases are mainly in business data, working documents. File types include files, pictures, videos, and so on.

We plan to store in China and hope to cooperate with more than 3 miners, with the storage proportion not exceeding 50%.

I'm willing to make the details public.

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaced6e2r7buekops6yz3sps5pe7a5fkqcf7aaud2ntwx75xm37keud6 
#### Address 
> f3r4vxzqne5nlpj25ynqnj24k3rzjck52gy27oorhuzgyxcvp3rt36os7hfs5b4o2oodqsjlyadbxhqnwkr46a
#### Datacap Allocated
> 2TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaced6e2r7buekops6yz3sps5pe7a5fkqcf7aaud2ntwx75xm37keud6
