### ISSUE TITLE
Client Allocation Request for: 四川达见卓鸿广告传播有限公司

### ISSUE THREAD

**Issue by hkhjkhoujkh** [filecoin-project/filecoin-plus-client-onboarding#908]
---

# Client Allocation Questions 

## Core Information
- Name: 四川达见卓鸿广告传播有限公司
- Website / Social Media: https://aiqicha.baidu.com/company_detail_31235007382009
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3wl2d5r2mscnbpk7piabeap2hafzepqllioqyoonehol23tjyialqxfsdjdtrguaxdkgujqk5mxnq4f2k455q
- Notary Requested: MRJAVAZHAO

@hkhjkhoujkh Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MRJAVAZHAO** [comment]
Hello, @hkhjkhoujkh 
Please provide the following materials.

Organization name, business scale, social media accounts&follwers, and business license (could be sent by email); if you are an individual, please provide name, date of birth, working company and scale, employment certificate, social media accounts&follwers, and ID card (can be sent by email);

When did you start learning about Filecoin? Please give a description about the projects you have participated in ? What do you want to get from Filecoin? Any suggestions or expectations for the Filecoin Network?

Is there any law risk? What percentage of questions are yours?

Please describe your organization, such as established time, the number of employees, users volumn, the number of social media followers.

How about your data volume, source and later planning? Please describe the type, format, source, storage capacity, publicity (and if data could be public, how can others retrieve it?) of the data to be stored in Filecoin.

In which area do you plan to store you data? How many miners do you want to find ? Please list the miner ID. How about the proportion of the storage for each miner? What are the requirements about miners? At last, please state your redundancy plan.

Do you agree to disclose transaction information? If you get DataCap, please make the transaction information public on the Issue in time.

**Comment by hkhjkhoujkh** [comment]
Sichuan Dajian Zhuohong Communication Co., LTD
We provide all integrated marketing services, including advertising, data and consulting. We customize brands according to different stages of brand development and specific needs based on market orientation, such as retail terminal promotion management, brand launch conference, brand product research, and special brand promotion. Cooperative industries such as tobacco industry, tourism industry, real estate industry and so on.
We do not operate official company social media accounts for the time being.

We learned about Filecoin this year, and because of the nature of our business, we had a lot of data and wanted to store it in a cost-effective way, so we looked at new technologies.

Sichuan Dajian Zhuohong Communication Co., Ltd. does not exist any legal risk.

Sichuan Dajian Zhuohong Communication Co., Ltd. was established in 2020. Although it is a newly established company, we have accumulated substantial customer resources before the establishment. Darjian Zhuohong has been committed to assisting customers to develop their brands and businesses. We continue to create precious cases with creativity, and through the integration of talent and expertise, innovation and operation. We have about 50 colleagues from operations, growth and innovation, advertising, and consumer experience working together to help our clients. At present, we have cooperated with more than 100 enterprise users, such as China Tobacco Yunnan, Shanghai Tobacco Group, Xiao You Technology and other well-known enterprises.

At present, our data has exceeded about 200T, and the stored data mainly includes various files, pictures, videos and market research reports in the business development process of the company. The data is partially public, and the ratio of public to non-public is about 3:7.

We don't care about the storage area, the number of miners is around 5 and there are no actual storage transactions yet, so everything is still pending. The storage ratio is probably in the range of 10%-30%. Miners need to be experienced in storing real data to ensure data security.

I agree to disclose

**Comment by MRJAVAZHAO** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaasiuh7ujmnlb6gyme5gcvl4bovbdixhu6krz663ih6nbmcn7rva 
#### Address 
> f3wl2d5r2mscnbpk7piabeap2hafzepqllioqyoonehol23tjyialqxfsdjdtrguaxdkgujqk5mxnq4f2k455q
#### Datacap Allocated
> 2TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaasiuh7ujmnlb6gyme5gcvl4bovbdixhu6krz663ih6nbmcn7rva
