### ISSUE TITLE
Client Allocation Request for: Momoshop

### ISSUE THREAD

**Issue by Xavieraie** [filecoin-project/filecoin-plus-client-onboarding#913]
---

# Client Allocation Questions 

## Core Information
- Name: Momoshop
- Website / Social Media: https://www.momoshop.com.tw/
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1ps4xce5y22nnlav2trdvvztlcw5gjpo4qkimrga
- Notary Requested: ozhtdong

@Xavieraie Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your request , some questions to you:
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by Xavieraie** [comment]
Happy to answer your questions.
1.I am ZhiHong Li, a manager in the company.
2. Momoshop is the leader of Taiwan's online retail industry, and its subsidiaries include momo shopping network, skyscraper, TV shopping and catalog shopping. Adhering to the corporate mission of "providing high-quality and affordable products and quality services to improve people's lives" and the four business values of "integrity, cordiality, professionalism and innovation", we provide consumers with diversified shopping services throughout the year.
3.Yes. Later I will show you.
4.We want 2-3 miners. It will be divided to them qually.
5.Yes. We only know github and will use it.
6.No tools. I want to find stable miners.

**Comment by Xavieraie** [comment]
Business license.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceavsbyykyllvskuqtt4tx6zjwbv5dul2qqnlirqwkwn7txnpcrl3w 
#### Address 
> f1ps4xce5y22nnlav2trdvvztlcw5gjpo4qkimrga
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceavsbyykyllvskuqtt4tx6zjwbv5dul2qqnlirqwkwn7txnpcrl3w
