### ISSUE TITLE
Client Allocation Request for: Friday

### ISSUE THREAD

**Issue by Yolandeyi** [filecoin-project/filecoin-plus-client-onboarding#914]
---

# Client Allocation Questions 

## Core Information
- Name: Friday
- Website / Social Media: https://shopping.friday.tw/
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1emyqnyaf5kaqdlfnkhhqrtt4hdodxc2egrjphea
- Notary Requested: ozhtdong

@Yolandeyi Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your request , some questions to you:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by Yolandeyi** [comment]
1.Qi Jing. I’m the chairman of Friday.
2. In 2014, friday shopping was published, with the innovative integration of the concept of "curation", starting from the lifestyle, exclusive sales of specialty products, and introducing expert recommendations to create a new shopping experience. In 2017, it merged with GoHappy Shopping, a subsidiary of Far East E-commerce, to deepen the operation of the friday shopping brand, and integrate the advantages of the group-combined with the largest retail channel under the department store sales line, hoping to create the most complete retail channel system for O2O in Taiwan. In the same year, friday shopping won the Visionary Five-Star Service Award First prize in the online shopping category.
Friday shopping adheres to the concept of "concern people" and officially launched the gold membership service in April 2019. friDay shopping shouts "Benefits every time，great life!", combining consumer feedback with unique products, health, entertainment, and convenience , security and other services, all-round upgrading of membership rights, operating a membership system, deepening the relationship between members, and creating an iron powder economy.
In 2020, friDay shopping starts from "let's shopping for a better life", and together with FarEasTone Telecom Group. We will use considerate and innovative services to make technology simpler, help people live in the present more conveniently and smartly, and become a good partner in people's digital life.
3.OK, I will.
4.I think 2 miners are enough. Each miner will be allocated 5 TiB.
5.Github can help us inspect miners.
6.We’ll use filfox. We would like to find out reliable miners.

**Comment by Yolandeyi** [comment]
Hey, here is the license.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaoi3slt3p7jwm5cysdybcyqxjbf4dvbiognt2pyct2zbwxypbati 
#### Address 
> f1emyqnyaf5kaqdlfnkhhqrtt4hdodxc2egrjphea
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaoi3slt3p7jwm5cysdybcyqxjbf4dvbiognt2pyct2zbwxypbati
