### ISSUE TITLE
Client Allocation Request for: books

### ISSUE THREAD

**Issue by canathompson** [filecoin-project/filecoin-plus-client-onboarding#917]
---

# Client Allocation Questions 

## Core Information
- Name: books
- Website / Social Media: https://www.books.com.tw/
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f16rfaj6lyjsl4i6wcyw7wp2xukazormp7iitpbaq
- Notary Requested: ozhtdong

@canathompson Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your request , some questions to you:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by canathompson** [comment]
1. I am Pirong Lin，the manager of books.
2. Established in 1995, Books is the largest channel for book and audio-visual sales. In recent years, it has actively stepped into an all-round online shopping retail platform. With the brand spirit of "Thinking in Shopping, Evolving in Reading", it continues to expand the merchandise category of department stores and services. With a simpler and more intimate shopping interface and process, convenient shipping speed and high-quality customer service, Books has obtained the "Data Privacy Protection Mark Certification" of the Ministry of Economic Affairs. Convenient and barrier-free shopping experience. 
3. I can send an email to you.
4. 3miners. We will allocate a share of no more than 40% to every miner.
5. Yes. We use github.
6. We don’t use any tool to inspect miners. We plan to select some miners who provide services reliably and stably.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceb44j6ncjmmn2v7vm2wojf455oakzhl44uxvmogauiqhix7aa3guc 
#### Address 
> f16rfaj6lyjsl4i6wcyw7wp2xukazormp7iitpbaq
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceb44j6ncjmmn2v7vm2wojf455oakzhl44uxvmogauiqhix7aa3guc
