### ISSUE TITLE
Client Allocation Request for: cari

### ISSUE THREAD

**Issue by hyltonturner** [filecoin-project/filecoin-plus-client-onboarding#918]
---

# Client Allocation Questions 

## Core Information
- Name: cari
- Website / Social Media: https://cari.com.my/
- Region: Asia excl. Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1cg7zkrrogqx7mo47mkvcdohfbyxe7lrrbnhyjui
- Notary Requested: ozhtdong

@hyltonturner Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your request , some questions to you:

1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by hyltonturner** [comment]
1. My name is Tom. I’m a drector.
2.Our company’s vision is to be the Most Creditable and Influential online new media in Malaysia. Our mission is to Publish / Disseminate News & Content that are from users, for users, and related to users. And we want to promise to be the platform for the voice of Malaysian, the platform to interact and exchange, views and opinions of all races and promise to actuate the beauty of Malaysia as a multi-ethnic, multicultural, and multilingual society.  Our Ambition is to promise to be the voice of Malaysian, and the Malaysian most preferred platform to voice out.
3.Yes. I will show you several minutes later.
4.I think 3-4 miners are ok. We plan to divide to every miner equally.
5.We will use github.
6.Filfox. We are looking for experienced miners.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceaij4zp235fa5rtjoibninij7gf3fv2pdyy7sju6vjulvawb6s7ha 
#### Address 
> f1cg7zkrrogqx7mo47mkvcdohfbyxe7lrrbnhyjui
#### Datacap Allocated
> 10TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceaij4zp235fa5rtjoibninij7gf3fv2pdyy7sju6vjulvawb6s7ha
