### ISSUE TITLE
Client Allocation Request for: anyiyun

### ISSUE THREAD

**Issue by knowltonroth** [filecoin-project/filecoin-plus-client-onboarding#927]
---

# Client Allocation Questions 

## Core Information
- Name: anyiyun
- Website / Social Media: www.anyidata.com
- Region: Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1v4oz6w5g5u5qoyr7k7jukn7torxwt7yksp27ebq
- Notary Requested: ozhtdong

@knowltonroth Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I have some questions:
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by knowltonroth** [comment]
1.My name is Xin Zhang. I’m the legal person.
2. List of Mianyang Hash Power Valley Projects. (1) Digital Mianyang Convenience Service Platform Project (2) Digital Film and Television Supercomputing Rendering Project (3) Sichuan Telecom "Magic Mirror" Video Cloud Base (4) Sichuan Mobile North Sichuan Big Data Center Project (5) Data from Sichuan Radio and Television and Sichuan Unicom Central project (6) Internet + trusted identity authentication (digital identity authentication platform) project (7) Blockchain medical big data platform-electronic film cloud service center (8) Visualized digital cloud brain, digital vertical Internet platform (9) Excellent Educational Resources Digital Education Inclusive Platform (10) Urban Nervous System and Urban Brain Project (11) Cold Chain Material Digital Traceability Commodity Trading Platform (12) Industry Application Comprehensive Platform under 5G Technology System
3.OK. I can email you.
4.We want 3 miners. It will be divided to them qually.
5.Yes. We only know github and will use it.
6.No tools. I want to find stable miners.

**Comment by knowltonroth** [comment]
Here it is.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacea7kqz7ch6avo6fodwwtua2ensqdhjzpyvba3rybj6jw26d2ptehs 
#### Address 
> f1v4oz6w5g5u5qoyr7k7jukn7torxwt7yksp27ebq
#### Datacap Allocated
> 15TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacea7kqz7ch6avo6fodwwtua2ensqdhjzpyvba3rybj6jw26d2ptehs
