### ISSUE TITLE
Client Allocation Request for: trueelite

### ISSUE THREAD

**Issue by diciccowaller** [filecoin-project/filecoin-plus-client-onboarding#931]
---

# Client Allocation Questions 

## Core Information
- Name: trueelite
- Website / Social Media: trueelite-global.com
- Region: Greater China
- DataCap Requested: 15TiB
- Addresses to be Notarized: f15bkiys3saxw5uu44j7ta5u7tidfjmltanpizqtq
- Notary Requested: ozhtdong

@diciccowaller Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by ozhtdong** [comment]
Thanks for your application. I have some questions:
1.What's your name? What's your position?
2.What's your company's business? Do you have any other social media link?
3.Could you show me your company's business license?
4.How many miners do you want to store your data to? How much data for each miner?
5.Will you record your allocation decision in public? Which platform will you use?
6.What method/tool will you use to inspect miners? Which aspect of miners will you inspect?

**Comment by diciccowaller** [comment]
1.Chris Zhang. I am a manager.
2.Cloud Managed Services enables enterprises to enjoy the benefits of abundant resources and the most suitable cloud architecture. Through comprehensive cloud application services and solutions, CloudRiches provides a set of one-stop services from planning and migration to cloud maintenance to help companies reduce costs, strengthen information security, make the cloud environment fault-tolerant and optimize cloud operations.
3.Yes, I can.
4. I think 3-4 miners are ok. We plan to divide to every miner equally.
5.We will use github.
6.Filfox. We are looking for experienced miners.

**Comment by diciccowaller** [comment]
Here is our business license.

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzaceamuajdsh4v2w2bjrjbprwdcyzbo3obkmju75n6zyrmz6n6o2fagk 
#### Address 
> f15bkiys3saxw5uu44j7ta5u7tidfjmltanpizqtq
#### Datacap Allocated
> 15TiB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzaceamuajdsh4v2w2bjrjbprwdcyzbo3obkmju75n6zyrmz6n6o2fagk
