### ISSUE TITLE
Client Allocation Request for: Booyeoung

### ISSUE THREAD

**Issue by Booyeoung** [filecoin-project/filecoin-plus-client-onboarding#946]
---

# Client Allocation Questions 

## Core Information
- Name: Booyeoung
- Website / Social Media: http://www.booyeoung.com/
- Region: Asia excl. Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3qfcto2fba5jvnjqthwziiflvm2ikaa6wcyad26b7ax3n3gjtnwklfcfycq5mbiedjfxaikiw27wh7qtkxtca
- Notary Requested: IPFSUnion

@Booyeoung Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by IPFSUnion** [comment]
```
Hi, Booyeoung. I'd like to know more about your business. Can you kindly answer my following questions?
* individual and organization  
    1.	Please introduce yourself and your team briefly, and show me some your social accounts such as email address, WeChat official account and other evidence proving that you have the right to apply on behalf of the company.
    2.	For your organization, Please describe its time since inception, registration country，scale, named officers, project, industry reputation etc.
* track record
    1. How did you know about Filecoin? Please describe your understanding of Filecoin storage.
    2. Regarding your data you intend to store, What’s the original source of those data, and do you have any proof of ownership or authorization?
    3. Has your organization obtained DataCap before? 
* use plan
    1.	Please describe your plan to use DataCap briefly? (such as use case, miner etc.)
```

**Comment by IPFSUnion** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebha2gut3gtf4woomraflqfkzsic7osjcxwhwzrybobl6nktkj7t2 
#### Address 
> f3qfcto2fba5jvnjqthwziiflvm2ikaa6wcyad26b7ax3n3gjtnwklfcfycq5mbiedjfxaikiw27wh7qtkxtca
#### Datacap Allocated
> NaNB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebha2gut3gtf4woomraflqfkzsic7osjcxwhwzrybobl6nktkj7t2
