### ISSUE TITLE
Client Allocation Request for: RICH ST PETE LLC

### ISSUE THREAD

**Issue by lambrage** [filecoin-project/filecoin-plus-client-onboarding#960]
---

# Client Allocation Questions 

## Core Information
- Name: RICH ST PETE LLC
- Website / Social Media: www.meiaoju.com
- Region: North America
- DataCap Requested: 20TiB
- Addresses to be Notarized: f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x4y7q
- Notary Requested: XnMatrixSV

@lambrage Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by XnMatrixSV** [comment]
Hi, @lambrage 
Thanks for your request. Can you kindly add more information here.
1.Is your company located in North America？
2.Please give the following informations, duration of etablishment, number of employees, business scope, users volume, number of social media followers, data size to be stored, products or projects, and so on. Provide links to social media/news mentions.
3.The history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time, etc.
Type, size, and source of the data you will be store on Filecoin,e.g. public data or private data, etc. Is there any sensitive or illegal content?
4.How do you intend to store the data on Filecoin, e.g. redundancy, location/miner preferences, etc
5.Have you already apply for DataCap to another notary, and whether it is accepted or rejected. Is there any reliable DataCap left?
6.Would you like to post real transactions on Github?

**Comment by XnMatrixSV** [comment]
Hi, @lambrage 
According to our allocation strategy, we will grant you a maximum of 5TiB.
Please ensure the following informations.

Scoring Result:
![image](https://user-images.githubusercontent.com/74889675/137254286-57d159bd-b61e-48bd-8461-49a90ba034fa.png)
The Address：f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x4y7q

**Comment by lambrage** [comment]
Confirmed.

**Comment by XnMatrixSV** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedir3ez4ch4vbaccmen7hbbgf5jwdpx4o3rk5fzyacl5iks7vsnkw 
#### Address 
> f3woqxpu6ekmj43nmpcv7j2pgu6lejxtzgxpzl6f2vrueoqlzjntakyhdkghymyffbzfbsio6dvfmy643x4y7q
#### Datacap Allocated
> NaNB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedir3ez4ch4vbaccmen7hbbgf5jwdpx4o3rk5fzyacl5iks7vsnkw
