### ISSUE TITLE
Client Allocation Request for: GMWBR INC

### ISSUE THREAD

**Issue by Vincentof** [filecoin-project/filecoin-plus-client-onboarding#961]
---

# Client Allocation Questions 

## Core Information
- Name: GMWBR INC
- Website / Social Media: www.gmwbr.org
- Region: North America
- DataCap Requested: 10TiB
- Addresses to be Notarized: f3w4wlayytfmsay6gu5phhij5r4yyx7t4xxrlosgotlmqg5eih3co5atsra4h2pe4qd2d6c76bvhj6nwim7lgq
- Notary Requested: XnMatrixSV

@Vincentof Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by XnMatrixSV** [comment]
Hi, @Vincentof 
Thanks for your request. Can you kindly add more information here.
1.Is your company located in North America？
2.Please give the following informations, duration of etablishment, number of employees, business scope, users volume, number of social media followers, data size to be stored, products or projects, and so on. Provide links to social media/news mentions.
3.The history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time, etc.
Type, size, and source of the data you will be store on Filecoin,e.g. public data or private data, etc. Is there any sensitive or illegal content?
4.How do you intend to store the data on Filecoin, e.g. redundancy, location/miner preferences, etc
5.Have you already apply for DataCap to another notary, and whether it is accepted or rejected. Is there any reliable DataCap left?
6.Would you like to post real transactions on Github?

**Comment by Vincentof** [comment]
Yes, it is.
Our compane established in August 21, 2019. There are more than 20 people work for the company.
We serve customers all over the country with more than 500+ users. We have no social media account. The size of the stored data is more than 1P.
GMWBR INC firstly conducts detailed market research for domestic competitive products combined with overseas e-commerce market environment. Mainly for the market volume, market competition, brand concentration and profit margin to make a pre-evaluation plan. Secondly, our core operation team will only recruit those with successful operation experience, operational thinking, sense of responsibility and dedication. We will ensure that qualified people work under the guidance of the company's unified operation philosophy, do a good job in process management and feedback, and timely adjust the operation direction. In the end, the overall data of the overseas operation process will be recorded through the block chain technology, so as to truly complete the new e-commerce model of mutual trust and group going abroad.
No previous exposure to IPFS/Filecoin network.
The data stored are mainly pictures, videos, platform data, store decoration materials, etc., which are all public data without any sensitive or illegal content.
We plan to select about 5 miners and make 3 copies of each data. There is no special preference for miners.
We haven't applied before.
We're willing to post real deals.

**Comment by XnMatrixSV** [comment]
Hi, @Vincentof 
According to our allocation strategy, we will grant you a maximum of 2TiB.
Please ensure the following informations.
Scoring Result:
![image](https://user-images.githubusercontent.com/74889675/137253968-217e9a45-a610-407f-8eb5-499afba86aab.png)
The Address：f3w4wlayytfmsay6gu5phhij5r4yyx7t4xxrlosgotlmqg5eih3co5atsra4h2pe4qd2d6c76bvhj6nwim7lgq

**Comment by Vincentof** [comment]
Yes.

**Comment by XnMatrixSV** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacecksoevva2ysfgwgpsocvtr6ejamk4ohq6di2tdhcdfq45x32arby 
#### Address 
> f3w4wlayytfmsay6gu5phhij5r4yyx7t4xxrlosgotlmqg5eih3co5atsra4h2pe4qd2d6c76bvhj6nwim7lgq
#### Datacap Allocated
> NaNB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacecksoevva2ysfgwgpsocvtr6ejamk4ohq6di2tdhcdfq45x32arby
