### ISSUE TITLE
Client Allocation Request for: WeiChen

### ISSUE THREAD

**Issue by de-authority** [filecoin-project/filecoin-plus-client-onboarding#965]
---

# Client Allocation Questions 

## Core Information
- Name: WeiChen
- Website / Social Media: https://github.com/dayou5168
- Region: Greater China
- DataCap Requested: 32GiB
- Addresses to be Notarized: f3vcrkxk5kvdq3hzqbabi4tfuumewaswhmn2jytwsnh5a2ywbhw6jl6jccvkeptd7ndb3bzjaxb5nc2qoyn5pq
- Notary Requested: MRJAVAZHAO

@dayou5168 Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by MRJAVAZHAO** [comment]
@dayou5168 Hi, if you just want to apply for 32GB, please use your Github directly on this website(https://verify.glif.io/).
![image](https://user-images.githubusercontent.com/47096545/136878360-7cf142cb-de08-43c1-9b9b-3a8480a95113.png)

**Comment by MRJAVAZHAO** [comment]
service@athenapool.com

**Comment by MRJAVAZHAO** [comment]
I will temporarily close this issue and open it again if necessary.

**Comment by dayou5168** [comment]
Thanks, @MRJAVAZHAO . it's too complex for a 32Gb datacap. I give up

**Comment by MRJAVAZHAO** [comment]
@dayou5168 If you have any good suggestions for individual application, please feel free to state them to me. 
I will improve the measures and improve the efficiency.
