### ISSUE TITLE
Client Allocation Request for: jyxx

### ISSUE THREAD

**Issue by finfrockberry** [filecoin-project/filecoin-plus-client-onboarding#974]
---

# Client Allocation Questions 

## Core Information
- Name: jyxx
- Website / Social Media: https://www.jing-yi.com.cn/
- Region: Greater China
- DataCap Requested: 10TiB
- Addresses to be Notarized: f1pm5uqcpqcw3zzcypg2ot4gisxg5wliiwczhrdfa
- Notary Requested: ozhtdong

@finfrockberry Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by finfrockberry** [comment]
our company's business license

**Comment by ozhtdong** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedf347k5iyhauxu2aiw442qznzceruyfaxv7qsf5a3t75wqtn7udy 
#### Address 
> f1pm5uqcpqcw3zzcypg2ot4gisxg5wliiwczhrdfa
#### Datacap Allocated
> NaNB
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedf347k5iyhauxu2aiw442qznzceruyfaxv7qsf5a3t75wqtn7udy
