### ISSUE TITLE
Client Allocation Request for: IPFSDNA

### ISSUE THREAD

**Issue by wwwaxzfz863** [filecoin-project/filecoin-plus-client-onboarding#98]
---

# Client Allocation Questions 

## Core Information
- Name: IPFSDNA
- Website / Social Media: https://slingshot.filecoin.io/project/5ffd0bda96cb52da4a78adf4
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3ujxtlbu6orbqwqlxdacklt3t44ivrl3vvzyx2d67evsvt66hmcoi3k4cpiggpam3vmmpfgsl4jmg55rsfzda
- Notary Requested: philippbanhardt

**Comment by philippbanhardt** [comment]
Hey @wwwaxzfz863 - thanks for your request. Can you kindly add more information / context here on:

- yourself , e.g. include links to social media / news mentions etc
- your history working on IPFS / Filecoin, e.g. notable contributions to the community, type of engagement shown over time etc
- type, size and source of the data you (and by extension other Discover participants) are looking to store on Filecoin, e.g. public data vs private data etc
- your relationship with the data, especially with regard to copyright
- how you intend to store the data on Filecoin, e.g. redundancy, location / miner preferences, etc

Thanks
