### ISSUE TITLE
Client Allocation Request for: IPFSDNA

### ISSUE THREAD

**Issue by wwwaxzfz863** [filecoin-project/filecoin-plus-client-onboarding#99]
---

# Client Allocation Questions 

## Core Information
- Name: IPFSDNA
- Website / Social Media: https://slingshot.filecoin.io/project/5ffd0bda96cb52da4a78adf4
- DataCap Requested: 5TiB
- Addresses to be Notarized: f3ujxtlbu6orbqwqlxdacklt3t44ivrl3vvzyx2d67evsvt66hmcoi3k4cpiggpam3vmmpfgsl4jmg55rsfzda
- Notary Requested: ann-shin

**Comment by ann-shin** [comment]
Thank you for your application. Because of our account problem, you need to login plus.fil.org to apply again.
