### ISSUE TITLE
Client Allocation Request for: X-TREME VIDEO

### ISSUE THREAD

**Issue by georginabaderbc** [filecoin-project/filecoin-plus-client-onboarding#995]
---

# Client Allocation Questions 

## Core Information
- Name: X-TREME VIDEO
- Website / Social Media: https://www.x-tremevideo.com/
- Region: North America
- DataCap Requested: 15TiB
- Addresses to be Notarized: f1b7ed6t5oywwl3ffgtgw4hxl5yhqktofsmqyklga
- Notary Requested: TimWilliams00

@georginabaderbc Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by TimWilliams00** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacebn2kz7cpw5sk43dzyhgbtt4irwji6a5nxeuk7ruixloms26tvpjm 
#### Address 
> f1b7ed6t5oywwl3ffgtgw4hxl5yhqktofsmqyklga
#### Datacap Allocated
> NaNB
#### Signer Address
> f1fkxkfxgopjf3ufnfg5i3m6qlwf73kp4w5zz7nnq
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacebn2kz7cpw5sk43dzyhgbtt4irwji6a5nxeuk7ruixloms26tvpjm
