### ISSUE TITLE
Client Allocation Request for: PacoEngineering

### ISSUE THREAD

**Issue by Pacoengine** [filecoin-project/filecoin-plus-client-onboarding#997]
---

# Client Allocation Questions 

## Core Information
- Name: PacoEngineering
- Website / Social Media: http://www.pacoeng.co.kr/
- Region: Asia excl. Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3uizzqt4occf4sf6ne7pvjqorfh2anb4sys7kzrxfpw77rgpfqjkdquat2m662rnmfitrfaoqzf6nfp77oqua
- Notary Requested: IPFSUnion

@Pacoengine Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by IPFSUnion** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedrhvxeoaxsitnx25ri3bpqvfhnwx5q2zjiiftd5jib3snurpcjms 
#### Address 
> f3uizzqt4occf4sf6ne7pvjqorfh2anb4sys7kzrxfpw77rgpfqjkdquat2m662rnmfitrfaoqzf6nfp77oqua
#### Datacap Allocated
> NaNB
#### Signer Address
> f1enfilmuyphmnqexjt33zfbk56c25mo2lplgbpxa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedrhvxeoaxsitnx25ri3bpqvfhnwx5q2zjiiftd5jib3snurpcjms
