### ISSUE TITLE
Client Allocation Request for: Youshintech

### ISSUE THREAD

**Issue by Youshintec** [filecoin-project/filecoin-plus-client-onboarding#998]
---

# Client Allocation Questions 

## Core Information
- Name: Youshintech
- Website / Social Media: http://www.youshintec.co.kr/
- Region: Asia excl. Greater China
- DataCap Requested: 1TiB
- Addresses to be Notarized: f3sj3mwos34apjwy2seskztxamqceggh3foxyw6agqn7yqwzvcfq7im4xohhaaops4y4fqaigukh3u2wwnbffa
- Notary Requested: IPFSUnion

@Youshintec Please subscribe to notifications for this Issue to be aware of updates. Notaries may request additional information on the Issue.

**Comment by IPFSUnion** [comment]
The filecoin address you provided is invalid, please re-edit it asap.

**Comment by Youshintec** [comment]
Okay I change it.

f3sj3mwos34apjwy2seskztxamqceggh3foxyw6agqn7yqwzvcfq7im4xohhaaops4y4fqaigukh3u2wwnbffa

**Comment by IPFSUnion** [comment]
## Request Approved
Your Datacap Allocation Request has been approved by the Notary
#### Message sent to Filecoin Network
>bafy2bzacedvn4dhbfkcffivsjotikau2hzzo76iixfxucabd2ouw6wpwe2mfc 
#### Address 
> f3sj3mwos34apjwy2seskztxamqceggh3foxyw6agqn7yqwzvcfq7im4xohhaaops4y4fqaigukh3u2wwnbffa
#### Datacap Allocated
> NaNB
#### Signer Address
> f1enfilmuyphmnqexjt33zfbk56c25mo2lplgbpxa
#### You can check the status of the message here: https://filfox.info/en/message/bafy2bzacedvn4dhbfkcffivsjotikau2hzzo76iixfxucabd2ouw6wpwe2mfc
